// arXiv math subject-class display names, for the "reveal subfield" chip.
export const SUBFIELD_NAMES: Record<string, string> = {
  'math.AG': 'Algebraic Geometry',
  'math.AT': 'Algebraic Topology',
  'math.AP': 'Analysis of PDEs',
  'math.CT': 'Category Theory',
  'math.CA': 'Classical Analysis and ODEs',
  'math.CO': 'Combinatorics',
  'math.AC': 'Commutative Algebra',
  'math.CV': 'Complex Variables',
  'math.DG': 'Differential Geometry',
  'math.DS': 'Dynamical Systems',
  'math.FA': 'Functional Analysis',
  'math.GM': 'General Mathematics',
  'math.GN': 'General Topology',
  'math.GT': 'Geometric Topology',
  'math.GR': 'Group Theory',
  'math.HO': 'History and Overview',
  'math.IT': 'Information Theory',
  'math.KT': 'K-Theory and Homology',
  'math.LO': 'Logic',
  'math.MP': 'Mathematical Physics',
  'math.MG': 'Metric Geometry',
  'math.NT': 'Number Theory',
  'math.NA': 'Numerical Analysis',
  'math.OA': 'Operator Algebras',
  'math.OC': 'Optimization and Control',
  'math.PR': 'Probability',
  'math.QA': 'Quantum Algebra',
  'math.RA': 'Rings and Algebras',
  'math.RT': 'Representation Theory',
  'math.SP': 'Spectral Theory',
  'math.ST': 'Statistics Theory',
  'math.SG': 'Symplectic Geometry',
};
