"""math.AC - Commutative Algebra.

Seeded from the build spec and expanded with the algebra/number-theory research
dossier into a broad working vocabulary of rings, ideals, and resolutions.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

AC = SubfieldLexicon(
    code="math.AC",
    name="Commutative Algebra",
    weight=5.0,
    banks={
        "objects": [
            "Noetherian ring",
            "local ring",
            "regular local ring",
            "Cohen--Macaulay ring",
            "Gorenstein ring",
            "complete intersection",
            "polynomial ring",
            "power series ring",
            "graded ring",
            "monomial ideal",
            "prime ideal",
            "maximal ideal",
            "radical ideal",
            "Jacobian ideal",
            "Fitting ideal",
            "initial ideal",
            "edge ideal",
            "Stanley--Reisner ring",
            "free resolution",
            "minimal free resolution",
            "Koszul complex",
            "graded module",
            "maximal Cohen--Macaulay module",
            "canonical module",
            "dualizing complex",
            "syzygy module",
            "tilting module",
            "Rees algebra",
            "associated graded ring",
            "fiber cone",
            "completion",
            "valuation ring",
            "Dedekind domain",
            "normal domain",
            "toric ring",
            "semigroup ring",
            "matroid",
            "hyperplane arrangement",
            "simplicial complex",
            "Hilbert series",
            "Groebner basis",
            "primary decomposition",
        ],
        "props": [
            "Noetherian",
            "Artinian",
            "regular",
            "normal",
            "reduced",
            "integral",
            "integrally closed",
            "Cohen--Macaulay",
            "sequentially Cohen--Macaulay",
            "Gorenstein",
            "complete intersection",
            "Koszul",
            "graded",
            "standard graded",
            "multigraded",
            "monomial",
            "squarefree",
            "flat",
            "faithfully flat",
            "finitely generated",
            "free",
            "projective",
            "torsion-free",
            "reflexive",
            "saturated",
            "unmixed",
            "equidimensional",
            "shellable",
            "Stanley--Reisner",
            "perfect",
            "acyclic",
            "exact",
            "homogeneous",
            "local",
            "complete",
            "henselian",
            "excellent",
            "normally torsion-free",
            "componentwise linear",
        ],
        "spaces": [
            "spectrum",
            "maximal spectrum",
            "ring of integers",
            "polynomial ring",
            "power series ring",
            "local cohomology module",
            "Koszul homology",
            "Tor module",
            "Ext module",
            "free resolution",
            "minimal free resolution",
            "Rees algebra",
            "associated graded ring",
            "completion",
            "fraction field",
            "residue field",
            "Stanley--Reisner ring",
            "canonical module",
            "dualizing complex",
            "derived category",
        ],
        "maps": [
            "the localization map",
            "the completion map",
            "the structure morphism",
            "the canonical surjection",
            "the connecting homomorphism",
            "the Koszul differential",
            "the multiplication map",
            "the trace map",
            "the Frobenius endomorphism",
            "the natural inclusion",
            "the comparison map",
            "the boundary map",
            "the augmentation map",
            "the evaluation map",
            "the residue map",
        ],
        "invariants": [
            "Krull dimension",
            "depth",
            "codimension",
            "height",
            "embedding dimension",
            "multiplicity",
            "Hilbert function",
            "Hilbert polynomial",
            "Hilbert series",
            "Castelnuovo--Mumford regularity",
            "projective dimension",
            "injective dimension",
            "global dimension",
            "graded Betti numbers",
            "total Betti number",
            "type",
            "a-invariant",
            "analytic spread",
            "reduction number",
            "Loewy length",
            "minimal number of generators",
            "Frobenius complexity",
            "Hilbert--Kunz multiplicity",
            "F-signature",
            "socle dimension",
        ],
        "namedResults": [
            "the Auslander--Buchsbaum formula",
            "Hilbert's syzygy theorem",
            "the Hilbert--Burch theorem",
            "Hochster's theorem",
            "the Eisenbud--Goto conjecture",
            "the monomial conjecture",
            "the direct summand conjecture",
            "Serre's conditions",
            "the Auslander--Reiten conjecture",
            "the Buchsbaum--Eisenbud criterion",
            "the Lipman--Sathaye theorem",
            "the Briancon--Skoda theorem",
            "the Hilbert--Samuel theorem",
            "the local duality theorem",
            "the Cohen structure theorem",
            "the Krull intersection theorem",
            "the Buchberger algorithm",
            "the Kunz regularity theorem",
            "the Stanley conjecture",
            "the Eisenbud--Green--Harris conjecture",
            "the Lech--Mumford bound",
            "the Watanabe--Yoshida conjecture",
            "the Huneke--Wiegand conjecture",
            "the Lyubeznik--Smith theorem",
            "the Peskine--Szpiro theorem",
        ],
        "methods": [
            "local cohomology",
            "the theory of free resolutions",
            "Koszul homology",
            "Groebner basis methods",
            "reduction to characteristic $p$",
            "the Frobenius endomorphism",
            "tight closure theory",
            "the method of polarization",
            "liaison theory",
            "the Auslander--Buchsbaum formula",
            "spectral sequence techniques",
            "local duality",
            "an analysis of the minimal free resolution",
            "the theory of initial ideals",
            "deformation to the initial ideal",
            "the Rees algebra construction",
            "homological methods",
            "simplicial techniques",
            "lifting to characteristic zero",
            "the theory of regular sequences",
            "Hilbert function methods",
            "specialization",
            "an explicit computation of Tor",
            "the multiplicity formula",
        ],
        "objectGloss": [
            "controls the homological behavior of the ring",
            "measures the failure of regularity",
            "encodes the singularities of the ring",
            "governs the structure of free resolutions",
            "reflects the depth of the module",
            "is central to modern commutative algebra",
            "captures the asymptotic growth of the ideal",
            "interpolates between geometry and algebra",
        ],
    },
    # Object-naming letters only. No "p" (clashes with characteristic p and the
    # prime index) and no "i, j" (clash with resolution and cohomology indices).
    symbols=[
        "R",
        "S",
        "A",
        "B",
        "M",
        "N",
        "I",
        "\\mathfrak{m}",
        "\\mathfrak{p}",
        "F",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\operatorname{depth} XSYM = \dim XSYM",
        r"\operatorname{pd}_R XSYM + \operatorname{depth} XSYM = \operatorname{depth} R",
        r"\dim XSYM = @N@",
        r"\operatorname{ht}\mathfrak{p} + \dim R/\mathfrak{p} = \dim R",
        r"\operatorname{reg} XSYM \le @N@",
        r"\beta_{@I@,@C@}(XSYM) = @N@",
        r"\operatorname{Tor}_{@I@}^R(XSYM, ASYM) = 0",
        r"\operatorname{Ext}_R^{@I@}(XSYM, R) = 0",
        r"e(XSYM) = @N@",
        r"H_{\mathfrak{m}}^{@I@}(XSYM) = 0",
        r"\mu(XSYM) = @N@",
        r"\operatorname{grade}(I, R) = \operatorname{ht} I",
        r"H_{XSYM}(t) = \frac{Q(t)}{(1-t)^{@C@}}",
        r"\dim_k \mathfrak{m}/\mathfrak{m}^2 = \dim R",
        r"\sqrt{I} = \bigcap_{i=1}^{@C@} \mathfrak{p}_i",
        r"\ell(R/\mathfrak{q}) < \infty",
        r"\operatorname{gldim} R = \dim R",
        r"R \cong k[x_1,\dots,x_{@N@}]/I",
        r"\operatorname{in}_{<}(I) = (x_1^{@C@}, \dots, x_{@N@})",
        r"\lambda(M/\mathfrak{m}^{@C@} M) = e(\mathfrak{m}; M)",
        r"\operatorname{Ass}(R/I) = \{\mathfrak{p}_1, \dots, \mathfrak{p}_{@C@}\}",
        r"\operatorname{Frob}: R \to R, \quad r \mapsto r^{p}",
        r"\widehat{R} \cong k[[x_1, \dots, x_{@N@}]]",
        r"R_{\mathfrak{p}} \text{ is regular for all } \mathfrak{p}",
        r"\operatorname{type}(R) = \dim_k \operatorname{soc}(R)",
        r"a(R) = -\dim R + @R@",
        r"I^{@C@} \subseteq \overline{I}^{\,@C@}",
        r"\operatorname{rank}\, \varphi_{@I@} = @N@",
        r"\operatorname{codim} XSYM = @N@",
        r"H_{XSYM}(@C@) = \binom{@C@ + @N@}{@N@}",
        r"e_{HK}(R) \ge 1",
        r"\operatorname{Hom}_R(XSYM, R) \cong ASYM",
    ],
    display_eqns=[
        r"0 \to F_n \to \cdots \to F_1 \to F_0 \to XSYM \to 0, \qquad "
        r"F_i = \bigoplus_j R(-j)^{\beta_{i,j}}",
        r"\operatorname{pd}_R M + \operatorname{depth} M = \operatorname{depth} R",
        r"H_{XSYM}(t) = \sum_{i \ge 0} \dim_k (XSYM)_i \, t^{i} "
        r"= \frac{\sum_j h_j t^{j}}{(1-t)^{d}}",
        r"\chi(\mathbf{x}; M) = \sum_{i=0}^{n} (-1)^{i} \ell\bigl(H_i(\mathbf{x}; M)\bigr)",
        r"0 \to R \xrightarrow{\cdot x_1} R \to R/(x_1) \to 0",
        r"\operatorname{reg} XSYM = \max\{\, j - i : \beta_{i,j}(XSYM) \neq 0 \,\}",
        r"\ell(R/I^{n}) = \frac{e(I)}{d!}\, n^{d} + O(n^{d-1})",
        r"H_{\mathfrak{m}}^{i}(M) \cong "
        r"\operatorname{Hom}_R\bigl(\operatorname{Ext}_R^{d-i}(M, \omega_R), E\bigr)",
        r"0 \to M' \to M \to M'' \to 0 \;\Rightarrow\; "
        r"\operatorname{depth} M \ge \min\{\operatorname{depth} M', \operatorname{depth} M''\}",
        r"K_\bullet(\mathbf{x}; R): \quad 0 \to \textstyle\bigwedge^{n} R^{n} "
        r"\to \cdots \to \textstyle\bigwedge^{1} R^{n} \to R \to 0",
        r"\dim R = \sup\{\, n : \mathfrak{p}_0 \subsetneq \mathfrak{p}_1 "
        r"\subsetneq \cdots \subsetneq \mathfrak{p}_n \,\}",
        r"I = \bigcap_{i=1}^{r} \mathfrak{q}_i, \qquad "
        r"\sqrt{\mathfrak{q}_i} = \mathfrak{p}_i \text{ distinct}",
        r"P_{XSYM}(t) = \sum_{i \ge 0} \dim_k \operatorname{Tor}_i^R(XSYM, k)\, t^{i}",
        r"e_{HK}(R) = \lim_{n \to \infty} \frac{\ell\bigl(R/\mathfrak{m}^{[p^n]}\bigr)}{p^{nd}}",
        r"\beta_i(XSYM) = \dim_k \operatorname{Tor}_i^R(XSYM, k) "
        r"= \sum_j \beta_{i,j}(XSYM)",
        r"\operatorname{Ass}(M) \subseteq \operatorname{Supp}(M), \qquad "
        r"\operatorname{Min}(M) \subseteq \operatorname{Ass}(M)",
        r"0 \to \omega_R \to F^{0} \to \cdots \to F^{d} \to 0, \qquad "
        r"F^{i} \text{ injective}",
        r"\overline{I^{n}} \subseteq I^{\,n - d + 1} \quad \text{for all } n \ge d",
    ],
    msc=["13D02", "13H10", "13D45", "13C14", "13F55", "13A35", "13D40", "13P10"],
    adjacent=["math.AG", "math.RA"],
)
