"""math.AG - Algebraic Geometry.

Seed from the build spec, expanded with the algebra/number-theory research
dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

AG = SubfieldLexicon(
    code="math.AG",
    name="Algebraic Geometry",
    weight=10.0,
    banks={
        "objects": [
            "smooth projective variety",
            "abelian variety",
            "elliptic curve",
            "K3 surface",
            "hyper-Kähler manifold",
            "Calabi--Yau threefold",
            "Fano threefold",
            "del Pezzo surface",
            "rational surface",
            "Enriques surface",
            "toric variety",
            "Shimura variety",
            "moduli space",
            "moduli stack",
            "moduli stack of vector bundles",
            "Hilbert scheme",
            "Quot scheme",
            "coherent sheaf",
            "vector bundle",
            "line bundle",
            "Higgs bundle",
            "vector bundle on a curve",
            "perverse sheaf",
            "$\\ell$-adic sheaf",
            "divisor",
            "canonical divisor",
            "ample divisor",
            "linear system",
            "rational curve",
            "algebraic cycle",
            "zero-cycle",
            "Chow group",
            "motive",
            "Hodge structure",
            "variation of Hodge structure",
            "flag variety",
            "Schubert variety",
            "Grassmannian",
            "quiver variety",
            "blow-up",
            "deformation",
            "log scheme",
            "perfectoid space",
            "algebraic stack",
        ],
        "props": [
            "smooth",
            "proper",
            "projective",
            "affine",
            "quasi-projective",
            "étale",
            "flat",
            "unramified",
            "normal",
            "regular",
            "integral",
            "reduced",
            "irreducible",
            "geometrically irreducible",
            "geometrically connected",
            "rational",
            "unirational",
            "rationally connected",
            "Fano",
            "Calabi--Yau",
            "of general type",
            "minimal",
            "canonical",
            "terminal",
            "log canonical",
            "ample",
            "very ample",
            "nef",
            "big",
            "semistable",
            "stable",
            "polystable",
            "torsion-free",
            "locally free",
            "reflexive",
            "perverse",
            "equivariant",
            "toric",
            "perfectoid",
            "of finite type",
        ],
        "spaces": [
            "moduli space",
            "moduli stack",
            "coarse moduli space",
            "good moduli space",
            "Hilbert scheme",
            "Picard scheme",
            "Albanese variety",
            "Jacobian variety",
            "intermediate Jacobian",
            "Néron--Severi group",
            "Chow ring",
            "derived category of coherent sheaves",
            "bounded derived category",
            "Picard group",
            "Brauer group",
            "automorphism group scheme",
            "stack of $G$-bundles",
            "affine Grassmannian",
            "period domain",
            "Berkovich analytification",
        ],
        "maps": [
            "the structure morphism",
            "Frobenius",
            "the canonical map",
            "the Albanese map",
            "the Abel--Jacobi map",
            "the period map",
            "the cycle class map",
            "the Hodge bundle projection",
            "the Fourier--Mukai transform",
            "the Gauss--Manin connection",
            "blow-up",
            "normalization",
            "base change",
            "specialization",
            "the Kodaira--Spencer map",
        ],
        "invariants": [
            "dimension",
            "degree",
            "genus",
            "arithmetic genus",
            "geometric genus",
            "Kodaira dimension",
            "canonical class",
            "Picard number",
            "Hodge number",
            "Betti number",
            "Euler characteristic",
            "holomorphic Euler characteristic",
            "Chern class",
            "Chern character",
            "Todd class",
            "intersection number",
            "self-intersection number",
            "Hilbert polynomial",
            "Hilbert series",
            "plurigenus",
            "irregularity",
            "canonical volume",
            "discrepancy",
            "slope",
            "Frobenius trace",
        ],
        "namedResults": [
            "the Hodge conjecture",
            "the Tate conjecture",
            "the Weil conjectures",
            "Grothendieck--Riemann--Roch",
            "the Hirzebruch--Riemann--Roch theorem",
            "Serre duality",
            "the Kodaira vanishing theorem",
            "the Kawamata--Viehweg vanishing theorem",
            "the minimal model program",
            "the Beauville--Voisin conjecture",
            "Bloch's conjecture",
            "the Mumford--Tate conjecture",
            "the Standard Conjectures",
            "the Lefschetz hyperplane theorem",
            "the hard Lefschetz theorem",
            "the decomposition theorem",
            "Mori's cone theorem",
            "the Bogomolov--Miyaoka--Yau inequality",
            "Castelnuovo's contraction theorem",
            "the Torelli theorem",
            "the Enriques--Kodaira classification",
            "Matsusaka's big theorem",
            "the Nakai--Moishezon criterion",
            "Hironaka's resolution of singularities",
            "the Deligne--Mumford compactification",
        ],
        "methods": [
            "the minimal model program",
            "intersection theory",
            "deformation theory",
            "Hodge theory",
            "$p$-adic Hodge theory",
            "the theory of perverse sheaves",
            "vanishing theorems",
            "the decomposition theorem",
            "Fourier--Mukai techniques",
            "geometric invariant theory",
            "stack-theoretic methods",
            "Mori theory",
            "wall-crossing",
            "the theory of stability conditions",
            "specialization arguments",
            "a degeneration argument",
            "the theory of motives",
            "$\\ell$-adic cohomology",
            "the Weil conjectures",
            "Bridgeland stability",
            "the language of derived categories",
            "Gromov--Witten theory",
            "tropical methods",
            "an analysis of the Hodge filtration",
        ],
        "objectGloss": [
            "encodes the geometry of the underlying variety",
            "governs the classification of algebraic surfaces",
            "arises naturally in the minimal model program",
            "controls the moduli of the associated sheaves",
            "is central to modern algebraic geometry",
            "reflects the Hodge structure on cohomology",
            "parametrizes deformations of the underlying object",
            "lies at the heart of the theory of motives",
        ],
    },
    # Object-naming letters only, kept disjoint from the running symbols in the
    # equation pool: no "Y" (target of f: X -> Y), no "C" (a curve), no "M"
    # (moduli M_g), no "T"/"P" (tangent sheaf, Hilbert polynomial), and none of
    # \mathcal{F}, \mathcal{L}, \mathcal{M} (the running sheaf/bundle/moduli).
    symbols=[
        "X",
        "S",
        "V",
        "W",
        "B",
        "A",
        "G",
        "D",
        "\\mathcal{E}",
        "\\mathcal{X}",
        "\\mathcal{Y}",
        "\\mathfrak{M}",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\dim XSYM = @N@",
        r"\deg XSYM = @N@",
        r"K_{XSYM}^{2} = @N@",
        r"\dim H^{@I@}(XSYM, \mathcal{O}_{XSYM}) = @R@",
        r"\chi(XSYM, \mathcal{O}_{XSYM}) = @R@",
        r"p_g(XSYM) = @R@",
        r"q(XSYM) = @R@",
        r"\kappa(XSYM) = @R@",
        r"h^{@I@,@I@}(XSYM) = @N@",
        r"\rho(XSYM) = @N@",
        r"c_1(XSYM)^{@C@} = @N@",
        r"\mathrm{Pic}(XSYM) \cong \mathbb{Z}^{@C@}",
        r"H^{@I@}(XSYM, \mathcal{O}_{XSYM}) = 0",
        r"\omega_{XSYM} \cong \mathcal{O}_{XSYM}",
        r"K_{XSYM} \sim_{\mathbb{Q}} 0",
        r"XSYM \hookrightarrow \mathbb{P}^{@N@}",
        r"\mathrm{NS}(XSYM) \otimes \mathbb{Q} \cong \mathbb{Q}^{@C@}",
        r"\mu(ASYM) = \frac{\deg ASYM}{\operatorname{rk} ASYM}",
        r"\operatorname{rk} ASYM = @C@",
        r"\#\,XSYM(\mathbb{F}_q) = q^{@N@} + O(q^{@R@})",
        r"H^{2i}(XSYM, \mathbb{Q})^{\,\mathrm{Hdg}} \neq 0",
        r"\mathrm{CH}^{@I@}(XSYM)_{\mathbb{Q}} \cong \mathbb{Q}",
        r"\mathrm{Ext}^{@I@}(\mathcal{F}, \mathcal{G}) = 0",
        r"\chi(\mathcal{F}) = \deg \mathcal{F} + \operatorname{rk}\mathcal{F}",
        r"-K_{XSYM} \text{ is ample}",
        r"c_2(XSYM) \cdot H = @N@",
        r"\dim M_{g} = 3g - 3",
        r"g(C) = \tfrac{1}{2}(d-1)(d-2)",
        r"\mathrm{Aut}(XSYM) \text{ is finite}",
        r"\phi_{|K_{XSYM}|} \colon XSYM \dashrightarrow \mathbb{P}^{@N@}",
        r"h^{0}(XSYM, \mathcal{L}) = @N@",
        r"\mathcal{L}^{@C@} \cdot \mathcal{L}' = @N@",
        r"\operatorname{td}(XSYM) = 1 + \tfrac{1}{2}c_1 + \cdots",
        r"\beta_i(XSYM) = @N@",
        r"\mathrm{Br}(XSYM)[\ell] = @R@",
    ],
    display_eqns=[
        r"\chi(XSYM, \mathcal{F}) = \int_{XSYM} "
        r"\operatorname{ch}(\mathcal{F}) \,\operatorname{td}(T_{XSYM})",
        r"H^{i}(XSYM, \mathcal{F}) \times H^{n-i}(XSYM, "
        r"\omega_{XSYM} \otimes \mathcal{F}^{\vee}) \to H^{n}(XSYM, "
        r"\omega_{XSYM}) \cong k",
        r"\chi(\mathcal{O}_{XSYM}) = \frac{c_1^{2} + c_2}{12} "
        r"\qquad \text{(Noether's formula)}",
        r"H^{k}(XSYM, \mathbb{C}) = \bigoplus_{p+q=k} "
        r"H^{p,q}(XSYM), \qquad H^{q,p} = \overline{H^{p,q}}",
        r"\sum_{i} (-1)^{i} \dim H^{i}(XSYM, \mathbb{Q}) "
        r"= \int_{XSYM} c_{n}(T_{XSYM})",
        r"0 \to \mathcal{O}_{XSYM}(-@N@) \to \mathcal{O}_{XSYM} "
        r"\to \mathcal{O}_{ASYM} \to 0",
        r"H^{i}(XSYM, \mathcal{L}) = 0 \quad \text{for } i > 0, "
        r"\ \mathcal{L} = \omega_{XSYM} \otimes \mathcal{A}, "
        r"\ \mathcal{A} \text{ ample}",
        r"Z(XSYM, t) = \prod_{i=0}^{2n} \det\bigl(1 - t\,\mathrm{Frob} "
        r"\mid H^{i}_{\mathrm{\acute{e}t}}(XSYM)\bigr)^{(-1)^{i+1}}",
        r"\#\,XSYM(\mathbb{F}_{q}) = \sum_{i=0}^{2n} (-1)^{i} "
        r"\operatorname{tr}\bigl(\mathrm{Frob} \mid "
        r"H^{i}_{\mathrm{\acute{e}t}}(XSYM, \mathbb{Q}_{\ell})\bigr)",
        r"K_{XSYM} \equiv f^{*} K_{Y} + \sum_{i} a_i E_i, "
        r"\qquad a_i > -1",
        r"\overline{\mathrm{NE}}(XSYM) = \overline{\mathrm{NE}}(XSYM)_{K_{XSYM} \ge 0} "
        r"+ \sum_{j} \mathbb{R}_{\ge 0} [C_j]",
        r"c_1(XSYM)^{2} \le 3\,c_2(XSYM) "
        r"\qquad \text{for } XSYM \text{ of general type}",
        r"P(XSYM, m) = \chi\bigl(XSYM, \mathcal{O}_{XSYM}(m)\bigr) "
        r"= \frac{H^{n}}{n!}\,m^{n} + O(m^{n-1})",
        r"0 \to H^{1}(XSYM, \mathcal{O}_{XSYM}) \to "
        r"\mathrm{Pic}(XSYM) \to \mathrm{NS}(XSYM) \to 0",
        r"\mathrm{ch}(\mathcal{F}) = \operatorname{rk}\mathcal{F} "
        r"+ c_1(\mathcal{F}) + \tfrac{1}{2}\bigl(c_1^{2} - 2c_2\bigr) + \cdots",
        r"H^{q,p}(XSYM) \cong H^{p}\bigl(XSYM, \Omega_{XSYM}^{q}\bigr), "
        r"\qquad b_k = \sum_{p+q=k} h^{p,q}",
        r"\mathrm{Rf}_{*}\,\mathbb{Q}_{XSYM} \cong \bigoplus_{i} "
        r"{}^{p}\!\mathcal{H}^{i}(\mathrm{Rf}_{*}\mathbb{Q}_{XSYM})[-i]",
        r"\dim \mathcal{M}_{XSYM}(v) = 1 + \langle v, v \rangle, "
        r"\qquad v = \operatorname{ch}(\mathcal{F})\sqrt{\operatorname{td}}",
    ],
    msc=["14J60", "14F22", "14D20", "14C30", "14E30", "14G15", "14F08", "14H60"],
    adjacent=["math.NT", "math.RT", "math.AC"],
)
