"""math.AP - Analysis of PDEs.

Seed from the build spec, expanded with the analysis research dossier into a
broad working vocabulary centered on PDEs, estimates, and well-posedness.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

AP = SubfieldLexicon(
    code="math.AP",
    name="Analysis of PDEs",
    weight=8.0,
    banks={
        "objects": [
            "weak solution",
            "viscosity solution",
            "mild solution",
            "classical solution",
            "renormalized solution",
            "entropy solution",
            "self-similar solution",
            "traveling wave",
            "standing wave",
            "ground state",
            "soliton",
            "blow-up solution",
            "free boundary",
            "minimal surface",
            "self-shrinker",
            "harmonic map",
            "heat kernel",
            "fundamental solution",
            "Green's function",
            "the Navier--Stokes equations",
            "the Euler equations",
            "the nonlinear Schrödinger equation",
            "the wave equation",
            "the heat equation",
            "the porous medium equation",
            "the thin-film equation",
            "the Hamilton--Jacobi equation",
            "the Monge--Ampère equation",
            "the Yamabe flow",
            "the $p$-Laplacian",
            "the fractional Laplacian",
            "the Schrödinger operator",
            "the heat semigroup",
            "an energy functional",
            "an obstacle problem",
            "a transport equation",
            "a kinetic equation",
            "a reaction--diffusion system",
            "a conservation law",
            "an elliptic operator",
            "the initial data",
            "the nonlinearity",
            "the dissipation",
        ],
        "props": [
            "elliptic",
            "parabolic",
            "hyperbolic",
            "dispersive",
            "fully nonlinear",
            "quasilinear",
            "semilinear",
            "dissipative",
            "degenerate",
            "singular",
            "nonlocal",
            "fractional",
            "subcritical",
            "critical",
            "supercritical",
            "doubly critical",
            "incompressible",
            "viscous",
            "stationary",
            "self-adjoint",
            "hypoelliptic",
            "uniformly elliptic",
            "weakly nonlinear",
            "globally well-posed",
            "locally well-posed",
            "anisotropic",
            "isotropic",
            "radial",
            "rotationally symmetric",
            "low-regularity",
            "high-energy",
            "defocusing",
            "focusing",
            "energy-critical",
            "mass-critical",
            "scale-invariant",
            "conservative",
            "monotone",
            "coercive",
        ],
        "spaces": [
            "Sobolev space",
            "homogeneous Sobolev space",
            "Besov space",
            "Triebel--Lizorkin space",
            "Lebesgue space",
            "weighted Lebesgue space",
            "Hardy space",
            "the space $\\mathrm{BMO}$",
            "Morrey space",
            "the space of finite-energy data",
            "Schwartz space",
            "the space of tempered distributions",
            "the Strichartz space",
            "the energy space",
            "a bounded Lipschitz domain",
            "a smooth domain",
            "the exterior domain",
            "the torus",
            "the half-space",
            "the configuration space",
        ],
        "maps": [
            "the Laplacian",
            "the gradient",
            "the divergence operator",
            "the heat semigroup",
            "the Schrödinger propagator",
            "the resolvent",
            "the Riesz transform",
            "the trace operator",
            "the harmonic extension",
            "the Dirichlet-to-Neumann map",
            "the Hardy--Littlewood maximal operator",
            "the Leray projection",
            "the Littlewood--Paley projection",
            "the fractional Laplacian",
            "the heat flow",
        ],
        "invariants": [
            "energy",
            "mass",
            "momentum",
            "Hamiltonian",
            "scaling exponent",
            "regularity threshold",
            "blow-up rate",
            "decay rate",
            "lifespan",
            "Lyapunov functional",
            "dissipation rate",
            "Morse index",
            "ground-state energy",
            "critical Sobolev exponent",
            "concentration profile",
            "best constant",
            "spectral gap",
            "first eigenvalue",
            "modulus of continuity",
            "free-energy",
            "entropy",
            "enstrophy",
            "scattering norm",
            "regularity index",
            "principal eigenvalue",
        ],
        "namedResults": [
            "the Strichartz estimates",
            "the Sobolev embedding",
            "the Gagliardo--Nirenberg inequality",
            "the Caffarelli--Kohn--Nirenberg inequalities",
            "the Carleman estimates",
            "the Hörmander condition",
            "the Faber--Krahn inequality",
            "the logarithmic Sobolev inequality",
            "the Hardy inequality",
            "the Calderón--Zygmund theory",
            "the Littlewood--Paley theory",
            "the Serrin regularity criterion",
            "the Aubin--Lions lemma",
            "the De Giorgi--Nash--Moser theory",
            "the Harnack inequality",
            "the Pohozaev identity",
            "the Schauder estimates",
            "the maximum principle",
            "the Lax--Milgram theorem",
            "the Brezis--Lieb lemma",
            "the concentration--compactness principle",
            "the Trudinger--Moser inequality",
            "the Agmon--Douglis--Nirenberg estimates",
            "the Cordes condition",
            "the Onsager conjecture",
        ],
        "methods": [
            "energy methods",
            "a fixed-point argument",
            "the contraction mapping principle",
            "a compactness argument",
            "the concentration--compactness method",
            "the method of moving planes",
            "the vanishing viscosity method",
            "the Galerkin approximation",
            "a bootstrap argument",
            "the Littlewood--Paley decomposition",
            "Strichartz estimates",
            "Carleman estimates",
            "a priori estimates",
            "the De Giorgi iteration",
            "the variational method",
            "the viscosity-solution framework",
            "a perturbation argument",
            "the I-method",
            "the profile decomposition",
            "the heat-flow method",
            "a barrier construction",
            "the maximum principle",
            "duality arguments",
            "the moment method",
        ],
        "objectGloss": [
            "encodes the dissipation of energy in the system",
            "arises naturally in the study of nonlinear waves",
            "governs the long-time behavior of solutions",
            "controls the regularity of the flow",
            "is central to the modern theory of PDEs",
            "reflects the scaling symmetry of the equation",
            "captures the formation of singularities",
            "lies at the heart of the calculus of variations",
        ],
    },
    # Object-naming letters only. No "u","v","w","p" (reserved for solutions and
    # pressure), no "H","L" (operators/spaces), no "\Omega" (the domain).
    symbols=[
        "U",
        "\\Phi",
        "\\Psi",
        "G",
        "Q",
        "S",
        "\\Sigma",
        "\\Gamma",
        "F",
        "Z",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\lVert XSYM \rVert_{H^{@C@}} \le C\,\lVert ASYM \rVert_{L^{2}}",
        r"\lVert XSYM(t) \rVert_{L^{\infty}} \lesssim t^{-@K@}",
        r"H^{@C@}(\mathbb{R}^{@N@}) \hookrightarrow L^{q}(\mathbb{R}^{@N@})",
        r"-\Delta XSYM = \lambda\, XSYM \quad\text{in } \Omega",
        r"XSYM = 0 \quad\text{on } \partial\Omega",
        r"\lVert XSYM \rVert_{L^{p}} \le C\,\lVert \nabla XSYM \rVert_{L^{2}}",
        r"\partial_t XSYM = \Delta XSYM + f(XSYM)",
        r"\lambda_1(\Omega) \ge \frac{C}{|\Omega|^{2/@N@}}",
        r"\sigma(H) = [0,\infty) \cup \{\lambda_j\}_{j \ge 1}",
        r"\lVert XSYM \rVert_{\dot H^{@C@}} \approx \lVert |\nabla|^{@C@} XSYM \rVert_{L^{2}}",
        r"\lVert e^{it\Delta} ASYM \rVert_{L^{q}_t L^{r}_x} \lesssim \lVert ASYM \rVert_{L^{2}}",
        r"E(XSYM) = \tfrac12 \lVert \nabla XSYM \rVert_{L^{2}}^{2}"
        r" - \tfrac{1}{q} \lVert XSYM \rVert_{L^{q}}^{q}",
        r"\frac{d}{dt} \lVert XSYM \rVert_{L^{2}}^{2}"
        r" \le -c\,\lVert \nabla XSYM \rVert_{L^{2}}^{2}",
        r"\lVert XSYM \rVert_{L^{q}} \le C\,\lVert XSYM \rVert_{L^{2}}^{1-\theta}"
        r" \lVert \nabla XSYM \rVert_{L^{2}}^{\theta}",
        r"u(t) \to 0 \quad\text{as } t \to \infty",
        r"T^{*} = T^{*}(XSYM) < \infty",
        r"\lVert XSYM(t) \rVert_{H^{1}} \le \lVert ASYM \rVert_{H^{1}} e^{Ct}",
        r"\langle XSYM, ASYM \rangle = \int_{\Omega} XSYM\, ASYM \, dx",
        r"\dim \ker(L - \lambda) = @N@",
        r"\lVert XSYM \rVert_{B^{@C@}_{p,q}} < \infty",
        r"\Delta XSYM + |XSYM|^{p-1} XSYM = 0",
        r"\lVert XSYM \rVert_{\mathrm{BMO}} \le C\,\lVert ASYM \rVert_{L^{\infty}}",
        r"s_c = \frac{@N@}{2} - \frac{2}{p-1}",
        r"\lVert XSYM(t) \rVert_{L^{2}} = \lVert ASYM \rVert_{L^{2}}",
        r"\liminf_{t \to T^{*}} \lVert \nabla XSYM(t) \rVert_{L^{2}} = \infty",
        r"(-\Delta)^{s} XSYM = \lambda\, XSYM",
        r"\lVert XSYM \rVert_{W^{@I@,p}}"
        r" \le C\bigl(\lVert XSYM \rVert_{L^{p}} + \lVert \Delta XSYM \rVert_{L^{p}}\bigr)",
        r"\mathrm{div}\, XSYM = 0",
        r"\sigma_{\mathrm{ess}}(H) = [@R@,\infty)",
        r"\lVert XSYM \rVert_{L^{\infty}} \le C\,\lVert XSYM \rVert_{H^{@C@}}",
    ],
    display_eqns=[
        r"\partial_t XSYM + (XSYM \cdot \nabla) XSYM = -\nabla p + \nu \Delta XSYM, "
        r"\qquad \mathrm{div}\, XSYM = 0",
        r"i\,\partial_t XSYM + \Delta XSYM = \mu\,|XSYM|^{p-1} XSYM, "
        r"\qquad XSYM(0) = ASYM",
        r"\begin{cases} \partial_t XSYM = \Delta XSYM + f(XSYM) "
        r"& \text{in } \Omega \times (0,T), \\ "
        r"XSYM = 0 & \text{on } \partial\Omega, \\ "
        r"XSYM(\cdot,0) = ASYM & \text{in } \Omega. \end{cases}",
        r"\lVert e^{it\Delta} ASYM \rVert_{L^{q}_t L^{r}_x(\mathbb{R} \times \mathbb{R}^{@N@})} "
        r"\le C\,\lVert ASYM \rVert_{L^{2}(\mathbb{R}^{@N@})}, "
        r"\qquad \frac{2}{q} + \frac{@N@}{r} = \frac{@N@}{2}",
        r"\lVert XSYM \rVert_{L^{q}(\mathbb{R}^{@N@})} "
        r"\le C\,\lVert \nabla XSYM \rVert_{L^{p}(\mathbb{R}^{@N@})}, "
        r"\qquad \frac{1}{q} = \frac{1}{p} - \frac{1}{@N@}",
        r"E(XSYM(t)) = \frac{1}{2}\int_{\mathbb{R}^{@N@}} |\nabla XSYM|^{2}\, dx "
        r"- \frac{1}{p+1}\int_{\mathbb{R}^{@N@}} |XSYM|^{p+1}\, dx = E(ASYM)",
        r"\frac{1}{2}\frac{d}{dt}\lVert XSYM(t) \rVert_{L^{2}}^{2} "
        r"+ \nu \int_{\Omega} |\nabla XSYM|^{2}\, dx = \int_{\Omega} f \cdot XSYM \, dx",
        r"\lambda_1(\Omega) = \inf_{XSYM \in H^1_0(\Omega) \setminus \{0\}} "
        r"\frac{\int_{\Omega} |\nabla XSYM|^{2}\, dx}{\int_{\Omega} |XSYM|^{2}\, dx}",
        r"\int_{\mathbb{R}^{@N@}} |\nabla XSYM|^{2}\, dx \ge S\left(\int_{\mathbb{R}^{@N@}} "
        r"|XSYM|^{2^{*}}\, dx\right)^{2/2^{*}}, \qquad 2^{*} = \frac{2@N@}{@N@-2}",
        r"XSYM(t,x) = e^{t\Delta} ASYM(x) "
        r"+ \int_0^t e^{(t-s)\Delta} f(XSYM(s))\, ds",
        r"\sigma(H) = \sigma_{\mathrm{ess}}(H) \cup \sigma_{\mathrm{disc}}(H), "
        r"\qquad H = -\Delta + V",
        r"\lVert XSYM \rVert_{L^{q}} \le C\, \lVert XSYM \rVert_{L^{2}}^{1-\theta}\, "
        r"\lVert \nabla XSYM \rVert_{L^{2}}^{\theta}, "
        r"\qquad \theta = @N@\!\left(\frac{1}{2}-\frac{1}{q}\right)",
        r"-\Delta XSYM = |XSYM|^{2^{*}-2} XSYM \quad\text{in } \mathbb{R}^{@N@}, "
        r"\qquad XSYM > 0, \quad XSYM \in \dot H^{1}(\mathbb{R}^{@N@})",
        r"\frac{d}{dt}\int_{\Omega} G(XSYM)\, dx + \int_{\Omega} |\nabla XSYM|^{2}\, dx \le 0",
        r"\lVert XSYM(t) \rVert_{L^{\infty}(\mathbb{R}^{@N@})} "
        r"\le C\,(1+t)^{-@N@/2}\,\lVert ASYM \rVert_{L^{1}(\mathbb{R}^{@N@})}",
        r"\int_{\Omega} |\nabla XSYM|^{p}\, dx \le \frac{1}{p}\int_{\partial\Omega} "
        r"XSYM\,|\nabla XSYM|^{p-2}\,\partial_\nu XSYM \, dS",
        r"\partial_t XSYM = \Delta\bigl(XSYM^{m}\bigr) "
        r"\quad\text{in } \mathbb{R}^{@N@} \times (0,\infty), \qquad m > 1",
        r"\frac{@N@-2}{2}\int_{\mathbb{R}^{@N@}} |\nabla XSYM|^{2}\, dx "
        r"= \frac{@N@}{p+1}\int_{\mathbb{R}^{@N@}} |XSYM|^{p+1}\, dx",
        r"\lVert XSYM \rVert_{\dot B^{@C@}_{p,q}}^{q} = \sum_{j \in \mathbb{Z}} "
        r"2^{jq@C@}\,\lVert \Delta_j XSYM \rVert_{L^{p}}^{q}",
    ],
    msc=["35Q30", "35J60", "35K55", "35L05", "35B44", "35P15", "35A01", "35B65"],
    adjacent=["math.FA", "math.SP", "math.CA"],
)
