"""math.AT - Algebraic Topology.

Seed from the build spec, expanded with the geometry/topology research
dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

AT = SubfieldLexicon(
    code="math.AT",
    name="Algebraic Topology",
    weight=6.0,
    banks={
        "objects": [
            "spectrum",
            "ring spectrum",
            "$E_\\infty$-ring spectrum",
            "Thom spectrum",
            "suspension spectrum",
            "sphere spectrum",
            "fiber bundle",
            "fibration",
            "cofibration",
            "CW complex",
            "simplicial set",
            "classifying space",
            "Eilenberg--MacLane space",
            "loop space",
            "infinite loop space",
            "cobordism",
            "spin bordism",
            "characteristic class",
            "Chern class",
            "Stiefel--Whitney class",
            "Pontryagin class",
            "spectral sequence",
            "the Adams spectral sequence",
            "the Atiyah--Hirzebruch spectral sequence",
            "operad",
            "the little disks operad",
            "the spectral Lie operad",
            "the Steenrod algebra",
            "a Steenrod operation",
            "configuration space",
            "the cohomology ring",
            "a homotopy group",
            "a stable homotopy group",
            "a Postnikov tower",
            "a vector bundle",
            "an $\\infty$-category",
            "a model category",
            "a chain complex",
            "a simplicial complex",
            "persistent homology",
            "the Vietoris--Rips complex",
            "the Mapper graph",
        ],
        "props": [
            "stable",
            "unstable",
            "simply connected",
            "$n$-connected",
            "aspherical",
            "contractible",
            "acyclic",
            "fibrant",
            "cofibrant",
            "simplicial",
            "cosimplicial",
            "equivariant",
            "$G$-equivariant",
            "rational",
            "$p$-local",
            "$p$-complete",
            "chromatic",
            "highly structured",
            "$E_\\infty$",
            "$A_\\infty$",
            "homotopy-coherent",
            "homotopy-invariant",
            "monoidal",
            "symmetric monoidal",
            "triangulated",
            "derived",
            "spectral",
            "connective",
            "coconnective",
            "dualizable",
            "compact",
            "perfect",
            "orientable",
            "framed",
            "filtered",
            "graded",
            "free",
            "finitely generated",
            "torsion",
            "nilpotent",
        ],
        "spaces": [
            "classifying space",
            "the classifying space $BG$",
            "loop space",
            "free loop space",
            "the stable homotopy category",
            "the derived category",
            "configuration space",
            "the Thom space",
            "the cobordism category",
            "the moduli space of curves",
            "the bordism spectrum",
            "the $K$-theory spectrum",
            "topological Hochschild homology",
            "topological cyclic homology",
            "the function spectrum",
            "the mapping space",
            "the homotopy fixed point spectrum",
            "the Tate construction",
            "the geometric realization",
            "the simplicial nerve",
        ],
        "maps": [
            "the suspension map",
            "the Hurewicz map",
            "the connecting homomorphism",
            "the boundary map",
            "the Thom isomorphism",
            "the transfer map",
            "the unit map",
            "the assembly map",
            "the cup product",
            "the Bockstein homomorphism",
            "a Steenrod operation",
            "the Adams operation",
            "the Pontryagin--Thom collapse",
            "the cyclotomic Frobenius",
            "the diagonal map",
        ],
        "invariants": [
            "a homotopy group",
            "a stable homotopy group",
            "a homology group",
            "a cohomology group",
            "the cohomology ring",
            "the Euler characteristic",
            "the cup-length",
            "the Lusternik--Schnirelmann category",
            "the topological complexity",
            "the cohomological dimension",
            "a Betti number",
            "a characteristic number",
            "the signature",
            "the $\\hat A$-genus",
            "a bordism class",
            "the $K$-theory class",
            "a Steenrod operation",
            "the Chern character",
            "the Hopf invariant",
            "the Adams filtration",
            "a persistence barcode",
            "a persistence diagram",
            "the chromatic height",
            "the Toda bracket",
            "the Massey product",
        ],
        "namedResults": [
            "the Whitehead theorem",
            "the Hurewicz theorem",
            "the Freudenthal suspension theorem",
            "the Atiyah--Singer index theorem",
            "the Adams conjecture",
            "the Sullivan conjecture",
            "the Segal conjecture",
            "the Brown representability theorem",
            "the Bott periodicity theorem",
            "the nilpotence theorem",
            "the periodicity theorem",
            "the Quillen--Lichtenbaum conjecture",
            "the Hopkins--Miller theorem",
            "the Kervaire invariant one problem",
            "the Arone--Mahowald theorem",
            "the Eilenberg--Zilber theorem",
            "the Dold--Kan correspondence",
            "the Barratt--Priddy--Quillen theorem",
            "the Madsen--Weiss theorem",
            "the Atiyah--Hirzebruch spectral sequence",
            "the Mahowald--Ravenel--Shick conjecture",
            "the redshift conjecture",
            "the telescope conjecture",
            "the Goodwillie--Weiss calculus",
            "the Adams--Novikov spectral sequence",
        ],
        "methods": [
            "spectral sequences",
            "the Adams spectral sequence",
            "chromatic homotopy theory",
            "obstruction theory",
            "Goodwillie calculus",
            "the theory of operads",
            "rational homotopy theory",
            "equivariant stable homotopy theory",
            "the bar construction",
            "the theory of model categories",
            "$\\infty$-categorical methods",
            "the Pontryagin--Thom construction",
            "Morse theory",
            "the Serre spectral sequence",
            "Steenrod operations",
            "localization techniques",
            "the theory of $\\infty$-operads",
            "persistent homology",
            "the descent spectral sequence",
            "a comparison of spectral sequences",
            "the theory of Postnikov towers",
            "an Euler characteristic computation",
            "the cobordism hypothesis",
            "a Quillen equivalence",
        ],
        "objectGloss": [
            "encodes stable homotopy-theoretic information",
            "arises naturally in chromatic homotopy theory",
            "organizes the higher structure of mapping spaces",
            "is central to the study of cobordism",
            "reflects the symmetry of the underlying spectrum",
            "controls the global structure of the homotopy category",
            "detects subtle torsion in homotopy groups",
            "lies at the heart of stable homotopy theory",
        ],
    },
    # Object-naming letters only. No "K" (clashes with $K$-theory) and no
    # "n" (reserved as the running connectivity/dimension index).
    symbols=[
        "X",
        "Y",
        "Z",
        "E",
        "F",
        "B",
        "R",
        "S",
        "\\mathcal{C}",
        "\\mathcal{D}",
        "M",
        "G",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\pi_{@I@}(XSYM) = \mathbb{Z}/@N@",
        r"H^{@I@}(XSYM;\mathbb{Z}) = \mathbb{Z}^{@N@}",
        r"\dim H_{@I@}(XSYM;\mathbb{Q}) = @N@",
        r"\chi(XSYM) = @R@",
        r"H^*(XSYM) \cong \mathbb{Z}[x]/(x^{@N@})",
        r"\pi_{@I@}^{s} = \mathbb{Z}/@N@",
        r"\mathrm{Sq}^{@I@} x = x^2",
        r"b_{@I@}(XSYM) = @N@",
        r"\widetilde H_{@I@}(S^{@N@}) = \mathbb{Z}",
        r"\mathrm{cd}(XSYM) = @N@",
        r"\mathrm{cat}(XSYM) \le @N@",
        r"\mathrm{TC}(XSYM) = @N@",
        r"[XSYM] = @R@ \in \Omega^{\mathrm{SO}}_{@N@}",
        r"c_{@I@}(E) \in H^{2@I@}(XSYM)",
        r"w_{@I@}(E) \in H^{@I@}(XSYM;\mathbb{F}_2)",
        r"\Sigma^\infty XSYM \to \mathbb{S}",
        r"E_2^{p,q} \Rightarrow H^{p+q}(XSYM)",
        r"\pi_0(XSYM) = \ast",
        r"L_{@N@} \mathbb{S} \to \mathbb{S}",
        r"\dim_{\mathbb{F}_p} H^*(XSYM) = @N@",
        r"\mathrm{ch}(E) = @R@ + c_1(E)",
        r"f_* : \pi_{@I@}(XSYM) \xrightarrow{\sim} \pi_{@I@}(ASYM)",
        r"H_{@I@}(XSYM) = 0",
        r"\Omega XSYM \simeq ASYM",
        r"K(\mathbb{Z},@N@) = XSYM",
        r"\theta_j \in \pi_{2^{j+1}-2}^{s}",
        r"\mathrm{Ext}^{@I@,@N@}_{\mathcal{A}}(\mathbb{F}_p,\mathbb{F}_p)",
        r"\mathrm{rk}\, K^0(XSYM) = @N@",
        r"d_{@I@}(x) = y",
        r"\langle x, y, z \rangle \subseteq H^*(XSYM)",
        r"\mathrm{cofib}(f) \simeq ASYM",
        r"\pi_*(XSYM) = \mathbb{F}_p[v_{@N@}]",
        r"\widehat H^*(XSYM) = 0",
        r"\mathrm{ht}(XSYM) = @N@",
    ],
    display_eqns=[
        r"\cdots \to \pi_{@I@}(F) \to \pi_{@I@}(E) "
        r"\to \pi_{@I@}(B) \to \pi_{@I@ - 1}(F) \to \cdots",
        r"XSYM \xrightarrow{f} ASYM \to \mathrm{cofib}(f) "
        r"\to \Sigma XSYM \to \Sigma ASYM",
        r"A \to B \to C \to A[1]",
        r"E_2^{p,q} = H^p\bigl(B; H^q(F)\bigr) "
        r"\Rightarrow H^{p+q}(E)",
        r"E_2^{s,t} = \mathrm{Ext}^{s,t}_{\mathcal{A}}"
        r"(\mathbb{F}_p,\mathbb{F}_p) \Rightarrow \pi_{t-s}^{s}\,{}_{(p)}",
        r"H^*(XSYM;\mathbb{Z}) \cong "
        r"\mathbb{Z}[x_1,\dots,x_r]/(x_i^{@N@}), \qquad \lvert x_i \rvert = 2",
        r"\cdots \to H_{@I@}(XSYM) \xrightarrow{\partial} "
        r"H_{@I@-1}(A) \to H_{@I@-1}(XSYM) \to H_{@I@-1}(XSYM,A) \to \cdots",
        r"\Phi : \widetilde H^{@I@}(XSYM) "
        r"\xrightarrow{\sim} \widetilde H^{@I@+@N@}(\mathrm{Th}(E))",
        r"\mathrm{ch}(E) = \sum_{i \ge 0} "
        r"\frac{1}{i!}\,p_i(E) \in H^*(XSYM;\mathbb{Q})",
        r"\mathrm{sign}(XSYM) = \int_{XSYM} L(p_1,\dots,p_k), "
        r"\qquad \dim XSYM = 4k",
        r"\mathrm{Sq}^{@I@}(x \smile y) "
        r"= \sum_{i+j=@I@} \mathrm{Sq}^i x \smile \mathrm{Sq}^j y",
        r"\Omega^{\mathrm{fr}}_* \cong \pi_*^{s}(\mathbb{S}) "
        r"= \mathrm{colim}_n\, \pi_{*+n}(S^n)",
        r"L_{K(n)}\,\mathbb{S} \to L_{n}\,\mathbb{S} "
        r"\to L_{n-1}\,\mathbb{S} \to \Sigma L_{K(n)}\,\mathbb{S}",
        r"\mathrm{THH}(XSYM)^{tC_p} \to \mathrm{THH}(XSYM)^{hC_p}, "
        r"\qquad \mathrm{TC} = \mathrm{eq}\bigl(\varphi,\mathrm{can}\bigr)",
        r"\mathrm{Map}_{\mathcal{C}}(X,Y) "
        r"\simeq \Omega^\infty F(X,Y), \qquad F(X,Y) \in \mathrm{Sp}",
        r"\bigsqcup_{n \ge 0} B\Sigma_n "
        r"\xrightarrow{\sim} \Omega^\infty \Sigma^\infty S^0\,{}_{+}",
        r"H^*(BG;\mathbb{F}_p) \cong "
        r"\mathbb{F}_p[c_1,\dots,c_r], \qquad \lvert c_i \rvert = 2i",
        r"P_n F(X) = \mathrm{holim}\, F\bigl(X \cup (\text{cells})\bigr), "
        r"\qquad F \simeq \mathrm{holim}_n\, P_n F",
    ],
    msc=["55N15", "55P42", "55Q45", "55T15", "55N91", "55P43", "55S10", "55N31"],
    adjacent=["math.GT", "math.CT"],
)
