"""math.CA - Classical Analysis and ODEs.

Seed from the build spec, expanded with the analysis research dossier into a
broad working vocabulary spanning special functions, harmonic analysis, and ODEs.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

CA = SubfieldLexicon(
    code="math.CA",
    name="Classical Analysis and ODEs",
    weight=6.0,
    banks={
        "objects": [
            "orthogonal polynomial",
            "hypergeometric function",
            "Laguerre polynomial",
            "Jacobi polynomial",
            "Hermite polynomial",
            "Chebyshev polynomial",
            "Bessel function",
            "Gamma function",
            "Painlevé transcendent",
            "the Painlevé hierarchy",
            "a special function",
            "a generating function",
            "a Fourier series",
            "a power series",
            "a Dirichlet series",
            "the Riesz transform",
            "the Hilbert transform",
            "a singular integral",
            "a Carleson measure",
            "a maximal function",
            "a Sturm--Liouville problem",
            "a linear ODE",
            "a nonlinear ODE",
            "a vector field",
            "a period annulus",
            "a limit cycle",
            "an integral equation",
            "a continued fraction",
            "a moment problem",
            "a weight function",
            "a kernel",
            "a quadrature formula",
            "a recurrence relation",
            "a difference equation",
            "an asymptotic expansion",
            "a singular ODE",
            "a Riemann--Hilbert problem",
            "an oscillatory integral",
            "a measure",
            "the spectral measure",
            "a polynomial sequence",
            "the orthogonality weight",
        ],
        "props": [
            "orthogonal",
            "classical",
            "hypergeometric",
            "oscillatory",
            "singular",
            "regular",
            "weighted",
            "absolutely continuous",
            "asymptotic",
            "convergent",
            "divergent",
            "summable",
            "integrable",
            "monotone",
            "convex",
            "subharmonic",
            "real-analytic",
            "entire",
            "meromorphic",
            "transcendental",
            "positive-definite",
            "self-adjoint",
            "completely monotone",
            "log-convex",
            "uniformly bounded",
            "tempered",
            "rapidly decreasing",
            "compactly supported",
            "bounded-variation",
            "Lipschitz",
            "Hölder continuous",
            "doubling",
            "dyadic",
            "non-degenerate",
            "elementary",
            "explicit",
            "extremal",
            "isoperimetric",
            "sharp",
        ],
        "spaces": [
            "Lebesgue space",
            "weighted Lebesgue space",
            "Hardy space",
            "the space $\\mathrm{BMO}$",
            "a weighted $L^2$ space",
            "the space of bounded variation",
            "a Banach function space",
            "the Schwartz space",
            "the space of tempered distributions",
            "a Sobolev space",
            "a Dirichlet-type space",
            "a reproducing kernel Hilbert space",
            "the unit disk",
            "the real line",
            "the upper half-plane",
            "the support of the measure",
            "the space of test functions",
            "a Muckenhoupt class",
            "the space of polynomials",
            "the configuration space",
        ],
        "maps": [
            "the Fourier transform",
            "the Hilbert transform",
            "the Riesz transform",
            "the Hardy--Littlewood maximal operator",
            "the Laplace transform",
            "the Mellin transform",
            "a singular integral operator",
            "the Poisson integral",
            "the differentiation operator",
            "the shift operator",
            "the Cauchy transform",
            "a convolution operator",
            "the Stieltjes transform",
            "the conformal map",
            "the monodromy map",
        ],
        "invariants": [
            "moment",
            "recurrence coefficient",
            "leading coefficient",
            "zero-counting measure",
            "order of growth",
            "type",
            "rate of decay",
            "radius of convergence",
            "Stokes multiplier",
            "monodromy",
            "spectral measure",
            "$A_p$ constant",
            "doubling constant",
            "best constant",
            "modulus of continuity",
            "Hausdorff dimension",
            "exponent of convergence",
            "Mahler measure",
            "discriminant",
            "asymptotic constant",
            "number of limit cycles",
            "cyclicity",
            "weight exponent",
            "logarithmic capacity",
            "total variation",
        ],
        "namedResults": [
            "the Calderón--Zygmund theory",
            "the Littlewood--Paley theory",
            "the Carleson--Hunt theorem",
            "the Hardy inequality",
            "the Gagliardo--Nirenberg inequality",
            "the Turán--Nazarov inequality",
            "the Bernstein inequality",
            "the Riemann--Hilbert approach",
            "the Bellman function method",
            "the Muckenhoupt $A_p$ condition",
            "the Plancherel--Rotach asymptotics",
            "the Szegő asymptotics",
            "the Riesz--Thorin interpolation theorem",
            "the Marcinkiewicz interpolation theorem",
            "the Stone--Weierstrass theorem",
            "the Favard theorem",
            "the Watson lemma",
            "the steepest-descent method",
            "the Christoffel--Darboux formula",
            "the Hausdorff moment problem",
            "the Bochner classification",
            "the Hilbert--Schmidt theorem",
            "the Paley--Wiener theorem",
            "the Beurling--Malliavin theorem",
            "the Denjoy--Carleman theorem",
        ],
        "methods": [
            "the steepest-descent method",
            "the Riemann--Hilbert approach",
            "the WKB approximation",
            "the saddle-point method",
            "asymptotic analysis",
            "the Bellman function method",
            "interpolation of operators",
            "a Calderón--Zygmund decomposition",
            "the Littlewood--Paley decomposition",
            "the method of moments",
            "a generating-function argument",
            "the theory of orthogonal polynomials",
            "contour integration",
            "the nonlinear steepest-descent method",
            "Tauberian arguments",
            "a continuity argument",
            "the method of stationary phase",
            "averaging techniques",
            "a perturbation argument",
            "the Christoffel--Darboux kernel",
            "the matrix-model approach",
            "a comparison argument",
            "spectral analysis",
            "the moment method",
        ],
        "objectGloss": [
            "encodes the asymptotics of the underlying expansion",
            "arises naturally in the theory of special functions",
            "governs the distribution of zeros",
            "controls the oscillation of the integral",
            "is central to classical harmonic analysis",
            "reflects the orthogonality of the weight",
            "captures the singular behavior near the boundary",
            "lies at the heart of the theory of integrable systems",
        ],
    },
    # Object-naming letters only. No "x","t" (variables), no "n","k" (indices),
    # no "p" (exponent), no "H","L" (operators).
    symbols=[
        "P",
        "Q",
        "\\Phi",
        "\\Psi",
        "F",
        "G",
        "W",
        "\\mu",
        "R",
        "\\Lambda",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"XSYM_n(x) = \kappa_n x^{n} + \cdots, \qquad \kappa_n > 0",
        r"\int_{-1}^{1} XSYM_m(x)\, XSYM_n(x)\, w(x)\, dx = h_n\,\delta_{mn}",
        r"\lVert TXSYM \rVert_{L^{p}} \le C_p\,\lVert XSYM \rVert_{L^{p}}",
        r"XSYM(s) = \int_0^{\infty} t^{s-1} e^{-t}\, dt",
        r"\widehat{XSYM}(\xi) = \int_{\mathbb{R}} XSYM(x)\, e^{-2\pi i x\xi}\, dx",
        r"XSYM_n(x) \sim \frac{C}{\sqrt{n}}\,\cos\!\bigl(n\theta + \gamma\bigr)",
        r"\sum_{n=0}^{@N@} XSYM_n(x)\, t^{n} = \frac{ASYM(x,t)}{(1-t)^{@C@}}",
        r"XSYM(z) = \sum_{n \ge 0} a_n z^{n}, \qquad |z| < R",
        r"\lvert XSYM(x) \rvert \le C\,(1+|x|)^{-@N@}",
        r"x\,XSYM_n = a_n XSYM_{n+1} + b_n XSYM_n + c_n XSYM_{n-1}",
        r"\lVert XSYM \rVert_{L^{p}(w)} \le C\,[w]_{A_p}^{@K@}\,\lVert XSYM \rVert_{L^{p}(w)}",
        r"\int_{\mathbb{R}} XSYM(x)\, e^{i\lambda \phi(x)}\, dx = O(\lambda^{-@C@})",
        r"XSYM''(x) + q(x)\, XSYM(x) = \lambda\, XSYM(x)",
        r"\frac{d}{dx} XSYM = ASYM(x)\, XSYM, \qquad XSYM(0) = XSYM_0",
        r"XSYM(z) \sim \sum_{n \ge 0} \frac{a_n}{z^{n}} \quad (z \to \infty)",
        r"\lvert XSYM_n(z) \rvert \le e^{n\,g(z)}",
        r"\mu_k = \int x^{k}\, d\mu(x)",
        r"\deg XSYM_n = n, \qquad n = 0,1,2,\dots",
        r"\lVert XSYM \rVert_{\mathrm{BMO}} \le C\,\lVert ASYM \rVert_{L^{\infty}}",
        r"\sum_{n \ge 1} \frac{1}{XSYM_n} < \infty",
        r"XSYM(x) = {}_2F_1(a,b;c;x)",
        r"\int_0^{\infty} XSYM(t)\, e^{-st}\, dt = ASYM(s)",
        r"\zeta(XSYM) = \prod_{n} \bigl(1 - \lambda_n^{-XSYM}\bigr)^{-1}",
        r"\lvert \widehat{XSYM}(\xi) \rvert \le C\,e^{-c|\xi|}",
        r"XSYM_{n+1}(x) = 2x\, XSYM_n(x) - XSYM_{n-1}(x)",
        r"\sup_{\lambda > 0} \lambda\,|\{|TXSYM| > \lambda\}| \le C\,\lVert XSYM \rVert_{L^{1}}",
        r"\operatorname{cap}(XSYM) = e^{-V}, \qquad V = \inf_{\mu} I(\mu)",
        r"XSYM(x) = \frac{1}{2\pi i}\oint \frac{ASYM(z)}{z-x}\, dz",
        r"\rho_n = \frac{a_n}{a_{n-1}} \to R \quad (n \to \infty)",
    ],
    display_eqns=[
        r"XSYM(s) = \int_0^{\infty} t^{s-1} e^{-t}\, dt, \qquad \Re(s) > 0, \qquad "
        r"XSYM(s+1) = s\, XSYM(s)",
        r"(1-x^{2})\,XSYM_n'' - 2x\,XSYM_n' + n(n+1)\,XSYM_n = 0, \qquad n = 0,1,2,\dots",
        r"\sum_{k=0}^{n} XSYM_k(x)\, XSYM_k(y) "
        r"= \frac{\kappa_n}{\kappa_{n+1}}\,"
        r"\frac{XSYM_{n+1}(x) XSYM_n(y) - XSYM_n(x) XSYM_{n+1}(y)}{x-y}",
        r"XSYM_n(\cos\theta) = \sqrt{\frac{2}{\pi n \sin\theta}}\,"
        r"\cos\!\left[\Bigl(n+\tfrac12\Bigr)\theta - \tfrac{\pi}{4}\right] + O(n^{-3/2})",
        r"\int_{\mathbb{R}} XSYM(x)\, e^{i\lambda \phi(x)}\, dx "
        r"\sim \sqrt{\frac{2\pi}{\lambda |\phi''(x_0)|}}\, XSYM(x_0)\,"
        r" e^{i\lambda\phi(x_0) + i\pi/4}",
        r"\lVert T XSYM \rVert_{L^{p}} \le C_p\, \lVert XSYM \rVert_{L^{p}}, "
        r"\qquad 1 < p < \infty, \qquad T XSYM(x) = \mathrm{p.v.}\int K(x-y) XSYM(y)\, dy",
        r"-\bigl(p(x)\, XSYM'\bigr)' + q(x)\, XSYM = \lambda\, w(x)\, XSYM "
        r"\quad\text{on } (a,b), \qquad XSYM(a) = XSYM(b) = 0",
        r"\frac{1}{|I|}\int_I |XSYM - XSYM_I|\, dx \le C "
        r"\quad\text{for all intervals } I \subset \mathbb{R}",
        r"\left(\frac{1}{|I|}\int_I w\right)\!\left(\frac{1}{|I|}\int_I w^{-1/(p-1)}\right)^{p-1} "
        r"\le [w]_{A_p} < \infty",
        r"XSYM(z) = \frac{1}{2\pi i}\int_{\Gamma} \frac{ASYM(\zeta)}{\zeta - z}\, d\zeta, "
        r"\qquad XSYM_+(z) = G(z)\, XSYM_-(z) \text{ on } \Gamma",
        r"{}_2F_1(a,b;c;z) = \sum_{n=0}^{\infty} "
        r"\frac{(a)_n (b)_n}{(c)_n}\,\frac{z^{n}}{n!}, \qquad |z| < 1",
        r"\int_{-1}^{1} XSYM_m(x)\, XSYM_n(x)\,(1-x)^{\alpha}(1+x)^{\beta}\, dx "
        r"= h_n\,\delta_{mn}, \qquad \alpha,\beta > -1",
        r"XSYM(z) \sim \sum_{n=0}^{N-1} \frac{a_n}{z^{n}} + O\!\left(z^{-N}\right) "
        r"\quad (z \to \infty), \qquad a_n = \frac{ASYM^{(n)}(0)}{n!}",
        r"\sup_{\lambda > 0} \lambda\,\bigl|\{\,x : |M XSYM(x)| > \lambda\,\}\bigr| "
        r"\le C\,\lVert XSYM \rVert_{L^{1}(\mathbb{R}^{@N@})}",
        r"\lVert XSYM \rVert_{L^{q}} \le C\,\lVert XSYM \rVert_{L^{p_0}}^{1-\theta}\,"
        r"\lVert XSYM \rVert_{L^{p_1}}^{\theta}, "
        r"\qquad \frac{1}{q} = \frac{1-\theta}{p_0} + \frac{\theta}{p_1}",
        r"\dot{XSYM} = ASYM(XSYM,\mu), \qquad XSYM \in \mathbb{R}^{@N@}, "
        r"\qquad \#\{\text{limit cycles}\} \le @C@",
        r"\sum_{n \ge 0} XSYM_n(x)\,\frac{t^{n}}{n!} "
        r"= \exp\!\bigl(2xt - t^{2}\bigr), \qquad x \in \mathbb{R}",
        r"\int_{\mathbb{R}} \log XSYM(\theta)\, \frac{d\theta}{2\pi} "
        r"= \lim_{n \to \infty} \frac{1}{n}\,\log \det\bigl[\mu_{j-k}\bigr]_{j,k=0}^{n}",
    ],
    msc=["33C45", "34M55", "42B20", "42C05", "34L40", "30E25", "42B25", "33C05"],
    adjacent=["math.AP", "math.FA", "math-ph"],
)
