"""math.CO - Combinatorics.

Seed from the build spec, expanded with the discrete/probability/applied
research dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

CO = SubfieldLexicon(
    code="math.CO",
    name="Combinatorics",
    weight=9.0,
    banks={
        "objects": [
            "graph",
            "random graph",
            "hypergraph",
            "triple system",
            "hypertree",
            "tournament",
            "digraph",
            "Cayley graph",
            "expander",
            "matroid",
            "biased graph",
            "simplicial complex",
            "polytope",
            "lattice path",
            "permutation",
            "stack-sortable permutation",
            "Young tableau",
            "partition",
            "set partition",
            "symmetric function",
            "Schur function",
            "forest polynomial",
            "chromatic polynomial",
            "generating function",
            "design",
            "Steiner system",
            "Latin square",
            "perfect matching",
            "Hamilton cycle",
            "spanning tree",
            "independent set",
            "clique",
            "antichain",
            "poset",
            "set system",
            "incidence structure",
            "Ramsey number",
            "Turan number",
            "sum-free set",
            "Sidon set",
            "additive set",
            "coloring",
            "edge coloring",
        ],
        "props": [
            "extremal",
            "random",
            "sparse",
            "dense",
            "regular",
            "bipartite",
            "connected",
            "$k$-connected",
            "vertex-transitive",
            "edge-transitive",
            "planar",
            "chordal",
            "perfect",
            "triangle-free",
            "$H$-free",
            "self-complementary",
            "Eulerian",
            "Hamiltonian",
            "acyclic",
            "unimodal",
            "log-concave",
            "Ramsey",
            "intersecting",
            "downward-closed",
            "monotone",
            "balanced",
            "pseudorandom",
            "quasirandom",
            "$d$-degenerate",
            "uniformly random",
            "labelled",
            "unlabelled",
            "rainbow",
            "properly colored",
            "saturated",
            "shellable",
            "Cohen--Macaulay",
            "vertex-critical",
            "edge-critical",
        ],
        "spaces": [
            "vertex set",
            "edge set",
            "ground set",
            "cycle space",
            "lattice of flats",
            "face lattice",
            "Boolean lattice",
            "symmetric group",
            "automorphism group",
            "incidence algebra",
            "homology of the order complex",
            "Tutte polynomial ring",
            "ring of symmetric functions",
            "configuration space",
            "Johnson scheme",
            "Hamming scheme",
            "association scheme",
            "Bruhat order",
            "subgraph lattice",
        ],
        "maps": [
            "the adjacency operator",
            "the graph Laplacian",
            "the transfer matrix",
            "the shift operator",
            "the RSK correspondence",
            "the Tutte polynomial",
            "the incidence map",
            "the contraction map",
            "the deletion map",
            "the homomorphism density",
            "the regularity partition",
            "the compression operator",
            "a graphon limit",
            "the random coloring",
            "the switching operation",
        ],
        "invariants": [
            "chromatic number",
            "independence number",
            "clique number",
            "girth",
            "diameter",
            "spectral gap",
            "Turan density",
            "Ramsey number",
            "treewidth",
            "genus",
            "crossing number",
            "matching number",
            "vertex cover number",
            "domination number",
            "fractional chromatic number",
            "list chromatic number",
            "strong chromatic index",
            "edge density",
            "minimum degree",
            "maximum degree",
            "spectral radius",
            "expansion",
            "isoperimetric constant",
            "VC dimension",
            "discrepancy",
        ],
        "namedResults": [
            "the Szemeredi regularity lemma",
            "the Erdos--Ko--Rado theorem",
            "the Erdos matching conjecture",
            "the Littlewood--Richardson rule",
            "the Kruskal--Katona theorem",
            "Turan's theorem",
            "Ramsey's theorem",
            "Dilworth's theorem",
            "the Hajnal--Szemeredi theorem",
            "the Lovasz local lemma",
            "the Frankl--Rodl theorem",
            "the Kahn--Kalai conjecture",
            "the Caccetta--Haggkvist conjecture",
            "the Erdos--Stone theorem",
            "Brooks' theorem",
            "Vizing's theorem",
            "the Alon--Boppana bound",
            "the Cayley formula",
            "the Bollobas set-pair inequality",
            "the Sunflower lemma",
            "the Green--Tao theorem",
            "the Hales--Jewett theorem",
            "the Sauer--Shelah lemma",
            "the Aldous--Lyons conjecture",
            "the Sidorenko conjecture",
        ],
        "methods": [
            "the probabilistic method",
            "the regularity method",
            "the absorption method",
            "the container method",
            "the entropy method",
            "the polynomial method",
            "the semidefinite method",
            "Fourier analysis on the cube",
            "the Lovasz local lemma",
            "the switching method",
            "the second moment method",
            "the nibble method",
            "the dependent random choice",
            "spectral techniques",
            "the differential equation method",
            "an extremal counting argument",
            "the stability method",
            "flag algebras",
            "the deletion method",
            "the first moment method",
            "the transference principle",
            "a double counting argument",
            "generating function methods",
            "the hypergraph removal lemma",
        ],
        "objectGloss": [
            "encodes rich extremal structure",
            "exhibits a sharp phase transition",
            "lies at the heart of extremal combinatorics",
            "controls the threshold for substructure emergence",
            "is central to the probabilistic method",
            "reflects deep additive structure",
            "governs the asymptotics of random discrete systems",
            "links algebraic and combinatorial invariants",
        ],
    },
    # Object-naming letters only. "G" names graphs, "H" subgraphs; avoid "n"
    # (vertex count), "p" (edge probability), "k" (running parameter).
    symbols=[
        "G",
        "H",
        "F",
        "T",
        "M",
        "P",
        "Q",
        "\\Gamma",
        "\\mathcal{H}",
        "\\mathcal{F}",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\chi(XSYM) \le @K@",
        r"\alpha(XSYM) \ge \frac{n}{@K@}",
        r"\omega(XSYM) \le @K@",
        r"\mathrm{ex}(n, ASYM) = \left(1 - \tfrac{1}{@K@}\right)\tfrac{n^{2}}{2}",
        r"R(@K@,@K@) \le 4^{@K@}",
        r"e(XSYM) \le \tfrac{1}{2}\!\left(1 - \tfrac{1}{@K@}\right) n^{2}",
        r"\lambda_2(XSYM) \le 2\sqrt{@K@ - 1}",
        r"\mathrm{tw}(XSYM) = O\!\left(\sqrt{n}\right)",
        r"\delta(XSYM) \ge \left(\tfrac{1}{2} + \varepsilon\right) n",
        r"\mathbb{P}\bigl(XSYM \supseteq ASYM\bigr) \to @R@",
        r"d_H(XSYM) = (1 + o(1))\, p^{e(H)}",
        r"\chi'(XSYM) \in \{\Delta, \Delta + 1\}",
        r"\binom{n}{@K@} \sim \frac{n^{@K@}}{@K@!}",
        r"\pi(ASYM) = 1 - \frac{1}{@K@ - 1}",
        r"\mathrm{mad}(XSYM) < @C@",
        r"\sum_{v} \deg(v) = 2\, e(XSYM)",
        r"\mathbb{E}\bigl[X_{ASYM}\bigr] = \binom{n}{@K@} p^{\binom{@K@}{2}}",
        r"\det\!\bigl(I - x A_{XSYM}\bigr) \neq 0",
        r"a_n = a_{n-1} + a_{n-2}",
        r"\mathrm{disc}(XSYM) = \Omega\!\left(\sqrt{n}\right)",
        r"\mathrm{VC}(XSYM) \le @C@",
        r"\nu(XSYM) = \tau(XSYM)",
        r"\mathbb{P}\bigl(XSYM \text{ is connected}\bigr) \to 1",
        r"\mathrm{diam}(XSYM) = \Theta\!\left(\tfrac{\log n}{\log d}\right)",
        r"\chi_f(XSYM) = \frac{n}{\alpha(XSYM)}",
        r"|XSYM \cap ASYM| \ge n - @K@",
        r"\rho(A_{XSYM}) \le \Delta",
        r"t_H(XSYM) \ge t_H(\text{random})",
        r"g(XSYM) \ge 2\log_{d-1} n",
        r"\#\{\text{spanning trees}\} = n^{\,n-2}",
    ],
    display_eqns=[
        r"\mathrm{ex}(n, K_{r+1}) = \left(1 - \frac{1}{r}\right)\frac{n^{2}}{2} "
        r"+ o(n^{2})",
        r"R(s,t) \le \binom{s + t - 2}{s - 1}, \qquad "
        r"R(@K@,@K@) \le \frac{4^{@K@}}{\sqrt{@K@}}",
        r"\sum_{n \ge 0} C_n x^{n} = \frac{1 - \sqrt{1 - 4x}}{2x}, \qquad "
        r"C_n = \frac{1}{n+1}\binom{2n}{n}",
        r"e(A,B) = d\,|A|\,|B| \pm \lambda \sqrt{|A|\,|B|}",
        r"\mathbb{P}\!\left(\bigcap_{i} \overline{A_i}\right) > 0 "
        r"\quad\text{if } e\, p\,(d + 1) \le 1",
        r"\chi(XSYM) \ge \frac{n}{\alpha(XSYM)} "
        r"\ge \frac{n}{(2 + o(1)) \log_b n}",
        r"\left| t_H(XSYM) - t_H(W) \right| "
        r"\le e(H)\, \|XSYM - W\|_{\square}",
        r"\sum_{i} \binom{n}{a_i} \le \binom{n}{\lfloor n/2 \rfloor} "
        r"\cdot @K@",
        r"\frac{S_n - \mathbb{E} S_n}{\sqrt{\operatorname{Var} S_n}} "
        r"\xrightarrow{d} N(0,1)",
        r"\sum_{\lambda} s_\lambda(x)\, s_\lambda(y) "
        r"= \prod_{i,j} \frac{1}{1 - x_i y_j}",
        r"s_\mu \, s_\nu = \sum_{\lambda} c^{\lambda}_{\mu\nu}\, s_\lambda",
        r"\mathbb{P}\bigl(\,|X - \mathbb{E} X| \ge t\,\bigr) "
        r"\le 2 \exp\!\left(-\frac{t^{2}}{2\sigma^{2}}\right)",
        r"\binom{V}{r} = \bigcup_{i=1}^{@C@} XSYM_i, \qquad "
        r"XSYM_i \text{ monochromatic}",
        r"p_c = \frac{\log n + c}{n}, \qquad "
        r"\mathbb{P}\bigl(G(n,p_c)\text{ connected}\bigr) \to e^{-e^{-c}}",
        r"\lim_{n \to \infty} \frac{\log R(n,n)}{n} = \log 2",
        r"Z(XSYM; q) = \sum_{F \subseteq E} q^{c(F)} (-1)^{|F|} "
        r"v^{|F|}",
        r"T_{XSYM}(x,y) = \sum_{F \subseteq E} "
        r"(x-1)^{r(E) - r(F)} (y-1)^{|F| - r(F)}",
        r"\mathbb{E}\,[\text{triangles}] = \binom{n}{3} p^{3}, \qquad "
        r"\operatorname{Var} = \Theta\!\left(n^{4} p^{5}\right)",
    ],
    msc=["05C80", "05D10", "05D40", "05C15", "05A16", "05C35", "05E05", "05B05"],
    adjacent=["math.PR", "cs.DM"],
)
