"""math.CT - Category Theory.

Seeded from the geometry/topology research dossier and expanded into a broad
working vocabulary covering ordinary, enriched, and higher category theory,
topos theory, and homotopical algebra.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

CT = SubfieldLexicon(
    code="math.CT",
    name="Category Theory",
    weight=4.0,
    banks={
        "objects": [
            "category",
            "small category",
            "locally small category",
            "functor",
            "natural transformation",
            "adjunction",
            "monad",
            "comonad",
            "limit",
            "colimit",
            "Kan extension",
            "presheaf",
            "copresheaf",
            "representable functor",
            "Yoneda embedding",
            "monoidal category",
            "symmetric monoidal category",
            "braided monoidal category",
            "closed monoidal category",
            "enriched category",
            "$2$-category",
            "bicategory",
            "$\\infty$-category",
            "$(\\infty,1)$-category",
            "quasicategory",
            "simplicial set",
            "model category",
            "Quillen adjunction",
            "derived functor",
            "triangulated category",
            "derived category",
            "singularity category",
            "stable $\\infty$-category",
            "abelian category",
            "exact category",
            "topos",
            "presheaf topos",
            "Grothendieck topos",
            "locale",
            "site",
            "sheaf",
            "operad",
            "fibration of categories",
            "Grothendieck construction",
        ],
        "props": [
            "small",
            "locally small",
            "essentially small",
            "complete",
            "cocomplete",
            "finitely complete",
            "presentable",
            "locally presentable",
            "accessible",
            "cartesian closed",
            "monoidal",
            "symmetric monoidal",
            "closed",
            "enriched",
            "abelian",
            "additive",
            "exact",
            "triangulated",
            "stable",
            "pointed",
            "filtered",
            "cofiltered",
            "full",
            "faithful",
            "fully faithful",
            "essentially surjective",
            "conservative",
            "(co)continuous",
            "left exact",
            "right exact",
            "representable",
            "corepresentable",
            "adjoint",
            "self-adjoint",
            "idempotent",
            "reflective",
            "coreflective",
            "dense",
            "compactly generated",
            "well-powered",
        ],
        "spaces": [
            "the category $\\mathcal{C}$",
            "the opposite category $\\mathcal{C}^{\\mathrm{op}}$",
            "the functor category $\\mathrm{Fun}(\\mathcal{C},\\mathcal{D})$",
            "the presheaf category $\\widehat{\\mathcal{C}}$",
            "the category of presheaves $\\mathrm{PSh}(\\mathcal{C})$",
            "the category of sheaves $\\mathrm{Sh}(\\mathcal{C})$",
            "the homotopy category $\\mathrm{Ho}(\\mathcal{C})$",
            "the derived category $D(\\mathcal{A})$",
            "the Yoneda embedding $\\mathcal{C} \\hookrightarrow \\widehat{\\mathcal{C}}$",
            "the slice category $\\mathcal{C}/X$",
            "the comma category $F \\downarrow G$",
            "the category of elements $\\int_{\\mathcal{C}} F$",
            "the simplex category $\\Delta$",
            "the nerve $N(\\mathcal{C})$",
            "the category $\\mathrm{Cat}$ of small categories",
            "the $\\infty$-category of spaces",
            "the stable $\\infty$-category of spectra",
            "the classifying topos",
        ],
        "maps": [
            "a functor",
            "a natural transformation",
            "the unit of the adjunction",
            "the counit of the adjunction",
            "the Yoneda embedding",
            "the left adjoint",
            "the right adjoint",
            "the left Kan extension",
            "the right Kan extension",
            "the localization functor",
            "the forgetful functor",
            "the free functor",
            "the diagonal functor",
            "the geometric morphism",
            "the comparison functor",
        ],
        "invariants": [
            "the homotopy category",
            "the Grothendieck group",
            "the set of isomorphism classes",
            "the automorphism group of an object",
            "the endomorphism monoid",
            "the Hom-set",
            "the mapping space",
            "the derived Hom",
            "the Ext groups",
            "the Tor groups",
            "the $K$-theory spectrum",
            "the Hochschild homology",
            "the cyclic homology",
            "the Euler characteristic",
            "the cardinality of the skeleton",
            "the nerve",
            "the homotopy groups of the mapping space",
            "the global dimension",
            "the Picard group",
            "the center of the category",
            "the Drinfeld center",
            "the spectrum of a tensor-triangulated category",
            "the Brauer group",
            "the lattice of subobjects",
            "the subobject classifier",
        ],
        "namedResults": [
            "the Yoneda lemma",
            "the adjoint functor theorem",
            "the special adjoint functor theorem",
            "the Freyd--Mitchell embedding theorem",
            "the Gabriel--Ulmer duality",
            "the Beck monadicity theorem",
            "the Barr--Beck theorem",
            "the Quillen equivalence",
            "the Dold--Kan correspondence",
            "the Eilenberg--Watts theorem",
            "the Giraud theorem",
            "the Diaconescu equivalence",
            "the Brown representability theorem",
            "the Bousfield--Kan localization",
            "the Lurie straightening--unstraightening equivalence",
            "the recognition principle",
            "the Eckmann--Hilton argument",
            "the Joyal--Tierney theorem",
            "the nerve--realization adjunction",
            "the Day convolution theorem",
            "the Isbell duality",
            "the Reedy model structure theorem",
            "the Quillen--Thomason theorem",
            "the Toda--Verdier localization",
            "the Schwede--Shipley theorem",
        ],
        "methods": [
            "the Yoneda lemma",
            "an adjoint functor argument",
            "the calculus of (co)limits",
            "Kan extension techniques",
            "the theory of monads",
            "the Grothendieck construction",
            "the straightening--unstraightening equivalence",
            "a localization argument",
            "the small object argument",
            "model-categorical methods",
            "the theory of presentable categories",
            "an enrichment argument",
            "the bar construction",
            "the theory of derivators",
            "a coend computation",
            "the nerve construction",
            "a monadicity argument",
            "the theory of factorization systems",
            "homotopy-coherent diagrams",
            "the calculus of fractions",
            "a descent argument",
            "the theory of Grothendieck fibrations",
            "the simplicial replacement",
            "an end--coend manipulation",
        ],
        "objectGloss": [
            "organizes mathematical structures and their morphisms",
            "is determined up to isomorphism by a universal property",
            "represents a functor by the Yoneda lemma",
            "arises as a (co)limit of simpler objects",
            "encodes an adjunction between two categories",
            "captures the homotopy theory of the underlying objects",
            "classifies geometric morphisms into a topos",
            "is central to modern category theory",
        ],
    },
    # Object-naming symbols only: categories C, D, E; functors F, G, H; objects
    # X, Y; the Yoneda functor h. No lowercase index letters used as morphisms.
    symbols=[
        "\\mathcal{C}",
        "\\mathcal{D}",
        "\\mathcal{E}",
        "F",
        "G",
        "H",
        "X",
        "Y",
        "T",
        "h",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\mathrm{Hom}(FX, Y) \cong \mathrm{Hom}(X, GY)",
        r"F \dashv G",
        r"\mathrm{id}_{\mathcal{C}} \Rightarrow GF",
        r"FG \Rightarrow \mathrm{id}_{\mathcal{D}}",
        r"\mathrm{Hom}(h_X, F) \cong FX",
        r"h_X = \mathrm{Hom}(-, X)",
        r"\mathcal{C}(X, Y) = \mathrm{Hom}_{\mathcal{C}}(X, Y)",
        r"GF = T",
        r"\mu \circ T\mu = \mu \circ \mu_T",
        r"\eta \colon \mathrm{id} \Rightarrow T",
        r"\lim_{i} X_i \in \mathcal{C}",
        r"\mathrm{colim}_{i} X_i \in \mathcal{C}",
        r"F(\lim_i X_i) \cong \lim_i F(X_i)",
        r"\mathrm{Lan}_F G \dashv (- \circ F)",
        r"(- \circ F) \dashv \mathrm{Ran}_F",
        r"X \otimes Y \cong Y \otimes X",
        r"\mathrm{Hom}(X \otimes Y, Z) \cong \mathrm{Hom}(X, [Y, Z])",
        r"\mathcal{C} \simeq \mathcal{D}",
        r"\widehat{\mathcal{C}} = \mathrm{Fun}(\mathcal{C}^{\mathrm{op}}, \mathbf{Set})",
        r"\mathrm{Nat}(F, G) \cong \mathrm{end}_X\, \mathcal{D}(FX, GX)",
        r"\pi_0\,\mathcal{C} = \mathrm{Ob}(\mathcal{C})/{\cong}",
        r"\mathrm{Ext}^{@I@}(X, Y) \neq 0",
        r"D^{b}(\mathcal{A}) \simeq D^{b}(\mathcal{B})",
        r"X \to Y \to Z \to X[1]",
        r"R^{@I@}F = H^{@I@}(\mathbf{R}F)",
        r"\mathcal{C}^{\mathrm{op}} \times \mathcal{C} \to \mathbf{Set}",
        r"a \cong b \pmod{\cong}",
        r"\mathrm{Map}_{\mathcal{C}}(X, Y) \in \mathcal{S}",
        r"N(\mathcal{C})_{n} = \mathrm{Fun}([n], \mathcal{C})",
        r"|N(\mathcal{C})| \simeq B\mathcal{C}",
        r"\mathrm{Sub}(X) \cong \mathrm{Hom}(X, \Omega)",
        r"\Omega \colon \mathcal{E}^{\mathrm{op}} \to \mathbf{Set}",
        r"\mathrm{Fun}(\mathcal{C}, \mathcal{D})(F, G) = \mathrm{Nat}(F, G)",
        r"\mathrm{gl.dim}\,\mathcal{A} = @N@",
        r"K_0(\mathcal{C}) \cong \mathbb{Z}^{@N@}",
        r"\mathrm{Hom}(\operatorname{colim} X_i, Y) \cong \lim_i \mathrm{Hom}(X_i, Y)",
    ],
    display_eqns=[
        r"\mathrm{Nat}(h_X, F) \cong F(X), \qquad "
        r"h_X = \mathrm{Hom}_{\mathcal{C}}(-, X)",
        r"\mathrm{Hom}_{\mathcal{D}}(F X, Y) \cong "
        r"\mathrm{Hom}_{\mathcal{C}}(X, G Y) \quad\text{naturally in } X, Y",
        r"(\mathrm{Lan}_K F)(d) \cong \mathrm{colim}_{(c,\, Kc \to d)}\, F(c), "
        r"\qquad \mathrm{Lan}_K \dashv (- \circ K)",
        r"\mathrm{Nat}(F, G) \cong \int_{X \in \mathcal{C}} "
        r"\mathrm{Hom}_{\mathcal{D}}(F X, G X)",
        r"(F \star G)(c) = \int^{a, b} \mathcal{C}(a \otimes b, c) "
        r"\times F a \times G b",
        r"\lim_{\leftarrow} F = \int_{i \in I} F(i), \qquad "
        r"\mathrm{colim}_{\rightarrow} F = \int^{i \in I} F(i)",
        r"\mathrm{Hom}_{\mathcal{C}}(X \otimes Y, Z) \cong "
        r"\mathrm{Hom}_{\mathcal{C}}(X, [Y, Z]) \quad\text{(closed monoidal)}",
        r"T = G F, \quad \eta \colon \mathrm{id}_{\mathcal{C}} \Rightarrow T, "
        r"\quad \mu = G \varepsilon F \colon T^{2} \Rightarrow T",
        r"\mathcal{C} \xrightarrow{\ \sim\ } \mathcal{D}^{T}, \qquad "
        r"X \longmapsto (G X,\ G \varepsilon_X) \quad\text{(monadicity)}",
        r"\mathrm{PSh}(\mathcal{C}) = \mathrm{Fun}(\mathcal{C}^{\mathrm{op}}, \mathbf{Set}), "
        r"\qquad \mathcal{C} \hookrightarrow \mathrm{PSh}(\mathcal{C})",
        r"\mathcal{E} \simeq \mathrm{Sh}(\mathcal{C}, J) \hookrightarrow "
        r"\mathrm{PSh}(\mathcal{C}) \quad\text{(Giraud: a Grothendieck topos)}",
        r"\mathrm{Hom}_{\mathrm{Topos}}(\mathcal{F}, \mathrm{Sh}(\mathcal{C})) "
        r"\simeq \mathrm{Hom}_{\mathrm{Site}}(\mathcal{C}, \mathcal{F})",
        r"\cdots \to X \to Y \to Z \xrightarrow{+1} X[1] \to \cdots "
        r"\quad\text{(distinguished triangle)}",
        r"R^{n} F(X) = H^{n}\bigl(F(I^{\bullet})\bigr), \qquad "
        r"X \xrightarrow{\ \sim\ } I^{\bullet} \ \text{injective resolution}",
        r"\mathrm{Map}_{\mathcal{C}}(X, Y) = \mathrm{Fun}(\mathcal{C})/X \times_{\mathcal{C}} Y, "
        r"\qquad \pi_n\, \mathrm{Map}_{\mathcal{C}}(X, Y) = @N@",
        r"\mathrm{St} \colon \mathrm{Fun}(\mathcal{C}, \mathcal{S}) "
        r"\xrightarrow{\ \sim\ } \mathrm{LFib}(\mathcal{C}) \;:\; \mathrm{Un}",
        r"K_0(\mathcal{C}) = \mathbb{Z}\langle [X] \rangle \big/ "
        r"\bigl([Y] = [X] + [Z] \ \text{for}\ X \to Y \to Z \bigr)",
        r"\mathrm{Sub}_{\mathcal{E}}(X) \cong \mathrm{Hom}_{\mathcal{E}}(X, \Omega), "
        r"\qquad \top \colon 1 \to \Omega \ \text{the subobject classifier}",
    ],
    msc=["18A40", "18A25", "18N60", "18G80", "18F10", "18M05", "18N50", "18E10"],
    adjacent=["math.AT", "math.LO"],
)
