"""math.CV - Complex Variables.

Seed from the build spec, expanded with the analysis research dossier into a
broad working vocabulary spanning holomorphic functions, several complex
variables, and complex geometry.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

CV = SubfieldLexicon(
    code="math.CV",
    name="Complex Variables",
    weight=4.0,
    banks={
        "objects": [
            "holomorphic function",
            "meromorphic function",
            "entire function",
            "inner function",
            "Blaschke product",
            "rational function",
            "univalent function",
            "subharmonic function",
            "plurisubharmonic function",
            "pluriharmonic function",
            "the Bergman kernel",
            "the Szegő kernel",
            "the Bergman space",
            "the Hardy space",
            "a de Branges--Rovnyak space",
            "a Toeplitz operator",
            "a Hankel operator",
            "a composition operator",
            "a holomorphic curve",
            "a complex manifold",
            "a Kähler manifold",
            "a pseudoconvex domain",
            "a strictly pseudoconvex domain",
            "a domain of holomorphy",
            "a Stein manifold",
            "a Riemann surface",
            "a divisor",
            "a current",
            "a holomorphic line bundle",
            "a Kähler--Einstein metric",
            "a holomorphic map",
            "the $\\bar\\partial$-operator",
            "the Monge--Ampère equation",
            "a Julia set",
            "a Fatou component",
            "a Siegel disk",
            "a wandering domain",
            "a normal family",
            "a quasiconformal map",
            "a conformal map",
            "a singular metric",
            "a positive current",
        ],
        "props": [
            "holomorphic",
            "meromorphic",
            "entire",
            "univalent",
            "conformal",
            "biholomorphic",
            "quasiconformal",
            "plurisubharmonic",
            "subharmonic",
            "pluriharmonic",
            "pseudoconvex",
            "strictly pseudoconvex",
            "hyperbolic",
            "Stein",
            "Kähler",
            "positive",
            "transcendental",
            "rational",
            "normal",
            "compact",
            "noncompact",
            "bounded",
            "of finite type",
            "of finite order",
            "completely invariant",
            "totally disconnected",
            "essentially bounded",
            "nondegenerate",
            "ample",
            "nef",
            "big",
            "polarized",
            "Fano",
            "negatively curved",
            "complete",
            "analytic",
            "singular",
            "extremal",
            "rotationally symmetric",
            "holomorphically convex",
        ],
        "spaces": [
            "Hardy space",
            "Bergman space",
            "the Dirichlet space",
            "a de Branges--Rovnyak space",
            "a model space",
            "the disk algebra",
            "the unit disk",
            "the unit ball",
            "the polydisk",
            "a pseudoconvex domain",
            "a Stein manifold",
            "a Kähler manifold",
            "a Riemann surface",
            "the space of holomorphic functions",
            "a Teichmüller space",
            "the Fatou set",
            "the space of currents",
            "a reproducing kernel Hilbert space",
            "the space of plurisubharmonic functions",
        ],
        "maps": [
            "the $\\bar\\partial$-operator",
            "the Cauchy transform",
            "the Bergman projection",
            "the Szegő projection",
            "the conformal map",
            "the Riemann map",
            "a composition operator",
            "a Toeplitz operator",
            "the monodromy map",
            "the Gauss map",
            "the uniformization map",
            "the period map",
            "the Poincaré metric",
            "the complex Hessian",
            "the holomorphic projection",
        ],
        "invariants": [
            "order of growth",
            "type",
            "Nevanlinna characteristic",
            "deficiency",
            "winding number",
            "valence",
            "multiplier",
            "rotation number",
            "Lyapunov exponent",
            "Schwarzian derivative",
            "capacity",
            "Lelong number",
            "Monge--Ampère mass",
            "Kähler class",
            "Chern class",
            "degree",
            "genus",
            "conformal modulus",
            "extremal length",
            "Kobayashi distance",
            "Bergman metric",
            "hyperbolic volume",
            "Hausdorff dimension",
            "harmonic measure",
            "logarithmic capacity",
        ],
        "namedResults": [
            "the Riemann mapping theorem",
            "the maximum modulus principle",
            "the Schwarz lemma",
            "the Picard theorem",
            "the Montel theorem",
            "the Hartogs extension theorem",
            "the Oka--Cartan theory",
            "the Hörmander estimates",
            "the Demailly transcendental Morse inequality",
            "the Calabi--Yau theorem",
            "the Ohsawa--Takegoshi extension theorem",
            "the Beurling--Lax theorem",
            "the Nevanlinna theory",
            "the Koebe distortion theorem",
            "the Bieberbach conjecture",
            "the Carathéodory extension theorem",
            "the Sullivan no-wandering-domains theorem",
            "the Fatou--Julia theory",
            "the Bergman--Skoda estimate",
            "the Siu semicontinuity theorem",
            "the Kodaira embedding theorem",
            "the Levi problem",
            "the Bochner--Martinelli formula",
            "the Lelong--Poincaré formula",
            "the Pick--Nevanlinna interpolation theorem",
        ],
        "methods": [
            "the $\\bar\\partial$-method",
            "the Hörmander $L^2$-estimates",
            "a normal families argument",
            "the theory of currents",
            "pluripotential theory",
            "the continuity method",
            "a value-distribution argument",
            "the Bergman kernel asymptotics",
            "a quasiconformal surgery",
            "the variational method",
            "potential theory",
            "the Ohsawa--Takegoshi extension",
            "a complex Monge--Ampère argument",
            "the theory of holomorphic foliations",
            "the renormalization method",
            "a Schwarz-lemma argument",
            "the method of harmonic maps",
            "an extremal-length argument",
            "the theory of model spaces",
            "a degeneration argument",
            "the holomorphic Morse inequalities",
            "the theory of plurisubharmonic functions",
            "a deformation argument",
            "the uniformization method",
        ],
        "objectGloss": [
            "encodes the value distribution of the function",
            "arises naturally in several complex variables",
            "governs the growth of the entire function",
            "controls the geometry of the underlying domain",
            "is central to complex analytic geometry",
            "reflects the rigidity of holomorphic maps",
            "captures the dynamics of the iterated map",
            "lies at the heart of pluripotential theory",
        ],
    },
    # Object-naming letters only. No "z","w" (complex variables), no "n","k"
    # (indices), no "\Omega","D" (domains).
    symbols=[
        "f",
        "g",
        "F",
        "\\varphi",
        "\\Phi",
        "\\psi",
        "B",
        "S",
        "\\mu",
        "\\Theta",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\bar\partial XSYM = 0 \quad\text{in } \Omega",
        r"|XSYM(z)| \le M \quad\text{for } |z| < 1",
        r"XSYM(z) = \prod_{n} \frac{|a_n|}{a_n}\,\frac{a_n - z}{1 - \bar a_n z}",
        r"T(r, XSYM) = m(r, XSYM) + N(r, XSYM)",
        r"\rho(XSYM) = \limsup_{r \to \infty} \frac{\log\log M(r, XSYM)}{\log r}",
        r"i\,\partial\bar\partial XSYM \ge 0",
        r"\sum_{n} (1 - |a_n|) < \infty",
        r"|XSYM'(0)| \le \frac{1}{1 - |XSYM(0)|^{2}}",
        r"\nu(XSYM, x) = \liminf_{z \to x} \frac{XSYM(z)}{\log|z-x|}",
        r"XSYM = \frac{1}{2\pi i}\oint \frac{ASYM(\zeta)}{\zeta - z}\, d\zeta",
        r"\lVert XSYM \rVert_{H^{2}}^{2} = \sum_{n \ge 0} |\widehat{XSYM}(n)|^{2}",
        r"\deg XSYM = @N@, \qquad \#\,\mathrm{Fix}(XSYM) = @N@ + 1",
        r"\dim_{\mathbb{C}} H^{0}(X, \mathcal{O}(XSYM)) = @N@",
        r"K_\Omega(z,z) = \sup\{\,|XSYM(z)|^{2} : \lVert XSYM \rVert \le 1\,\}",
        r"\lambda'(z) = \frac{2}{1 - |z|^{2}}",
        r"XSYM(\mathbb{C}) \supset \mathbb{C} \setminus \{a, b\}",
        r"\int_{\mathbb{D}} (\Delta XSYM)\, dA \ge 0",
        r"\lVert XSYM \rVert_{\infty} = \sup_{|z| < 1} |XSYM(z)|",
        r"\frac{1}{4} \le |XSYM'(0)| \cdot \operatorname{dist}(0, \partial XSYM(\mathbb{D}))",
        r"XSYM^{*} XSYM = I - \langle \cdot, k \rangle k",
        r"c_1(XSYM)^{@N@} > 0",
        r"\dim_H \mathcal{J}(XSYM) = @C@/@C@",
        r"\bar\partial XSYM = ASYM \quad\text{with } "
        r"\lVert XSYM \rVert_{L^2} \le C\lVert ASYM \rVert_{L^2}",
        r"|a_n| \le n \quad\text{for } XSYM(z) = z + \textstyle\sum_{n \ge 2} a_n z^{n}",
        r"(dd^{c} XSYM)^{@N@} = \mu",
        r"XSYM \circ ASYM = \mathrm{id} \quad\text{on } \mathbb{D}",
        r"N(r, XSYM) = \int_0^{r} \frac{n(t, XSYM) - n(0, XSYM)}{t}\, dt",
        r"\operatorname{Ric}(\omega) = \lambda\,\omega",
        r"\#\{\,z : XSYM(z) = a\,\} = \deg XSYM",
    ],
    display_eqns=[
        r"XSYM(z) = \frac{1}{2\pi i}\oint_{\partial\Omega} "
        r"\frac{ASYM(\zeta)}{\zeta - z}\, d\zeta, \qquad z \in \Omega",
        r"T(r, XSYM) = \sum_{a} m\!\left(r, \frac{1}{XSYM - a}\right) + N(r, XSYM) + S(r, XSYM)",
        r"XSYM(z) = e^{i\gamma}\, z^{m} \prod_{n} \frac{|a_n|}{a_n}\,"
        r"\frac{a_n - z}{1 - \bar a_n z}, \qquad \sum_n (1 - |a_n|) < \infty",
        r"\int_{\Omega} |XSYM|^{2}\, e^{-\varphi}\, dV "
        r"\le \int_{\Omega} |\bar\partial XSYM|^{2}_{i\partial\bar\partial\varphi}"
        r"\, e^{-\varphi}\, dV",
        r"(i\,\partial\bar\partial XSYM)^{@N@} = e^{XSYM}\, \omega^{@N@} "
        r"\quad\text{on the Kahler manifold } X",
        r"\frac{1}{2\pi}\int_0^{2\pi} \log|XSYM(re^{i\theta})|\, d\theta "
        r"= \log|XSYM(0)| + \sum_{|a_k| < r} \log\frac{r}{|a_k|}",
        r"d_X(p, q) = \inf \int_0^1 \frac{2\,|\gamma'(t)|}{1 - |\gamma(t)|^{2}}\, dt, "
        r"\qquad \gamma(0) = p, \ \gamma(1) = q",
        r"\sum_{q=0}^{@N@} (-1)^{q}\, h^{q}(X, \mathcal{O}(XSYM)) "
        r"\le \frac{1}{@N@!}\int_X \bigl(c_1(XSYM)\bigr)^{@N@} + o(1)",
        r"K_\Omega(z, w) = \sum_{j} \varphi_j(z)\,\overline{\varphi_j(w)}, "
        r"\qquad \{\varphi_j\} \text{ an orthonormal basis of } A^{2}(\Omega)",
        r"\Bigl|\,XSYM\Bigl(\frac{z - a}{1 - \bar a z}\Bigr)\,\Bigr| \le |z| "
        r"\quad\text{for all } z \in \mathbb{D} \quad (\text{Schwarz--Pick})",
        r"\frac{1 - |z|}{(1 + |z|)^{3}} \le |XSYM'(z)| \le \frac{1 + |z|}{(1 - |z|)^{3}}, "
        r"\qquad XSYM \in S",
        r"dd^{c} \log|XSYM| = \sum_{j} \nu_j\,[H_j] \quad (\text{Lelong--Poincaré}), "
        r"\qquad \nu_j = \operatorname{ord}_{H_j} XSYM",
        r"XSYM_{n+1}(z) = XSYM_n(z)^{2} + c, \qquad "
        r"\mathcal{J}(XSYM) = \partial\{\,z : XSYM_n(z) \not\to \infty\,\}",
        r"\int_{\mathbb{D}} \log\frac{1}{|XSYM|}\, \frac{dA}{\pi} "
        r"= \sum_{n} (1 - |a_n|^{2}) "
        r"+ \frac{1}{2\pi}\int_0^{2\pi} \log\frac{1}{|XSYM(e^{i\theta})|}\, d\theta",
        r"\operatorname{Ric}(\omega_{KE}) = \lambda\,\omega_{KE}, "
        r"\qquad \omega_{KE} = i\,\partial\bar\partial XSYM, \quad \lambda \in \{-1, 0, 1\}",
        r"XSYM(z) = z + \sum_{n=2}^{\infty} a_n z^{n}, \qquad |a_n| \le n "
        r"\quad\text{for all } n \ge 2 \quad (\text{de Branges})",
        r"\Theta_{XSYM}(z) = \begin{pmatrix} a(z) & b(z) \\ c(z) & d(z) \end{pmatrix}, "
        r"\qquad \Theta_{XSYM}(z)^{*} J\,\Theta_{XSYM}(z) \le J",
        r"\int_X (dd^{c} XSYM)^{@N@} = \int_X (dd^{c} ASYM)^{@N@} "
        r"\quad\text{whenever } XSYM = ASYM \text{ on } \partial X",
    ],
    msc=["32A10", "30D35", "32U05", "30C35", "32Q20", "32W05", "37F10", "30H10"],
    adjacent=["math.AP", "math.DS", "math.AG"],
)
