"""math.DG - Differential Geometry.

Seed from the build spec, expanded with the geometry/topology research
dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

DG = SubfieldLexicon(
    code="math.DG",
    name="Differential Geometry",
    weight=9.0,
    banks={
        "objects": [
            "Riemannian manifold",
            "Kähler manifold",
            "Kähler--Einstein manifold",
            "Einstein manifold",
            "Calabi--Yau manifold",
            "symplectic manifold",
            "complex manifold",
            "spin manifold",
            "Sasakian manifold",
            "Finsler manifold",
            "$G_2$-manifold",
            "Ricci flow",
            "Kähler--Ricci flow",
            "mean curvature flow",
            "Lagrangian mean curvature flow",
            "harmonic map heat flow",
            "Yamabe flow",
            "Ricci soliton",
            "gradient Ricci soliton",
            "Kähler--Ricci soliton",
            "minimal surface",
            "minimal hypersurface",
            "free boundary minimal submanifold",
            "constant mean curvature hypersurface",
            "harmonic map",
            "harmonic spinor",
            "Higgs bundle",
            "holomorphic vector bundle",
            "Hermitian--Einstein connection",
            "Yang--Mills connection",
            "instanton",
            "gravitational instanton",
            "principal bundle",
            "spinor bundle",
            "Dirac operator",
            "Laplace operator",
            "geodesic",
            "totally geodesic submanifold",
            "Kähler potential",
            "moduli space of Higgs bundles",
            "quiver variety",
            "metric measure space",
            "tangent cone",
        ],
        "props": [
            "Riemannian",
            "Kähler",
            "non-Kähler",
            "locally conformally Kähler",
            "Einstein",
            "Kähler--Einstein",
            "complete",
            "geodesically complete",
            "compact",
            "closed",
            "Ricci-positive",
            "Ricci-flat",
            "non-positively curved",
            "negatively curved",
            "positively curved",
            "flat",
            "asymptotically flat",
            "asymptotically conical",
            "minimal",
            "stable",
            "unstable",
            "harmonic",
            "holomorphic",
            "totally geodesic",
            "umbilic",
            "totally umbilic",
            "self-dual",
            "anti-self-dual",
            "irreducible",
            "homogeneous",
            "locally symmetric",
            "isometric",
            "conformally flat",
            "parabolic",
            "hyperbolic",
            "Lorentzian",
            "integrable",
            "polarized",
            "stationary",
        ],
        "spaces": [
            "moduli space",
            "moduli space of Higgs bundles",
            "moduli space of instantons",
            "Teichmüller space",
            "space of metrics",
            "tangent bundle",
            "cotangent bundle",
            "frame bundle",
            "loop space",
            "space of connections",
            "twistor space",
            "Gromov--Hausdorff limit",
            "tangent cone",
            "universal cover",
            "Wasserstein space",
            "configuration space",
            "spectrum of the Laplacian",
            "de Rham cohomology",
            "Dolbeault cohomology",
            "harmonic spinor space",
        ],
        "maps": [
            "the exponential map",
            "the Gauss map",
            "the second fundamental form",
            "the Levi-Civita connection",
            "the Dirac operator",
            "the Hodge star",
            "the Laplace--Beltrami operator",
            "parallel transport",
            "the moment map",
            "the developing map",
            "the harmonic map",
            "the holonomy representation",
            "the period map",
            "the Weingarten map",
            "the shape operator",
        ],
        "invariants": [
            "scalar curvature",
            "sectional curvature",
            "Ricci curvature",
            "holomorphic sectional curvature",
            "mean curvature",
            "Gaussian curvature",
            "Euler characteristic",
            "signature",
            "first Chern class",
            "Chern number",
            "$\\hat A$-genus",
            "holonomy group",
            "injectivity radius",
            "diameter",
            "volume",
            "systole",
            "Yamabe invariant",
            "spectral gap",
            "first eigenvalue",
            "ADM mass",
            "Bartnik mass",
            "Morse index",
            "isoperimetric constant",
            "Cheeger constant",
            "Hodge number",
        ],
        "namedResults": [
            "the Gauss--Bonnet theorem",
            "the Atiyah--Singer index theorem",
            "the Cheeger--Gromoll splitting theorem",
            "Toponogov's theorem",
            "Yau's theorem",
            "the Calabi--Yau theorem",
            "the positive mass theorem",
            "the Schoen--Yau theorem",
            "the Bonnet--Myers theorem",
            "the Bochner--Weitzenböck formula",
            "the Hodge decomposition theorem",
            "the Donaldson--Uhlenbeck--Yau theorem",
            "the Cheeger--Colding theory",
            "the Yamabe problem",
            "the Bishop--Gromov inequality",
            "the Lichnerowicz theorem",
            "the Hard Lefschetz condition",
            "the Hitchin--Kobayashi correspondence",
            "the Nash embedding theorem",
            "the Gromov compactness theorem",
            "the Obata theorem",
            "the Frankel conjecture",
            "the Calabi conjecture",
            "the Hamilton--Ivey estimate",
            "the Li--Yau inequality",
        ],
        "methods": [
            "the maximum principle",
            "a priori estimates",
            "Bochner techniques",
            "the continuity method",
            "geometric flows",
            "blow-up analysis",
            "comparison geometry",
            "the variational method",
            "the moving frame method",
            "Schauder estimates",
            "elliptic regularity theory",
            "heat kernel methods",
            "the method of moving planes",
            "Cheeger--Colding theory",
            "convergence theory",
            "the Hamilton--Perelman program",
            "gluing constructions",
            "spectral methods",
            "Morse theory",
            "the Sacks--Uhlenbeck method",
            "an analysis of the Monge--Ampère equation",
            "a curvature estimate",
            "the index theorem",
            "Gromov--Hausdorff convergence",
        ],
        "objectGloss": [
            "carries rich curvature information",
            "arises naturally in Riemannian geometry",
            "models the geometry of the underlying space",
            "is central to the study of geometric flows",
            "reflects the symmetry of the holonomy group",
            "controls the global topology of the manifold",
            "encodes the spectral data of the Laplacian",
            "lies at the heart of comparison geometry",
        ],
    },
    # Object-naming letters only. No "R" (clashes with the Riemann/Ricci
    # curvature) and no "K" (clashes with sectional curvature K).
    symbols=[
        "M",
        "N",
        "X",
        "Y",
        "g",
        "E",
        "L",
        "\\Sigma",
        "\\omega",
        "\\nabla",
        "\\phi",
        "\\Phi",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\mathrm{Ric}(XSYM) \ge -(@N@-1)",
        r"\mathrm{Sec}(XSYM) \ge 0",
        r"\mathrm{Scal}(XSYM) \ge 0",
        r"\dim_{\mathbb{R}} XSYM = @N@",
        r"\dim H^{@I@}(XSYM;\mathbb{R}) = @N@",
        r"\chi(XSYM) = 2 - 2g",
        r"\partial_t g = -2\,\mathrm{Ric}(g)",
        r"\partial_t F = \vec H",
        r"\Delta_g u = \lambda u",
        r"\lambda_1(XSYM) \ge \frac{@N@}{@N@-1}",
        r"c_1(XSYM) = 0",
        r"\mathrm{vol}(XSYM) \le \omega_{@N@}",
        r"\mathrm{inj}(XSYM) \ge \iota_0 > 0",
        r"\nabla_X Y - \nabla_Y X = [X,Y]",
        r"H = \mathrm{const}",
        r"\Box \phi = 0",
        r"\mathrm{Ric} = \lambda g",
        r"K \equiv -1",
        r"\int_{XSYM} \mathrm{Scal}\, d\mathrm{vol} \le 0",
        r"\hat A(XSYM) = @R@",
        r"\mathrm{Hol}(XSYM) \subseteq \mathrm{SU}(@C@)",
        r"d\omega = 0",
        r"\nabla \omega = 0",
        r"\mathrm{diam}(XSYM) \le \pi",
        r"b_{@I@}(XSYM) = @N@",
        r"\sigma(XSYM) = @R@",
        r"\dim_{\mathbb{C}} XSYM = @C@",
        r"\mathrm{sign}(XSYM) = @R@",
        r"\lvert \mathrm{Rm} \rvert \le \frac{@C@}{t}",
        r"F^{+} = 0",
        r"\Delta_{\bar\partial} ASYM = 0",
        r"\mathrm{index}(D) = \hat A(XSYM)",
        r"R_{ijkl} = -R_{jikl}",
        r"\mathrm{Scal} = @N@(@N@-1)",
        r"\lvert XSYM(t) \rvert \to 0",
    ],
    display_eqns=[
        r"\partial_t g_{ij} = -2\,R_{ij}, \qquad g(0) = g_0",
        r"\int_{XSYM} K\, d\mathrm{vol} = 2\pi\,\chi(XSYM)",
        r"\int_{XSYM} \mathrm{Scal}\, d\mathrm{vol} "
        r"+ 2\int_{\partial XSYM} H\, d\sigma = 2\pi\,\chi(XSYM)",
        r"\mathrm{Ric} - \tfrac{1}{2}\mathrm{Scal}\, g + \Lambda g = 0",
        r"\Delta f - \lvert \nabla f \rvert^2 + \mathrm{Scal} = \mathrm{const}",
        r"\mathrm{Ric}(g) + \nabla^2 f = \lambda g",
        r"\mathrm{index}(D) = \int_{XSYM} \hat A(XSYM)\,\mathrm{ch}(E)",
        r"(\det g_{i\bar j})\,\det\!\left(g_{i\bar j} "
        r"+ \partial_i \partial_{\bar j}\varphi\right)^{-1} = e^{F}",
        r"H^{@I@}_{\mathrm{dR}}(XSYM) \cong "
        r"\bigoplus_{p+q=@I@} H^{p,q}_{\bar\partial}(XSYM)",
        r"0 \to \mathbb{R} \to \Omega^0(XSYM) \xrightarrow{d} "
        r"\Omega^1(XSYM) \xrightarrow{d} \Omega^2(XSYM)",
        r"\lambda_1(XSYM) \ge \frac{n}{n-1}\,\inf_{XSYM}\mathrm{Ric}, "
        r"\qquad \dim XSYM = n",
        r"\mathrm{vol}\bigl(B_r(x)\bigr) "
        r"\le \mathrm{vol}\bigl(B_r^{\kappa}\bigr), \qquad \mathrm{Ric} \ge (n-1)\kappa",
        r"\frac{d}{dt}\,\mathrm{vol}(XSYM,g_t) "
        r"= -\int_{XSYM} \mathrm{Scal}\, d\mathrm{vol}_{g_t}",
        r"\Box_g \phi = \Delta_g \phi - \frac{n-2}{4(n-1)}\,\mathrm{Scal}\,\phi",
        r"\mathcal{W}(g,f,\tau) = \int_{XSYM}\!\bigl[\tau(\mathrm{Scal} "
        r"+ \lvert\nabla f\rvert^2) + f - n\bigr]\,(4\pi\tau)^{-n/2} e^{-f} d\mathrm{vol}",
        r"\frac{1}{16\pi G}\,m_{\mathrm{ADM}}(XSYM) "
        r"= \lim_{r\to\infty}\int_{S_r}(\partial_j g_{ij} - \partial_i g_{jj})\,\nu^i\, d\sigma",
        r"\chi(XSYM) = \frac{1}{(2\pi)^n}\int_{XSYM}\mathrm{Pf}(\Omega), "
        r"\qquad \dim XSYM = 2n",
        r"E_2^{p,q} = H^p\bigl(B; H^q(F)\bigr) \Rightarrow H^{p+q}(XSYM)",
    ],
    msc=["53C20", "53C21", "53C25", "53C44", "53C55", "58J05", "58J60", "53E20"],
    adjacent=["math.GT", "math.AP"],
)
