"""math.DS - Dynamical Systems.

Seed from the build spec, expanded with the arXiv analysis dossier (DS/SP/CA
cluster) into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

DS = SubfieldLexicon(
    code="math.DS",
    name="Dynamical Systems",
    weight=7.0,
    banks={
        "objects": [
            "dynamical system",
            "flow",
            "diffeomorphism",
            "homeomorphism",
            "iterated map",
            "circle map",
            "interval map",
            "geodesic flow",
            "horocycle flow",
            "Anosov flow",
            "Axiom A diffeomorphism",
            "hyperbolic set",
            "attractor",
            "strange attractor",
            "invariant measure",
            "SRB measure",
            "physical measure",
            "Gibbs measure",
            "equilibrium state",
            "periodic orbit",
            "homoclinic orbit",
            "heteroclinic connection",
            "stable manifold",
            "unstable manifold",
            "Julia set",
            "Fatou set",
            "Mandelbrot set",
            "Siegel disk",
            "wandering domain",
            "rotation number",
            "invariant torus",
            "KAM torus",
            "subshift of finite type",
            "symbolic system",
            "transfer operator",
            "Koopman operator",
            "Lyapunov exponent",
            "vector field",
            "period annulus",
            "limit cycle",
            "cocycle",
            "skew product",
            "renormalization operator",
            "interval exchange transformation",
        ],
        "props": [
            "hyperbolic",
            "partially hyperbolic",
            "uniformly hyperbolic",
            "nonuniformly hyperbolic",
            "Anosov",
            "Axiom A",
            "ergodic",
            "uniquely ergodic",
            "mixing",
            "weakly mixing",
            "topologically transitive",
            "minimal",
            "chaotic",
            "expansive",
            "expanding",
            "contracting",
            "structurally stable",
            "robustly transitive",
            "conservative",
            "dissipative",
            "measure-preserving",
            "invariant",
            "recurrent",
            "transitive",
            "topologically conjugate",
            "smoothly conjugate",
            "Diophantine",
            "quasi-periodic",
            "almost periodic",
            "renormalizable",
            "infinitely renormalizable",
            "transcendental",
            "rational",
            "entire",
            "low-regularity",
            "time-varying",
            "random",
            "stationary",
            "equidistributed",
        ],
        "spaces": [
            "phase space",
            "the state space",
            "the configuration space",
            "the attractor",
            "the stable manifold",
            "the unstable manifold",
            "the center manifold",
            "the space of invariant measures",
            "the symbol space",
            "the shift space",
            "the moduli space",
            "the parameter space",
            "the Julia set",
            "the basin of attraction",
            "the non-wandering set",
            "the Teichmüller space",
            "the space of cocycles",
            "the suspension flow",
            "the inverse limit",
            "the spectrum of the transfer operator",
        ],
        "maps": [
            "the time-$t$ map",
            "the first-return map",
            "the Poincaré map",
            "the transfer operator",
            "the Koopman operator",
            "the renormalization operator",
            "the shift map",
            "the holonomy map",
            "the monodromy map",
            "the projection along stable leaves",
            "the conjugacy",
            "the linearization",
            "the rotation map",
            "the doubling map",
            "the return-time function",
        ],
        "invariants": [
            "topological entropy",
            "metric entropy",
            "Kolmogorov--Sinai entropy",
            "Lyapunov exponent",
            "rotation number",
            "Hausdorff dimension",
            "box-counting dimension",
            "correlation dimension",
            "the Lyapunov spectrum",
            "the pressure",
            "the dimension spectrum",
            "the multifractal spectrum",
            "the escape rate",
            "the decay of correlations",
            "the mixing rate",
            "the Mather $\\beta$-function",
            "Mather's $\\alpha$-function",
            "the rotation set",
            "the periodic data",
            "the SRB measure",
            "the Ruelle zeta function",
            "the topological pressure",
            "the spectral gap",
            "the Lyapunov dimension",
            "the entropy production",
        ],
        "namedResults": [
            "the Poincaré recurrence theorem",
            "the Birkhoff ergodic theorem",
            "the Oseledets multiplicative ergodic theorem",
            "Pesin theory",
            "Pesin's entropy formula",
            "the Ruelle inequality",
            "the variational principle for pressure",
            "KAM theory",
            "the KAM theorem",
            "the Anosov closing lemma",
            "the shadowing lemma",
            "the Sharkovskii theorem",
            "the Smale horseshoe theorem",
            "the Hartman--Grobman theorem",
            "the Sinai--Ruelle--Bowen theorem",
            "the Livshits theorem",
            "Ratner's theorems",
            "the Furstenberg multiple recurrence theorem",
            "the Ornstein isomorphism theorem",
            "the Hopf argument",
            "the Conley--Zehnder theorem",
            "the Denjoy theorem",
            "Yoccoz's theorem",
            "the Mañé--Bochi dichotomy",
            "the Bowen--Margulis formula",
        ],
        "methods": [
            "the thermodynamic formalism",
            "the transfer operator method",
            "the variational principle",
            "Pesin theory",
            "the multiplicative ergodic theorem",
            "symbolic dynamics",
            "Markov partitions",
            "the cone technique",
            "the coupling method",
            "KAM theory",
            "renormalization",
            "the shadowing method",
            "the Hopf argument",
            "spectral analysis of the transfer operator",
            "the Anosov closing lemma",
            "an analysis of the Lyapunov exponents",
            "the bracket method",
            "averaging methods",
            "normal form theory",
            "the cohomological equation",
            "equidistribution techniques",
            "the standard pair technique",
            "a study of the periodic orbit structure",
            "Conley index theory",
        ],
        "objectGloss": [
            "encodes the long-time behavior of the system",
            "governs the statistical properties of the orbits",
            "arises naturally in the study of hyperbolic dynamics",
            "controls the rate of mixing of the flow",
            "is central to the ergodic theory of the map",
            "reflects the chaotic structure of the dynamics",
            "captures the asymptotic distribution of trajectories",
            "lies at the heart of the thermodynamic formalism",
        ],
    },
    # Object-naming letters only. No "n", "k", "i" (running indices / iteration
    # count) and no "t" (the continuous time variable in flows \phi_t).
    symbols=[
        "f",
        "T",
        "F",
        "\\varphi",
        "\\Phi",
        "g",
        "\\mu",
        "\\Lambda",
        "X",
        "\\sigma",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"XSYM_{*}\mu = \mu",
        r"h_{\mu}(XSYM) \le h_{\mathrm{top}}(XSYM)",
        r"\lambda = \lim_{n\to\infty}\tfrac{1}{n}\log\lVert D XSYM^n\rVert",
        r"\rho(XSYM) = \lim_{n\to\infty}\tfrac{F^n(x)}{n}",
        r"\mu\bigl(XSYM^{-1}A\bigr) = \mu(A)",
        r"XSYM^{n}(x) \to p \ \text{as}\ n \to \infty",
        r"\dim_H \Lambda = @R@",
        r"h_{\mathrm{top}}(XSYM) = \log\lambda_{\max}",
        r"\frac{1}{n}\sum_{j=0}^{n-1}\varphi\circ XSYM^j \to \int \varphi\, d\mu",
        r"\sum_i \lambda_i = \int \log|\det D XSYM|\, d\mu",
        r"P(\varphi) = \sup_\mu\bigl(h_\mu(XSYM) + \textstyle\int\varphi\, d\mu\bigr)",
        r"\mathcal{L}_\varphi g(x) = \sum_{XSYM(y)=x} e^{\varphi(y)} g(y)",
        r"\lvert C_n(\varphi,\psi)\rvert \le C\,\theta^n",
        r"E^s \oplus E^c \oplus E^u = T_x M",
        r"\lVert D XSYM^n|_{E^s}\rVert \le C\,\lambda^n",
        r"\#\mathrm{Fix}(XSYM^n) = e^{n\, h_{\mathrm{top}}}",
        r"h_\mu(XSYM) = \sum_{\lambda_i > 0}\lambda_i\, m_i",
        r"\omega(x) = \bigcap_{n}\overline{\{XSYM^k(x) : k \ge n\}}",
        r"\zeta(s) = \exp\sum_{n\ge1}\frac{1}{n}\#\mathrm{Fix}(XSYM^n)\, e^{-sn}",
        r"\lambda_1 \ge \lambda_2 \ge \cdots \ge \lambda_d",
        r"XSYM = h^{-1}\circ ASYM \circ h",
        r"\sigma\colon \{1,\dots,@K@\}^{\mathbb{N}} \to \{1,\dots,@K@\}^{\mathbb{N}}",
        r"\rho(XSYM) \in \mathbb{R}\setminus\mathbb{Q}",
        r"D XSYM_p\, v = \lambda\, v",
        r"\mu = \lim_{n\to\infty}\tfrac{1}{n}\sum_{j=0}^{n-1}\delta_{XSYM^j(x)}",
        r"\mathrm{Leb}\bigl(B(\mu)\bigr) > 0",
        r"\varphi\circ XSYM - \varphi = \psi - \int\psi\, d\mu",
        r"\lambda(\omega) = \int \log\lVert A(\omega)\rVert\, d\mathbb{P}",
        r"d(XSYM^n x, XSYM^n y) \le C\,\lambda^n d(x,y)",
        r"P(t\,\varphi) = 0 \ \Rightarrow\ \dim_H = t",
        r"h_{\mathrm{top}}(XSYM) > 0",
        r"\mu_{\varphi} = \tfrac{1}{Z}\, e^{\varphi}\, m",
    ],
    display_eqns=[
        r"h_{\mathrm{top}}(XSYM) = \sup_{\mu \in \mathcal{M}_{XSYM}} h_\mu(XSYM) "
        r"= \lim_{n\to\infty}\frac{1}{n}\log N(n,\varepsilon)",
        r"P(\varphi) = \sup_{\mu \in \mathcal{M}_{XSYM}} "
        r"\left( h_\mu(XSYM) + \int \varphi \, d\mu \right)",
        r"\lambda_i(x) = \lim_{n\to\infty} \frac{1}{n}\,\log\bigl\lVert "
        r"D XSYM^n(x)\, v_i \bigr\rVert, \qquad v_i \in E_i(x)",
        r"h_\mu(XSYM) = \int \sum_{\lambda_i(x) > 0} \lambda_i(x)\, m_i(x)\, d\mu(x) "
        r"\qquad (\text{Pesin})",
        r"\lim_{n\to\infty} \frac{1}{n}\sum_{j=0}^{n-1} \varphi\bigl(XSYM^j(x)\bigr) "
        r"= \int \varphi \, d\mu \quad \text{for } \mu\text{-a.e. } x",
        r"\int \varphi \, d(XSYM_{*}\mu) = \int \varphi \circ XSYM \, d\mu, \qquad "
        r"XSYM_{*}\mu = \mu",
        r"\mathcal{L}_\varphi g(x) = \sum_{y\, :\, XSYM(y) = x} "
        r"e^{\varphi(y)}\, g(y), \qquad \mathcal{L}_\varphi^{*}\, \nu = \lambda\, \nu",
        r"\bigl| \textstyle\int (\psi\circ XSYM^n)\,\phi\, d\mu "
        r"- \int\psi\, d\mu \int\phi\, d\mu \bigr| \le C\,\theta^n\,"
        r"\lVert\psi\rVert\,\lVert\phi\rVert",
        r"h_\mu(XSYM) \le \int \sum_{\lambda_i(x) > 0} \lambda_i(x)\, m_i(x)\, d\mu(x) "
        r"\qquad (\text{Ruelle inequality})",
        r"P(t\, \varphi_u) = 0 \quad\Longrightarrow\quad \dim_H(\Lambda) = t, "
        r"\qquad \varphi_u = -\log\lVert D XSYM|_{E^u}\rVert",
        r"T_x M = E^s(x) \oplus E^u(x), \qquad "
        r"\lVert D XSYM^n|_{E^s}\rVert \le C\,\lambda^n,\ \ "
        r"\lVert D XSYM^{-n}|_{E^u}\rVert \le C\,\lambda^n",
        r"\zeta_{XSYM}(s) = \exp\!\left( \sum_{n \ge 1} \frac{1}{n} "
        r"\sum_{x \in \mathrm{Fix}(XSYM^n)} e^{-s\, S_n\varphi(x)} \right)",
        r"\mu_\varphi(A) = \lim_{n\to\infty} \frac{\sum_{XSYM^n x = x,\ x \in A} "
        r"e^{S_n\varphi(x)}}{\sum_{XSYM^n x = x} e^{S_n\varphi(x)}}",
        r"\frac{1}{n}\sum_{j=0}^{n-1}\delta_{XSYM^j(x)} \xrightarrow{\ w^{*}\ } \mu "
        r"\quad \text{for Lebesgue-a.e. } x \in B(\mu)",
        r"\dot{x} = f(x), \qquad \frac{\partial}{\partial t}\,(XSYM_t)_{*}\mu = 0 "
        r"\ \Longleftrightarrow\ \operatorname{div}(f\mu) = 0",
        r"\lambda(\omega) = \lim_{n\to\infty} \frac{1}{n}\,\log\bigl\lVert "
        r"A(XSYM^{n-1}\omega)\cdots A(\omega)\bigr\rVert \quad \mathbb{P}\text{-a.s.}",
        r"\#\bigl\{\, x : XSYM^n(x) = x \,\bigr\} = e^{n\, h_{\mathrm{top}}(XSYM)}"
        r"\bigl(1 + o(1)\bigr) \quad (n \to \infty)",
        r"\rho(F) = \lim_{n\to\infty} \frac{F^n(x) - x}{n}, \qquad "
        r"F(x+1) = F(x) + 1,\ \ \rho(F) \notin \mathbb{Q}",
    ],
    msc=["37D20", "37A35", "37C40", "37D35", "37E10", "37A25", "37C25", "37H15"],
    adjacent=["math.SP", "math.CA"],
)
