"""math.FA - Functional Analysis.

Seed from the build spec, expanded with the analysis research dossier into a
broad working vocabulary spanning operators, Banach and Hilbert spaces.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

FA = SubfieldLexicon(
    code="math.FA",
    name="Functional Analysis",
    weight=7.0,
    banks={
        "objects": [
            "bounded operator",
            "compact operator",
            "Fredholm operator",
            "self-adjoint operator",
            "unbounded operator",
            "Toeplitz operator",
            "Hankel operator",
            "composition operator",
            "weighted shift",
            "the resolvent",
            "a semigroup",
            "a strongly continuous semigroup",
            "a contraction semigroup",
            "an unconditional basis",
            "a Schauder basis",
            "a frame",
            "a Riesz basis",
            "a reproducing kernel",
            "a positive functional",
            "a bounded functional",
            "a bilinear form",
            "a quadratic form",
            "a projection",
            "a partial isometry",
            "a normal operator",
            "a Lipschitz-free space",
            "a Banach function space",
            "an interpolation space",
            "a tensor product",
            "a numerical range",
            "the spectrum",
            "an invariant subspace",
            "a closed subspace",
            "a convex body",
            "an extreme point",
            "a dual space",
            "a predual",
            "a bidual",
            "an operator ideal",
            "a multiplier",
            "a generator",
            "a contraction",
        ],
        "props": [
            "bounded",
            "compact",
            "self-adjoint",
            "normal",
            "unitary",
            "Fredholm",
            "closed",
            "densely defined",
            "positive",
            "completely positive",
            "completely bounded",
            "nuclear",
            "reflexive",
            "separable",
            "uniformly convex",
            "strictly convex",
            "weakly compact",
            "hypercontractive",
            "contractive",
            "cyclic",
            "hyponormal",
            "subnormal",
            "essentially self-adjoint",
            "dissipative",
            "accretive",
            "sectorial",
            "amenable",
            "hyperreflexive",
            "absolutely summing",
            "$p$-summable",
            "weak-$*$ closed",
            "isometric",
            "isomorphic",
            "complemented",
            "extremal",
            "non-atomic",
            "order-continuous",
            "spectral",
            "trace-class",
        ],
        "spaces": [
            "Banach space",
            "Hilbert space",
            "the dual space",
            "the bidual",
            "a reflexive Banach space",
            "a Lipschitz-free space",
            "a Banach function space",
            "an Orlicz space",
            "a Lebesgue space",
            "the sequence space $\\ell^p$",
            "a Hardy space",
            "a Bergman space",
            "a de Branges--Rovnyak space",
            "a reproducing kernel Hilbert space",
            "an interpolation space",
            "the space of trace-class operators",
            "the space of compact operators",
            "the algebra of bounded operators",
            "a tensor product",
            "the space $c_0$",
        ],
        "maps": [
            "the resolvent",
            "the adjoint",
            "the spectral projection",
            "the functional calculus",
            "the canonical embedding",
            "the quotient map",
            "the multiplication operator",
            "the composition operator",
            "the evaluation functional",
            "the dual map",
            "the inclusion operator",
            "the trace functional",
            "the polar decomposition",
            "the Gelfand transform",
            "the conditional expectation",
        ],
        "invariants": [
            "norm",
            "operator norm",
            "numerical radius",
            "spectral radius",
            "essential norm",
            "Fredholm index",
            "rank",
            "nuclear norm",
            "trace",
            "spectrum",
            "essential spectrum",
            "point spectrum",
            "approximation number",
            "singular value",
            "Banach--Mazur distance",
            "cotype",
            "type",
            "modulus of convexity",
            "James constant",
            "Daugavet constant",
            "basis constant",
            "entropy number",
            "Kolmogorov width",
            "dimension",
            "codimension",
        ],
        "namedResults": [
            "the spectral theorem",
            "the Hahn--Banach theorem",
            "the open mapping theorem",
            "the closed graph theorem",
            "the uniform boundedness principle",
            "the Banach--Steinhaus theorem",
            "the Krein--Milman theorem",
            "the Riesz representation theorem",
            "the Balian--Low theorem",
            "the Daugavet property",
            "the Lax--Milgram theorem",
            "the Hille--Yosida theorem",
            "the Lumer--Phillips theorem",
            "the Gelfand--Naimark theorem",
            "the Eberlein--Šmulian theorem",
            "the Dvoretzky theorem",
            "the Grothendieck inequality",
            "the Pietsch factorization theorem",
            "the Atkinson theorem",
            "the Fredholm alternative",
            "the Beurling--Lax theorem",
            "the Sz.-Nagy dilation theorem",
            "the Russo--Dye theorem",
            "the Kadec--Snobar theorem",
            "the James characterization",
        ],
        "methods": [
            "the functional calculus",
            "a dilation argument",
            "interpolation of operators",
            "a duality argument",
            "the closed-range theorem",
            "a fixed-point argument",
            "spectral analysis",
            "the theory of semigroups",
            "a factorization argument",
            "an ultrapower construction",
            "a renorming technique",
            "the Bellman function method",
            "a perturbation argument",
            "the Gelfand transform",
            "the theory of operator ideals",
            "a compactness argument",
            "the variational method",
            "a separation argument",
            "the theory of frames",
            "a tensor-product construction",
            "an approximation argument",
            "a weak-$*$ compactness argument",
            "the method of dilations",
            "the resolvent calculus",
        ],
        "objectGloss": [
            "encodes the spectral structure of the operator",
            "arises naturally in the geometry of Banach spaces",
            "governs the convergence of the associated series",
            "controls the approximation properties of the space",
            "is central to modern operator theory",
            "reflects the duality between the space and its dual",
            "captures the compactness of the underlying map",
            "lies at the heart of the theory of semigroups",
        ],
    },
    # Object-naming letters only. No "x","y" (vectors), no "n","k" (indices),
    # no "H","L" (reserved for ambient spaces), no "p" (exponent).
    symbols=[
        "T",
        "A",
        "S",
        "B",
        "\\Phi",
        "\\Psi",
        "P",
        "U",
        "M",
        "\\Lambda",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\lVert XSYM ASYM \rVert \le \lVert XSYM \rVert\,\lVert ASYM \rVert",
        r"\sigma(XSYM) \subset \{\,z : |z| \le \lVert XSYM \rVert\,\}",
        r"\operatorname{ind} XSYM = \dim \ker XSYM - \dim \operatorname{coker} XSYM",
        r"XSYM^{*} XSYM = XSYM XSYM^{*}",
        r"r(XSYM) = \lim_{n \to \infty} \lVert XSYM^{n} \rVert^{1/n}",
        r"\lVert XSYM \rVert_{\mathrm{cb}} = \sup_{n} \lVert XSYM \otimes \mathrm{id}_n \rVert",
        r"w(XSYM) \le \lVert XSYM \rVert \le 2\,w(XSYM)",
        r"\dim \ker(XSYM - \lambda) = @N@",
        r"\lVert XSYM \rVert_{1} = \operatorname{tr}\,|XSYM| = \sum_{n} s_n(XSYM)",
        r"\langle XSYM \xi, \xi \rangle \ge 0 \quad\text{for all } \xi",
        r"XSYM = U|XSYM|, \qquad |XSYM| = (XSYM^{*} XSYM)^{1/2}",
        r"\lVert ASYM \rVert_{X^{*}} = \sup_{\lVert \xi \rVert \le 1} |ASYM(\xi)|",
        r"\sigma_{\mathrm{ess}}(XSYM) = \sigma(XSYM) \setminus \sigma_{\mathrm{disc}}(XSYM)",
        r"\overline{XSYM(B_X)} = B_{X^{**}}",
        r"\lVert e^{tXSYM} \rVert \le M\,e^{\omega t}",
        r"s_n(XSYM) = \inf_{\operatorname{rank} R < n} \lVert XSYM - R \rVert",
        r"\lVert XSYM \xi \rVert \ge c\,\lVert \xi \rVert \quad\text{for all } \xi",
        r"XSYM = XSYM^{2} = XSYM^{*}",
        r"\delta_X(\varepsilon) = \inf\{1 - \tfrac12\lVert \xi + \eta \rVert :"
        r" \lVert \xi - \eta \rVert \ge \varepsilon\}",
        r"\lVert XSYM \rVert_{X \to Y} \le C",
        r"\operatorname{tr}(XSYM ASYM) = \operatorname{tr}(ASYM XSYM)",
        r"XSYM \xi_n \rightharpoonup XSYM \xi",
        r"\dim X = @N@ < \infty",
        r"\lVert I - XSYM ASYM \rVert < 1",
        r"\sigma_p(XSYM) = \{\lambda_n\}_{n \ge 1}",
        r"\lVert XSYM \rVert_{\mathrm{HS}}^{2} = \sum_{n} \lVert XSYM e_n \rVert^{2}",
        r"d_{BM}(X,Y) \le @C@",
        r"\lVert XSYM \rVert_{p} = \Bigl(\sum_n s_n(XSYM)^{p}\Bigr)^{1/p}",
        r"R(\lambda, XSYM) = (\lambda I - XSYM)^{-1}",
    ],
    display_eqns=[
        r"XSYM = \int_{\sigma(XSYM)} \lambda\, dE(\lambda), \qquad "
        r"f(XSYM) = \int_{\sigma(XSYM)} f(\lambda)\, dE(\lambda)",
        r"R(\lambda, XSYM) = (\lambda I - XSYM)^{-1} = \sum_{n=0}^{\infty} "
        r"\frac{XSYM^{n}}{\lambda^{n+1}}, \qquad |\lambda| > r(XSYM)",
        r"e^{tXSYM} = \frac{1}{2\pi i}\int_{\Gamma} e^{t\lambda}\,"
        r"(\lambda I - XSYM)^{-1}\, d\lambda, \qquad t \ge 0",
        r"0 \to \ker XSYM \to X \xrightarrow{\;XSYM\;} Y \to \operatorname{coker} XSYM \to 0, "
        r"\qquad \operatorname{ind} XSYM = @R@ - @C@",
        r"\lVert \xi \rVert = \sup_{\lVert ASYM \rVert_{X^{*}} \le 1} |ASYM(\xi)|, "
        r"\qquad \xi \in X",
        r"XSYM \xi = \sum_{n=1}^{\infty} s_n\,\langle \xi, e_n \rangle\, f_n, "
        r"\qquad s_1 \ge s_2 \ge \cdots \ge 0",
        r"\langle XSYM \xi, \eta \rangle = \langle \xi, XSYM^{*} \eta \rangle "
        r"\quad\text{for all } \xi, \eta \in H",
        r"\left|\sum_{i,j} a_{ij}\,\langle \xi_i, \eta_j \rangle\right| "
        r"\le K_G\,\lVert (a_{ij}) \rVert\,\sup_i \lVert \xi_i \rVert\,\sup_j \lVert \eta_j \rVert",
        r"\lVert XSYM + \lambda I \rVert = \lVert XSYM \rVert + |\lambda| "
        r"\quad\text{for all } \lambda \in \mathbb{C} \quad (\text{Daugavet})",
        r"\sigma(XSYM) = \sigma_{\mathrm{disc}}(XSYM) \cup \sigma_{\mathrm{ess}}(XSYM), "
        r"\qquad XSYM = XSYM^{*}",
        r"\xi = \sum_{n=1}^{\infty} \langle \xi, e_n \rangle\, e_n, \qquad "
        r"\lVert \xi \rVert^{2} = \sum_{n=1}^{\infty} |\langle \xi, e_n \rangle|^{2}",
        r"A\,\lVert \xi \rVert^{2} \le \sum_{n} |\langle \xi, f_n \rangle|^{2} "
        r"\le B\,\lVert \xi \rVert^{2}, \qquad 0 < A \le B < \infty",
        r"\lVert XSYM \rVert_{[X_0,X_1]_\theta} \le \lVert XSYM \rVert_{X_0}^{1-\theta}\,"
        r"\lVert XSYM \rVert_{X_1}^{\theta}, \qquad 0 < \theta < 1",
        r"XSYM = \begin{pmatrix} XSYM_{11} & XSYM_{12} \\ XSYM_{21} & XSYM_{22} \end{pmatrix}, "
        r"\qquad XSYM_{ij} \in \mathcal{B}(H)",
        r"\frac{d}{dt}\,\xi(t) = XSYM\,\xi(t), \quad t > 0, \qquad \xi(0) = \xi_0, "
        r"\qquad \xi(t) = e^{tXSYM}\xi_0",
        r"XSYM = U|XSYM|, \qquad |XSYM| = (XSYM^{*}XSYM)^{1/2}, "
        r"\qquad U \text{ a partial isometry}",
        r"\operatorname{tr}(XSYM) = \sum_{n=1}^{\infty} \langle XSYM e_n, e_n \rangle, "
        r"\qquad |\operatorname{tr}(XSYM)| \le \lVert XSYM \rVert_1",
        r"W(XSYM) = \{\,\langle XSYM \xi, \xi \rangle : \lVert \xi \rVert = 1\,\}, "
        r"\qquad \sigma(XSYM) \subset \overline{W(XSYM)}",
    ],
    msc=["46B20", "47A10", "46E15", "47B35", "46B07", "47D06", "47A53", "46L07"],
    adjacent=["math.OA", "math.CA", "math.AP"],
)
