"""math.GM - General Mathematics.

Deliberately broad and eclectic: a cross-cutting working vocabulary of general
mathematical objects, widely known results, and broad methods, kept at roughly
the same scale as the number-theory dossier.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

GM = SubfieldLexicon(
    code="math.GM",
    name="General Mathematics",
    weight=1.0,
    banks={
        "objects": [
            "mathematical structure",
            "classical construction",
            "function",
            "series",
            "sequence",
            "identity",
            "equation",
            "inequality",
            "expression",
            "formula",
            "theorem",
            "lemma",
            "framework",
            "model",
            "system",
            "transformation",
            "operator",
            "polynomial",
            "integer",
            "rational number",
            "real number",
            "complex number",
            "matrix",
            "vector",
            "set",
            "mapping",
            "relation",
            "group",
            "ring",
            "field",
            "space",
            "graph",
            "tree",
            "partition",
            "permutation",
            "distribution",
            "limit",
            "approximation",
            "generalization",
            "abstraction",
            "general principle",
            "unifying notion",
            "elementary object",
        ],
        "props": [
            "classical",
            "elementary",
            "explicit",
            "general",
            "fundamental",
            "well-known",
            "standard",
            "elegant",
            "self-contained",
            "rigorous",
            "constructive",
            "abstract",
            "concrete",
            "finite",
            "infinite",
            "discrete",
            "continuous",
            "bounded",
            "unbounded",
            "symmetric",
            "linear",
            "nonlinear",
            "regular",
            "natural",
            "canonical",
            "arbitrary",
            "universal",
            "foundational",
            "unifying",
            "broadly applicable",
            "widely used",
            "deceptively simple",
            "remarkably general",
            "cross-cutting",
            "well-posed",
            "non-trivial",
            "essentially unique",
            "intuitive",
        ],
        "spaces": [
            "the real line",
            "the plane",
            "the complex plane",
            "the integers",
            "the rationals",
            "the natural numbers",
            "Euclidean space",
            "a finite set",
            "a vector space",
            "a function space",
            "a metric space",
            "a topological space",
            "an abstract structure",
            "the unit interval",
            "the unit circle",
            "a coordinate system",
            "an algebraic structure",
            "the continuum",
            "a discrete domain",
            "a normed space",
        ],
        "maps": [
            "the identity map",
            "a linear map",
            "a bijection",
            "an isomorphism",
            "a homomorphism",
            "a projection",
            "the inverse map",
            "the derivative",
            "an integral transform",
            "the summation operator",
            "a substitution",
            "a change of variables",
            "the limit operation",
            "a recursive procedure",
            "the composition of maps",
        ],
        "invariants": [
            "degree",
            "dimension",
            "cardinality",
            "order",
            "rank",
            "index",
            "size",
            "norm",
            "length",
            "magnitude",
            "parity",
            "sign",
            "sum",
            "product",
            "ratio",
            "trace",
            "determinant",
            "coefficient",
            "exponent",
            "the number of solutions",
            "the count of configurations",
            "the value at a point",
            "the limiting value",
            "a scaling constant",
            "the leading coefficient",
        ],
        "namedResults": [
            "the fundamental theorem of algebra",
            "the fundamental theorem of calculus",
            "the fundamental theorem of arithmetic",
            "Euler's formula",
            "the prime number theorem",
            "Cauchy's theorem",
            "the binomial theorem",
            "the Pythagorean theorem",
            "the intermediate value theorem",
            "the mean value theorem",
            "the Cauchy--Schwarz inequality",
            "the triangle inequality",
            "the pigeonhole principle",
            "the principle of induction",
            "Fermat's little theorem",
            "the Chinese remainder theorem",
            "Stirling's formula",
            "Taylor's theorem",
            "the spectral theorem",
            "the contraction mapping principle",
            "the irrationality of $\\sqrt{2}$",
            "the infinitude of primes",
            "the Basel problem",
            "the Bolzano--Weierstrass theorem",
            "the arithmetic--geometric mean inequality",
        ],
        "methods": [
            "elementary techniques",
            "a generating-function argument",
            "an explicit construction",
            "mathematical induction",
            "a counting argument",
            "a direct computation",
            "proof by contradiction",
            "a change of variables",
            "a telescoping argument",
            "an inductive argument",
            "a symmetry argument",
            "a combinatorial bijection",
            "a limiting argument",
            "an elementary estimate",
            "a geometric construction",
            "a recursive decomposition",
            "term-by-term comparison",
            "a pigeonhole argument",
            "a fixed-point argument",
            "a careful case analysis",
            "an appeal to first principles",
            "a generalization of a classical result",
            "a unified treatment",
        ],
        "objectGloss": [
            "appears throughout the mathematical sciences",
            "admits many equivalent formulations",
            "unifies several apparently unrelated ideas",
            "is taught in nearly every introductory course",
            "illustrates the power of elementary reasoning",
            "connects distant branches of mathematics",
            "continues to inspire new lines of inquiry",
            "underlies much of modern mathematics",
        ],
    },
    # Generic object-naming letters, kept collision-free with the equation
    # templates below (no "n" or "k", which appear as summation indices).
    symbols=[
        "X",
        "f",
        "a_n",
        "S",
        "F",
        "P",
        "A",
        "g",
        "T",
        "M",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw.
    inline_eqns=[
        r"\binom{@N@}{@C@} = \binom{@N@}{@N@-@C@}",
        r"\sum_{k=0}^{@N@} \binom{@N@}{k} = 2^{@N@}",
        r"\sum_{k=1}^{@N@} k = \frac{@N@(@N@+1)}{2}",
        r"\sum_{k=1}^{@N@} k^{3} = \left(\frac{@N@(@N@+1)}{2}\right)^{2}",
        r"\sum_{k=1}^{@N@} (2k-1) = @N@^{2}",
        r"e^{i\pi} + 1 = 0",
        r"a_n = a_{n-1} + a_{n-2}",
        r"\gcd(a,b)\,\operatorname{lcm}(a,b) = ab",
        r"\lvert x + y \rvert \le \lvert x \rvert + \lvert y \rvert",
        r"\left\lvert \langle x, y \rangle \right\rvert \le \lVert x \rVert\,\lVert y \rVert",
        r"\frac{a+b}{2} \ge \sqrt{ab}",
        r"XSYM \circ ASYM = \mathrm{id}",
        r"(a+b)^{2} = a^{2} + 2ab + b^{2}",
        r"a^{3} - b^{3} = (a-b)(a^{2}+ab+b^{2})",
        r"\sum_{k=0}^{@N@} r^{k} = \frac{1 - r^{@N@+1}}{1 - r}",
        r"\det(AB) = \det A \, \det B",
        r"n! = n\,(n-1)!",
        r"\zeta(2) = \frac{\pi^{2}}{6}",
        r"\cos^{2}\theta + \sin^{2}\theta = 1",
        r"\frac{d}{dx} e^{x} = e^{x}",
        r"\int_0^1 x^{@N@}\,dx = \frac{1}{@N@+1}",
        r"\log(ab) = \log a + \log b",
        r"\lim_{n \to \infty} \left(1 + \tfrac{1}{n}\right)^{n} = e",
        r"\operatorname{tr}(AB) = \operatorname{tr}(BA)",
        r"\sqrt{2} \notin \mathbb{Q}",
        r"\deg(fg) = \deg f + \deg g",
        r"\lvert XSYM \rvert = @N@",
        r"F_{n+1} F_{n-1} - F_n^{2} = (-1)^{n}",
    ],
    display_eqns=[
        r"e^{i\theta} = \cos\theta + i\sin\theta",
        r"\sum_{n=0}^{\infty} x^{n} = \frac{1}{1-x}, \qquad \lvert x \rvert < 1",
        r"(a+b)^{n} = \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^{k}",
        r"\left( \sum_{k=1}^{n} a_k b_k \right)^{2} "
        r"\le \left( \sum_{k=1}^{n} a_k^{2} \right)\left( \sum_{k=1}^{n} b_k^{2} \right)",
        r"\sum_{n=0}^{\infty} \frac{x^{n}}{n!} = e^{x}",
        r"\sum_{n=1}^{\infty} \frac{1}{n^{2}} = \frac{\pi^{2}}{6}",
        r"\int_{-\infty}^{\infty} e^{-x^{2}}\,dx = \sqrt{\pi}",
        r"\sum_{k=0}^{n} \binom{n}{k}^{2} = \binom{2n}{n}",
        r"\sum_{n \ge 0} F_n\, x^{n} = \frac{x}{1 - x - x^{2}}",
        r"n! \sim \sqrt{2\pi n}\,\left(\frac{n}{e}\right)^{n} \quad (n \to \infty)",
        r"\binom{n}{k} = \binom{n-1}{k-1} + \binom{n-1}{k}",
        r"\frac{a_1 + a_2 + \cdots + a_n}{n} \ge \sqrt[n]{a_1 a_2 \cdots a_n}",
        r"\pi(x) \sim \frac{x}{\log x} \quad (x \to \infty)",
        r"f(x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(a)}{n!}\,(x-a)^{n}",
        r"\int_a^b f'(x)\,dx = f(b) - f(a)",
        r"\sum_{d \mid n} \varphi(d) = n",
    ],
    msc=["00A05", "00A06", "00A30", "00A35", "00A69", "00A71"],
    adjacent=["math.HO"],
)
