"""math.GN - General Topology.

Seeded from the geometry/topology research dossier and expanded into a broad
working vocabulary covering set-theoretic topology, compactifications, continua
theory, and topological algebra.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

GN = SubfieldLexicon(
    code="math.GN",
    name="General Topology",
    weight=2.0,
    banks={
        "objects": [
            "topological space",
            "open set",
            "closed set",
            "neighborhood filter",
            "filter",
            "ultrafilter",
            "net",
            "base",
            "subbase",
            "local base",
            "open cover",
            "refinement",
            "compactification",
            "Stone-Čech compactification",
            "one-point compactification",
            "Wallman compactification",
            "remainder",
            "continuum",
            "indecomposable continuum",
            "Peano continuum",
            "dendrite",
            "topological group",
            "topological vector space",
            "uniform space",
            "uniformity",
            "proximity space",
            "frame",
            "locale",
            "spectrum of a ring",
            "Stone space",
            "Cantor set",
            "Sorgenfrey line",
            "long line",
            "Tychonoff plank",
            "Niemytzki plane",
            "$\\beta\\mathbb{N}$",
            "Boolean algebra",
            "lattice of open sets",
            "hyperspace",
            "inverse limit",
            "cardinal invariant",
            "separable metrizable space",
            "zero-dimensional space",
        ],
        "props": [
            "compact",
            "locally compact",
            "countably compact",
            "sequentially compact",
            "pseudocompact",
            "paracompact",
            "metacompact",
            "Lindelöf",
            "connected",
            "locally connected",
            "path-connected",
            "totally disconnected",
            "Hausdorff",
            "regular",
            "completely regular",
            "normal",
            "perfectly normal",
            "Tychonoff",
            "first-countable",
            "second-countable",
            "separable",
            "metrizable",
            "completely metrizable",
            "Polish",
            "zero-dimensional",
            "extremally disconnected",
            "scattered",
            "nowhere dense",
            "dense",
            "$T_1$",
            "$T_3$",
            "hereditarily Lindelöf",
            "$\\sigma$-compact",
            "realcompact",
            "Baire",
            "homogeneous",
            "rim-compact",
            "well-filtered",
            "sober",
            "ccc",
        ],
        "spaces": [
            "a topological space $XSYM$",
            "the Stone-Čech compactification $\\beta XSYM$",
            "the remainder $XSYM^{*}$",
            "the space of ultrafilters",
            "the Stone space of a Boolean algebra",
            "the Cantor set",
            "the Hilbert cube",
            "the Sorgenfrey line",
            "the long line",
            "the hyperspace $2^{XSYM}$",
            "the space of continuous functions $C(XSYM)$",
            "the one-point compactification $XSYM^{+}$",
            "the Wallman compactification",
            "the inverse limit space",
            "the absolute of a space",
            "the Tychonoff product",
            "the Niemytzki plane",
            "the lattice of open sets",
        ],
        "maps": [
            "a continuous map",
            "a homeomorphism",
            "a perfect map",
            "a quotient map",
            "an open map",
            "a closed map",
            "a proper map",
            "the canonical embedding into $\\beta XSYM$",
            "the evaluation map",
            "a retraction",
            "the projection of an inverse system",
            "a closed irreducible map",
            "the Stone duality functor",
            "a uniformly continuous map",
            "the natural projection onto the remainder",
        ],
        "invariants": [
            "the weight",
            "the density",
            "the character",
            "the cellularity",
            "the spread",
            "the extent",
            "the Lindelöf number",
            "the tightness",
            "the $\\pi$-weight",
            "the network weight",
            "the covering dimension $\\dim$",
            "the small inductive dimension $\\mathrm{ind}$",
            "the large inductive dimension $\\mathrm{Ind}$",
            "the cardinality",
            "the number of connected components",
            "the Souslin number",
            "the pseudocharacter",
            "the compactness degree",
            "the Novak number",
            "the cofinality of the remainder",
            "the cardinal function $hL$",
            "the cardinal function $hd$",
            "the local compactness defect",
            "the order of a continuum",
            "the span",
        ],
        "namedResults": [
            "Urysohn's lemma",
            "the Tietze extension theorem",
            "the Tychonoff theorem",
            "the Stone-Čech theorem",
            "Stone's representation theorem",
            "the Stone duality",
            "the Baire category theorem",
            "the Urysohn metrization theorem",
            "the Nagata--Smirnov metrization theorem",
            "the Bing metrization theorem",
            "Michael's selection theorem",
            "the Alexander subbase lemma",
            "the Hahn--Mazurkiewicz theorem",
            "the Čech--Pospišil theorem",
            "the Glicksberg theorem",
            "the Eberlein--Šmulian theorem",
            "the Katetov--Tong insertion theorem",
            "Dowker's theorem",
            "the Dugundji extension theorem",
            "the Mardesić factorization theorem",
            "the Parovičenko theorem",
            "the Boolean prime ideal theorem",
            "the Hewitt--Marczewski--Pondiczery theorem",
            "the Arhangel'skii theorem",
            "the Pixley--Roy construction",
        ],
        "methods": [
            "the theory of filters and ultrafilters",
            "a compactification argument",
            "Stone duality",
            "transfinite induction",
            "an inverse limit construction",
            "the method of cardinal invariants",
            "a forcing argument",
            "the technique of elementary submodels",
            "a partition of unity",
            "the analysis of the remainder",
            "a closing-off argument",
            "a $\\Delta$-system argument",
            "the absolute of a space",
            "a selection-theoretic argument",
            "the theory of proximity spaces",
            "the Wallman construction",
            "a continuum-theoretic argument",
            "the Stone space functor",
            "a refinement argument",
            "a metrization argument",
            "the analysis of convergent nets",
            "an extension-by-continuity argument",
            "the technique of free sequences",
            "a pressing-down argument",
        ],
        "objectGloss": [
            "encodes the convergence structure of the space",
            "compactifies the space in a universal way",
            "detects separation properties of the space",
            "controls the cardinal invariants of the space",
            "reflects the set-theoretic complexity of the topology",
            "governs the extension of continuous functions",
            "captures the lattice structure of the open sets",
            "is central to set-theoretic topology",
        ],
    },
    # Object-naming letters and forms only. No "T" (the topology itself / the
    # separation axioms T_i), no lowercase index letters used as points.
    symbols=[
        "X",
        "Y",
        "Z",
        "K",
        "U",
        "F",
        "\\mathcal{U}",
        "\\mathcal{F}",
        "\\beta",
        "\\tau",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\overline{A} = A \cup A'",
        r"\mathrm{int}(A) \subseteq A \subseteq \overline{A}",
        r"\bigcap_{i} U_i \in \tau",
        r"w(XSYM) = @N@",
        r"d(XSYM) \le w(XSYM)",
        r"|XSYM| \le 2^{w(XSYM)}",
        r"\dim XSYM = @N@",
        r"\mathrm{ind}\, XSYM \le \mathrm{Ind}\, XSYM",
        r"c(XSYM) \le \mathfrak{c}",
        r"\chi(x, XSYM) = \aleph_0",
        r"XSYM \hookrightarrow [0,1]^{w(XSYM)}",
        r"|\beta\mathbb{N}| = 2^{\mathfrak{c}}",
        r"\overline{f(\overline{A})} = \overline{f(A)}",
        r"U \cap V = \varnothing",
        r"\mathcal{U} \to x",
        r"L(XSYM) \le @N@",
        r"t(XSYM) \le \aleph_0",
        r"|XSYM| \le 2^{L(XSYM)\,\chi(XSYM)}",
        r"XSYM \cong \varprojlim XSYM_\alpha",
        r"\beta XSYM \setminus XSYM = XSYM^{*}",
        r"f: XSYM \twoheadrightarrow Y",
        r"hd(XSYM) = hL(XSYM)",
        r"\mathcal{F} \subseteq \mathcal{U}",
        r"\bigcup \mathcal{U} = XSYM",
        r"s(XSYM) \le c(XSYM)^{+}",
        r"\mathrm{nw}(XSYM) \le w(XSYM)",
        r"XSYM = \overline{D},\ |D| \le \aleph_0",
        r"\pi w(XSYM) \le w(XSYM)",
        r"\mathrm{Clop}(XSYM) \cong B",
        r"\psi(x, XSYM) \le @N@",
        r"K \subseteq \bigcup_{i=1}^{@N@} U_i",
        r"e(XSYM) \le L(XSYM)",
        r"\beta(XSYM \times Y) = \beta XSYM \times \beta Y",
        r"\mathcal{U} = \{ A : x \in \mathrm{int}\, A \}",
        r"\dim(XSYM \times Y) \le \dim XSYM + \dim Y",
        r"|\,XSYM^{*}| = 2^{\mathfrak{c}}",
    ],
    display_eqns=[
        r"\beta XSYM = \bigl\{\, \mathcal{U} : \mathcal{U} \text{ is an ultrafilter on } "
        r"Z(XSYM) \,\bigr\}",
        r"C(XSYM) \xrightarrow{\ \sim\ } C(\beta XSYM), "
        r"\qquad f \longmapsto f^{\beta}",
        r"XSYM \xrightarrow{\ e\ } \beta XSYM, \qquad "
        r"e(x) = \{\, A \in Z(XSYM) : x \in A \,\}",
        r"\beta XSYM = \overline{e(XSYM)} \subseteq [0,1]^{C(XSYM,[0,1])}",
        r"|XSYM| \le 2^{\,L(XSYM)\cdot\chi(XSYM)} "
        r"\qquad\text{(the Arhangel'skii inequality)}",
        r"d(XSYM) \le \mathfrak{m} \ \Longrightarrow\ "
        r"d\Bigl(\prod_{i \in I} X_i\Bigr) \le \mathfrak{m}, \quad |I| \le 2^{\mathfrak{m}}",
        r"\mathrm{Spec}(B) = \bigl\{\, \mathfrak{p} : "
        r"\mathfrak{p} \text{ a prime ideal of } B \,\bigr\}, \quad "
        r"\mathrm{Clop}(\mathrm{Spec}\, B) \cong B",
        r"f|_{A} \colon A \to [0,1] \ \Longrightarrow\ "
        r"\exists\, F \colon XSYM \to [0,1],\ F|_{A} = f|_{A}",
        r"A \cap B = \varnothing \ \Longrightarrow\ "
        r"\exists\, U \colon XSYM \to [0,1],\ U|_{A} = 0,\ U|_{B} = 1",
        r"\prod_{i \in I} K_i \text{ is compact} "
        r"\iff K_i \text{ is compact for every } i \in I",
        r"\mathrm{ind}\, XSYM = -1 \iff XSYM = \varnothing, \qquad "
        r"\mathrm{ind}\, XSYM \le n+1 \text{ via small bases}",
        r"w(XSYM) = \sup\bigl\{\, \chi(x, XSYM) : x \in XSYM \,\bigr\} \cdot L(XSYM)",
        r"XSYM = \varprojlim_{\alpha < \kappa} (XSYM_\alpha, p_{\beta\alpha}), "
        r"\qquad p_{\gamma\alpha} = p_{\beta\alpha} \circ p_{\gamma\beta}",
        r"\bigcap_{n \in \mathbb{N}} U_n \text{ is dense} "
        r"\quad\text{whenever each } U_n \text{ is dense open in a Baire space}",
        r"hL(XSYM) = \sup\bigl\{\, L(Y) : Y \subseteq XSYM \,\bigr\}, "
        r"\qquad hd(XSYM) = \sup\bigl\{\, d(Y) : Y \subseteq XSYM \,\bigr\}",
        r"\beta\mathbb{N} \setminus \mathbb{N} = \mathbb{N}^{*} "
        r"\cong \mathrm{Spec}\bigl(\mathcal{P}(\mathbb{N})/\mathrm{fin}\bigr)",
        r"K \subseteq \bigcup_{\alpha} U_\alpha \ \Longrightarrow\ "
        r"K \subseteq \bigcup_{i=1}^{n} U_{\alpha_i} \quad\text{(some finite subfamily)}",
        r"c(XSYM) = \sup\bigl\{\, |\mathcal{U}| : \mathcal{U} \text{ a disjoint family of "
        r"open sets} \,\bigr\}",
    ],
    msc=["54A20", "54D35", "54D30", "54F15", "54A25", "54D80", "54G05", "06E15"],
    adjacent=["math.LO", "math.GR"],
)
