"""math.GR - Group Theory.

Seeded from the build spec and expanded with the algebra/number-theory research
dossier into a broad working vocabulary of finite, profinite, and geometric
group theory.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

GR = SubfieldLexicon(
    code="math.GR",
    name="Group Theory",
    weight=6.0,
    banks={
        "objects": [
            "finite group",
            "simple group",
            "finite simple group",
            "$p$-group",
            "nilpotent group",
            "solvable group",
            "Sylow subgroup",
            "Coxeter group",
            "Coxeter system",
            "Weyl group",
            "reflection group",
            "symmetric group",
            "alternating group",
            "free group",
            "free product",
            "hyperbolic group",
            "relatively hyperbolic group",
            "right-angled Artin group",
            "Artin group",
            "braid group",
            "mapping class group",
            "profinite group",
            "pro-$p$ group",
            "totally disconnected group",
            "locally compact group",
            "Thompson's group",
            "Bianchi group",
            "arithmetic group",
            "lattice",
            "linear group",
            "matrix group",
            "permutation group",
            "conjugacy class",
            "centralizer",
            "normalizer",
            "commutator subgroup",
            "Frattini subgroup",
            "wreath product",
            "Cayley graph",
            "commuting graph",
            "string C-group",
            "fusion system",
        ],
        "props": [
            "finite",
            "infinite",
            "simple",
            "solvable",
            "nilpotent",
            "supersolvable",
            "perfect",
            "abelian",
            "non-abelian",
            "metabelian",
            "polycyclic",
            "free",
            "virtually free",
            "virtually abelian",
            "residually finite",
            "residually $p$",
            "hyperbolic",
            "relatively hyperbolic",
            "acylindrically hyperbolic",
            "amenable",
            "linear",
            "profinite",
            "pro-$p$",
            "totally disconnected",
            "locally finite",
            "locally compact",
            "compactly generated",
            "finitely generated",
            "finitely presented",
            "torsion-free",
            "transitive",
            "primitive",
            "$2$-transitive",
            "sharply transitive",
            "quasisimple",
            "characteristically simple",
            "Frobenius",
            "supersingular",
            "self-normalizing",
            "maximal",
        ],
        "spaces": [
            "Cayley graph",
            "commuting graph",
            "Bass--Serre tree",
            "boundary at infinity",
            "Rips complex",
            "classifying space",
            "building",
            "symmetric space",
            "character variety",
            "representation variety",
            "outer automorphism group",
            "automorphism group",
            "profinite completion",
            "pro-$p$ completion",
            "Burnside ring",
            "group algebra",
            "complex group algebra",
            "lattice of subgroups",
            "conjugacy class",
            "coset space",
        ],
        "maps": [
            "the transfer map",
            "the regular representation",
            "the natural projection",
            "the conjugation action",
            "the quotient map",
            "the inclusion of a subgroup",
            "the abelianization map",
            "a faithful permutation action",
            "the verbal map",
            "the restriction map",
            "the induction functor",
            "the Cayley embedding",
            "the augmentation map",
            "the word map",
            "the canonical surjection",
        ],
        "invariants": [
            "order",
            "exponent",
            "index",
            "rank",
            "nilpotency class",
            "derived length",
            "Fitting length",
            "number of conjugacy classes",
            "commuting probability",
            "minimal degree",
            "subgroup growth",
            "word growth",
            "growth rate",
            "girth",
            "diameter",
            "spectral gap",
            "Hirsch length",
            "cohomological dimension",
            "virtual cohomological dimension",
            "Euler characteristic",
            "character degree",
            "class number",
            "centralizer order",
            "fixed-point ratio",
            "minimal faithful degree",
        ],
        "namedResults": [
            "the classification of finite simple groups",
            "Sylow's theorems",
            "Cauchy's theorem",
            "Hall's theorem",
            "Lagrange's theorem",
            "Burnside's theorem",
            "the Feit--Thompson theorem",
            "the Schur--Zassenhaus theorem",
            "the Jordan--Hölder theorem",
            "the Krull--Schmidt theorem",
            "the Nielsen--Schreier theorem",
            "the Stallings--Swan theorem",
            "the Bass--Serre theory",
            "the Tits alternative",
            "Gromov's theorem",
            "the Margulis superrigidity theorem",
            "the normal subgroup theorem",
            "the Baer theorem",
            "the Frobenius--Schur theory",
            "the Brauer--Fowler theorem",
            "the Z* theorem",
            "the Higman--Sims construction",
            "the O'Nan--Scott theorem",
            "the McKay conjecture",
            "the Alperin weight conjecture",
        ],
        "methods": [
            "character theory",
            "the theory of group actions",
            "Bass--Serre theory",
            "the classification of finite simple groups",
            "small cancellation theory",
            "geometric group theory",
            "the theory of fusion systems",
            "the transfer homomorphism",
            "a counting argument",
            "the orbit--stabilizer theorem",
            "the theory of permutation groups",
            "representation-theoretic methods",
            "the probabilistic method",
            "an analysis of the maximal subgroups",
            "the theory of buildings",
            "cohomological methods",
            "the amalgam method",
            "an induction on the order",
            "the theory of $p$-groups",
            "local analysis",
            "the theory of profinite groups",
            "spectral methods on the Cayley graph",
            "the word problem techniques",
            "ping-pong arguments",
        ],
        "objectGloss": [
            "captures the symmetry of the underlying object",
            "encodes the local structure of the group",
            "governs the subgroup lattice",
            "reflects the geometry of the Cayley graph",
            "controls the representation theory of the group",
            "is central to modern group theory",
            "measures the complexity of the word problem",
            "arises naturally in the classification program",
        ],
    },
    # Object-naming letters only. No "n, i, j" (clash with order and indexing)
    # and no "p" (clashes with the prime p in p-groups and Sylow p-subgroups).
    symbols=[
        "G",
        "H",
        "N",
        "K",
        "A",
        "Q",
        "\\Gamma",
        "S",
        "W",
        "\\rho",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"[G : H] = \frac{|G|}{|H|}",
        r"|G| = @P@^{@C@} \cdot @N@",
        r"|XSYM| = @N@",
        r"XSYM \cong \mathbb{Z}/@N@\mathbb{Z}",
        r"[XSYM, XSYM] \trianglelefteq XSYM",
        r"Z(XSYM) \neq 1",
        r"n_p \equiv 1 \pmod p",
        r"k(XSYM) = @N@",
        r"XSYM / Z(XSYM) \cong \mathrm{Inn}(XSYM)",
        r"\mathrm{rank}\, XSYM = @C@",
        r"\langle x, y \mid x^{@C@} = y^{@C@} = 1 \rangle",
        r"|\mathrm{Cl}(g)| = [G : C_G(g)]",
        r"\sum_{\chi \in \mathrm{Irr}(G)} \chi(1)^2 = |G|",
        r"H \cap K = 1, \quad HK = G",
        r"\gamma_{@I@}(XSYM) = 1",
        r"XSYM^{(@C@)} = 1",
        r"\mathrm{Syl}_p(XSYM) \neq \varnothing",
        r"\langle S \rangle = XSYM",
        r"\mathrm{cd}(XSYM) = @N@",
        r"\chi(1) \mid [G : Z(G)]",
        r"\mathrm{exp}(XSYM) = @N@",
        r"|\mathrm{Aut}(XSYM)| = @N@",
        r"d(XSYM) \le @C@",
        r"\beta_{XSYM}(@N@) \asymp @N@^{@C@}",
        r"XSYM \hookrightarrow \mathrm{Sym}(@N@)",
        r"|N| \cdot |G/N| = |G|",
        r"\mathrm{Pr}(G) = \frac{k(G)}{|G|}",
        r"\langle a, b \mid [a, b] = 1 \rangle \cong \mathbb{Z}^{2}",
        r"|G : N_G(P)| \equiv 1 \pmod p",
        r"\delta_G \asymp e^{@C@ n}",
    ],
    display_eqns=[
        r"1 \to N \to G \to G/N \to 1",
        r"|G| = \sum_{i=1}^{k} [G : C_G(g_i)] = |Z(G)| + \sum_{i} [G : C_G(g_i)]",
        r"\sum_{\chi \in \mathrm{Irr}(G)} \chi(1)^{2} = |G|, "
        r"\qquad |\mathrm{Irr}(G)| = k(G)",
        r"G = G_0 \trianglerighteq G_1 \trianglerighteq \cdots "
        r"\trianglerighteq G_n = 1, \qquad G_{i}/G_{i+1} \text{ simple}",
        r"\bigl|\{\, x \in X : g \cdot x = x \,\}\bigr| "
        r"= |X^{g}|, \qquad |X/G| = \frac{1}{|G|}\sum_{g \in G} |X^{g}|",
        r"1 \to \mathrm{Inn}(G) \to \mathrm{Aut}(G) \to \mathrm{Out}(G) \to 1",
        r"\gamma_1(G) = G \supseteq \gamma_2(G) \supseteq \cdots, "
        r"\qquad \gamma_{i+1}(G) = [\gamma_i(G), G]",
        r"\sum_{d \mid n} \bigl|\{\, g \in G : g^{d} = 1 \,\}\bigr| "
        r"\equiv 0 \pmod{\gcd(n, |G|)}",
        r"G \cong \pi_1\bigl(\Gamma\bigr) = "
        r"\Bigl( \ast_{v} G_v \Bigr) \big/ \langle\langle \text{edge relations} \rangle\rangle",
        r"\beta_G(n) = \#\{\, g \in G : |g|_S \le n \,\} "
        r"\asymp \lambda^{n} \quad (\lambda > 1)",
        r"a_n(G) = \#\{\, H \le G : [G : H] = n \,\}, "
        r"\qquad \zeta_G(s) = \sum_{n \ge 1} a_n(G)\, n^{-s}",
        r"\chi_{\mathrm{reg}} = \sum_{\chi \in \mathrm{Irr}(G)} \chi(1)\, \chi, "
        r"\qquad \chi_{\mathrm{reg}}(1) = |G|",
        r"P \in \mathrm{Syl}_p(G) \;\Rightarrow\; "
        r"n_p = [G : N_G(P)] \equiv 1 \pmod p, \quad n_p \mid |G|",
        r"\mathrm{vcd}(G) = \max\{\, n : H^{n}(G'; \mathbb{Z}G') \neq 0 \,\}",
        r"1 \to K \to G \xrightarrow{\rho} \mathrm{GL}_d(\mathbb{C}) "
        r"\to \mathrm{coker}\,\rho \to 1",
        r"\mathrm{Pr}(G) = \frac{k(G)}{|G|} = "
        r"\frac{1}{|G|^{2}}\,\bigl|\{\, (x, y) : xy = yx \,\}\bigr|",
        r"\langle x_1, \dots, x_g \mid w_1, \dots, w_r \rangle, "
        r"\qquad \mathrm{def}(G) = g - r",
        r"G \times_H K = \{\, (g, k) : \pi(g) = \psi(k) \,\} "
        r"\le G \times K",
    ],
    msc=["20D05", "20F65", "20C15", "20E18", "20F55", "20F10", "20B15", "20D20"],
    adjacent=["math.RT", "math.GT"],
)
