"""math.GT - Geometric Topology.

Seed from the build spec, expanded with the geometry/topology research
dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

GT = SubfieldLexicon(
    code="math.GT",
    name="Geometric Topology",
    weight=6.0,
    banks={
        "objects": [
            "knot",
            "link",
            "virtual knot",
            "torus knot",
            "satellite knot",
            "fibered knot",
            "3-manifold",
            "hyperbolic 3-manifold",
            "Seifert fibered space",
            "Sol 3-manifold",
            "contact 3-manifold",
            "4-manifold",
            "exotic 4-manifold",
            "K3 surface",
            "lens space",
            "mapping torus",
            "Heegaard splitting",
            "open book decomposition",
            "Dehn twist",
            "mapping class group",
            "surface bundle",
            "Seifert surface",
            "branched cover",
            "Heegaard Floer homology",
            "knot Floer homology",
            "instanton Floer homology",
            "Khovanov homology",
            "the Alexander polynomial",
            "the Jones polynomial",
            "the HOMFLY polynomial",
            "the quantum $A$-polynomial",
            "the hyperbolic volume",
            "the Casson invariant",
            "the Turaev--Viro invariant",
            "a triangulation",
            "an ideal triangulation",
            "a spine",
            "a Dehn filling",
            "a surgery presentation",
            "a tangle",
            "a cobordism",
            "a curve complex",
        ],
        "props": [
            "hyperbolic",
            "geometrically finite",
            "atoroidal",
            "irreducible",
            "Haken",
            "fibered",
            "Seifert fibered",
            "amphichiral",
            "chiral",
            "alternating",
            "quasi-alternating",
            "slice",
            "ribbon",
            "smoothly slice",
            "topologically slice",
            "exotic",
            "smooth",
            "topological",
            "orientable",
            "non-orientable",
            "aspherical",
            "incompressible",
            "essential",
            "boundary-parallel",
            "tight",
            "overtwisted",
            "pseudo-Anosov",
            "reducible",
            "periodic",
            "prime",
            "satellite",
            "tame",
            "wild",
            "spin",
            "simply connected",
            "closed",
            "bounded",
            "null-homologous",
            "achiral",
        ],
        "spaces": [
            "mapping class group",
            "curve complex",
            "Teichmüller space",
            "character variety",
            "$\\mathrm{SL}_2(\\mathbb{C})$-character variety",
            "configuration space",
            "moduli space of flat connections",
            "Torelli group",
            "outer space",
            "the figure-eight knot complement",
            "the universal cover",
            "Heegaard Floer homology",
            "knot Floer homology",
            "the symplectic Floer complex",
            "the Alexander module",
            "the link concordance group",
            "the homology cobordism group",
            "the Goeritz group",
            "the Johnson kernel",
            "the spin bordism group",
        ],
        "maps": [
            "a Dehn twist",
            "the monodromy",
            "a pseudo-Anosov homeomorphism",
            "the hyperelliptic involution",
            "the Johnson homomorphism",
            "the boundary map",
            "a branched covering",
            "the deck transformation",
            "the connecting homomorphism",
            "the Birman--Hilden correspondence",
            "the Casson--Gordon invariant",
            "the satellite operation",
            "the cabling map",
            "the surgery cobordism",
            "the holonomy representation",
        ],
        "invariants": [
            "the genus",
            "the Seifert genus",
            "the slice genus",
            "the unknotting number",
            "the bridge number",
            "the crossing number",
            "the hyperbolic volume",
            "the signature",
            "the determinant",
            "the Casson invariant",
            "the Rokhlin invariant",
            "the $d$-invariant",
            "the Heegaard genus",
            "the Thurston norm",
            "the Alexander polynomial",
            "the Jones polynomial",
            "the linking number",
            "the Arf invariant",
            "the Euler characteristic",
            "the simplicial volume",
            "the cusp volume",
            "the Turaev--Viro invariant",
            "the maximal Thurston--Bennequin number",
            "the concordance order",
            "the homology cobordism class",
        ],
        "namedResults": [
            "the Poincaré conjecture",
            "the $h$-cobordism theorem",
            "the geometrization theorem",
            "the hyperbolic Dehn surgery theorem",
            "Mostow rigidity",
            "the Smith conjecture",
            "the Nielsen realization problem",
            "the Dehn--Nielsen--Baer theorem",
            "the Birman--Hilden theorem",
            "the Casson--Gordon obstruction",
            "the Lickorish--Wallace theorem",
            "the Gordon--Luecke theorem",
            "the cyclic surgery theorem",
            "the Property R conjecture",
            "Thurston's hyperbolization theorem",
            "the slice--ribbon conjecture",
            "the Andrews--Curtis conjecture",
            "the virtual Haken conjecture",
            "Waldhausen's theorem",
            "the Milnor conjecture",
            "the Freedman classification",
            "Donaldson's diagonalization theorem",
            "the tameness theorem",
            "the surgery exact triangle",
            "the Meyer signature cocycle",
        ],
        "methods": [
            "Dehn surgery",
            "Heegaard Floer theory",
            "Khovanov homology",
            "gauge theory",
            "the theory of normal surfaces",
            "the Thurston norm",
            "train track theory",
            "the curve complex machinery",
            "branched covers",
            "the geometrization program",
            "hyperbolic geometry",
            "the Casson--Gordon method",
            "surgery theory",
            "the mapping class group action",
            "Kirby calculus",
            "the bordered Floer package",
            "the $A$-polynomial",
            "an analysis of the character variety",
            "a genus bound",
            "the surgery exact triangle",
            "Reidemeister torsion",
            "the theory of taut foliations",
            "Morse--Novikov theory",
            "a covering space argument",
        ],
        "objectGloss": [
            "encodes the topology of the complement",
            "arises naturally in low-dimensional topology",
            "detects subtle smooth structures",
            "is central to the study of 3-manifolds",
            "reflects the symmetry of the underlying manifold",
            "controls the surgery behavior of the manifold",
            "distinguishes exotic smooth structures",
            "lies at the heart of knot concordance",
        ],
    },
    # Object-naming letters only. No "g" (clashes with the genus invariant)
    # and no "K" (used for the knot but reserved against curvature collisions).
    symbols=[
        "M",
        "N",
        "X",
        "Y",
        "L",
        "\\Sigma",
        "\\Gamma",
        "\\phi",
        "T",
        "S",
        "W",
        "C",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"g_4(XSYM) \le g_3(XSYM)",
        r"\dim H_{@I@}(XSYM;\mathbb{Q}) = @N@",
        r"\chi(XSYM) = 2 - 2g",
        r"\Delta_{XSYM}(t) = \Delta_{XSYM}(t^{-1})",
        r"\sigma(XSYM) = @R@",
        r"\det(XSYM) = \lvert \Delta_{XSYM}(-1) \rvert",
        r"\mathrm{vol}(XSYM) = @N@\,v_3",
        r"b_1(XSYM) = @N@",
        r"\mathrm{lk}(XSYM,ASYM) = @R@",
        r"u(XSYM) \ge \tfrac{1}{2}\lvert \sigma(XSYM) \rvert",
        r"\widehat{HF}(XSYM) = \mathbb{Z}^{@N@}",
        r"\lvert H_1(XSYM) \rvert = @N@",
        r"d(XSYM) \in \mathbb{Q}",
        r"\mathrm{tb}(XSYM) \le 2g(XSYM) - 1",
        r"\pi_1(XSYM) = \langle a,b \mid r \rangle",
        r"c(XSYM) = @N@",
        r"\mathrm{br}(XSYM) = @C@",
        r"\lambda(XSYM) = @R@",
        r"\|XSYM\|_{\mathrm{Th}} = @N@",
        r"\widehat{HFK}(XSYM,@I@) \ne 0",
        r"V_{XSYM}(q) \in \mathbb{Z}[q^{\pm 1/2}]",
        r"\mathrm{rk}\, \mathrm{Kh}(XSYM) = @N@",
        r"\phi^{@N@} \simeq \mathrm{id}",
        r"\partial XSYM = \emptyset",
        r"H_2(XSYM;\mathbb{Z}) \cong \mathbb{Z}^{@N@}",
        r"\mathrm{Arf}(XSYM) \in \{0,1\}",
        r"S^3_{@N@}(XSYM) = ASYM",
        r"\dim_{\mathbb{C}} XSYM = @C@",
        r"\Gamma \curvearrowright \mathbb{H}^{@C@}",
        r"\mathrm{cork}(XSYM) = @R@",
        r"[XSYM] = @R@ \in \Theta^3_{\mathbb{Z}}",
        r"\mathrm{sw}(XSYM) = @R@",
        r"\widehat{HF}(S^3) = \mathbb{Z}",
        r"g_3(XSYM) = @N@",
    ],
    display_eqns=[
        r"\cdots \to \widehat{HF}(XSYM) \to \widehat{HF}(ASYM) "
        r"\to \widehat{HF}(W) \to \widehat{HF}(XSYM) \to \cdots",
        r"V_{L_+}(q) - V_{L_-}(q) "
        r"= \bigl(q^{1/2} - q^{-1/2}\bigr)\,V_{L_0}(q)",
        r"\Delta_{XSYM}(t) = \det\!\bigl(V - t V^{\mathsf T}\bigr)",
        r"\mathrm{vol}(XSYM) = \sum_{i} \mathrm{vol}(\Delta_i), "
        r"\qquad XSYM = \bigcup_i \Delta_i",
        r"0 \to \mathrm{Tor}\, H_1(XSYM) \to H_1(XSYM) "
        r"\to H_1(XSYM)/\mathrm{Tor} \to 0",
        r"1 \to \pi_1(F) \to \pi_1(XSYM) \to \pi_1(S^1) \to 1",
        r"H^k(XSYM;\mathbb{Z}) \cong H_{n-k}(XSYM,\partial XSYM;\mathbb{Z}), "
        r"\qquad n = \dim XSYM",
        r"\mathrm{Kh}^{i,j}(XSYM) \Rightarrow "
        r"\mathrm{gr}^{j}\, \widehat{HFK}(XSYM)",
        r"1 \to \mathcal{I}(\Sigma) \to \mathrm{Mod}(\Sigma) "
        r"\to \mathrm{Sp}(2g,\mathbb{Z}) \to 1",
        r"\sigma_\omega(XSYM) = \mathrm{sign}\bigl((1-\omega)V "
        r"+ (1-\bar\omega)V^{\mathsf T}\bigr)",
        r"\widehat{HFK}(XSYM) = \bigoplus_{s} "
        r"\widehat{HFK}(XSYM,s), \qquad \chi = \Delta_{XSYM}(t)",
        r"d\bigl(S^3_{p/q}(XSYM)\bigr) "
        r"= d\bigl(S^3_{p/q}(U)\bigr) - 2\,V_{\lfloor \cdots \rfloor}",
        r"\dim H_*(XSYM;\mathbb{F}_2) "
        r"\ge \lvert \chi(\widehat{HF}(XSYM)) \rvert",
        r"\Gamma \backslash \mathbb{H}^3 = XSYM, "
        r"\qquad \mathrm{vol}(XSYM) = -\tfrac{1}{2}\sum_i \mathrm{Im}\,\mathrm{Li}_2(z_i)",
        r"1 \to \mathbb{Z} \to \pi_1(XSYM) \to \pi_1^{\mathrm{orb}}(B) \to 1",
        r"\mathrm{tb}(XSYM) + \lvert \mathrm{rot}(XSYM) \rvert "
        r"\le 2g(XSYM) - 1",
        r"b_2^+(XSYM) + b_2^-(XSYM) = b_2(XSYM), "
        r"\qquad \sigma(XSYM) = b_2^+ - b_2^-",
        r"\|XSYM\|_{\mathrm{Th}} "
        r"= \max\{\, \langle e(\xi), [\Sigma] \rangle : [\Sigma] \in H_2 \,\}",
    ],
    msc=["57K10", "57K31", "57K30", "57M50", "57R57", "57K18", "57M60", "57R55"],
    adjacent=["math.DG", "math.AT"],
)
