"""math.HO - History and Overview.

Deliberately broad and eclectic: a cross-cutting working vocabulary of
classical objects, named results, and elementary methods drawn from across
mathematics, kept at roughly the same scale as the number-theory dossier.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

HO = SubfieldLexicon(
    code="math.HO",
    name="History and Overview",
    weight=1.0,
    banks={
        "objects": [
            "mathematical structure",
            "classical construction",
            "function",
            "series",
            "sequence",
            "identity",
            "equation",
            "inequality",
            "theorem",
            "proof",
            "conjecture",
            "axiom",
            "definition",
            "framework",
            "formalism",
            "notation",
            "diagram",
            "figure",
            "polynomial",
            "integer",
            "rational number",
            "real number",
            "complex number",
            "matrix",
            "vector",
            "set",
            "group",
            "ring",
            "field",
            "graph",
            "curve",
            "surface",
            "triangle",
            "circle",
            "continued fraction",
            "generating function",
            "recurrence relation",
            "geometric figure",
            "number system",
            "counting argument",
            "logical principle",
            "mathematical tradition",
            "historical manuscript",
            "expository account",
        ],
        "props": [
            "classical",
            "elementary",
            "explicit",
            "general",
            "fundamental",
            "well-known",
            "celebrated",
            "elegant",
            "self-contained",
            "rigorous",
            "intuitive",
            "constructive",
            "abstract",
            "concrete",
            "finite",
            "infinite",
            "discrete",
            "continuous",
            "symmetric",
            "regular",
            "natural",
            "canonical",
            "historical",
            "expository",
            "pedagogical",
            "foundational",
            "unifying",
            "accessible",
            "remarkable",
            "surprising",
            "classical and modern",
            "broadly applicable",
            "cross-cutting",
            "deceptively simple",
            "widely cited",
            "frequently rediscovered",
            "long-studied",
            "much-celebrated",
        ],
        "spaces": [
            "the real line",
            "the plane",
            "the complex plane",
            "the integers",
            "the rationals",
            "the natural numbers",
            "Euclidean space",
            "a finite set",
            "a vector space",
            "a function space",
            "a number system",
            "an abstract structure",
            "the unit interval",
            "the unit circle",
            "a coordinate system",
            "an axiomatic system",
            "the continuum",
            "a discrete lattice",
            "a metric space",
            "a configuration of points",
        ],
        "maps": [
            "the identity map",
            "a linear transformation",
            "a bijection",
            "an isomorphism",
            "a projection",
            "the inverse",
            "the derivative",
            "the integral operator",
            "the summation operator",
            "a substitution",
            "a change of variables",
            "the limit operation",
            "a recursive procedure",
            "an iteration",
            "the composition of maps",
        ],
        "invariants": [
            "degree",
            "dimension",
            "cardinality",
            "order",
            "rank",
            "index",
            "size",
            "length",
            "area",
            "volume",
            "magnitude",
            "parity",
            "sign",
            "sum",
            "product",
            "ratio",
            "remainder",
            "coefficient",
            "exponent",
            "the number of solutions",
            "the count of configurations",
            "the value at a point",
            "the limiting value",
            "a constant of proportionality",
            "the leading term",
        ],
        "namedResults": [
            "the fundamental theorem of algebra",
            "the fundamental theorem of calculus",
            "the fundamental theorem of arithmetic",
            "Euler's formula",
            "the prime number theorem",
            "Cauchy's theorem",
            "the binomial theorem",
            "the Pythagorean theorem",
            "the intermediate value theorem",
            "the mean value theorem",
            "the Cauchy--Schwarz inequality",
            "the triangle inequality",
            "the pigeonhole principle",
            "the principle of induction",
            "Fermat's little theorem",
            "the Chinese remainder theorem",
            "Stirling's formula",
            "Taylor's theorem",
            "the law of large numbers",
            "the four color theorem",
            "the irrationality of $\\sqrt{2}$",
            "the infinitude of primes",
            "the Basel problem",
            "the Bolzano--Weierstrass theorem",
            "the arithmetic--geometric mean inequality",
        ],
        "methods": [
            "elementary techniques",
            "a generating-function argument",
            "an explicit construction",
            "mathematical induction",
            "a counting argument",
            "a direct computation",
            "proof by contradiction",
            "a change of variables",
            "a telescoping argument",
            "an inductive argument",
            "a symmetry argument",
            "a combinatorial bijection",
            "a limiting argument",
            "an elementary estimate",
            "a geometric construction",
            "a recursive decomposition",
            "term-by-term comparison",
            "a pigeonhole argument",
            "the method of exhaustion",
            "a careful case analysis",
            "an appeal to first principles",
            "a historical reconstruction",
            "a survey of the literature",
        ],
        "objectGloss": [
            "remains a cornerstone of mathematical thought",
            "has been rediscovered many times across the centuries",
            "unifies several apparently unrelated ideas",
            "is taught in nearly every introductory course",
            "illustrates the power of elementary reasoning",
            "connects distant branches of mathematics",
            "continues to inspire new lines of inquiry",
            "shaped the development of the modern subject",
        ],
    },
    # Generic object-naming letters, kept collision-free with the equation
    # templates below (no "n" or "k", which appear as summation indices).
    symbols=[
        "X",
        "f",
        "a_n",
        "S",
        "F",
        "P",
        "A",
        "g",
        "T",
        "Q",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw.
    inline_eqns=[
        r"\binom{@N@}{@C@} = \binom{@N@}{@N@-@C@}",
        r"\sum_{k=0}^{@N@} \binom{@N@}{k} = 2^{@N@}",
        r"\sum_{k=1}^{@N@} k = \frac{@N@(@N@+1)}{2}",
        r"\sum_{k=1}^{@N@} k^{2} = \frac{@N@(@N@+1)(2@N@+1)}{6}",
        r"\sum_{k=1}^{@N@} (2k-1) = @N@^{2}",
        r"e^{i\pi} + 1 = 0",
        r"a_n = a_{n-1} + a_{n-2}",
        r"\gcd(a,b)\,\operatorname{lcm}(a,b) = ab",
        r"\lvert x + y \rvert \le \lvert x \rvert + \lvert y \rvert",
        r"\left\lvert \langle x, y \rangle \right\rvert \le \lVert x \rVert\,\lVert y \rVert",
        r"\frac{a+b}{2} \ge \sqrt{ab}",
        r"XSYM = ASYM \implies ASYM = XSYM",
        r"(a+b)^{2} = a^{2} + 2ab + b^{2}",
        r"a^{2} - b^{2} = (a-b)(a+b)",
        r"\sum_{k=0}^{@N@} r^{k} = \frac{1 - r^{@N@+1}}{1 - r}",
        r"\binom{@N@}{0} = \binom{@N@}{@N@} = 1",
        r"n! = n\,(n-1)!",
        r"\zeta(2) = \frac{\pi^{2}}{6}",
        r"\cos^{2}\theta + \sin^{2}\theta = 1",
        r"\frac{d}{dx} x^{@N@} = @N@\,x^{@N@-1}",
        r"\int_0^1 x^{@N@}\,dx = \frac{1}{@N@+1}",
        r"\log(ab) = \log a + \log b",
        r"\lim_{n \to \infty} \frac{1}{n} = 0",
        r"(@P@-1)! \equiv -1 \pmod{@P@}",
        r"\sqrt{2} \notin \mathbb{Q}",
        r"\deg(fg) = \deg f + \deg g",
        r"\lvert XSYM \rvert = @N@",
        r"F_{n+1} F_{n-1} - F_n^{2} = (-1)^{n}",
    ],
    display_eqns=[
        r"e^{i\theta} = \cos\theta + i\sin\theta",
        r"\sum_{n=0}^{\infty} x^{n} = \frac{1}{1-x}, \qquad \lvert x \rvert < 1",
        r"(a+b)^{n} = \sum_{k=0}^{n} \binom{n}{k} a^{n-k} b^{k}",
        r"\left( \sum_{k=1}^{n} a_k b_k \right)^{2} "
        r"\le \left( \sum_{k=1}^{n} a_k^{2} \right)\left( \sum_{k=1}^{n} b_k^{2} \right)",
        r"\sum_{n=0}^{\infty} \frac{x^{n}}{n!} = e^{x}",
        r"\sum_{n=1}^{\infty} \frac{1}{n^{2}} = \frac{\pi^{2}}{6}",
        r"\int_0^\infty e^{-x^{2}}\,dx = \frac{\sqrt{\pi}}{2}",
        r"\sum_{k=0}^{n} \binom{n}{k}^{2} = \binom{2n}{n}",
        r"\frac{1}{1-x} \prod_{k\ge 1}(1 + x^{k}) \cdots \quad "
        r"\sum_{n \ge 0} p(n)\, x^{n} = \prod_{k \ge 1} \frac{1}{1 - x^{k}}",
        r"n! \sim \sqrt{2\pi n}\,\left(\frac{n}{e}\right)^{n} \quad (n \to \infty)",
        r"\binom{n}{k} = \binom{n-1}{k-1} + \binom{n-1}{k}",
        r"\frac{a_1 + a_2 + \cdots + a_n}{n} \ge \sqrt[n]{a_1 a_2 \cdots a_n}",
        r"\pi(x) \sim \frac{x}{\log x} \quad (x \to \infty)",
        r"f(x) = \sum_{n=0}^{\infty} \frac{f^{(n)}(a)}{n!}\,(x-a)^{n}",
        r"\int_a^b f'(x)\,dx = f(b) - f(a)",
        r"\sum_{d \mid n} \varphi(d) = n",
    ],
    msc=["01A05", "01A50", "01A60", "01A99", "00A05", "00A30"],
    adjacent=["math.GM"],
)
