"""math.IT - Information Theory.

Seed from the build spec, expanded with the discrete/probability/applied
research dossier into a broad working vocabulary for channels, codes, and the
fundamental limits of communication.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

IT = SubfieldLexicon(
    code="math.IT",
    name="Information Theory",
    weight=3.0,
    banks={
        "objects": [
            "channel",
            "discrete memoryless channel",
            "Gaussian channel",
            "MIMO channel",
            "relay channel",
            "diamond network",
            "broadcast channel",
            "multiple-access channel",
            "wiretap channel",
            "source",
            "memoryless source",
            "codebook",
            "error-correcting code",
            "Reed--Solomon code",
            "Reed--Muller code",
            "LDPC code",
            "polar code",
            "convolutional code",
            "lattice code",
            "stabilizer code",
            "quantum LDPC code",
            "linear code",
            "cyclic code",
            "MDS code",
            "decoder",
            "encoder",
            "typical set",
            "codeword",
            "parity-check matrix",
            "generator matrix",
            "rate-distortion function",
            "test channel",
            "joint type",
            "fading process",
            "side information",
            "feedback scheme",
            "random coding ensemble",
            "spectrum-sharing protocol",
            "covering code",
            "compression scheme",
            "hash function",
        ],
        "props": [
            "memoryless",
            "stationary",
            "ergodic",
            "discrete",
            "continuous",
            "Gaussian",
            "additive",
            "symmetric",
            "degraded",
            "linear",
            "cyclic",
            "systematic",
            "binary",
            "$q$-ary",
            "capacity-achieving",
            "asymptotically optimal",
            "maximum-distance-separable",
            "perfect",
            "self-dual",
            "low-density",
            "sparse",
            "list-decodable",
            "uniquely decodable",
            "prefix-free",
            "lossless",
            "lossy",
            "noisy",
            "feedback",
            "causal",
            "strongly typical",
            "jointly typical",
            "secret",
            "private",
            "achievable",
            "converse",
            "stabilizer",
            "fault-tolerant",
            "concatenated",
            "universal",
        ],
        "spaces": [
            "input alphabet",
            "output alphabet",
            "message set",
            "codebook",
            "Hamming space",
            "probability simplex",
            "type class",
            "typical set",
            "rate region",
            "capacity region",
            "distortion region",
            "channel polytope",
            "signal space",
            "constellation",
            "dual code",
            "syndrome space",
            "feasible rate set",
            "binary symmetric channel",
            "Gaussian ensemble",
            "lattice",
        ],
        "maps": [
            "the encoder",
            "the decoder",
            "the channel transition kernel",
            "the typical-set projection",
            "the syndrome map",
            "the belief-propagation operator",
            "the parity-check map",
            "the maximum-likelihood decoder",
            "the joint typicality decoder",
            "the random binning map",
            "the rate-distortion map",
            "the entropy functional",
            "the mutual information functional",
            "the channel coding map",
            "the successive-cancellation decoder",
        ],
        "invariants": [
            "channel capacity",
            "mutual information",
            "entropy",
            "differential entropy",
            "conditional entropy",
            "relative entropy",
            "transfer entropy",
            "rate",
            "minimum distance",
            "code rate",
            "block length",
            "dimension",
            "covering radius",
            "error exponent",
            "list size",
            "distortion",
            "rate-distortion function",
            "signal-to-noise ratio",
            "spectral efficiency",
            "redundancy",
            "weight enumerator",
            "free distance",
            "secrecy capacity",
            "degrees of freedom",
            "diversity gain",
        ],
        "namedResults": [
            "Shannon's channel coding theorem",
            "the Shannon capacity",
            "the source coding theorem",
            "the Singleton bound",
            "the Hamming bound",
            "the Gilbert--Varshamov bound",
            "the Plotkin bound",
            "the Fano inequality",
            "the data-processing inequality",
            "the Slepian--Wolf theorem",
            "the Wyner--Ziv theorem",
            "the Gel'fand--Pinsker coding scheme",
            "the Csiszár--Körner converse",
            "the entropy power inequality",
            "the rate-distortion theorem",
            "the joint source--channel coding theorem",
            "the sphere-packing bound",
            "the Costa writing-on-dirty-paper result",
            "the Kraft--McMillan inequality",
            "the strong converse",
            "the random coding bound",
            "the cut-set bound",
            "the Han--Kobayashi achievable region",
            "the Berlekamp--Massey algorithm",
            "the Welch bound",
        ],
        "methods": [
            "random coding",
            "joint typicality decoding",
            "the method of types",
            "random binning",
            "superposition coding",
            "successive cancellation",
            "belief propagation",
            "list decoding",
            "the polarization technique",
            "lattice coding",
            "a converse argument",
            "the entropy method",
            "channel polarization",
            "a sphere-packing argument",
            "rate splitting",
            "writing on dirty paper",
            "successive refinement",
            "an error-exponent analysis",
            "syndrome decoding",
            "concatenated coding",
            "dirty-paper coding",
            "a single-letterization argument",
            "interference alignment",
            "the typical-sequence approach",
        ],
        "objectGloss": [
            "quantifies the fundamental limit of reliable communication",
            "achieves the capacity of the underlying channel",
            "arises in the analysis of noisy channels",
            "controls the trade-off between rate and reliability",
            "is central to the theory of error-correcting codes",
            "reflects the entropy of the underlying source",
            "characterizes the achievable rate region",
            "lies at the heart of Shannon theory",
        ],
    },
    # Object-naming letters only. No "H"/"I"/"D" (entropy / mutual information /
    # divergence), "C" (capacity), "p"/"q" (probabilities/alphabet size), or
    # "n"/"k"/"d" (length / dimension / distance).
    symbols=[
        "X",
        "Y",
        "Z",
        "W",
        "\\mathcal{C}",
        "\\mathcal{X}",
        "\\mathcal{Y}",
        "G",
        "\\Phi",
        "S",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"C = \max_{p(x)} I(X;Y)",
        r"H(X) = -\sum_x p(x)\log p(x)",
        r"I(X;Y) = H(X) - H(X\mid Y)",
        r"D(P\,\Vert\,Q) = \sum_x P(x)\log\frac{P(x)}{Q(x)}",
        r"d \le n - k + 1",
        r"R = \frac{k}{n}",
        r"H(X,Y) = H(X) + H(Y\mid X)",
        r"C = \tfrac{1}{2}\log_2\!\left(1 + \mathrm{SNR}\right)",
        r"R < C",
        r"H(X\mid Y) \le H(X)",
        r"I(X;Y) = I(Y;X) \ge 0",
        r"\lvert XSYM\rvert = q^{k}",
        r"d_{\min}(XSYM) = @N@",
        r"2^{nH(X)} \le \lvert A_\varepsilon^{(n)}\rvert \le 2^{n(H(X)+\varepsilon)}",
        r"P_e \ge 1 - \frac{R}{C} - \frac{1}{nR}",
        r"\sum_i 2^{-\ell_i} \le 1",
        r"C_{\mathrm{BSC}} = 1 - H_b(p)",
        r"R(D) = \min_{p(\hat x\mid x)} I(X;\hat X)",
        r"I(X;Y\mid Z) \le I(X;Y)",
        r"\dim XSYM = @N@",
        r"H_b(p) = -p\log p - (1-p)\log(1-p)",
        r"q^{n-d+1} \ge \lvert XSYM\rvert",
        r"\sum_{i=0}^{t} \binom{n}{i}(q-1)^i \le q^{n-k}",
        r"E_r(R) = \max_{0 \le \rho \le 1}\bigl(E_0(\rho) - \rho R\bigr)",
        r"I(X;Y) = D\bigl(p_{XY}\,\Vert\, p_X p_Y\bigr)",
        r"\lvert A_\varepsilon^{(n)}\rvert \doteq 2^{nH(X)}",
        r"C_s = \max_{p(x)}\bigl[I(X;Y) - I(X;Z)\bigr]^{+}",
        r"H(XSYM) \le \log_2 \lvert \mathcal{X}\rvert",
        r"d_H(x, y) = \lvert\{ i : x_i \ne y_i\}\rvert",
        r"k/n \le 1 - H_q(d/n)",
    ],
    display_eqns=[
        r"C = \max_{p(x)} I(X;Y) = \max_{p(x)} \sum_{x,y} p(x)\,W(y\mid x) "
        r"\log \frac{W(y\mid x)}{\sum_{x'} p(x') W(y\mid x')}",
        r"H(X) = -\sum_{x \in \mathcal{X}} p(x) \log_2 p(x), \qquad "
        r"0 \le H(X) \le \log_2 \lvert \mathcal{X}\rvert",
        r"I(X;Y) = \sum_{x,y} p(x,y) \log \frac{p(x,y)}{p(x)\,p(y)} "
        r"= D\bigl(p_{XY}\,\Vert\, p_X \otimes p_Y\bigr)",
        r"d_{\min}(XSYM) \le n - k + 1 \qquad \text{(Singleton bound)}",
        r"P_e^{(n)} \ge 1 - \frac{C}{R} - \frac{1}{nR}, \qquad \text{so } R > C "
        r"\implies P_e^{(n)} \not\to 0",
        r"\lvert XSYM\rvert \le \frac{q^{n}}{\sum_{i=0}^{\lfloor (d-1)/2\rfloor} "
        r"\binom{n}{i}(q-1)^{i}} \qquad \text{(Hamming bound)}",
        r"\lvert XSYM\rvert \ge \frac{q^{n}}{\sum_{i=0}^{d-1} \binom{n}{i}(q-1)^{i}} "
        r"\qquad \text{(Gilbert--Varshamov)}",
        r"C = \tfrac{1}{2}\log_2\!\left(1 + \frac{P}{N}\right) \quad "
        r"\text{bits per channel use}",
        r"R(D) = \min_{\,p(\hat x\mid x):\, \mathbb{E}[d(X,\hat X)] \le D} I(X;\hat X)",
        r"H(X^{n}) = H(X_1) + \sum_{i=2}^{n} H(X_i \mid X_1,\dots,X_{i-1}) "
        r"\quad \text{(chain rule)}",
        r"I(X; Y, Z) = I(X; Z) + I(X; Y \mid Z), \qquad I(X;Y) \ge I(X; g(Y))",
        r"E(R) = \max_{0 \le \rho \le 1} \max_{p(x)} \Bigl[ E_0(\rho, p) - \rho R\Bigr], "
        r"\qquad P_e \le 2^{-n E(R)}",
        r"\Pr\!\bigl( (X^n, Y^n) \in A_\varepsilon^{(n)}\bigr) \to 1, \qquad "
        r"\bigl\lvert A_\varepsilon^{(n)}\bigr\rvert \doteq 2^{n H(X,Y)}",
        r"R_1 \le H(X\mid Y), \quad R_2 \le H(Y\mid X), \quad R_1 + R_2 \ge H(X,Y) "
        r"\quad \text{(Slepian--Wolf)}",
        r"h(X+Y) \ge h\!\left(\tilde X + \tilde Y\right) \quad\Longleftrightarrow\quad "
        r"e^{2h(X+Y)} \ge e^{2h(X)} + e^{2h(Y)}",
        r"C_{\mathrm{cut}} = \min_{S} \, I\bigl(X_S; Y_{S^c} \mid X_{S^c}\bigr), "
        r"\qquad S \subseteq \{1,\dots,m\}",
        r"\max_{i \ne j} \lvert\langle c_i, c_j\rangle\rvert^2 \ge "
        r"\frac{N - m}{m\,(N-1)} \qquad \text{(Welch bound)}",
        r"GH^\top = 0, \qquad \mathbf{s} = H\mathbf{y}^\top, \qquad "
        r"\hat{\mathbf{e}} = \arg\min_{H\mathbf{e}^\top = \mathbf{s}} \operatorname{wt}(\mathbf e)",
    ],
    msc=["94A24", "94B05", "94A17", "94A15", "94B65", "94A40", "94B35", "60F10"],
    adjacent=["cs.IT", "math.PR"],
)
