"""math.KT - K-Theory and Homology.

Seeded from the build spec and expanded with the algebra/number-theory research
dossier into a broad working vocabulary of K-groups, spectra, and assembly maps.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

KT = SubfieldLexicon(
    code="math.KT",
    name="K-Theory and Homology",
    weight=4.0,
    banks={
        "objects": [
            "algebraic $K$-theory spectrum",
            "topological $K$-theory",
            "Hermitian $K$-theory",
            "$K$-group",
            "Milnor $K$-theory",
            "motivic cohomology",
            "motivic spectrum",
            "topological Hochschild homology",
            "topological cyclic homology",
            "cyclic homology",
            "Hochschild homology",
            "negative cyclic homology",
            "periodic cyclic homology",
            "the assembly map",
            "the Baum--Connes map",
            "the cyclotomic trace",
            "the trace map",
            "$C^{*}$-algebra",
            "$E_\\infty$-ring spectrum",
            "structured ring spectrum",
            "perfect complex",
            "dualizable object",
            "stable $\\infty$-category",
            "triangulated category",
            "Waldhausen category",
            "exact category",
            "spectral Mackey functor",
            "Goncharov Lie coalgebra",
            "regulator",
            "the Chern character",
            "the Adams operation",
            "$\\gamma$-filtration",
            "the Brown--Comenetz dual",
            "the $K(n)$-local sphere",
            "syntomic cohomology",
            "prismatic cohomology",
            "motivic filtration",
            "the trace ideal",
            "the Karoubi--Villamayor $K$-theory",
            "the Witt vector ring",
            "the topological cyclic homology spectrum",
        ],
        "props": [
            "connective",
            "coconnective",
            "stable",
            "additive",
            "localizing",
            "truncating",
            "nilinvariant",
            "$\\mathbb{A}^1$-invariant",
            "motivic",
            "syntomic",
            "prismatic",
            "cyclotomic",
            "topological",
            "Hermitian",
            "equivariant",
            "genuine",
            "Borel",
            "perfect",
            "compact",
            "dualizable",
            "rigid",
            "smooth",
            "proper",
            "regular",
            "Noetherian",
            "henselian",
            "complete",
            "$p$-complete",
            "finitely generated",
            "split",
            "exact",
            "homotopy invariant",
            "excisive",
            "finitary",
            "presentable",
            "idempotent-complete",
            "filtered",
            "graded",
            "highly structured",
            "weakly equivalent",
        ],
        "spaces": [
            "algebraic $K$-theory spectrum",
            "$K$-theory space",
            "topological cyclic homology",
            "topological Hochschild homology",
            "cyclic homology",
            "motivic cohomology",
            "stable $\\infty$-category",
            "derived category",
            "category of perfect complexes",
            "Waldhausen category",
            "the sphere spectrum",
            "$E_\\infty$-ring spectrum",
            "the $K$-theory of a ring",
            "the assembly map target",
            "the cyclotomic trace target",
            "syntomic cohomology",
            "prismatic cohomology",
            "the Witt vector ring",
            "the Brauer group",
            "the Picard spectrum",
        ],
        "maps": [
            "the assembly map",
            "the Baum--Connes map",
            "the cyclotomic trace",
            "the Dennis trace",
            "the Chern character",
            "the regulator map",
            "the Adams operation",
            "the localization sequence",
            "the linearization map",
            "the comparison map",
            "the trace map",
            "the boundary map",
            "the transfer map",
            "the norm map",
            "the Frobenius",
        ],
        "invariants": [
            "$K_0$",
            "$K_1$",
            "the higher $K$-groups",
            "Milnor $K$-theory",
            "the Whitehead group",
            "the class group",
            "the Picard group",
            "the Brauer group",
            "the Euler characteristic",
            "the rank",
            "the Chern class",
            "the regulator",
            "the Borel regulator",
            "the $\\gamma$-filtration",
            "the weight filtration",
            "the slice filtration",
            "the motivic weight",
            "the Adams filtration",
            "the chromatic height",
            "the Hochschild homology",
            "the cyclic homology",
            "the topological cyclic homology",
            "the trace form",
            "the Witt group",
            "the signature",
        ],
        "namedResults": [
            "the Quillen--Lichtenbaum conjecture",
            "the Bloch--Kato conjecture",
            "the Farrell--Jones conjecture",
            "the Baum--Connes conjecture",
            "the Atiyah conjecture",
            "the Beilinson--Soule conjecture",
            "the Beilinson conjectures",
            "the Bass finiteness conjecture",
            "the Snaith equivalence",
            "the Dundas--Goodwillie--McCarthy theorem",
            "the Nikolaus--Scholze theorem",
            "the Bott periodicity theorem",
            "the Merkurjev--Suslin theorem",
            "the localization theorem",
            "the resolution theorem",
            "the dévissage theorem",
            "Quillen's theorem",
            "the Gersten conjecture",
            "the Parshin conjecture",
            "the Hochschild--Kostant--Rosenberg theorem",
            "the Goodwillie theorem",
            "the Suslin rigidity theorem",
            "the Thomason--Trobaugh theorem",
            "the Voevodsky theorem",
            "the Borel computation",
        ],
        "methods": [
            "the cyclotomic trace",
            "trace methods",
            "the Dundas--Goodwillie--McCarthy theorem",
            "topological cyclic homology",
            "motivic homotopy theory",
            "the slice spectral sequence",
            "the motivic spectral sequence",
            "the localization sequence",
            "dévissage",
            "the plus construction",
            "the $Q$-construction",
            "the theory of stable $\\infty$-categories",
            "Goodwillie calculus",
            "chromatic homotopy theory",
            "the descent spectral sequence",
            "the theory of noncommutative motives",
            "an analysis of the assembly map",
            "the comparison with cyclic homology",
            "syntomic methods",
            "prismatic cohomology",
            "the theory of trace forms",
            "equivariant methods",
            "the Atiyah--Hirzebruch spectral sequence",
            "the theory of localizing invariants",
        ],
        "objectGloss": [
            "measures the difference between algebra and topology",
            "captures the higher homotopy of the ring",
            "linearizes algebraic $K$-theory",
            "encodes deep arithmetic information",
            "interpolates special values of $L$-functions",
            "is central to modern $K$-theory",
            "controls the obstruction to assembly",
            "reflects the chromatic structure of the spectrum",
        ],
    },
    # Object-naming letters only. No "n, i, k" (clash with degree and indexing)
    # and no "p" (clashes with the prime p in p-completion).
    symbols=[
        "K",
        "X",
        "R",
        "A",
        "M",
        "\\mathbb{S}",
        "\\mathcal{C}",
        "E",
        "F",
        "T",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"K_0(XSYM) \cong \mathbb{Z}^{@C@}",
        r"K_{@I@}(XSYM) = 0",
        r"K_1(R) \cong R^{\times}",
        r"\pi_{@I@} \mathrm{TC}(XSYM) = @N@",
        r"\operatorname{rank} K_{@I@}(\mathcal{O}_F) = r_1 + r_2",
        r"\mathrm{ch}: K_0(XSYM) \otimes \mathbb{Q} \xrightarrow{\sim} ASYM",
        r"K_{2@I@-1}(\mathbb{Z}) \cong \mathbb{Z}/w_{@I@}",
        r"\mathrm{THH}(R) = R \otimes_{R \otimes R} R",
        r"K(XSYM) \simeq K(ASYM)",
        r"\mathrm{TC}(R; p) \xrightarrow{\sim} K(R)^{\wedge}_p",
        r"H_{@I@}(\mathcal{C}) \cong H_{@I@}(ASYM)",
        r"\dim_{\mathbb{Q}} K_{@I@}(F) \otimes \mathbb{Q} = @N@",
        r"\psi^{@C@}\!\left(x\right) = @C@^{n} x \text{ on } K_{2n}",
        r"\mathrm{gr}^{@I@}_\gamma K_0(XSYM) = @N@",
        r"K^{\mathrm{top}}_{@I@}(\mathbb{C}) = \mathbb{Z}",
        r"\mathrm{Wh}(G) = 0",
        r"K_{@I@}(\mathbb{F}_q) = \mathbb{Z}/(q^{@C@} - 1)",
        r"\mathrm{HH}_{@I@}(R/k) \cong \Omega^{@I@}_{R/k}",
        r"\beta: K_{@I@}(XSYM) \xrightarrow{\sim} K_{@I@+2}(XSYM)",
        r"\mathrm{cl}: K_0(XSYM) \to \mathrm{CH}^{*}(XSYM)",
        r"L(\mathcal{C}) \in \mathrm{Sp}",
        r"\mathrm{reg}: K_{@I@}(F) \to \mathbb{R}^{@C@}",
        r"\zeta_F(1 - @C@) \sim \frac{\# K_{2@C@-2}(\mathcal{O}_F)}{\# K_{2@C@-1}(\mathcal{O}_F)}",
        r"K^{\mathrm{Sel}}_{@I@}(R) \cong K_{@I@}(R)^{\wedge}_p",
        r"\pi_0 \mathbb{S} \cong \mathbb{Z}",
        r"H^{@I@}_{\mathrm{mot}}(XSYM, \mathbb{Z}(@C@)) = @N@",
        r"\mathrm{Pic}(XSYM) \hookrightarrow K_0(XSYM)",
        r"\mathrm{rk}\, K_{@I@}(XSYM) = @N@",
        r"\mathrm{Br}(XSYM) \cong H^{2}_{\mathrm{et}}(XSYM, \mathbb{G}_m)_{\mathrm{tors}}",
        r"K_{@I@}(R) \otimes \mathbb{Z}_p \cong \pi_{@I@} \mathrm{TC}(R; p)",
    ],
    display_eqns=[
        r"\cdots \to K_{n}(Z) \to K_{n}(X) \to K_{n}(U) "
        r"\to K_{n-1}(Z) \to \cdots",
        r"\mathrm{TC}(R; p) = \mathrm{eq}\!\left( "
        r"\mathrm{TC}^{-}(R; p) \rightrightarrows \mathrm{TP}(R; p) \right)",
        r"K(R) \xrightarrow{\mathrm{tr}} \mathrm{TC}(R) "
        r"\xrightarrow{\mathrm{can} - \varphi} \mathrm{TC}^{-}(R)",
        r"E_2^{p,q} = H^{p}_{\mathrm{mot}}\bigl(X, \mathbb{Z}(-q/2)\bigr) "
        r"\Rightarrow K_{-p-q}(X)",
        r"\mathrm{ch}_n: K_n(X) \otimes \mathbb{Q} "
        r"\xrightarrow{\sim} \bigoplus_i H^{2i - n}_{\mathrm{mot}}(X, \mathbb{Q}(i))",
        r"K_n(\mathbb{Z}) \otimes \mathbb{Q} = "
        r"\begin{cases} \mathbb{Q} & n = 0 \\ "
        r"\mathbb{Q}^{r} & n \equiv 1 \!\!\pmod 4,\ n > 1 \\ "
        r"0 & \text{otherwise} \end{cases}",
        r"\mathrm{HH}_\bullet(R/k) \cong \bigoplus_{n \ge 0} \Omega^{n}_{R/k}[n] "
        r"\quad (R/k \text{ smooth})",
        r"\mathrm{fib}\bigl(K(R) \to \mathrm{TC}(R)\bigr) "
        r"\xrightarrow{\sim} \mathrm{fib}\bigl(K(R/I) \to \mathrm{TC}(R/I)\bigr)",
        r"H_n^{G}\bigl(\underline{E}G; \mathbb{K}_R\bigr) "
        r"\xrightarrow{\sim} K_n\bigl(R[G]\bigr)",
        r"\zeta_F(1 - n) = \pm \frac{\# K_{2n-2}(\mathcal{O}_F)}{\# K_{2n-1}(\mathcal{O}_F)} "
        r"\quad (n \ge 2 \text{ even})",
        r"0 \to K_n(R) \to K_n(R[t]) \oplus K_n(R[t^{-1}]) "
        r"\to K_n(R[t, t^{-1}]) \to K_{n-1}(R) \to 0",
        r"\Omega^{\infty} K(\mathcal{C}) = "
        r"\bigl(\,|N\mathcal{C}^{\simeq}|\,\bigr)^{+} \times \pi_0 K(\mathcal{C})",
        r"K^{\mathrm{top}}_n(\mathrm{pt}) = "
        r"\begin{cases} \mathbb{Z} & n \text{ even} \\ 0 & n \text{ odd} \end{cases}",
        r"\mathrm{TP}_n(R; p) = \pi_n \bigl(\mathrm{THH}(R)^{tS^1}\bigr), "
        r"\qquad \mathrm{TP}(R) = \mathrm{THH}(R)^{tS^1}",
        r"K_n^{M}(F) = \underbrace{F^{\times} \otimes \cdots \otimes F^{\times}}_{n} "
        r"\big/ \langle a \otimes (1 - a) \rangle",
        r"\mathrm{gr}^{i}_\gamma K_0(X) \otimes \mathbb{Q} \cong "
        r"\mathrm{CH}^{i}(X) \otimes \mathbb{Q}",
        r"L_{K(n)} \mathbb{S} \xrightarrow{\sim} "
        r"\bigl(E_n^{h\mathbb{G}_n}\bigr), \qquad \mathbb{G}_n = \mathbb{S}_n \rtimes \mathrm{Gal}",
        r"\mathrm{fib}\bigl(\mathrm{can} - \varphi\bigr): "
        r"\mathrm{TC}^{-}(R; p) \to \mathrm{TP}(R; p) \xrightarrow{\sim} \mathrm{TC}(R; p)",
    ],
    msc=["19D55", "19E20", "19L47", "19D50", "55N15", "18F25", "14F42", "19F27"],
    adjacent=["math.AG", "math.AT"],
)
