"""math.LO - Logic.

Seed from the build spec, expanded with the discrete/probability/applied
research dossier into a broad working vocabulary for model theory, set theory,
computability, and proof theory.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

LO = SubfieldLexicon(
    code="math.LO",
    name="Logic",
    weight=4.0,
    banks={
        "objects": [
            "first-order theory",
            "model-theoretic structure",
            "complete theory",
            "type",
            "definable set",
            "definable group",
            "Borel equivalence relation",
            "o-minimal structure",
            "Pfaffian function",
            "modal logic",
            "Gödel--Löb logic",
            "pseudovariety",
            "sharply 2-transitive group",
            "ultrafilter",
            "ultraproduct",
            "universal minimal flow",
            "saturated model",
            "prime model",
            "atomic model",
            "elementary substructure",
            "language",
            "signature",
            "formula",
            "sentence",
            "model of arithmetic",
            "forcing notion",
            "generic filter",
            "Boolean algebra",
            "cardinal",
            "ordinal",
            "large cardinal",
            "Turing degree",
            "computable structure",
            "recursive set",
            "stable theory",
            "simple theory",
            "NIP theory",
            "strongly minimal set",
            "imaginary element",
            "automorphism group",
            "Scott sentence",
            "indiscernible sequence",
        ],
        "props": [
            "definable",
            "interpretable",
            "complete",
            "consistent",
            "categorical",
            "$\\omega$-categorical",
            "decidable",
            "undecidable",
            "axiomatizable",
            "finitely axiomatizable",
            "stable",
            "superstable",
            "simple",
            "NIP",
            "o-minimal",
            "strongly minimal",
            "saturated",
            "homogeneous",
            "atomic",
            "prime",
            "elementary",
            "minimal",
            "definably connected",
            "monadic",
            "predicatively definable",
            "Borel",
            "analytic",
            "hyperarithmetic",
            "computable",
            "recursively enumerable",
            "generic",
            "absolute",
            "indiscernible",
            "model-complete",
            "quantifier-eliminable",
            "totally transcendental",
            "modular",
            "$\\aleph_0$-categorical",
            "definably amenable",
        ],
        "spaces": [
            "type space",
            "Stone space",
            "structure",
            "model",
            "universe",
            "monster model",
            "language",
            "signature",
            "Boolean algebra",
            "Lindenbaum algebra",
            "forcing poset",
            "Cantor space",
            "Baire space",
            "constructible universe",
            "cumulative hierarchy",
            "ultrapower",
            "Polish space",
            "definable closure",
            "algebraic closure",
            "imaginaries sort",
        ],
        "maps": [
            "the satisfaction relation",
            "the elementary embedding",
            "the interpretation map",
            "the forcing relation",
            "the Stone duality",
            "an automorphism",
            "the type map",
            "the definable closure operator",
            "the truth definition",
            "the ultrapower embedding",
            "the canonical projection",
            "the Mostowski collapse",
            "the realization map",
            "the quotient by a definable relation",
            "the evaluation map",
        ],
        "invariants": [
            "Morley rank",
            "Lascar rank",
            "$U$-rank",
            "Cantor--Bendixson rank",
            "VC dimension",
            "dp-rank",
            "Morley degree",
            "cardinality",
            "spectrum",
            "stability spectrum",
            "Hanf number",
            "Löwenheim number",
            "consistency strength",
            "Turing degree",
            "Scott rank",
            "number of types",
            "cofinality",
            "burden",
            "weight",
            "imaginary degree",
            "definable dimension",
            "ordinal height",
            "quantifier rank",
            "number of models",
            "saturation cardinal",
        ],
        "namedResults": [
            "the Gödel completeness theorem",
            "the Gödel incompleteness theorems",
            "the compactness theorem",
            "the Löwenheim--Skolem theorem",
            "Morley's categoricity theorem",
            "the Cherlin--Zilber conjecture",
            "the Burnside problem",
            "the omitting types theorem",
            "the Ryll-Nardzewski theorem",
            "the Shelah classification theory",
            "Vaught's conjecture",
            "the Baldwin--Lachlan theorem",
            "the Keisler--Shelah theorem",
            "the Lindström theorem",
            "the Paris--Harrington theorem",
            "the Tarski undefinability theorem",
            "the Cantor--Bendixson theorem",
            "the Engeler--Ryll-Nardzewski--Svenonius theorem",
            "the Feferman--Vaught theorem",
            "the Borel determinacy theorem",
            "the Glimm--Effros dichotomy",
            "the Löwenheim--Skolem--Tarski theorem",
            "the Ehrenfeucht--Mostowski construction",
            "the Robinson joint consistency theorem",
            "the Beth definability theorem",
        ],
        "methods": [
            "the compactness argument",
            "quantifier elimination",
            "back-and-forth",
            "forcing",
            "the method of indiscernibles",
            "an ultraproduct construction",
            "elimination of imaginaries",
            "a Morley rank computation",
            "the omitting types construction",
            "an Ehrenfeucht--Fraïssé game",
            "Fraïssé amalgamation",
            "the stability-theoretic analysis",
            "an absoluteness argument",
            "a priority argument",
            "the constructible hierarchy",
            "an inner model construction",
            "diagonalization",
            "a definability analysis",
            "the type-counting argument",
            "iterated forcing",
            "a Boolean-valued model",
            "an interpretation argument",
            "the Scott analysis",
            "a coding argument",
        ],
        "objectGloss": [
            "captures the definable structure of the underlying model",
            "controls the number of models of the theory",
            "arises in the classification of first-order theories",
            "measures the complexity of definable sets",
            "is central to modern model theory",
            "reflects the consistency strength of the axioms",
            "governs the realization of types over the model",
            "lies at the heart of stability theory",
        ],
    },
    # Object-naming letters only. No "T" (a theory), "M" (a model), "n"/"k"
    # (indices), "p" (a type/parameter), or "\varphi"/"\psi" (formulas).
    symbols=[
        "\\mathcal{M}",
        "\\mathcal{N}",
        "\\mathfrak{C}",
        "A",
        "G",
        "X",
        "S",
        "\\Gamma",
        "\\Sigma",
        "\\mathcal{U}",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\mathcal{M} \models \varphi",
        r"T \vdash \varphi",
        r"\mathrm{RM}(XSYM) = @N@",
        r"\mathrm{U}(p) = @N@",
        r"\mathcal{M} \prec \mathcal{N}",
        r"\lvert S_n(T)\rvert \le \aleph_0",
        r"\mathcal{M} \equiv \mathcal{N}",
        r"T \models \varphi \iff T \vdash \varphi",
        r"\operatorname{dp\text{-}rk}(XSYM) < \infty",
        r"\mathrm{Th}(\mathcal{M}) = \{\varphi : \mathcal{M} \models \varphi\}",
        r"p \in S_n(A)",
        r"\mathcal{M} \models \mathrm{ZFC}",
        r"\kappa \to (\kappa)^{2}_{2}",
        r"V = L",
        r"2^{\aleph_0} = \aleph_@N@",
        r"\mathrm{cf}(\kappa) = \kappa",
        r"\Sigma_@N@ \subsetneq \Pi_@N@",
        r"\mathcal{M} \cong \prod_{i} \mathcal{M}_i / \mathcal{U}",
        r"a \in \operatorname{dcl}(A)",
        r"\mathrm{VC}(\mathcal{F}) = @N@",
        r"\lvert \mathcal{M}\rvert = \aleph_@N@",
        r"p \mathop{\smile\hspace{-0.9em}^{|}}_A b",
        r"\mathcal{M} \models \exists x\, \varphi(x)",
        r"\mathrm{RM}(p) = @N@,\ \mathrm{Mlt}(p) = @C@",
        r"I(\aleph_@N@, T) \le \aleph_0",
        r"\Vdash_{\mathbb{P}} \dot\varphi",
        r"\mathrm{tp}(a/A) = p",
        r"T \cup \{\neg\varphi\} \vdash \bot",
        r"\mathcal{M} \prec_{\Sigma_@N@} \mathcal{N}",
        r"\operatorname{acl}(A) \supseteq \operatorname{dcl}(A)",
    ],
    display_eqns=[
        r"\mathcal{M} \models \varphi[\bar a] \quad\Longleftrightarrow\quad "
        r"\mathcal{M} \models \psi[\bar a] \quad \text{for all } \bar a \in M^{n}",
        r"I(\aleph_\alpha, T) \in \bigl\{ 1,\ \aleph_0,\ \aleph_1,\ \dots,\ "
        r"2^{\aleph_\alpha} \bigr\} \qquad \text{(Vaught's conjecture)}",
        r"\mathrm{RM}(\varphi) = \sup\bigl\{ \mathrm{RM}(\psi) + 1 : \psi \vdash \varphi,\ "
        r"\psi \text{ refines } \varphi \bigr\}",
        r"T \text{ is } \kappa\text{-categorical for some } \kappa > \lvert T\rvert "
        r"\implies T \text{ is } \kappa\text{-categorical for all such } \kappa",
        r"\bigl(\textstyle\prod_{i \in I} \mathcal{M}_i \big/ \mathcal{U}\bigr) \models \varphi "
        r"\quad\Longleftrightarrow\quad \{ i : \mathcal{M}_i \models \varphi\} \in \mathcal{U}",
        r"\mathrm{Con}(\mathrm{ZFC}) \implies \mathrm{ZFC} \nvdash \mathrm{Con}(\mathrm{ZFC}) "
        r"\qquad \text{(second incompleteness theorem)}",
        r"T \text{ is } \aleph_0\text{-categorical} \iff \lvert S_n(T)\rvert < \aleph_0 "
        r"\text{ for all } n \qquad \text{(Ryll-Nardzewski)}",
        r"\mathcal{M} \prec \mathcal{N} \iff \forall \varphi\, \forall \bar a \in M:\ "
        r"\mathcal{M} \models \varphi[\bar a] \Leftrightarrow \mathcal{N} \models \varphi[\bar a]",
        r"p \mathop{\smile\hspace{-0.9em}^{|}}_A B \iff \mathrm{tp}(p/AB) "
        r"\text{ does not fork over } A",
        r"\kappa \to (\alpha)^{n}_{\gamma} \quad : \quad \forall f : [\kappa]^{n} \to \gamma\ "
        r"\exists H \in [\kappa]^{\alpha}\ \bigl(\lvert f[[H]^{n}]\rvert = 1\bigr)",
        r"M[G] \models \varphi \quad\Longleftrightarrow\quad \exists p \in G\ "
        r"\bigl( p \Vdash_{\mathbb{P}} \varphi\bigr)",
        r"\mathrm{SR}(\mathcal{M}) = \sup\bigl\{ \mathrm{rk}(\mathrm{tp}(\bar a)) + 1 : "
        r"\bar a \in M^{<\omega}\bigr\} \qquad \text{(Scott rank)}",
        r"\lvert \{ \varphi : T \vdash \varphi\}\rvert = \aleph_0 \quad \text{and} \quad "
        r"T \vdash \varphi \ \text{or}\ T \vdash \neg\varphi \quad \text{(completeness)}",
        r"\mathrm{cf}(2^{\aleph_0}) > \aleph_0 \quad \text{and} \quad "
        r"\aleph_0 < \mathrm{cf}(\kappa) \le \kappa \le 2^{\aleph_0} \text{ is consistent}",
        r"\Sigma^{0}_{n} \subsetneq \Delta^{0}_{n+1} \subsetneq \Sigma^{0}_{n+1}, "
        r"\qquad \emptyset' <_T \emptyset'' <_T \cdots <_T \emptyset^{(n)}",
        r"\mathrm{Th}(\mathcal{M}) \text{ decidable} \implies \exists \text{ algorithm } "
        r"\mathcal{A}:\ \mathcal{A}(\varphi) = 1 \iff \mathcal{M} \models \varphi",
        r"\mathcal{M} \models \mathrm{PA} + \neg\mathrm{Con}(\mathrm{PA}) \implies "
        r"\mathcal{M} \text{ is nonstandard}",
        r"\bigl\lvert \{ \mathcal{M} : \mathcal{M} \models T,\ \lvert M\rvert "
        r"= \aleph_\alpha \}/{\cong}\bigr\rvert = I(\aleph_\alpha, T)",
    ],
    msc=["03C45", "03E35", "03C10", "03B25", "03D28", "03C64", "03E55", "03F40"],
    adjacent=["math.CT", "math.GR"],
)
