"""math.MG - Metric Geometry.

Seeded from the geometry/topology research dossier and expanded into a broad
working vocabulary covering metric measure spaces, optimal transport, curvature
in the sense of Alexandrov, and coarse geometry.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

MG = SubfieldLexicon(
    code="math.MG",
    name="Metric Geometry",
    weight=4.0,
    banks={
        "objects": [
            "metric space",
            "metric measure space",
            "length space",
            "geodesic space",
            "Alexandrov space",
            "Lorentzian length space",
            "Wasserstein space",
            "$\\mathrm{CAT}(0)$ space",
            "$\\mathrm{CAT}(\\kappa)$ space",
            "$\\mathrm{RCD}$ space",
            "$\\mathrm{CD}(K,N)$ space",
            "geodesic",
            "minimizing geodesic",
            "simple closed geodesic",
            "saddle connection",
            "geodesic ray",
            "Busemann function",
            "optimal transport plan",
            "transport map",
            "displacement interpolation",
            "Wasserstein geodesic",
            "doubling measure",
            "rectifiable set",
            "rectifiable measure",
            "tangent cone",
            "metric tangent space",
            "Gromov-Hausdorff limit",
            "ultralimit",
            "asymptotic cone",
            "quasigeodesic",
            "quasi-isometry",
            "coarse map",
            "isoperimetric region",
            "perimeter",
            "Cheeger energy",
            "modulus of a curve family",
            "aperiodic tiling",
            "Wang tile",
            "Apollonian gasket",
            "self-similar fractal",
            "metric graph",
            "ultrametric space",
            "boundary at infinity",
        ],
        "props": [
            "geodesic",
            "uniquely geodesic",
            "complete",
            "geodesically complete",
            "locally compact",
            "proper",
            "doubling",
            "uniformly convex",
            "non-positively curved",
            "$\\mathrm{CAT}(0)$",
            "lower Ricci bounded",
            "essentially non-branching",
            "non-branching",
            "infinitesimally Hilbertian",
            "rectifiable",
            "purely unrectifiable",
            "Ahlfors regular",
            "$Q$-regular",
            "Loewner",
            "quasiconvex",
            "uniform",
            "John",
            "Gromov-hyperbolic",
            "coarsely connected",
            "amenable",
            "ultrahomogeneous",
            "self-similar",
            "aperiodic",
            "doubling with constant $C$",
            "asymptotically flat",
            "compact",
            "totally bounded",
            "geodesically convex",
            "displacement convex",
            "$K$-convex",
            "negatively curved",
            "globally hyperbolic",
            "purely $1$-unrectifiable",
            "metrically homogeneous",
        ],
        "spaces": [
            "metric space $(X,d)$",
            "metric measure space $(X,d,\\mathfrak{m})$",
            "the Wasserstein space $\\mathcal{P}_2(X)$",
            "an Alexandrov space",
            "a $\\mathrm{CAT}(0)$ space",
            "an $\\mathrm{RCD}(K,N)$ space",
            "the Gromov-Hausdorff limit",
            "the asymptotic cone",
            "the tangent cone at a point",
            "the boundary at infinity $\\partial_\\infty X$",
            "the space of geodesics",
            "the Cheeger-Sobolev space $W^{1,2}(X)$",
            "the cotangent module",
            "the space of probability measures",
            "the Urysohn universal space",
            "the Gromov-Hausdorff space of compact metric spaces",
            "a Carnot group",
            "the Heisenberg group",
        ],
        "maps": [
            "the optimal transport map",
            "the Gromov-Hausdorff approximation",
            "a quasi-isometry",
            "a coarse embedding",
            "the Busemann function",
            "the distance function",
            "the gradient flow of the entropy",
            "the heat flow",
            "the displacement interpolation",
            "the Kuratowski embedding",
            "a $1$-Lipschitz map",
            "the projection onto a convex set",
            "the comparison map",
            "the Cheeger differential",
            "the barycenter map",
        ],
        "invariants": [
            "the Hausdorff dimension",
            "the Assouad dimension",
            "the doubling constant",
            "the Gromov-Hausdorff distance",
            "the Wasserstein distance",
            "the Lipschitz constant",
            "the diameter",
            "the perimeter",
            "the isoperimetric profile",
            "the Cheeger constant",
            "the modulus of a curve family",
            "the conformal dimension",
            "the asymptotic dimension",
            "the curvature bound",
            "the Ricci lower bound",
            "the dimension bound $N$",
            "the entropy",
            "the spectral gap",
            "the first eigenvalue",
            "the volume growth exponent",
            "the filling radius",
            "the systole",
            "the displacement convexity exponent",
            "the rough isometry constant",
            "the packing number",
        ],
        "namedResults": [
            "the Bonnet--Myers theorem",
            "the Bishop--Gromov inequality",
            "Gromov's compactness theorem",
            "Toponogov's theorem",
            "the Cheeger--Gromoll splitting theorem",
            "the Lott--Sturm--Villani theory",
            "the Ambrosio--Gigli--Savaré theorem",
            "the Cheeger--Colding theory",
            "the Lévy--Gromov isoperimetric inequality",
            "the Brunn--Minkowski inequality",
            "the Prékopa--Leindler inequality",
            "the Talagrand transport inequality",
            "the Otto--Villani theorem",
            "the Bakry--Émery criterion",
            "the Sturm--Gromov--Wasserstein distance",
            "the coarse Menger theorem",
            "the Burago--Gromov--Perelman theorem",
            "the Margulis lemma",
            "the Milnor--Schwarz lemma",
            "the Assouad embedding theorem",
            "the Bonk--Kleiner theorem",
            "the Cheeger differentiation theorem",
            "the Lévy concentration inequality",
            "the Heintze--Karcher inequality",
            "the Ohta--Sturm equivalence",
        ],
        "methods": [
            "optimal transport methods",
            "Gromov-Hausdorff convergence",
            "the theory of gradient flows",
            "comparison geometry",
            "the entropy method",
            "displacement convexity arguments",
            "the localization technique",
            "the needle decomposition",
            "$\\Gamma$-convergence",
            "the calculus on metric measure spaces",
            "the Cheeger differentiation theory",
            "ultralimit techniques",
            "a coarse geometric argument",
            "the curvature-dimension condition",
            "a measure contraction argument",
            "the heat semigroup approach",
            "blow-up analysis",
            "tangent cone analysis",
            "the modulus method",
            "a doubling argument",
            "the Bakry-Émery calculus",
            "metric differentiation",
            "the splitting theorem technique",
            "an isoperimetric comparison",
        ],
        "objectGloss": [
            "encodes curvature without a smooth structure",
            "arises as a limit of Riemannian manifolds",
            "governs the behavior of optimal transport",
            "synthesizes lower Ricci curvature bounds",
            "controls the isoperimetric profile of the space",
            "captures the large-scale geometry of the space",
            "reflects the convexity of the entropy functional",
            "is central to modern metric geometry",
        ],
    },
    # Object-naming letters and forms only. No "d" (the metric / distance),
    # no "K" or "N" (curvature-dimension parameters in CD(K,N)).
    symbols=[
        "X",
        "Y",
        "Z",
        "\\mu",
        "\\nu",
        "\\mathfrak{m}",
        "\\gamma",
        "\\Omega",
        "\\Gamma",
        "\\Sigma",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"d(x,z) \le d(x,y) + d(y,z)",
        r"\dim_H XSYM = @N@",
        r"\mathrm{Ric} \ge K",
        r"\mathrm{CD}(K,N)",
        r"\mathrm{RCD}(K,N)",
        r"W_2(ASYM,\nu) \le \varepsilon",
        r"\mathrm{diam}(XSYM) \le \pi\sqrt{(N-1)/K}",
        r"\mathfrak{m}(B_{2r}) \le @C@\,\mathfrak{m}(B_r)",
        r"d_{GH}(X_n, XSYM) \to 0",
        r"\mathrm{Lip}(f) \le @N@",
        r"|\nabla f|(x) \le \mathrm{Lip}\,f(x)",
        r"\mathcal{H}^{s}(ASYM) > 0",
        r"\kappa \le \mathrm{Sec} \le \kappa'",
        r"\mathrm{Ent}(\mu) = \int \rho \log\rho \, d\mathfrak{m}",
        r"d(\gamma_s,\gamma_t) = |t-s|\, d(\gamma_0,\gamma_1)",
        r"W_2(\mu_t,\mu_s) \le |t-s|\, W_2(\mu_0,\mu_1)",
        r"\dim_A XSYM \le @N@",
        r"\mathfrak{m}(B_r(x)) \asymp r^{@N@}",
        r"\langle x, y \rangle_p \ge 0",
        r"h(XSYM) = \inf_A \frac{P(A)}{\mathfrak{m}(A)}",
        r"\mathrm{Mod}_p(\Gamma) = @R@",
        r"\lambda_1(XSYM) \ge \frac{NK}{N-1}",
        r"d_{GH}(XSYM,\ast) \le \mathrm{diam}(XSYM)",
        r"\mathrm{sys}(XSYM) \le @C@\,\mathrm{vol}(XSYM)^{1/n}",
        r"|f(x)-f(y)| \le L\, d(x,y)",
        r"\mathfrak{m} = \mathcal{H}^{N}",
        r"\theta_x = \lim_{r\to 0}\frac{\mathfrak{m}(B_r(x))}{\omega_N r^{N}}",
        r"\beta_K(t) = \frac{\sin(t\sqrt{K})}{\sqrt{K}}",
        r"\mathrm{asdim}(XSYM) \le @N@",
        r"\mathrm{Per}(E) = \mathcal{H}^{N-1}(\partial^{*}E)",
        r"x \sim y \iff d(x,y) < \infty",
        r"\mathrm{Ch}(f) = \tfrac{1}{2}\int |\nabla f|^{2}\, d\mathfrak{m}",
        r"\mu_t = (\mathrm{e}_t)_{\#}\,\Pi",
        r"\mathrm{Ric}_N \ge K\, g",
        r"d_W(\delta_x,\delta_y) = d(x,y)",
        r"\angle(\gamma_1,\gamma_2) \ge \tilde\angle(\gamma_1,\gamma_2)",
    ],
    display_eqns=[
        r"W_2(\mu,\nu)^{2} = \inf_{\pi \in \Pi(\mu,\nu)} "
        r"\int_{X \times X} d(x,y)^{2}\, d\pi(x,y)",
        r"\mathrm{Ent}(\mu_t) \le (1-t)\,\mathrm{Ent}(\mu_0) "
        r"+ t\,\mathrm{Ent}(\mu_1) - \frac{K}{2}\,t(1-t)\, W_2(\mu_0,\mu_1)^{2}",
        r"d_{GH}(X,Y) = \tfrac{1}{2}\inf_{R}\,\sup_{(x,y),(x',y') \in R} "
        r"\bigl| d_X(x,x') - d_Y(y,y') \bigr|",
        r"\frac{\mathfrak{m}(B_R(x))}{\mathfrak{m}(B_r(x))} "
        r"\le \frac{\int_0^R \beta_{K,N}(t)\, dt}{\int_0^r \beta_{K,N}(t)\, dt}, "
        r"\qquad 0 < r \le R",
        r"\mathfrak{m}\bigl(\{f > t\}\bigr)^{\frac{N-1}{N}} "
        r"\le \frac{1}{c_{N,K}}\, P\bigl(\{f > t\}\bigr)",
        r"\rho(t,x)^{1/N} \ge \tau_{K,N}^{(1-t)}(\theta)\,\rho_0(x_0)^{1/N} "
        r"+ \tau_{K,N}^{(t)}(\theta)\,\rho_1(x_1)^{1/N}",
        r"\tilde\angle_K(y\,x\,z) \le \angle(y\,x\,z) "
        r"\quad\text{for all geodesic triangles in } XSYM",
        r"d(x,z)^{2} \le (1-t)\,d(x,y_0)^{2} + t\,d(x,y_1)^{2} "
        r"- t(1-t)\,d(y_0,y_1)^{2}",
        r"\lambda_1(XSYM) \ge \frac{N K}{N-1}, \qquad \mathrm{Ric} \ge K > 0",
        r"\int_X |\nabla u|^{2}\, d\mathfrak{m} "
        r"\ge \lambda_1 \int_X u^{2}\, d\mathfrak{m}, "
        r"\quad \int_X u\, d\mathfrak{m} = 0",
        r"W_2(\mu_s,\mu_t) = \int_s^t \|\dot\mu_r\|\, dr, "
        r"\qquad \partial_t \mu_t + \mathrm{div}(v_t\,\mu_t) = 0",
        r"\mathcal{H}^{s}(XSYM) = \lim_{\delta \to 0}\,\inf "
        r"\sum_i (\mathrm{diam}\, U_i)^{s}, \quad \mathrm{diam}\, U_i \le \delta",
        r"\mathrm{Per}(E;\Omega) = \sup\Bigl\{ \int_E \mathrm{div}\,\varphi\, d\mathfrak{m} "
        r": \varphi \in C_c^{1}, \ |\varphi| \le 1 \Bigr\}",
        r"\frac{d}{dt}\,\mathrm{Ent}(\mu_t) "
        r"= -\int_X |\nabla \log\rho_t|^{2}\, d\mu_t \le 0",
        r"\mathfrak{m}(B_r(x)) \le \omega_N \int_0^r "
        r"\left(\frac{\sinh(t\sqrt{-K})}{\sqrt{-K}}\right)^{N-1} dt",
        r"d_X(x,x') = \lim_{\omega}\, d_n(x_n, x'_n) "
        r"\quad\text{in the ultralimit } (X_\omega, d_\omega)",
        r"\frac{1}{C}\,d_Y(f(x),f(y)) - C \le d_X(x,y) "
        r"\le C\, d_Y(f(x),f(y)) + C",
        r"\mathrm{Mod}_p(\Gamma) = \inf_{\rho} \int_X \rho^{p}\, d\mathfrak{m}, "
        r"\quad \int_\gamma \rho\, ds \ge 1 \ \ \forall\, \gamma \in \Gamma",
    ],
    msc=["51F30", "53C23", "30L05", "49Q22", "53C21", "28A75", "51K10", "20F65"],
    adjacent=["math.DG", "math.FA"],
)
