"""math.MP - Mathematical Physics.

Seed from the build spec, expanded with the arXiv analysis dossier (MP/SP/CA
cluster) into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

MP = SubfieldLexicon(
    code="math.MP",
    name="Mathematical Physics",
    weight=5.0,
    banks={
        "objects": [
            "Schrödinger operator",
            "Hamiltonian",
            "Dirac operator",
            "transfer matrix",
            "partition function",
            "Gibbs measure",
            "Gaussian free field",
            "spin system",
            "Ising model",
            "vertex model",
            "six-vertex model",
            "quantum spin chain",
            "Heisenberg model",
            "lattice gauge theory",
            "soliton",
            "soliton gas",
            "integrable system",
            "Lax pair",
            "$R$-matrix",
            "Yang--Baxter equation",
            "Bethe ansatz",
            "Painlevé transcendent",
            "Riemann--Hilbert problem",
            "tau function",
            "correlation function",
            "two-point function",
            "scattering amplitude",
            "$S$-matrix",
            "random matrix ensemble",
            "determinantal point process",
            "Toda lattice",
            "KdV hierarchy",
            "conformal field theory",
            "vertex operator algebra",
            "Coulomb gas",
            "interacting particle system",
            "quantum field",
            "Schramm--Loewner evolution",
            "Bose gas",
            "many-body Hamiltonian",
            "Hubbard model",
            "transfer operator",
            "ground state",
        ],
        "props": [
            "integrable",
            "exactly solvable",
            "quantum",
            "classical",
            "relativistic",
            "non-relativistic",
            "Hamiltonian",
            "self-adjoint",
            "translation-invariant",
            "gauge-invariant",
            "conformally invariant",
            "scale-invariant",
            "critical",
            "subcritical",
            "supercritical",
            "massless",
            "massive",
            "interacting",
            "free",
            "Gaussian",
            "ergodic",
            "disordered",
            "random",
            "ground-state",
            "thermal",
            "equilibrium",
            "out-of-equilibrium",
            "dispersive",
            "dissipative",
            "conservative",
            "Hermitian",
            "unitary",
            "completely integrable",
            "quasi-periodic",
            "localized",
            "extended",
            "renormalizable",
            "semiclassical",
            "many-body",
        ],
        "spaces": [
            "Hilbert space",
            "Fock space",
            "phase space",
            "configuration space",
            "the lattice $\\mathbb{Z}^d$",
            "the torus $\\mathbb{T}^d$",
            "the state space",
            "the spectrum",
            "the moduli space",
            "the symplectic manifold",
            "the spin configuration space",
            "the space of fields",
            "the path space",
            "the transfer matrix algebra",
            "the Bethe ansatz spectrum",
            "the Verma module",
            "the representation space",
            "the loop space",
            "the energy shell",
            "the Liouville space",
        ],
        "maps": [
            "the time evolution",
            "the transfer matrix",
            "the partition function",
            "the Lax operator",
            "the monodromy matrix",
            "the scattering map",
            "the $R$-matrix",
            "the Hamiltonian flow",
            "the renormalization group flow",
            "the Bethe ansatz map",
            "the dressing transformation",
            "the inverse scattering transform",
            "the spectral curve map",
            "the Poisson bracket",
            "the correlation kernel",
        ],
        "invariants": [
            "energy",
            "ground-state energy",
            "partition function",
            "free energy",
            "entropy",
            "spectral gap",
            "correlation length",
            "critical exponent",
            "central charge",
            "scaling dimension",
            "transmission coefficient",
            "conserved charge",
            "action variable",
            "Casimir invariant",
            "topological charge",
            "winding number",
            "magnetization",
            "susceptibility",
            "spectral form factor",
            "level spacing distribution",
            "Lyapunov exponent",
            "density of states",
            "scattering phase",
            "monodromy",
            "$R$-matrix",
        ],
        "namedResults": [
            "the Yang--Baxter equation",
            "the Bethe ansatz",
            "the Lieb--Robinson bound",
            "the Mermin--Wagner theorem",
            "the Lee--Yang theorem",
            "the Onsager solution",
            "the KPZ scaling",
            "the Tracy--Widom distribution",
            "the Wigner--Dyson statistics",
            "the Kadanoff--Baym equations",
            "the Mori--Zwanzig formalism",
            "Onsager's variational principle",
            "the Bogoliubov inequality",
            "the Lieb--Thirring inequality",
            "the Hohenberg--Mermin--Wagner theorem",
            "the fluctuation--dissipation theorem",
            "the Kubo formula",
            "the Coleman--Mandula theorem",
            "the Reeh--Schlieder theorem",
            "the Osterwalder--Schrader axioms",
            "the Knizhnik--Zamolodchikov equation",
            "the BPZ equations",
            "the Hellmann--Feynman theorem",
            "the Hofstadter butterfly",
            "the Lenard--Magri recursion",
        ],
        "methods": [
            "the Bethe ansatz",
            "the inverse scattering transform",
            "the Riemann--Hilbert approach",
            "the transfer matrix method",
            "the renormalization group",
            "the replica method",
            "the cluster expansion",
            "the steepest descent method",
            "semiclassical analysis",
            "the quantum inverse scattering method",
            "the Mori--Zwanzig formalism",
            "constructive field theory",
            "the algebraic Bethe ansatz",
            "the nonlinear steepest descent method",
            "free probability",
            "the Coulomb gas formalism",
            "conformal bootstrap",
            "the Hamiltonian formalism",
            "an analysis of the spectral curve",
            "the supersymmetric method",
            "the loop equations",
            "the recursion relations",
            "perturbation theory",
            "the saddle-point method",
        ],
        "objectGloss": [
            "encodes the dynamics of the physical system",
            "governs the thermodynamics of the model",
            "arises naturally in integrable systems",
            "controls the critical behavior near the transition",
            "is central to exactly solvable models",
            "reflects the underlying conformal symmetry",
            "captures the long-range correlations of the field",
            "lies at the heart of the quantum integrability",
        ],
    },
    # Object-naming letters only. No "n", "k", "j" (running indices, momenta)
    # and no "t" (the time variable in the Hamiltonian flow).
    symbols=[
        "H",
        "L",
        "Z",
        "T",
        "R",
        "S",
        "\\Phi",
        "\\Psi",
        "M",
        "\\mathcal{H}",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"XSYM \Psi = E \Psi",
        r"Z = \operatorname{tr}\, e^{-\beta XSYM}",
        r"\langle \sigma_0 \sigma_r\rangle \sim e^{-r/\xi}",
        r"R_{12} R_{13} R_{23} = R_{23} R_{13} R_{12}",
        r"[XSYM, ASYM] = 0",
        r"\frac{d}{dt} XSYM = \{XSYM, H\}",
        r"F = -\beta^{-1} \log Z",
        r"S = -k_B \sum_i p_i \log p_i",
        r"c = 1 - \frac{6}{m(m+1)}",
        r"\langle \phi(x)\phi(y)\rangle \sim |x-y|^{-2\Delta}",
        r"\xi \sim |T - T_c|^{-\nu}",
        r"E_n = -\frac{1}{2}\sum_{a} \lambda_a^2",
        r"\Delta E \ge \gamma > 0",
        r"\frac{dL}{dt} = [M, L]",
        r"\Lambda(z) = \prod_a \frac{z - \lambda_a}{z + \lambda_a}",
        r"\det(I - K)\big|_{[s,\infty)}",
        r"\lVert [\tau_t(A), B]\rVert \le C e^{v t - d(X,Y)}",
        r"\sum_a \frac{2}{\lambda_a} = \sum_{b \neq a} \frac{2}{\lambda_a - \lambda_b}",
        r"\rho(\lambda) = \frac{1}{2\pi}\sqrt{4 - \lambda^2}",
        r"p(\theta) = \frac{1}{\pi}\frac{\sigma}{\sigma^2 + \theta^2}",
        r"\langle H\rangle = \operatorname{tr}(\rho\, XSYM)",
        r"P(s) \sim s^{\beta} e^{-c s^2}",
        r"\tau_n = \det\bigl(I + K_n\bigr)",
        r"Z_N = \int e^{-N \operatorname{tr} V(M)}\, dM",
        r"q'' = 6 q^2 + z \quad (\text{Painlevé II})",
        r"H = -\sum_i \partial_i^2 + \sum_{i<j} V(x_i - x_j)",
        r"\langle \mathcal{O}\rangle = \frac{1}{Z}\int \mathcal{O}\, e^{-S}\, \mathcal{D}\phi",
        r"m \sim (T_c - T)^{\beta}",
        r"\chi \sim |T - T_c|^{-\gamma}",
        r"S(\theta) = \frac{\sinh\theta - i\sin\mu}{\sinh\theta + i\sin\mu}",
        r"E_0 / N \to e_\infty",
        r"\Phi_t = e^{-it XSYM/\hbar}\Phi_0",
    ],
    display_eqns=[
        r"Z = \sum_{\{\sigma\}} \exp\!\left(\beta \sum_{\langle i,j\rangle} "
        r"J_{ij}\,\sigma_i \sigma_j + h \sum_i \sigma_i\right)",
        r"R_{12}(u-v)\, R_{13}(u)\, R_{23}(v) = R_{23}(v)\, R_{13}(u)\, R_{12}(u-v)",
        r"\frac{d}{dt} XSYM = [M, XSYM], \qquad XSYM = XSYM(t),\ M = M(t)",
        r"E_\beta = e^{-\beta N e_\infty}\bigl(1 + o(1)\bigr), \qquad "
        r"e_\infty = \lim_{N\to\infty} \frac{E_0(N)}{N}",
        r"\prod_{j=1}^{N} \frac{\lambda_a - \lambda_j + i}{\lambda_a - \lambda_j - i} "
        r"= \left(\frac{\lambda_a + i/2}{\lambda_a - i/2}\right)^{L}, \quad a = 1,\dots,N",
        r"S = -\operatorname{tr}(\rho \log \rho), \qquad "
        r"\rho = \frac{e^{-\beta XSYM}}{\operatorname{tr}\, e^{-\beta XSYM}}",
        r"\bigl\lVert [\,\tau_t(A),\, B\,]\bigr\rVert \le C\,\lVert A\rVert\,\lVert B\rVert\,"
        r"e^{\,v|t| - \mu\, d(X,Y)}",
        r"F_{\mathrm{GUE}}(s) = \exp\!\left(-\int_s^{\infty} (x-s)\, q(x)^2\, dx\right), "
        r"\quad q'' = s q + 2 q^3",
        r"P(\lambda)\,d\lambda = \frac{1}{Z_N} \prod_{i<j} |\lambda_i - \lambda_j|^{\beta} "
        r"\prod_i e^{-\frac{N}{2}\lambda_i^2}\, d\lambda",
        r"\langle \phi(x_1)\cdots\phi(x_n)\rangle "
        r"= \frac{1}{Z}\int \phi(x_1)\cdots\phi(x_n)\, e^{-S[\phi]}\,\mathcal{D}\phi",
        r"\partial_t u + 6\, u\, \partial_x u + \partial_x^3 u = 0, \qquad "
        r"L = -\partial_x^2 + u, \ \partial_t L = [L, P]",
        r"\frac{d^2 q}{dz^2} = 6\, q^2 + z, \qquad "
        r"q(z) \sim \mathrm{Ai}(z) \ \text{as}\ z \to +\infty",
        r"\Phi_+(\lambda) = \Phi_-(\lambda)\, G(\lambda), \quad \lambda \in \Gamma; "
        r"\qquad \Phi(\lambda) \to I \ \text{as}\ \lambda \to \infty",
        r"i\hbar\, \partial_t \Psi = XSYM\, \Psi, \qquad "
        r"XSYM = -\frac{\hbar^2}{2m}\,\Delta + V(x)",
        r"\langle T(z)\, T(w)\rangle = \frac{c/2}{(z-w)^4} "
        r"+ \frac{2\,\langle T(w)\rangle}{(z-w)^2} + \frac{\partial_w \langle T(w)\rangle}{z-w}",
        r"\frac{1}{Z}\sum_{\{\sigma\}} \sigma_0\, e^{-\beta H} "
        r"= \left(1 - \frac{1}{\sinh^4 2\beta J}\right)^{1/8} \quad (T < T_c)",
        r"\partial_{z_i}\Psi = \frac{1}{\kappa}\sum_{j \neq i} "
        r"\frac{\Omega_{ij}}{z_i - z_j}\,\Psi \qquad (\text{Knizhnik--Zamolodchikov})",
        r"\rho(\lambda) = \frac{1}{2\pi}\sqrt{4 - \lambda^2}\,\mathbf{1}_{[-2,2]}(\lambda), "
        r"\qquad \int \rho(\lambda)\, d\lambda = 1",
    ],
    msc=["82B23", "81Q10", "82B20", "37K10", "81T40", "60B20", "82B10", "35Q15"],
    adjacent=["math-ph", "math.SP"],
)
