"""math.NA - Numerical Analysis.

Seed from the build spec, expanded with the discrete/probability/applied
research dossier into a broad working vocabulary for discretizations, solvers,
and error analysis.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

NA = SubfieldLexicon(
    code="math.NA",
    name="Numerical Analysis",
    weight=4.0,
    banks={
        "objects": [
            "finite element method",
            "finite difference scheme",
            "discontinuous Galerkin method",
            "virtual element method",
            "spectral method",
            "collocation scheme",
            "Runge--Kutta method",
            "multistep method",
            "convolution quadrature",
            "quadrature rule",
            "Quasi-Monte Carlo rule",
            "preconditioner",
            "multigrid solver",
            "Krylov subspace method",
            "domain decomposition method",
            "polytopal mesh",
            "triangulation",
            "basis function",
            "shape function",
            "stiffness matrix",
            "mass matrix",
            "interpolant",
            "spline",
            "wavelet basis",
            "tensor decomposition",
            "hierarchical Tucker tensor",
            "low-rank approximation",
            "model order reduction",
            "reduced basis",
            "discrete operator",
            "discrete solution",
            "numerical flux",
            "time integrator",
            "a posteriori error estimator",
            "adaptive mesh",
            "iterative solver",
            "Schur complement",
            "discretization error",
            "boundary value problem",
            "stiff system",
            "physics-informed network",
            "randomized sketch",
        ],
        "props": [
            "consistent",
            "stable",
            "convergent",
            "conservative",
            "high-order",
            "low-order",
            "positivity-preserving",
            "invariant-domain-preserving",
            "monotone",
            "well-posed",
            "well-conditioned",
            "ill-conditioned",
            "coercive",
            "inf-sup stable",
            "conforming",
            "nonconforming",
            "structure-preserving",
            "symplectic",
            "energy-stable",
            "A-stable",
            "L-stable",
            "explicit",
            "implicit",
            "semi-implicit",
            "adaptive",
            "quasi-uniform",
            "shape-regular",
            "spectrally accurate",
            "pseudo-spectral",
            "low-rank",
            "sparse",
            "matrix-free",
            "scalable",
            "robust",
            "uniform",
            "asymptotically exact",
            "superconvergent",
            "dissipative",
            "multiscale",
        ],
        "spaces": [
            "finite element space",
            "Sobolev space",
            "Hilbert space",
            "Banach space",
            "trial space",
            "test space",
            "Krylov subspace",
            "polynomial space",
            "discrete function space",
            "broken Sobolev space",
            "tensor product space",
            "reduced basis space",
            "interpolation space",
            "Lebesgue space",
            "dual space",
            "Bochner space",
            "discrete energy space",
            "approximation space",
            "snapshot space",
            "coarse space",
        ],
        "maps": [
            "the interpolation operator",
            "the projection operator",
            "the prolongation operator",
            "the restriction operator",
            "the discrete Laplacian",
            "the Ritz projection",
            "the quasi-interpolant",
            "the trace operator",
            "the preconditioner $M^{-1}$",
            "the discrete gradient",
            "the lifting operator",
            "the smoothing operator",
            "the transfer operator",
            "the discrete divergence",
            "the solution operator",
        ],
        "invariants": [
            "discretization error",
            "consistency error",
            "approximation order",
            "convergence rate",
            "condition number",
            "mesh size",
            "polynomial degree",
            "time step",
            "CFL number",
            "spectral radius",
            "stability constant",
            "inf-sup constant",
            "coercivity constant",
            "interpolation constant",
            "energy norm",
            "residual",
            "effectivity index",
            "rank",
            "numerical rank",
            "operator norm",
            "truncation error",
            "round-off error",
            "global error",
            "local truncation error",
            "stability region",
        ],
        "namedResults": [
            "Cea's lemma",
            "the Céa quasi-optimality estimate",
            "the Lax equivalence theorem",
            "the Bramble--Hilbert lemma",
            "the Aubin--Nitsche duality argument",
            "the inf-sup condition",
            "the Babuška--Brezzi theorem",
            "the Strang lemmas",
            "the Courant--Friedrichs--Lewy condition",
            "the Runge--Kutta convolution quadrature",
            "the Eckart--Young theorem",
            "the Kantorovich theorem",
            "the Dahlquist barrier",
            "the Crouzeix conjecture",
            "the Gershgorin disc theorem",
            "the Perron--Frobenius theorem",
            "the Galerkin orthogonality principle",
            "the trace inequality",
            "the inverse inequality",
            "the discrete Poincaré inequality",
            "the Banach fixed-point theorem",
            "the Lebesgue constant bound",
            "the Faber--Krahn inequality",
            "the spectral equivalence estimate",
            "the a posteriori reliability bound",
        ],
        "methods": [
            "the finite element method",
            "the discontinuous Galerkin method",
            "a Galerkin projection",
            "operator preconditioning",
            "multigrid acceleration",
            "domain decomposition",
            "the conjugate gradient method",
            "GMRES",
            "adaptive mesh refinement",
            "a posteriori error estimation",
            "Richardson extrapolation",
            "convolution quadrature",
            "the method of lines",
            "implicit-explicit time stepping",
            "low-rank truncation",
            "randomized linear algebra",
            "a duality argument",
            "the walk-on-spheres method",
            "tensor compression",
            "model order reduction",
            "spectral collocation",
            "a stability and consistency analysis",
            "the discrete energy method",
            "preconditioned Krylov iteration",
        ],
        "objectGloss": [
            "approximates the continuous solution to high order",
            "controls the discretization error on adaptive meshes",
            "arises when discretizing partial differential equations",
            "governs the convergence of the iterative solver",
            "is central to modern scientific computing",
            "reflects the stability of the time integrator",
            "balances accuracy against computational cost",
            "lies at the heart of error analysis",
        ],
    },
    # Object-naming letters only. No "h" (mesh size), "p" (polynomial degree),
    # "C" (generic constant), or "n"/"k" (indices/iteration counts).
    symbols=[
        "A",
        "M",
        "P",
        "Q",
        "T",
        "\\mathcal{A}",
        "\\Pi",
        "\\Phi",
        "S",
        "R",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\lVert u - u_h\rVert \le C\,h^{@C@}",
        r"\lVert u - u_h\rVert_{L^2} \le C\,h^{p+1}",
        r"\kappa(A) = \lVert A\rVert\,\lVert A^{-1}\rVert",
        r"\lVert x_k - x^\star\rVert \le C\rho^{k}",
        r"\rho = \frac{\sqrt{\kappa}-1}{\sqrt{\kappa}+1}",
        r"\lVert u - I_h u\rVert_{H^1} \le C\,h^{p}\,\lvert u\rvert_{H^{p+1}}",
        r"\Delta t \le C\,h",
        r"a(u_h, v_h) = (f, v_h) \quad \forall v_h \in V_h",
        r"\lVert e_h\rVert \le \frac{C}{1-\theta}\,\eta(u_h)",
        r"\kappa(M^{-1}A) = O(1)",
        r"\lVert u - u_h\rVert_a = \min_{v_h \in V_h} \lVert u - v_h\rVert_a",
        r"\sigma_{@C@}(A) = \min_{\operatorname{rank}B \le @R@} \lVert A - B\rVert",
        r"\inf_{u_h} \sup_{v_h} \frac{a(u_h, v_h)}{\lVert u_h\rVert\,\lVert v_h\rVert} \ge \beta",
        r"y_{n+1} = y_n + \Delta t\,\Phi(y_n)",
        r"\lvert R(z)\rvert \le 1 \quad \text{for } \Re(z) \le 0",
        r"\lambda_i(A) \in [c, C]",
        r"\lVert A - \tilde A\rVert \le \varepsilon\,\lVert A\rVert",
        r"\operatorname{rank}(XSYM) = @R@",
        r"e_n = O\!\left(\Delta t^{@C@}\right)",
        r"\lVert \nabla(u - u_h)\rVert_{L^2} \le C\,h^{p}",
        r"\eta^2 = \sum_{K} \eta_K^2",
        r"\lVert M^{-1/2} A M^{-1/2}\rVert \le \Lambda",
        r"\dim V_h = N_h \asymp h^{-d}",
        r"\theta = \frac{\lambda_{\max} - \lambda_{\min}}{\lambda_{\max} + \lambda_{\min}}",
        r"(A x, x) \ge \alpha\,\lVert x\rVert^2",
        r"\lVert (I - M^{-1}A)\rVert \le \delta < 1",
        r"\operatorname{cond}(XSYM) \le @N@",
        r"u_h = \sum_{j=1}^{N} c_j\,\varphi_j",
        r"\lVert u - u_h\rVert_{L^\infty} \le C\,h^{p+1}\lvert\log h\rvert",
        r"\lambda_{\max}(A)/\lambda_{\min}(A) = \kappa",
    ],
    display_eqns=[
        r"\lVert u - u_h\rVert_{H^1(\Omega)} \le C\,h^{p}\,\lvert u\rvert_{H^{p+1}(\Omega)}, "
        r"\qquad h = \max_{K \in \mathcal{T}_h} \operatorname{diam}(K)",
        r"\lVert x_k - x^\star\rVert_A \le 2\,\rho^{k}\,\lVert x_0 - x^\star\rVert_A, \qquad "
        r"\rho = \frac{\sqrt{\kappa}-1}{\sqrt{\kappa}+1}, \quad \kappa = \kappa(A)",
        r"\lVert u - u_h\rVert_{L^2(\Omega)} \le C\,h^{p+1}\,\lvert u\rvert_{H^{p+1}(\Omega)} "
        r"\qquad \text{(Aubin--Nitsche)}",
        r"a(u_h, v_h) = \ell(v_h) \quad \forall v_h \in V_h, \qquad "
        r"a(u - u_h, v_h) = 0 \quad \forall v_h \in V_h",
        r"y_{n+1} = y_n + \Delta t \sum_{i=1}^{s} b_i\, k_i, \qquad k_i "
        r"= F\Bigl(y_n + \Delta t \textstyle\sum_{j} a_{ij} k_j\Bigr)",
        r"\inf_{u_h \in V_h} \sup_{v_h \in W_h} \frac{b(u_h, v_h)}"
        r"{\lVert u_h\rVert_{V}\,\lVert v_h\rVert_{W}} \ge \beta > 0",
        r"A = \sum_{i=1}^{r} \sigma_i\, u_i v_i^\top, \qquad "
        r"\lVert A - A_k\rVert_2 = \sigma_{k+1} \quad \text{(Eckart--Young)}",
        r"\eta^2(u_h) = \sum_{K \in \mathcal{T}_h} h_K^2 \lVert f + \Delta u_h\rVert_{L^2(K)}^2 "
        r"+ \sum_{e} h_e \lVert \llbracket \nabla u_h\rrbracket\rVert_{L^2(e)}^2",
        r"\lVert u - u_h\rVert_a \le \frac{C_a}{c_a} \inf_{v_h \in V_h} \lVert u - v_h\rVert_a "
        r"\qquad \text{(Céa's lemma)}",
        r"\frac{c_1}{c_0}\,\eta_h^2 - \mathrm{osc}^2 \le \lVert u - u_h\rVert_a^2 "
        r"\le C_1\,\eta_h^2 + \mathrm{osc}^2",
        r"\frac{u_h^{n+1} - u_h^n}{\Delta t} + A_h u_h^{n+1} = f_h^{n+1}, \qquad "
        r"\Delta t \le C\,\frac{h^2}{\lVert A_h\rVert}",
        r"\int_a^b f(x)\, dx \approx \sum_{i=1}^{N} w_i\, f(x_i), \qquad "
        r"\Bigl\lvert E_N \Bigr\rvert \le C\,N^{-2p}\,\lVert f^{(2p)}\rVert_\infty",
        r"\kappa(M^{-1}A) = \frac{\lambda_{\max}(M^{-1}A)}{\lambda_{\min}(M^{-1}A)} \le \Lambda, "
        r"\qquad \Lambda \text{ independent of } h",
        r"\lVert e^{n}\rVert \le \lVert e^{0}\rVert + \Delta t \sum_{j=0}^{n-1} "
        r"\lVert \tau^{j}\rVert, \qquad \tau^{j} = O\!\left(\Delta t^{p}\right)",
        r"u(x,t) \approx \sum_{k=-N}^{N} \hat u_k(t)\, e^{i k x}, \qquad "
        r"\lVert u - u_N\rVert \le C\,N^{-m}\,\lVert u\rVert_{H^m}",
        r"\lVert A - \tilde A\rVert_F \le \Bigl(1 + \varepsilon\Bigr) "
        r"\Bigl(\sum_{j > k} \sigma_j^2\Bigr)^{1/2} \quad \text{(randomized SVD)}",
        r"\bigl\lvert R(z)\bigr\rvert \le 1 \quad \text{for all } \Re(z) \le 0 "
        r"\qquad \text{(A-stability)}",
        r"\lVert u_h\rVert_{L^\infty(K)} \le C\,h_K^{-d/2}\,\lVert u_h\rVert_{L^2(K)} "
        r"\qquad \text{(inverse inequality)}",
    ],
    msc=["65N30", "65M60", "65F08", "65L06", "65N15", "65D32", "65F10", "65M12"],
    adjacent=["math.OC", "cs.NA"],
)
