"""math.NT - Number Theory.

Seed from the build spec, expanded with the algebra/number-theory research
dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

NT = SubfieldLexicon(
    code="math.NT",
    name="Number Theory",
    weight=10.0,
    banks={
        "objects": [
            "prime",
            "elliptic curve",
            "abelian variety",
            "modular form",
            "cusp form",
            "newform",
            "Hecke eigenform",
            "Maass form",
            "Hilbert modular form",
            "Siegel modular form",
            "Eisenstein series",
            "theta series",
            "automorphic form",
            "automorphic representation",
            "cuspidal representation",
            "Galois representation",
            "Artin representation",
            "$\\ell$-adic representation",
            "Dirichlet character",
            "Hecke character",
            "$L$-function",
            "$p$-adic $L$-function",
            "Dedekind zeta function",
            "number field",
            "function field",
            "local field",
            "global field",
            "Shimura variety",
            "modular curve",
            "Drinfeld module",
            "Tate module",
            "Selmer group",
            "ideal class",
            "fractional ideal",
            "lattice",
            "quadratic form",
            "binary form",
            "Diophantine equation",
            "motive",
            "$p$-divisible group",
            "formal group",
            "Rankin--Selberg convolution",
            "Eisenstein ideal",
            "Hecke module",
        ],
        "props": [
            "$p$-adic",
            "$\\ell$-adic",
            "cyclotomic",
            "anticyclotomic",
            "totally real",
            "totally imaginary",
            "supersingular",
            "ordinary",
            "$p$-ordinary",
            "ramified",
            "unramified",
            "tamely ramified",
            "wildly ramified",
            "split",
            "inert",
            "primitive",
            "imprimitive",
            "cuspidal",
            "automorphic",
            "modular",
            "crystalline",
            "semistable",
            "potentially crystalline",
            "de Rham",
            "Hodge--Tate",
            "absolutely irreducible",
            "residually irreducible",
            "essentially self-dual",
            "self-dual",
            "polarized",
            "CM",
            "non-CM",
            "tempered",
            "generic",
            "Steinberg",
            "squarefree",
            "monogenic",
            "integral",
            "geometrically irreducible",
            "everywhere unramified",
        ],
        "spaces": [
            "number field",
            "local field",
            "ring of integers",
            "adele ring",
            "idele class group",
            "Hecke algebra",
            "Selmer group",
            "Bloch--Kato Selmer group",
            "absolute Galois group",
            "Weil group",
            "Weil--Deligne group",
            "class group",
            "Tate--Shafarevich group",
            "modular curve",
            "Shimura variety",
            "eigencurve",
            "eigenvariety",
            "Iwasawa algebra",
            "universal deformation ring",
            "Hida family",
            "Coleman family",
            "$p$-adic period ring",
        ],
        "maps": [
            "Frobenius",
            "the Hecke operator $T_p$",
            "the Atkin--Lehner involution",
            "the $U_p$-operator",
            "complex conjugation",
            "the cyclotomic character",
            "the Artin reciprocity map",
            "base change",
            "automorphic induction",
            "the Jacquet--Langlands transfer",
            "the theta lift",
            "the $p$-adic regulator",
            "the Bloch--Kato exponential",
            "the Eichler--Shimura isomorphism",
            "specialization",
            "the reciprocity map",
        ],
        "invariants": [
            "rank",
            "analytic rank",
            "algebraic rank",
            "conductor",
            "discriminant",
            "different",
            "regulator",
            "class number",
            "root number",
            "central value",
            "special value",
            "order of vanishing",
            "Iwasawa $\\lambda$-invariant",
            "Iwasawa $\\mu$-invariant",
            "Tamagawa number",
            "level",
            "weight",
            "nebentypus",
            "Hecke eigenvalue",
            "Satake parameter",
            "Frobenius trace",
            "canonical height",
            "Faltings height",
            "Mahler measure",
            "$p$-adic valuation",
            "residue",
            "functional equation",
        ],
        "namedResults": [
            "the Riemann Hypothesis",
            "the Birch--Swinnerton-Dyer conjecture",
            "the Sato--Tate conjecture",
            "the Bombieri--Vinogradov theorem",
            "the Keating--Snaith conjecture",
            "the Rudnick--Sarnak density conjecture",
            "Langlands functoriality",
            "the Iwasawa Main Conjecture",
            "the Bloch--Kato conjecture",
            "the $abc$ conjecture",
            "Serre's modularity conjecture",
            "the Mordell--Weil theorem",
            "Mazur's torsion theorem",
            "Faltings's theorem",
            "the modularity theorem",
            "the Gross--Zagier formula",
            "Waldspurger's formula",
            "Kolyvagin's theorem",
            "the Ramanujan--Petersson conjecture",
            "the Artin conjecture",
            "the Stark conjecture",
            "the Leopoldt conjecture",
            "the Chebotarev density theorem",
            "the Brauer--Siegel theorem",
            "the Cohen--Lenstra heuristics",
            "the Gross--Koblitz formula",
        ],
        "methods": [
            "the circle method",
            "sieve methods",
            "the large sieve",
            "the trace formula",
            "the relative trace formula",
            "modularity lifting",
            "Taylor--Wiles patching",
            "the theory of Euler systems",
            "Iwasawa theory",
            "$p$-adic Hodge theory",
            "the theta correspondence",
            "the doubling method",
            "Rankin--Selberg unfolding",
            "the converse theorem",
            "automorphic descent",
            "$p$-adic interpolation",
            "the method of Heegner points",
            "equidistribution techniques",
            "subconvexity bounds",
            "the amplification method",
            "the Petersson formula",
            "an analysis of the associated $L$-function",
            "a descent argument",
            "the theory of newforms",
        ],
        "objectGloss": [
            "encodes deep arithmetic information",
            "governs the distribution of primes",
            "arises naturally in the Langlands program",
            "controls the arithmetic of the associated motive",
            "is central to modern number theory",
            "reflects the symmetry of the underlying Galois representation",
            "interpolates special values of $L$-functions",
            "lies at the heart of the theory of automorphic forms",
        ],
    },
    # Object-naming letters only. No "p" (clashes with the prime index p in
    # T_p, a_p, \pmod p) and no "N" (clashes with counting functions N(x)).
    symbols=[
        "E",
        "K",
        "F",
        "f",
        "\\rho",
        "\\pi",
        "A",
        "V",
        "X",
        "Y",
    ],
    eqn_motif=lambda roles: (
        r"L(s,\chi) = \sum_{n \ge 1} \frac{\chi(n)}{n^{s}} "
        r"= \prod_{p} \bigl(1 - \chi(p) p^{-s}\bigr)^{-1}"
    ),
    msc=["11F11", "11G05", "11M06", "11R23", "11F33", "11G40", "11F80", "11R34"],
    adjacent=["math.AG", "math.RT"],
)
