"""math.OA - Operator Algebras.

Seed from the build spec, expanded with the arXiv analysis dossier (OA/FA
cluster) into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

OA = SubfieldLexicon(
    code="math.OA",
    name="Operator Algebras",
    weight=5.0,
    banks={
        "objects": [
            "C*-algebra",
            "von Neumann algebra",
            "factor",
            "hyperfinite factor",
            "type $\\mathrm{II}_1$ factor",
            "type $\\mathrm{III}$ factor",
            "AF algebra",
            "UHF algebra",
            "Cuntz algebra",
            "Cuntz--Krieger algebra",
            "graph algebra",
            "crossed product",
            "groupoid C*-algebra",
            "transformation groupoid",
            "ample groupoid",
            "Toeplitz algebra",
            "Calkin algebra",
            "subfactor",
            "inclusion of factors",
            "conditional expectation",
            "state",
            "tracial state",
            "weight",
            "projection",
            "partial isometry",
            "unitary",
            "Fredholm operator",
            "Toeplitz operator",
            "Hilbert module",
            "completely positive map",
            "Kasparov module",
            "spectral triple",
            "tensor category",
            "fusion category",
            "planar algebra",
            "standard invariant",
            "Cartan subalgebra",
            "masa",
            "amenable trace",
            "quantum group",
            "compact quantum group",
            "free product algebra",
            "Fourier--Stieltjes algebra",
            "group von Neumann algebra",
        ],
        "props": [
            "simple",
            "nuclear",
            "exact",
            "amenable",
            "hyperfinite",
            "approximately finite-dimensional",
            "purely infinite",
            "stably finite",
            "quasidiagonal",
            "separable",
            "unital",
            "$\\sigma$-unital",
            "monotracial",
            "self-adjoint",
            "completely positive",
            "completely bounded",
            "normal",
            "faithful",
            "type $\\mathrm{I}$",
            "type $\\mathrm{II}_1$",
            "type $\\mathrm{III}_\\lambda$",
            "$\\mathcal{Z}$-stable",
            "classifiable",
            "approximately inner",
            "outer",
            "ergodic",
            "free",
            "minimal",
            "essentially free",
            "rigid",
            "property (T)",
            "Haagerup",
            "weakly amenable",
            "residually finite-dimensional",
            "AT",
            "real rank zero",
            "stable rank one",
            "tracially approximately finite",
        ],
        "spaces": [
            "Hilbert space",
            "Hilbert C*-module",
            "the GNS Hilbert space",
            "the standard form",
            "the predual",
            "the center",
            "the bidual",
            "the enveloping von Neumann algebra",
            "the multiplier algebra",
            "the Calkin algebra",
            "the unitary group",
            "the projection lattice",
            "the trace simplex",
            "the state space",
            "the spectrum",
            "the primitive ideal space",
            "the K-theory group",
            "the KK-group",
            "the tracial cone",
            "the fundamental group",
        ],
        "maps": [
            "the conditional expectation",
            "the trace",
            "the modular automorphism group",
            "the GNS representation",
            "the comultiplication",
            "the index map",
            "the Kasparov product",
            "the Baum--Connes assembly map",
            "the boundary map",
            "the dual coaction",
            "the canonical shift",
            "the Connes cocycle",
            "the completely positive map",
            "the conditional expectation $E$",
            "the basic construction",
        ],
        "invariants": [
            "K-theory",
            "$K_0$ group",
            "$K_1$ group",
            "the Elliott invariant",
            "the trace",
            "the Murray--von Neumann dimension",
            "the coupling constant",
            "the Jones index",
            "the global index",
            "the Connes invariant",
            "the $T$-invariant",
            "the $S$-invariant",
            "the flow of weights",
            "the fundamental group",
            "the nuclear dimension",
            "the decomposition rank",
            "the Cuntz semigroup",
            "the standard invariant",
            "the principal graph",
            "the radial limit",
            "the cb-norm",
            "the spectral flow",
            "the $\\mathrm{Ext}$ group",
            "the topological entropy",
            "the free entropy",
        ],
        "namedResults": [
            "the Connes classification of injective factors",
            "the Tomita--Takesaki theorem",
            "the GNS construction",
            "the Gelfand--Naimark theorem",
            "the Stinespring dilation theorem",
            "the Choi--Effros theorem",
            "the Jones index theorem",
            "the Elliott classification program",
            "the Kirchberg--Phillips theorem",
            "the Baum--Connes conjecture",
            "the Connes embedding conjecture",
            "the Powers--Størmer inequality",
            "the Pimsner--Voiculescu sequence",
            "Voiculescu's theorem",
            "the Cuntz--Pimsner construction",
            "the Murray--von Neumann classification",
            "Popa's deformation--rigidity theory",
            "the Kadison--Singer theorem",
            "the Toeplitz--Pimsner extension",
            "the Connes--Haagerup theorem",
            "the Effros--Handelman--Shen theorem",
            "the Russo--Dye theorem",
            "Arveson's extension theorem",
            "the Glimm dichotomy",
            "the Brown--Douglas--Fillmore theorem",
        ],
        "methods": [
            "the GNS construction",
            "Tomita--Takesaki theory",
            "modular theory",
            "the basic construction",
            "deformation--rigidity theory",
            "free probability",
            "the intertwining-by-bimodules technique",
            "KK-theory",
            "the Cuntz--Pimsner construction",
            "completely positive approximations",
            "the classification program",
            "the index theory of subfactors",
            "the planar algebra calculus",
            "an analysis of the modular flow",
            "groupoid techniques",
            "the crossed-product construction",
            "spectral triple methods",
            "the Elliott intertwining argument",
            "approximate finite-dimensionality",
            "the Connes cocycle perturbation",
            "the tensor category formalism",
            "the trace-kernel extension",
            "ultrapower techniques",
            "central sequence arguments",
        ],
        "objectGloss": [
            "encodes the symmetries of a quantum system",
            "classifies the underlying operator algebra",
            "arises naturally in noncommutative geometry",
            "controls the structure of the associated factor",
            "is central to the classification program",
            "reflects the dynamics of the modular flow",
            "captures the K-theoretic invariants of the algebra",
            "lies at the heart of subfactor theory",
        ],
    },
    # Object-naming letters only. No "n", "k", "i" (running indices, the
    # imaginary unit) and no "t" (the modular-flow time parameter \sigma_t).
    symbols=[
        "A",
        "B",
        "M",
        "N",
        "P",
        "Q",
        "\\varphi",
        "\\tau",
        "\\mathcal{A}",
        "\\Phi",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"XSYM \subset ASYM",
        r"[ASYM : XSYM] = @N@",
        r"XSYM' \cap ASYM = \mathbb{C}\,1",
        r"\tau(uu^{*}) = \tau(u^{*}u)",
        r"K_0(XSYM) \cong \mathbb{Z}^{@N@}",
        r"K_1(XSYM) = 0",
        r"\sigma_t^{\varphi}(x) = \Delta^{it} x \,\Delta^{-it}",
        r"XSYM \otimes \mathcal{K} \cong ASYM \otimes \mathcal{K}",
        r"\dim_{XSYM} L^2(ASYM) = [ASYM : XSYM]",
        r"\lVert \Phi \rVert_{\mathrm{cb}} = 1",
        r"XSYM \cong M_{@N@}(\mathbb{C})",
        r"\tau(p) \in \{0\} \cup [1,\infty]",
        r"[ASYM : XSYM] = 4\cos^2(\pi/@N@)",
        r"XSYM \rtimes_\alpha G",
        r"\mathrm{Ind}(T) = \dim\ker T - \dim\operatorname{coker} T",
        r"\Phi(a^{*}a) \ge \Phi(a)^{*}\Phi(a)",
        r"E(x) \ge 0 \ \text{for}\ x \ge 0",
        r"XSYM = \overline{\bigcup_n XSYM_n}",
        r"\mathrm{dim}_{\mathrm{nuc}}(XSYM) < \infty",
        r"W^{*}(\Gamma) \cong XSYM",
        r"\Delta = J \Delta J^{-1} \ \text{(modular)}",
        r"\tau \otimes \mathrm{Tr}\ \text{on}\ XSYM \otimes M_n",
        r"u^{*}u = 1,\ uu^{*} = p",
        r"[\,e\,] = [\,f\,] \ \text{in}\ K_0(XSYM)",
        r"XSYM \cong \mathcal{O}_{@N@}",
        r"\Gamma\colon XSYM \to XSYM \otimes XSYM",
        r"\mathrm{cb}(\Phi) \le \lVert \Phi \rVert",
        r"s_j s_k^{*} = \delta_{jk}\, p_j",
        r"\tau(1) = 1,\ \tau \ge 0",
        r"XSYM \cong XSYM \otimes \mathcal{Z}",
        r"\pi_\varphi(x)\,\xi_\varphi = x\,\xi_\varphi",
        r"\mathrm{Out}(XSYM) \neq \{1\}",
    ],
    display_eqns=[
        r"\varphi(xy) = \varphi\bigl(\sigma_{-i}^{\varphi}(y)\,x\bigr), \qquad "
        r"\sigma_t^{\varphi}(x) = \Delta^{it} x\, \Delta^{-it}",
        r"\Phi(x) = \sum_{i} V_i^{*}\, x\, V_i, \qquad \sum_i V_i^{*} V_i = 1",
        r"[ASYM : XSYM] \in \left\{\, 4\cos^2\!\tfrac{\pi}{n} : n \ge 3 \,\right\} "
        r"\cup\, [4, \infty]",
        r"K_0(XSYM \rtimes_\alpha \mathbb{Z}) \to K_0(XSYM) "
        r"\xrightarrow{\,1 - \alpha_{*}\,} K_0(XSYM) \to K_1(XSYM\rtimes_\alpha\mathbb{Z})",
        r"\mathrm{Ind}(T) = \dim \ker T - \dim \ker T^{*}, \qquad T \in XSYM",
        r"s_j^{*} s_k = \delta_{jk}\,1, \qquad \sum_{j=1}^{n} s_j s_j^{*} = 1 "
        r"\quad \text{in}\ \mathcal{O}_n",
        r"0 \to \mathcal{K} \to \mathcal{T} \to C(S^1) \to 0",
        r"\mathrm{Ext}(C(X), \mathcal{K}) \cong K^1(X)",
        r"(\mathrm{Ell})\quad \bigl(K_0(XSYM),\, K_0(XSYM)_+,\, [1],\, T(XSYM),\, "
        r"r_{XSYM}\bigr)",
        r"\dim_{XSYM} H = \tau\!\left(\,\textstyle\sum_i e_{ii}\,\right) "
        r"= [ASYM : XSYM]",
        r"\tau\bigl(P(X_1,\dots,X_n)\bigr) = \int P \, d\mu \qquad "
        r"\text{(free convolution semicircle law)}",
        r"\langle \mathrm{Tr}\, e^{-tD^2}\rangle \sim \sum_{k \ge 0} a_k\, t^{(k-d)/2}, "
        r"\quad (\mathcal{A}, H, D)",
        r"\mu_{XSYM}(\lambda) = \tau\bigl(\mathbf{1}_{[\lambda,\infty)}(|x|)\bigr), "
        r"\qquad x \in XSYM",
        r"E\colon ASYM \to XSYM, \qquad E(x^{*}x) \ge 0,\ E(axb) = a\,E(x)\,b "
        r"\ (a,b \in XSYM)",
        r"\Delta(u) = u \otimes u, \qquad (\varepsilon \otimes \mathrm{id})\Gamma "
        r"= \mathrm{id} = (\mathrm{id}\otimes\varepsilon)\Gamma",
        r"\mu(g) = \mathrm{ind}\,\langle [\partial], [g]\rangle \colon "
        r"K_*^{G}(\underline{E}G) \xrightarrow{\sim} K_*(C_r^{*}(G))",
        r"e\, M\, e \cong XSYM, \qquad [ASYM : XSYM] = \tau(e)^{-1}, "
        r"\quad e = e_{XSYM}",
        r"d_{\mathrm{HS}}(\Phi, \mathrm{Hom}) \to 0 "
        r"\quad\Longrightarrow\quad \exists\,\text{f.d. approximation of}\ XSYM",
    ],
    msc=["46L05", "46L10", "46L35", "46L55", "46L80", "47L40", "22D25", "81R15"],
    adjacent=["math.FA", "math.KT"],
)
