"""math.OC - Optimization and Control.

Seed from the build spec, expanded with the discrete/probability/applied
research dossier into a broad working vocabulary for convex programs, optimal
control, and large-scale optimization.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

OC = SubfieldLexicon(
    code="math.OC",
    name="Optimization and Control",
    weight=4.0,
    banks={
        "objects": [
            "convex program",
            "semidefinite program",
            "linear program",
            "conic program",
            "second-order cone program",
            "quadratic program",
            "optimal control problem",
            "mean-field control problem",
            "mean-field game",
            "stochastic control problem",
            "variational inequality",
            "monotone inclusion",
            "saddle-point problem",
            "min-max problem",
            "Schrödinger bridge",
            "optimal transport problem",
            "Hamilton--Jacobi--Bellman equation",
            "value function",
            "policy",
            "feedback law",
            "control system",
            "dynamical system",
            "objective functional",
            "Lagrangian",
            "dual problem",
            "proximal operator",
            "subgradient",
            "gradient flow",
            "descent method",
            "splitting scheme",
            "ADMM iteration",
            "trajectory",
            "admissible control",
            "adjoint state",
            "costate",
            "feasible region",
            "active set",
            "KKT system",
            "regret bound",
            "bandit problem",
            "Markov decision process",
            "distributionally robust program",
            "moment relaxation",
        ],
        "props": [
            "convex",
            "strongly convex",
            "nonconvex",
            "nonsmooth",
            "smooth",
            "Lipschitz",
            "coercive",
            "proper",
            "lower semicontinuous",
            "monotone",
            "strongly monotone",
            "cocoercive",
            "submodular",
            "separable",
            "bilinear",
            "saddle",
            "self-concordant",
            "well-posed",
            "controllable",
            "observable",
            "stabilizable",
            "detectable",
            "feasible",
            "bounded",
            "tight",
            "exact",
            "primal-dual",
            "stochastic",
            "online",
            "distributionally robust",
            "risk-averse",
            "constrained",
            "unconstrained",
            "regularized",
            "accelerated",
            "first-order",
            "high-dimensional",
            "decentralized",
            "affine",
        ],
        "spaces": [
            "feasible set",
            "constraint set",
            "decision space",
            "control space",
            "state space",
            "Hilbert space",
            "dual cone",
            "positive semidefinite cone",
            "simplex",
            "polytope",
            "spectrahedron",
            "epigraph",
            "subdifferential",
            "normal cone",
            "tangent cone",
            "probability simplex",
            "Wasserstein ball",
            "ambiguity set",
            "reachable set",
            "value space",
        ],
        "maps": [
            "the gradient $\\nabla f$",
            "the proximal operator",
            "the projection operator",
            "the resolvent",
            "the subgradient map",
            "the Fenchel conjugate",
            "the value function",
            "the feedback map",
            "the adjoint operator",
            "the Hamiltonian",
            "the Bellman operator",
            "the policy map",
            "the dual map",
            "the splitting operator",
            "the proximal-gradient step",
        ],
        "invariants": [
            "duality gap",
            "optimal value",
            "condition number",
            "convergence rate",
            "regret",
            "iteration complexity",
            "Lipschitz constant",
            "strong convexity parameter",
            "smoothness constant",
            "step size",
            "spectral norm",
            "objective gap",
            "primal residual",
            "dual residual",
            "stationarity measure",
            "constraint violation",
            "value of the game",
            "Lagrange multiplier",
            "horizon",
            "discount factor",
            "stability margin",
            "controllability gramian",
            "cost-to-go",
            "suboptimality gap",
            "sample complexity",
        ],
        "namedResults": [
            "the Pontryagin maximum principle",
            "the Hamilton--Jacobi--Bellman equation",
            "the Karush--Kuhn--Tucker conditions",
            "strong duality",
            "the Lasry--Lions regularization",
            "the Schrödinger bridge problem",
            "Tseng's splitting method",
            "the ADMM algorithm",
            "Slater's condition",
            "the Bellman optimality principle",
            "Danskin's theorem",
            "the Moreau--Yosida envelope",
            "the Fenchel--Rockafellar duality",
            "Nesterov's acceleration",
            "the Lyapunov equation",
            "the Riccati equation",
            "the minimax theorem",
            "the Krasnoselskii--Mann iteration",
            "the Douglas--Rachford splitting",
            "the proximal-point algorithm",
            "the Frank--Wolfe method",
            "the maximum principle",
            "the Kantorovich duality",
            "the Polyak--Lojasiewicz inequality",
            "the bandit lower bound",
        ],
        "methods": [
            "the proximal-gradient method",
            "operator splitting",
            "the alternating direction method of multipliers",
            "interior-point methods",
            "the cutting-plane method",
            "Lagrangian duality",
            "dynamic programming",
            "the maximum principle",
            "mirror descent",
            "stochastic gradient descent",
            "accelerated gradient methods",
            "primal-dual hybrid gradient",
            "semidefinite relaxation",
            "the moment-SOS hierarchy",
            "online convex optimization",
            "the Frank--Wolfe algorithm",
            "a Lyapunov analysis",
            "the method of multipliers",
            "trust-region methods",
            "policy iteration",
            "value iteration",
            "a primal-dual analysis",
            "the catalyst acceleration scheme",
            "stochastic approximation",
        ],
        "objectGloss": [
            "captures the trade-off between cost and constraint",
            "encodes the optimal feedback control",
            "arises in large-scale distributed optimization",
            "controls the long-run behavior of the iterates",
            "lies at the heart of modern convex analysis",
            "reflects the duality between primal and dual problems",
            "governs the convergence of first-order methods",
            "is central to the theory of optimal control",
        ],
    },
    # Object-naming letters only. No "f" (the objective), "x" (the iterate),
    # "t"/"k" (time/iteration indices), or "L" (the Lagrangian/Lipschitz).
    symbols=[
        "J",
        "V",
        "P",
        "Q",
        "M",
        "\\Phi",
        "\\Pi",
        "\\Gamma",
        "S",
        "\\mathcal{A}",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\min_{x \in \mathcal{X}} f(x)",
        r"\nabla f(x^\star) = 0",
        r"\lVert x_k - x^\star \rVert \le C\rho^{k}",
        r"\operatorname{Regret}_T = O\!\left(\sqrt{T}\right)",
        r"x_{k+1} = \operatorname{prox}_{\lambda g}\!\left(x_k - \lambda \nabla f(x_k)\right)",
        r"0 \in \partial f(x^\star) + N_{\mathcal{X}}(x^\star)",
        r"f(x_k) - f^\star \le \frac{C}{k^{@C@}}",
        r"\kappa = L/\mu",
        r"\nabla^2 f(x) \succeq \mu I",
        r"XSYM(x) = \sup_{\lambda \ge 0} \mathcal{L}(x,\lambda)",
        r"\eta_k = \frac{1}{L}",
        r"f(x_k) - f^\star \le \frac{2L\lVert x_0 - x^\star\rVert^2}{(k+1)^2}",
        r"x^\star = \Pi_{\mathcal{X}}\!\left(x^\star - \eta \nabla f(x^\star)\right)",
        r"\operatorname{prox}_{\lambda g}(v) = \arg\min_x \tfrac{1}{2}\lVert x-v\rVert^2 "
        r"+ \lambda g(x)",
        r"u^\star(t) = -R^{-1} B^\top P(t)\, x(t)",
        r"\dot{V}(x) \le -\alpha V(x)",
        r"\mathbb{E}\!\left[\lVert \nabla f(x_k)\rVert^2\right] \le \frac{C}{\sqrt{k}}",
        r"g(\lambda) = \inf_x \mathcal{L}(x,\lambda)",
        r"f^\star = \max_{\lambda \ge 0} g(\lambda)",
        r"\langle F(x) - F(y),\, x - y\rangle \ge \mu \lVert x-y\rVert^2",
        r"X \succeq 0,\quad \operatorname{tr}(XSYM) = @N@",
        r"\rho = 1 - \tfrac{1}{\kappa}",
        r"\lVert x_{k+1} - x^\star\rVert \le \rho\,\lVert x_k - x^\star\rVert",
        r"\gamma^{@K@} \le \frac{1}{1-\gamma}",
        r"\operatorname{rank}(XSYM) \le @R@",
        r"H(x,p,u) = \langle p, b(x,u)\rangle + \ell(x,u)",
        r"V(x) = \min_u \mathbb{E}\!\left[\int_0^T \ell\, dt\right]",
        r"\partial f(x) = \{ g : f(y) \ge f(x) + \langle g, y-x\rangle\}",
        r"\nabla f(x^\star) + \sum_{i=1}^{@N@} \lambda_i \nabla c_i(x^\star) = 0",
        r"f^\star_{\mathrm{primal}} = f^\star_{\mathrm{dual}}",
    ],
    display_eqns=[
        r"\partial_t V(x,t) + \min_{u \in U}\Bigl\{ \langle \nabla_x V, b(x,u)\rangle "
        r"+ \ell(x,u) \Bigr\} = 0, \qquad V(x,T) = \Phi(x)",
        r"\begin{aligned} \nabla f(x^\star) + \textstyle\sum_i \lambda_i^\star \nabla g_i(x^\star) "
        r"&= 0, \\ \lambda_i^\star \ge 0,\ g_i(x^\star) &\le 0,\ \lambda_i^\star g_i(x^\star) = 0. "
        r"\end{aligned}",
        r"f(x_k) - f^\star \le \frac{L\,\lVert x_0 - x^\star\rVert^2}{2k}, \qquad x_{k+1} "
        r"= x_k - \tfrac{1}{L}\nabla f(x_k)",
        r"\dot{x}(t) = \frac{\partial H}{\partial p}, \qquad \dot{p}(t) "
        r"= -\frac{\partial H}{\partial x}, \qquad u^\star(t) "
        r"= \arg\min_{u \in U} H\bigl(x(t),p(t),u\bigr)",
        r"\min_{x} \; f(x) + g(z) \quad \text{s.t.}\quad Ax + Bz = c, \qquad "
        r"\mathcal{L}_\rho(x,z,y) = f(x) + g(z) + \langle y, Ax+Bz-c\rangle "
        r"+ \tfrac{\rho}{2}\lVert Ax+Bz-c\rVert^2",
        r"\inf_{\hat\pi} \sup_{Q \in \mathcal{Q}} \mathbb{E}_{Q}\!\left[\ell(\hat\pi, \xi)\right] "
        r"= \sup_{Q \in \mathcal{Q}} \inf_{\hat\pi} \mathbb{E}_{Q}\!\left[\ell(\hat\pi,\xi)\right]",
        r"A^\top P + P A - P B R^{-1} B^\top P + XSYM = 0",
        r"V(x) = \min_{u} \Bigl\{ \ell(x,u) + \gamma\, \mathbb{E}\bigl[ V(x')\bigr] \Bigr\}, "
        r"\qquad 0 \le \gamma < 1",
        r"x_{k+1} = \arg\min_{x \in \mathcal{X}} \Bigl\{ \langle \nabla f(x_k), x\rangle "
        r"+ \tfrac{1}{2\eta} D(x, x_k) \Bigr\}",
        r"\max_{X \succeq 0} \; \langle C, X\rangle \quad \text{s.t.}\quad "
        r"\langle A_i, X\rangle = b_i,\ i = 1,\dots,@N@",
        r"W_2^2(\mu,\nu) = \inf_{\pi \in \Pi(\mu,\nu)} \int \lVert x - y\rVert^2 \, d\pi(x,y)",
        r"\frac{1}{T}\sum_{k=1}^{T} \bigl(f(x_k) - f(x^\star)\bigr) "
        r"\le \frac{\lVert x_0 - x^\star\rVert^2}{2\eta T} + \frac{\eta G^2}{2}",
        r"\mathbb{E}\!\left[ f(\bar x_T) - f^\star \right] "
        r"\le \frac{\lVert x_0 - x^\star\rVert^2}{2\eta T} + \frac{\eta \sigma^2}{2}",
        r"x^\star \in \mathcal{X}: \quad \langle F(x^\star),\, y - x^\star\rangle \ge 0 "
        r"\quad \text{for all } y \in \mathcal{X}",
        r"\sup_{\lambda \ge 0} \inf_{x} \mathcal{L}(x,\lambda) "
        r"= \inf_{x} \sup_{\lambda \ge 0} \mathcal{L}(x,\lambda) = f^\star",
        r"x_{k+1} = (1-\theta_k) x_k + \theta_k\, s_k, \qquad s_k "
        r"= \arg\min_{s \in \mathcal{X}} \langle \nabla f(x_k), s\rangle",
        r"\operatorname{Regret}_T = \sum_{t=1}^{T} f_t(x_t) - \min_{x \in \mathcal{X}} "
        r"\sum_{t=1}^{T} f_t(x) \le O\!\left(\sqrt{T}\right)",
        r"f(x) - f^\star \le \frac{1}{2\mu}\lVert \nabla f(x)\rVert^2 \quad "
        r"\text{(Polyak--Lojasiewicz)}",
    ],
    msc=["49J20", "90C25", "93E20", "49L20", "90C22", "65K05", "49N10", "93D05"],
    adjacent=["math.NA", "math.PR"],
)
