"""math.PR - Probability.

Seed from the build spec, expanded with the discrete/probability/applied
research dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

PR = SubfieldLexicon(
    code="math.PR",
    name="Probability",
    weight=9.0,
    banks={
        "objects": [
            "random variable",
            "random vector",
            "stochastic process",
            "martingale",
            "submartingale",
            "Markov chain",
            "Markov kernel",
            "Brownian motion",
            "Brownian bridge",
            "Levy process",
            "Gaussian process",
            "Gaussian random field",
            "diffusion",
            "stochastic differential equation",
            "McKean--Vlasov equation",
            "branching process",
            "growth-fragmentation process",
            "Galton--Watson tree",
            "random matrix",
            "Wigner matrix",
            "random graph",
            "percolation cluster",
            "Gibbs measure",
            "point process",
            "Poisson point process",
            "Hawkes process",
            "interacting particle system",
            "exclusion process",
            "random walk",
            "self-avoiding walk",
            "Dirichlet form",
            "occupation measure",
            "empirical measure",
            "spectral measure",
            "coupling",
            "stopping time",
            "filtration",
            "local time",
            "stochastic integral",
            "random recursive tree",
            "Schramm--Loewner evolution",
            "free energy",
        ],
        "props": [
            "stationary",
            "ergodic",
            "reversible",
            "exchangeable",
            "Gaussian",
            "sub-Gaussian",
            "subcritical",
            "supercritical",
            "critical",
            "recurrent",
            "transient",
            "Feller",
            "irreducible",
            "aperiodic",
            "self-similar",
            "self-avoiding",
            "self-repelling",
            "delocalized",
            "hyperuniform",
            "mean-field",
            "uniformly integrable",
            "tight",
            "absolutely continuous",
            "non-degenerate",
            "adapted",
            "predictable",
            "cadlag",
            "Harris recurrent",
            "geometrically ergodic",
            "long-range dependent",
            "heavy-tailed",
            "light-tailed",
            "infinitely divisible",
            "positive recurrent",
            "null recurrent",
            "conditionally independent",
            "spectrally positive",
            "path-dependent",
            "degenerate",
        ],
        "spaces": [
            "probability space",
            "sample space",
            "path space",
            "Skorokhod space",
            "Wiener space",
            "space of probability measures",
            "Wasserstein space",
            "configuration space",
            "state space",
            "filtration",
            "tail $\\sigma$-algebra",
            "Cameron--Martin space",
            "reproducing kernel Hilbert space",
            "space of cadlag paths",
            "Polish space",
            "Hilbert space of $L^2$ functionals",
            "tangent space of measures",
            "space of empirical measures",
            "Dirichlet energy space",
            "Schwartz distribution space",
        ],
        "maps": [
            "the transition kernel",
            "the infinitesimal generator",
            "the resolvent",
            "the semigroup",
            "the Malliavin derivative",
            "the divergence operator",
            "the conditional expectation",
            "the Doob--Meyer projection",
            "the optional projection",
            "the Levy symbol",
            "the characteristic function",
            "the Laplace transform",
            "the coupling map",
            "the time-change",
            "the Girsanov density",
        ],
        "invariants": [
            "mean",
            "variance",
            "covariance",
            "spectral gap",
            "mixing time",
            "relaxation time",
            "Lyapunov exponent",
            "rate function",
            "free energy",
            "partition function",
            "Hausdorff dimension",
            "critical probability",
            "extinction probability",
            "survival probability",
            "stationary distribution",
            "invariant measure",
            "quadratic variation",
            "predictable compensator",
            "entropy",
            "relative entropy",
            "total variation distance",
            "Wasserstein distance",
            "spectral density",
            "drift coefficient",
            "diffusion coefficient",
        ],
        "namedResults": [
            "the central limit theorem",
            "the large deviations principle",
            "the Wigner semicircle law",
            "KPZ universality",
            "Stein's method",
            "the propagation of chaos",
            "the Cramer theorem",
            "the Sanov theorem",
            "the Donsker invariance principle",
            "the martingale convergence theorem",
            "the optional stopping theorem",
            "the Itô formula",
            "the Girsanov theorem",
            "the Feynman--Kac formula",
            "the Burkholder--Davis--Gundy inequality",
            "the Dubins--Schwarz theorem",
            "the Komlos--Major--Tusnady coupling",
            "the Kolmogorov extension theorem",
            "the Skorokhod embedding theorem",
            "the de Finetti theorem",
            "the Aldous--Hoover representation",
            "the Harris theorem",
            "the Varadhan lemma",
            "the Tracy--Widom law",
            "the Marchenko--Pastur law",
        ],
        "methods": [
            "the martingale method",
            "the coupling method",
            "Stein's method",
            "Malliavin calculus",
            "the Lyapunov function method",
            "the entropy method",
            "the second moment method",
            "Fourier analysis of characteristic functions",
            "the change of measure",
            "the Itô calculus",
            "the moment method",
            "the contraction principle",
            "the transfer operator approach",
            "a tightness argument",
            "the reflection coupling",
            "the Aldous coupling",
            "the cavity method",
            "the Lindeberg replacement",
            "concentration of measure",
            "the spectral method",
            "the Skorokhod representation",
            "a chaining argument",
            "the propagation of chaos estimate",
            "a large deviations analysis",
        ],
        "objectGloss": [
            "captures the universal fluctuations of the system",
            "governs the long-time behavior of the dynamics",
            "encodes the limiting Gaussian structure",
            "controls the rate of convergence to equilibrium",
            "lies at the heart of modern probability",
            "reflects the underlying mean-field interaction",
            "quantifies the exponential decay of rare events",
            "links microscopic dynamics to a scaling limit",
        ],
    },
    # Object-naming letters only. "X","Y" name random variables, capitals name
    # processes; avoid "n" (sample index), "t" (time), "p" (probability).
    symbols=[
        "X",
        "Y",
        "Z",
        "W",
        "B",
        "M",
        "S",
        "\\mu",
        "\\nu",
        "\\Phi",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\mathbb{E}[XSYM] = @R@",
        r"\operatorname{Var}(XSYM) = \sigma^{2}",
        r"\mathbb{P}\bigl(|XSYM - \mathbb{E} XSYM| > t\bigr) "
        r"\le 2 e^{-c t^{2}}",
        r"\frac{S_n - n\mu}{\sigma\sqrt{n}} \xrightarrow{d} N(0,1)",
        r"\mathbb{P}\bigl(XSYM_n / n \approx x\bigr) \asymp e^{-n I(x)}",
        r"d_{TV}(\mu_n, \mu) \le C\, n^{-1/2}",
        r"\|XSYM_n - XSYM\|_{TV} \le @C@\, \rho^{n}",
        r"\mathbb{E}\bigl[XSYM \mid \mathcal{F}_t\bigr] = XSYM_t",
        r"W_2(\mu, \nu) \le \sqrt{2\, D(\mu \,\|\, \nu)}",
        r"\langle XSYM \rangle_t = \int_0^t \sigma_s^{2}\, ds",
        r"\mathbb{P}(\tau < \infty) = @R@",
        r"\lambda_{\mathrm{gap}} \ge \frac{1}{t_{\mathrm{mix}}}",
        r"XSYM_t = XSYM_0 + B_t",
        r"\mathbb{E}\bigl[e^{\theta XSYM}\bigr] \le e^{\theta^{2}\sigma^{2}/2}",
        r"\mu_n \Rightarrow \mu",
        r"d\, XSYM_t = b(XSYM_t)\, dt + \sigma\, dB_t",
        r"H(\mu) = -\sum_i \mu_i \log \mu_i",
        r"\rho_{\mathrm{sc}}(x) = \frac{1}{2\pi}\sqrt{4 - x^{2}}",
        r"\mathbb{P}(XSYM > t) \sim t^{-\alpha}",
        r"I(x) = \sup_{\theta}\,\bigl(\theta x - \Lambda(\theta)\bigr)",
        r"\mathbb{E}\bigl[XSYM_t \mid \mathcal{F}_s\bigr] \ge XSYM_s",
        r"p_c(\mathbb{Z}^{@C@}) \in (0,1)",
        r"\dim_H(\mathrm{range}\, B) = \min(@C@, 2)",
        r"\mathbb{E}\,[XSYM_t^{2}] = e^{2\beta t}",
        r"\mathbb{P}\bigl(\sup_{s \le t} B_s > a\bigr) "
        r"= 2\,\mathbb{P}(B_t > a)",
        r"\Lambda(\theta) = \log \mathbb{E}\,[e^{\theta XSYM}]",
        r"\operatorname{Cov}(XSYM_s, XSYM_t) = e^{-|t - s|}",
        r"\|XSYM\|_{\psi_2} \le @C@",
        r"\mathbb{E}\,XSYM_\tau = \mathbb{E}\,XSYM_0",
        r"\lambda_n(XSYM) \le 2 + n^{-2/3}\, \xi",
    ],
    display_eqns=[
        r"\frac{1}{\sqrt{n}}\sum_{i=1}^{n} (X_i - \mu) "
        r"\xrightarrow{d} N\!\left(0,\, \sigma^{2}\right)",
        r"\lim_{n \to \infty} \frac{1}{n} \log "
        r"\mathbb{P}\!\left(\frac{S_n}{n} \in A\right) "
        r"= -\inf_{x \in A} I(x)",
        r"d\, XSYM_t = b(XSYM_t)\, dt + \sigma(XSYM_t)\, dB_t, "
        r"\qquad XSYM_0 = x_0",
        r"XSYM_t = XSYM_0 + \int_0^t b(XSYM_s)\, ds "
        r"+ \int_0^t \sigma(XSYM_s)\, dB_s",
        r"\partial_t \rho_t = -\nabla \cdot (b\, \rho_t) "
        r"+ \tfrac{1}{2}\,\Delta\!\left(\sigma^{2} \rho_t\right)",
        r"\mathbb{P}\!\left(\max_{1 \le i \le n} \lambda_i "
        r"\le 2 + s\, n^{-2/3}\right) \to F_2(s)",
        r"d_{TV}\!\bigl(\mathcal{L}(W), N(0,1)\bigr) "
        r"\le \mathbb{E}\,\bigl| 1 - \langle DW, -DL^{-1} W \rangle \bigr|",
        r"\rho_{\mathrm{MP}}(x) = \frac{\sqrt{(\lambda_+ - x)(x - \lambda_-)}}"
        r"{2\pi \gamma\, x}, \qquad \lambda_\pm = (1 \pm \sqrt{\gamma})^{2}",
        r"f(XSYM_t) = f(XSYM_0) + \int_0^t f'(XSYM_s)\, d XSYM_s "
        r"+ \tfrac{1}{2}\int_0^t f''(XSYM_s)\, d\langle XSYM \rangle_s",
        r"\frac{d\mathbb{Q}}{d\mathbb{P}}\bigg|_{\mathcal{F}_t} "
        r"= \exp\!\left(\int_0^t \theta_s\, dB_s "
        r"- \tfrac{1}{2}\int_0^t \theta_s^{2}\, ds\right)",
        r"u(t,x) = \mathbb{E}^{x}\!\left[ g(B_t) "
        r"\exp\!\left(\int_0^t V(B_s)\, ds\right)\right]",
        r"\mathbb{E}\!\left[\sup_{s \le t} |M_s|^{p}\right] "
        r"\le C_p\, \mathbb{E}\,\langle M \rangle_t^{p/2}",
        r"W_2^{2}(\mu, \nu) = \inf_{\pi \in \Pi(\mu,\nu)} "
        r"\int |x - y|^{2}\, d\pi(x,y)",
        r"\frac{d}{dt}\, H(\rho_t \,\|\, \pi) "
        r"= -\, I(\rho_t \,\|\, \pi) \le 0",
        r"\mathcal{L} f(x) = b(x) \cdot \nabla f(x) "
        r"+ \tfrac{1}{2}\sum_{i,j} a_{ij}(x)\, \partial_i \partial_j f(x)",
        r"\mathbb{P}\!\left(\sup_{t \le T}\, |XSYM_t^{N} - \bar XSYM_t| > "
        r"\varepsilon\right) \le C\, e^{-c N \varepsilon^{2}}",
        r"\sum_{k} \mathbb{E}\,\bigl|X_k\bigr|^{3} "
        r"\Big/ \Bigl(\sum_k \operatorname{Var} X_k\Bigr)^{3/2} \to 0",
        r"\mathbb{P}\!\left(\frac{1}{n}\sum_{i=1}^{n} \delta_{X_i} "
        r"\in B\right) \asymp \exp\!\left(-n \inf_{\nu \in B} "
        r"D(\nu \,\|\, \mu)\right)",
    ],
    msc=["60F05", "60F10", "60J65", "60G44", "60H10", "60B20", "60K35", "60J60"],
    adjacent=["math.CO", "math.ST"],
)
