"""math.QA - Quantum Algebra.

Seeded from the build spec and expanded with the algebra/number-theory research
dossier into a broad working vocabulary of quantum groups, VOAs, and tensor
categories.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

QA = SubfieldLexicon(
    code="math.QA",
    name="Quantum Algebra",
    weight=5.0,
    banks={
        "objects": [
            "quantum group",
            "quantized enveloping algebra",
            "Hopf algebra",
            "Drinfeld double",
            "quasi-Hopf algebra",
            "ribbon Hopf algebra",
            "$R$-matrix",
            "vertex operator algebra",
            "vertex superalgebra",
            "chiral algebra",
            "conformal vertex algebra",
            "$W$-algebra",
            "finite $W$-algebra",
            "affine $W$-algebra",
            "deformed $W$-algebra",
            "affine Lie algebra",
            "Kac--Moody algebra",
            "Yangian",
            "quantum affine algebra",
            "fusion category",
            "modular tensor category",
            "braided tensor category",
            "ribbon category",
            "spherical category",
            "tensor category",
            "module category",
            "Temperley--Lieb algebra",
            "Hecke algebra",
            "quantum Schur algebra",
            "crystal basis",
            "canonical basis",
            "quiver variety",
            "Nichols algebra",
            "Lie bialgebra",
            "Poisson algebra",
            "deformation quantization",
            "knot invariant",
            "topological quantum field theory",
            "conformal block",
            "fusion ring",
            "skein module",
        ],
        "props": [
            "quantum",
            "quantized",
            "braided",
            "ribbon",
            "modular",
            "rational",
            "irrational",
            "$C_2$-cofinite",
            "lisse",
            "quasi-classical",
            "integrable",
            "semi-integrable",
            "highest weight",
            "simple",
            "semisimple",
            "indecomposable",
            "rigid",
            "fusion",
            "spherical",
            "pivotal",
            "unitary",
            "non-degenerate",
            "factorizable",
            "triangular",
            "quasitriangular",
            "cocommutative",
            "graded",
            "filtered",
            "conformal",
            "affine",
            "self-dual",
            "tilting",
            "admissible",
            "logarithmic",
            "abelian",
            "monoidal",
            "weakly integral",
            "pointed",
            "Frobenius--Perron",
        ],
        "spaces": [
            "quantum group",
            "vertex operator algebra",
            "fusion category",
            "modular tensor category",
            "representation category",
            "module category",
            "Drinfeld center",
            "Grothendieck ring",
            "fusion ring",
            "Yangian",
            "quantum affine algebra",
            "Hecke algebra",
            "quiver variety",
            "crystal",
            "Hopf algebra",
            "conformal block",
            "category of modules",
            "Drinfeld double",
            "lattice vertex algebra",
            "Verlinde algebra",
        ],
        "maps": [
            "the universal $R$-matrix",
            "the antipode",
            "the comultiplication",
            "the braiding",
            "the Drinfeld associator",
            "the quantum Frobenius",
            "the ribbon element",
            "the coproduct",
            "the screening operator",
            "the intertwining operator",
            "the Casimir element",
            "the evaluation map",
            "the quantum trace",
            "the Knizhnik--Zamolodchikov connection",
            "the twist",
        ],
        "invariants": [
            "central charge",
            "quantum dimension",
            "Frobenius--Perron dimension",
            "conformal weight",
            "level",
            "rank",
            "global dimension",
            "$S$-matrix",
            "$T$-matrix",
            "fusion coefficient",
            "Verlinde formula",
            "$q$-character",
            "quantum parameter",
            "modular data",
            "Gauss sum",
            "topological twist",
            "anomaly",
            "categorical dimension",
            "Cartan matrix",
            "highest weight",
            "$q$-dimension",
            "character",
            "fusion rule",
            "associativity constraint",
            "braiding eigenvalue",
        ],
        "namedResults": [
            "the Verlinde formula",
            "the Kazhdan--Lusztig equivalence",
            "the quantum Frobenius",
            "Lusztig's conjecture",
            "the Kohno--Drinfeld theorem",
            "the Etingof--Kazhdan quantization",
            "Drinfeld's theorem",
            "the Reshetikhin--Turaev invariants",
            "the Frobenius--Perron theorem",
            "the Deligne--Simpson problem",
            "the Anderson--Moore theorem",
            "the Frenkel--Kac construction",
            "the Wakimoto realization",
            "the Frenkel--Zhu theorem",
            "the Coulomb branch conjecture",
            "the Feigin--Frenkel duality",
            "the Drinfeld--Sokolov reduction",
            "the Knizhnik--Zamolodchikov equation",
            "the Schur--Weyl duality",
            "the quantum McKay correspondence",
            "the Andersen--Jantzen--Soergel theorem",
            "the Beilinson--Drinfeld construction",
            "the Braverman--Finkelberg--Nakajima theorem",
            "the Etingof--Nikshych--Ostrik theorem",
            "the Witten--Reshetikhin--Turaev invariants",
        ],
        "methods": [
            "the theory of crystal bases",
            "geometric representation theory",
            "the quantum group action",
            "Drinfeld--Sokolov reduction",
            "the Wakimoto free-field realization",
            "the screening operator formalism",
            "vertex algebra techniques",
            "deformation quantization",
            "the Kazhdan--Lusztig functor",
            "the theory of fusion categories",
            "the Reshetikhin--Turaev construction",
            "categorification",
            "the theory of canonical bases",
            "the trace formula",
            "the $R$-matrix formalism",
            "Drinfeld's quantization",
            "the theory of modular data",
            "an analysis of conformal blocks",
            "the coset construction",
            "the orbifold construction",
            "the theory of $W$-algebras",
            "Schur--Weyl duality",
            "the BGG resolution",
            "factorization homology",
        ],
        "objectGloss": [
            "deforms the classical universal enveloping algebra",
            "encodes the braiding of a tensor category",
            "governs the fusion of conformal blocks",
            "categorifies the corresponding quantum invariant",
            "arises naturally in conformal field theory",
            "is central to modern quantum algebra",
            "reflects the symmetry of the underlying Lie algebra",
            "controls the representation theory at a root of unity",
        ],
    },
    # Object-naming letters only. No "q" (clashes with the quantum parameter q)
    # and no "i, j, n" (clash with running indices in fusion sums).
    symbols=[
        "U",
        "V",
        "W",
        "A",
        "H",
        "\\mathcal{C}",
        "\\mathfrak{g}",
        "L",
        "\\rho",
        "Y",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\Delta(E) = E \otimes 1 + K \otimes E",
        r"S(E) = -K^{-1} E",
        r"R = q^{H \otimes H / 2} \sum_n c_n E^{n} \otimes F^{n}",
        r"[E, F] = \frac{K - K^{-1}}{q - q^{-1}}",
        r"c = @C@ - \frac{6}{(p)(p+1)}",
        r"\dim_q XSYM = @N@",
        r"N_{ij}^{k} = \dim \operatorname{Hom}(i \otimes j, k)",
        r"\operatorname{FPdim}(XSYM) = @N@",
        r"\theta_i = e^{2\pi i\, h_i}",
        r"[n]_q = \frac{q^{n} - q^{-n}}{q - q^{-1}}",
        r"K E K^{-1} = q^{2} E",
        r"\mathcal{R}_{XSYM, ASYM}: XSYM \otimes ASYM \to ASYM \otimes XSYM",
        r"\dim \operatorname{Hom}_{\mathcal{C}}(XSYM, ASYM) = @N@",
        r"S^{2} = (TS)^{3}",
        r"q = e^{2\pi i / (\kappa + h^{\vee})}",
        r"\operatorname{rank} \mathcal{C} = @N@",
        r"h_i = \frac{C_i}{2(\kappa + h^{\vee})}",
        r"q^{@N@} = 1",
        r"L(\Lambda) = \bigoplus_{\mu} L(\Lambda)_{\mu}",
        r"\chi_{XSYM}(q) = \sum_{n \ge 0} \dim (XSYM)_n \, q^{n - c/24}",
        r"\dim \mathfrak{g} = @N@",
        r"[L_m, L_n] = (m-n) L_{m+n} + \frac{c}{12}(m^3 - m)\delta_{m+n,0}",
        r"\sum_k N_{ij}^{k} \dim_q(k) = \dim_q(i)\dim_q(j)",
        r"\mathrm{ch}\, L(\Lambda) = \sum_{w \in W} (-1)^{\ell(w)} e^{w(\Lambda+\rho)-\rho}",
        r"Y(a, z) = \sum_{n \in \mathbb{Z}} a_{(n)}\, z^{-n-1}",
        r"q^{\langle \lambda, \alpha^{\vee} \rangle}",
        r"\dim Z(\mathcal{C}) = (\dim \mathcal{C})^{2}",
        r"T_i T_j T_i = T_j T_i T_j",
        r"(T_i - q)(T_i + 1) = 0",
        r"\operatorname{tr}_q(\mathrm{id}_{XSYM}) = \dim_q XSYM",
    ],
    display_eqns=[
        r"R_{12} R_{13} R_{23} = R_{23} R_{13} R_{12}",
        r"N_{ij}^{k} = \sum_{m} \frac{S_{im} S_{jm} \overline{S_{km}}}{S_{0m}}",
        r"Y(u, z_1) Y(v, z_2) \sim \sum_{n} \frac{Y(u_{(n)} v, z_2)}{(z_1 - z_2)^{n+1}}",
        r"\mathrm{ch}\, L(\Lambda)(\tau) = "
        r"\frac{\sum_{w \in W} (-1)^{\ell(w)} \Theta_{w(\Lambda+\rho)}(\tau)}"
        r"{\eta(\tau)^{\dim \mathfrak{g}}}",
        r"\chi_{XSYM}\!\left(-\tfrac{1}{\tau}\right) = "
        r"\sum_{ASYM} S_{XSYM,\, ASYM}\, \chi_{ASYM}(\tau)",
        r"\Delta(x) = x \otimes 1 + 1 \otimes x, \qquad "
        r"S(x) = -x, \qquad \varepsilon(x) = 0",
        r"(\Delta \otimes \mathrm{id})R = R_{13} R_{23}, \qquad "
        r"(\mathrm{id} \otimes \Delta)R = R_{13} R_{12}",
        r"[L_m, L_n] = (m - n) L_{m+n} + \frac{c}{12}\bigl(m^{3} - m\bigr)\delta_{m+n, 0}",
        r"U_q(\mathfrak{g}) = \bigl\langle E_i, F_i, K_i^{\pm 1} : "
        r"1 \le i \le @N@ \bigr\rangle",
        r"a_{(m)} b = \sum_{i \ge 0} \binom{m}{i}\bigl(a_{(i)} b\bigr)_{(m - i)}",
        r"\bigl(q - q^{-1}\bigr)[E_i, F_j] = \delta_{ij}\bigl(K_i - K_i^{-1}\bigr)",
        r"\dim_q V = \prod_{\alpha > 0} \frac{q^{\langle \lambda + \rho, \alpha^{\vee}\rangle} - "
        r"q^{-\langle \lambda + \rho, \alpha^{\vee}\rangle}}"
        r"{q^{\langle \rho, \alpha^{\vee}\rangle} - q^{-\langle \rho, \alpha^{\vee}\rangle}}",
        r"\sum_{k} N_{ij}^{k}\, [k] = [i] \cdot [j] \quad \text{in } K_0(\mathcal{C})",
        r"\partial_{z_a} \Psi = \frac{1}{\kappa + h^{\vee}} "
        r"\sum_{b \neq a} \frac{\Omega_{ab}}{z_a - z_b}\, \Psi",
        r"H^{\bullet}\bigl(\mathfrak{n}_-, L(\Lambda)\bigr) = "
        r"\bigoplus_{w \in W} L\bigl(w \cdot \Lambda\bigr)[-\ell(w)]",
        r"Z(M) = \sum_{i} \bigl(\dim_q i\bigr)\, \mathrm{tr}\bigl(\rho_i(M)\bigr)",
        r"0 \to \bigoplus L(\mu) \to \cdots \to M(\lambda) \to L(\lambda) \to 0",
        r"\theta_i \, \theta_j \, s_{ij} = \sum_k N_{ij}^{k}\, \theta_k \, \dim_q(k)",
    ],
    msc=["17B37", "81R50", "18M20", "17B69", "16T05", "17B67", "18M15", "20G42"],
    adjacent=["math.RT", "math.RA"],
)
