"""math.RA - Rings and Algebras.

Seed from the build spec, expanded with the algebra/number-theory research
dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

RA = SubfieldLexicon(
    code="math.RA",
    name="Rings and Algebras",
    weight=4.0,
    banks={
        "objects": [
            "associative algebra",
            "finite-dimensional algebra",
            "noncommutative ring",
            "division algebra",
            "central simple algebra",
            "Azumaya algebra",
            "Hopf algebra",
            "Lie algebra",
            "Lie superalgebra",
            "Lie $2$-algebra",
            "Nijenhuis Lie algebra",
            "Leibniz algebra",
            "Jordan algebra",
            "Poisson algebra",
            "Rota--Baxter algebra",
            "Rota--Baxter operator",
            "skew brace",
            "left brace",
            "path algebra",
            "Leavitt path algebra",
            "Steinberg algebra",
            "quiver",
            "quiver with relations",
            "cluster algebra",
            "gentle algebra",
            "self-injective algebra",
            "Frobenius algebra",
            "Nakayama algebra",
            "tilting module",
            "projective module",
            "injective module",
            "indecomposable module",
            "bimodule",
            "two-sided ideal",
            "nilpotent ideal",
            "Jacobson radical",
            "idempotent",
            "derivation",
            "automorphism",
            "Ore extension",
            "skew polynomial ring",
            "group algebra",
            "matrix algebra",
            "operad",
        ],
        "props": [
            "associative",
            "commutative",
            "noncommutative",
            "unital",
            "simple",
            "semisimple",
            "prime",
            "semiprime",
            "primitive",
            "central",
            "left Noetherian",
            "right Noetherian",
            "Artinian",
            "hereditary",
            "self-injective",
            "Frobenius",
            "symmetric",
            "quasi-Frobenius",
            "local",
            "basic",
            "connected",
            "graded",
            "filtered",
            "finite-dimensional",
            "finitely generated",
            "free",
            "flat",
            "projective",
            "injective",
            "indecomposable",
            "nilpotent",
            "solvable",
            "perfect",
            "separable",
            "Koszul",
            "quadratic",
            "Morita equivalent",
            "tame",
            "wild",
            "representation-finite",
        ],
        "spaces": [
            "module category",
            "category of finite-dimensional modules",
            "derived category",
            "stable module category",
            "bounded derived category",
            "Grothendieck group",
            "center of the algebra",
            "Jacobson radical",
            "socle",
            "prime spectrum",
            "Brauer group",
            "Picard group of bimodules",
            "Auslander--Reiten quiver",
            "Hochschild cohomology ring",
            "universal enveloping algebra",
            "lattice of two-sided ideals",
            "Grothendieck monoid",
            "cluster category",
            "repetitive algebra",
            "derived Picard group",
        ],
        "maps": [
            "the multiplication map",
            "the comultiplication",
            "the antipode",
            "the Nakayama functor",
            "the Auslander--Reiten translation",
            "a derivation",
            "the trace map",
            "the reduced norm",
            "a Morita equivalence",
            "the Hochschild differential",
            "the bracket",
            "the Rota--Baxter operator",
            "the canonical projection",
            "base change",
            "tensoring with a bimodule",
        ],
        "invariants": [
            "dimension",
            "global dimension",
            "finitistic dimension",
            "Hochschild dimension",
            "representation dimension",
            "Gelfand--Kirillov dimension",
            "Krull dimension",
            "nilpotency index",
            "index",
            "degree",
            "exponent",
            "Schur index",
            "Cartan matrix",
            "Cartan determinant",
            "Coxeter polynomial",
            "Euler form",
            "Hilbert series",
            "Loewy length",
            "number of simple modules",
            "rank of the Grothendieck group",
            "Hochschild cohomology",
            "center",
            "trace",
            "Brauer class",
        ],
        "namedResults": [
            "the Artin--Wedderburn theorem",
            "the Wedderburn--Malcev theorem",
            "the Jacobson density theorem",
            "the Skolem--Noether theorem",
            "the Brauer--Cartan--Hua theorem",
            "Maschke's theorem",
            "the Hopkins--Levitzki theorem",
            "the Nakayama conjecture",
            "the Auslander--Reiten conjecture",
            "the finitistic dimension conjecture",
            "the first Brauer--Thrall conjecture",
            "the second Brauer--Thrall conjecture",
            "Gabriel's theorem",
            "Morita's theorem",
            "the Poincaré--Birkhoff--Witt theorem",
            "the Ado theorem",
            "Levitzki's theorem",
            "the Cartan--Eilenberg theorem",
            "the Hochschild--Kostant--Rosenberg theorem",
            "the Amitsur--Levitzki theorem",
            "Kaplansky's theorem",
            "the Posner theorem",
            "the Yang--Baxter equation",
            "the Frobenius theorem",
            "the Ringel duality theorem",
        ],
        "methods": [
            "Morita theory",
            "tilting theory",
            "Auslander--Reiten theory",
            "the theory of derived categories",
            "Hochschild cohomology",
            "the theory of quivers and relations",
            "covering theory",
            "Koszul duality",
            "the theory of cluster algebras",
            "the theory of Hopf algebras",
            "homological algebra",
            "the theory of central simple algebras",
            "Galois descent",
            "the structure theory of finite-dimensional algebras",
            "deformation theory",
            "the PBW basis",
            "an analysis of the Auslander--Reiten quiver",
            "a study of the Jacobson radical",
            "the theory of operads",
            "the calculus of derivations",
            "Galois cohomology",
            "the theory of Frobenius extensions",
            "a recollement of derived categories",
            "the theory of Rota--Baxter operators",
        ],
        "objectGloss": [
            "encodes the structure of the underlying algebra",
            "governs the representation type of the ring",
            "arises naturally in noncommutative algebra",
            "controls the homological dimension of the algebra",
            "is central to the theory of finite-dimensional algebras",
            "reflects the combinatorics of the underlying quiver",
            "measures the failure of commutativity",
            "lies at the heart of the structure theory of rings",
        ],
    },
    # Object-naming letters only, kept disjoint from the running symbols in the
    # equation pool: no "R" (Rota--Baxter operator / R-matrix), no "S" (antipode
    # S(x) / simple S_i), no "M"/"N"/"D" (matrix algebra M_n(D), modules), no
    # "B" (skew brace), no "Q"/"I" (quiver kQ/I), and no \mathfrak{g}.
    symbols=[
        "A",
        "T",
        "G",
        "\\Lambda",
        "\\Gamma",
        "\\mathcal{A}",
        "\\mathcal{B}",
        "\\mathcal{C}",
        "\\mathcal{D}",
        "\\mathcal{H}",
        "\\mathcal{R}",
        "\\mathcal{S}",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\dim_{k} XSYM = @N@",
        r"\operatorname{gl.dim} XSYM = @R@",
        r"\operatorname{findim} XSYM = @R@",
        r"\operatorname{GKdim} XSYM = @N@",
        r"\dim_{k} Z(XSYM) = @C@",
        r"XSYM \cong M_{@N@}(D)",
        r"XSYM \cong \prod_{i=1}^{@C@} M_{n_i}(D_i)",
        r"J(XSYM)^{@C@} = 0",
        r"\dim \mathrm{HH}^{@I@}(XSYM) = @R@",
        r"\dim \mathrm{Ext}^{@I@}_{XSYM}(M, N) = @R@",
        r"\deg XSYM = @N@^{2}",
        r"\mathrm{ind}(XSYM) = @N@",
        r"\exp(XSYM) \mid \mathrm{ind}(XSYM)",
        r"XSYM \otimes_{k} XSYM^{\mathrm{op}} \cong M_{@N@}(k)",
        r"\mathrm{Mod}\,XSYM \simeq \mathrm{Mod}\,ASYM",
        r"[XSYM] = @R@ \in \mathrm{Br}(k)",
        r"XSYM \cong kQ / I",
        r"\dim_{k} \mathrm{rad}\,XSYM = @N@",
        r"\tau\, ASYM \cong ASYM",
        r"D^{b}(XSYM) \simeq D^{b}(ASYM)",
        r"[x, y] = xy - yx",
        r"R(\partial)(ab) = R(\partial a)\, b + a\, R(\partial b)",
        r"S(ab) = S(b)\, S(a)",
        r"\dim \mathfrak{g} = @N@",
        r"\#\,\mathrm{Irr}(XSYM) = @N@",
        r"\det C_{XSYM} = @N@",
        r"\mathrm{LL}(XSYM) = @R@",
        r"\operatorname{rk} K_0(XSYM) = @N@",
        r"a \circ b - b \circ a = [a, b]",
        r"e^{2} = e \in XSYM",
        r"XSYM / J(XSYM) \cong \prod_i M_{n_i}(D_i)",
        r"\mathrm{Nrd}_{XSYM/k}(x) \in k^{\times}",
        r"\mathfrak{g} = \mathfrak{g}_0 \oplus \mathfrak{g}_1",
        r"\langle x \rangle \star \langle y \rangle = \langle x \cdot y \rangle",
    ],
    display_eqns=[
        r"XSYM \cong \prod_{i=1}^{r} M_{n_i}(D_i), \qquad "
        r"\dim_{k} XSYM = \sum_{i=1}^{r} n_i^{2}\, \dim_{k} D_i",
        r"0 \to \mathrm{rad}\,XSYM \to XSYM \to "
        r"XSYM/\mathrm{rad}\,XSYM \to 0",
        r"\mathrm{HH}^{n}(XSYM) = \mathrm{Ext}^{n}_{XSYM \otimes "
        r"XSYM^{\mathrm{op}}}(XSYM, XSYM)",
        r"\sum_{(x)} x_{(1)} \otimes x_{(2)} = \Delta(x), \qquad "
        r"\sum_{(x)} S(x_{(1)})\, x_{(2)} = \varepsilon(x)\, 1",
        r"R(x)\, R(y) = R\bigl(R(x)\, y + x\, R(y) + \lambda\, x y\bigr)",
        r"[[x, y], z] + [[y, z], x] + [[z, x], y] = 0",
        r"R_{12}\, R_{13}\, R_{23} = R_{23}\, R_{13}\, R_{12}",
        r"\langle \dim S_i, \dim S_j \rangle = "
        r"\delta_{ij} - \dim_{k} \mathrm{Ext}^{1}_{XSYM}(S_i, S_j)",
        r"0 \to ASYM \to E \to \tau^{-1} ASYM \to 0 "
        r"\qquad \text{(almost split sequence)}",
        r"\mathrm{Mod}\,XSYM \;\xrightarrow{\ \sim\ }\; \mathrm{Mod}\,ASYM, "
        r"\qquad ASYM = \operatorname{End}_{XSYM}(P)^{\mathrm{op}}",
        r"U(\mathfrak{g}) \cong \bigoplus_{n \ge 0} U_n / U_{n-1} "
        r"\cong S(\mathfrak{g}) \qquad \text{(PBW)}",
        r"\mathrm{HH}^{*}(XSYM) \cong \bigoplus_{n} \Omega^{n}_{XSYM/k} "
        r"\qquad \text{(HKR, } XSYM \text{ smooth)}",
        r"1 \to \mathfrak{a}(\mathrm{skew\ brace}) \to B "
        r"\to \mathrm{Sym}(B) \to 1, \qquad "
        r"a \cdot b = a + b + \lambda_a(b)",
        r"\operatorname{gl.dim} XSYM = \sup\{\, n : \mathrm{Ext}^{n}_{XSYM}"
        r"(M, N) \neq 0 \,\}",
        r"\chi(XSYM) = \sum_{i \ge 0} (-1)^{i} \dim_{k} "
        r"\mathrm{HH}^{i}(XSYM)",
        r"\mathrm{Br}(k) \cong H^{2}(\mathrm{Gal}(k^{\mathrm{sep}}/k), "
        r"(k^{\mathrm{sep}})^{\times})",
        r"P_{\bullet} \colon \cdots \to P_{1} \to P_{0} \to M \to 0, "
        r"\qquad \operatorname{pd}_{XSYM} M = @R@",
        r"\Phi_{XSYM}(t) = \det\bigl(t\, \mathrm{Id} - C_{XSYM}^{-\top} "
        r"C_{XSYM}\bigr) \qquad \text{(Coxeter polynomial)}",
    ],
    msc=["16D90", "16E10", "16G20", "16W25", "16K20", "16T05", "17B05", "16G60"],
    adjacent=["math.RT", "math.AG", "math.QA"],
)
