"""math.RT - Representation Theory.

Seed from the build spec, expanded with the algebra/number-theory research
dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

RT = SubfieldLexicon(
    code="math.RT",
    name="Representation Theory",
    weight=8.0,
    banks={
        "objects": [
            "irreducible representation",
            "finite-dimensional representation",
            "highest weight module",
            "Verma module",
            "simple module",
            "projective module",
            "tilting module",
            "Weyl module",
            "standard module",
            "costandard module",
            "induced module",
            "cuspidal representation",
            "supercuspidal representation",
            "admissible representation",
            "unitary representation",
            "principal series representation",
            "discrete series representation",
            "Harish-Chandra module",
            "$(\\mathfrak{g}, K)$-module",
            "smooth representation",
            "character sheaf",
            "perverse sheaf",
            "Soergel bimodule",
            "Lie algebra",
            "affine Lie algebra",
            "Kac--Moody algebra",
            "quantum group",
            "Hecke algebra",
            "affine Hecke algebra",
            "Schur algebra",
            "cellular algebra",
            "quiver",
            "quiver representation",
            "crystal basis",
            "canonical basis",
            "category $\\mathcal{O}$",
            "nilpotent orbit",
            "coadjoint orbit",
            "Springer fiber",
            "flag variety",
            "$W$-algebra",
            "vertex operator algebra",
            "Whittaker model",
        ],
        "props": [
            "irreducible",
            "indecomposable",
            "completely reducible",
            "semisimple",
            "simple",
            "reductive",
            "semisimple-rank-one",
            "split",
            "quasi-split",
            "parabolic",
            "Borel",
            "unipotent",
            "nilpotent",
            "solvable",
            "abelian",
            "self-dual",
            "tempered",
            "generic",
            "admissible",
            "unitary",
            "unitarizable",
            "supercuspidal",
            "cuspidal",
            "spherical",
            "integrable",
            "dominant",
            "regular",
            "singular",
            "highest-weight",
            "graded",
            "equivariant",
            "perverse",
            "polynomial",
            "rational",
            "modular",
            "cellular",
            "cluster-tilting",
            "Koszul",
            "monoidal",
            "braided",
        ],
        "spaces": [
            "representation ring",
            "Grothendieck group",
            "category $\\mathcal{O}$",
            "module category",
            "weight lattice",
            "root lattice",
            "Cartan subalgebra",
            "universal enveloping algebra",
            "center of the enveloping algebra",
            "Weyl group",
            "affine Weyl group",
            "flag variety",
            "nilpotent cone",
            "moment graph",
            "crystal graph",
            "fusion category",
            "derived category of category $\\mathcal{O}$",
            "stable module category",
            "Bernstein center",
            "spectrum of the Hecke algebra",
        ],
        "maps": [
            "parabolic induction",
            "Jacquet restriction",
            "the Harish-Chandra homomorphism",
            "the Chevalley restriction map",
            "the Frobenius twist",
            "the translation functor",
            "the Zuckerman functor",
            "the Jacquet--Langlands transfer",
            "the Satake isomorphism",
            "the Springer correspondence",
            "the categorification functor",
            "the Knapp--Stein intertwining operator",
            "the Casimir operator",
            "the comultiplication",
            "the universal $R$-matrix",
        ],
        "invariants": [
            "dimension",
            "highest weight",
            "central character",
            "infinitesimal character",
            "formal character",
            "multiplicity",
            "composition multiplicity",
            "Gelfand--Kirillov dimension",
            "associated variety",
            "Loewy length",
            "global dimension",
            "rank",
            "weight multiplicity",
            "Kazhdan--Lusztig polynomial",
            "$a$-function",
            "Lusztig $a$-invariant",
            "Bernstein degree",
            "fusion rule",
            "quantum dimension",
            "conformal weight",
            "Frobenius--Schur indicator",
            "Cartan matrix",
            "decomposition number",
            "trace of the Casimir",
            "tensor multiplicity",
        ],
        "namedResults": [
            "the local Langlands correspondence",
            "geometric Langlands",
            "the Kazhdan--Lusztig conjecture",
            "the Lusztig conjecture",
            "the Humphreys--Verma conjecture",
            "the Springer correspondence",
            "the Borel--Weil--Bott theorem",
            "the Weyl character formula",
            "the Peter--Weyl theorem",
            "Schur--Weyl duality",
            "the Littlewood--Richardson rule",
            "the Satake isomorphism",
            "the Deligne--Lusztig theory",
            "the Harish-Chandra isomorphism",
            "the Bernstein--Gelfand--Gelfand resolution",
            "the Beilinson--Bernstein localization theorem",
            "the Kac--Weisfeiler conjecture",
            "the Brauer--Nesbitt theorem",
            "Broué's abelian defect conjecture",
            "the Mackey decomposition",
            "Frobenius reciprocity",
            "the Jantzen sum formula",
            "the Kostant multiplicity formula",
            "the Steinberg tensor product theorem",
            "the Braverman--Kazhdan conjecture",
        ],
        "methods": [
            "highest weight theory",
            "the theory of category $\\mathcal{O}$",
            "Beilinson--Bernstein localization",
            "geometric representation theory",
            "the theory of perverse sheaves",
            "Kazhdan--Lusztig theory",
            "categorification",
            "the theory of crystal bases",
            "Soergel bimodule techniques",
            "the orbit method",
            "Deligne--Lusztig induction",
            "the trace formula",
            "the theory of Hecke algebras",
            "Howe duality",
            "the theta correspondence",
            "cluster-algebraic methods",
            "the geometric Satake equivalence",
            "the Langlands--Shahidi method",
            "tilting theory",
            "the theory of $W$-algebras",
            "quantum group techniques",
            "an analysis of the character",
            "a decomposition into weight spaces",
            "the theory of nilpotent orbits",
        ],
        "objectGloss": [
            "encodes the symmetry of the underlying algebra",
            "governs the decomposition of induced representations",
            "arises naturally in the Langlands program",
            "controls the structure of category $\\mathcal{O}$",
            "is central to geometric representation theory",
            "reflects the combinatorics of the Weyl group",
            "categorifies the action of the Hecke algebra",
            "lies at the heart of the theory of automorphic forms",
        ],
    },
    # Object-naming letters only, kept disjoint from the running symbols in the
    # equation pool: no "L"/"M" (simple/Verma modules L(\lambda), M(\mu)), no
    # "G"/"H" (the group and subgroup in induction), no "W" (Weyl group), no
    # "T" (maximal torus), and none of \lambda, \mu, \rho, \pi (weights/reps).
    symbols=[
        "V",
        "U",
        "E",
        "S",
        "\\Pi",
        "\\Sigma",
        "\\Phi",
        "\\Psi",
        "Y",
        "Z",
        "Q",
        "\\Theta",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"\dim XSYM = @N@",
        r"\dim \mathrm{Hom}(XSYM, ASYM) = @R@",
        r"\dim \mathrm{Ext}^{@I@}(XSYM, ASYM) = @R@",
        r"[XSYM : L(\lambda)] = @N@",
        r"XSYM \cong \mathrm{Ind}_{H}^{G} ASYM",
        r"\mathrm{Res}_{H}^{G} XSYM = \bigoplus_{@I@} ASYM",
        r"XSYM \otimes ASYM \cong \bigoplus_{\nu} N_{\lambda\mu}^{\nu}\, L(\nu)",
        r"\chi_{XSYM} = \sum_{w \in W} (-1)^{\ell(w)} e^{w(\lambda+\rho)-\rho}",
        r"\operatorname{GKdim} XSYM = @N@",
        r"\langle \lambda, \alpha^{\vee} \rangle = @R@",
        r"\dim L(\lambda) = \prod_{\alpha > 0} "
        r"\frac{\langle \lambda+\rho, \alpha^{\vee}\rangle}"
        r"{\langle \rho, \alpha^{\vee}\rangle}",
        r"P_{x,w}(q) \in \mathbb{Z}_{\ge 0}[q]",
        r"\mathrm{rk}\, XSYM = @C@",
        r"\Omega \cdot v = \langle \lambda, \lambda + 2\rho \rangle\, v",
        r"|W| = @N@",
        r"\dim XSYM^{H} = @R@",
        r"\operatorname{soc} XSYM = L(\lambda)",
        r"\operatorname{hd} XSYM = L(\mu)",
        r"\#\,\mathrm{Irr}(G) = @N@",
        r"[G : H] = @N@",
        r"\nu_2(XSYM) \in \{-1, 0, 1\}",
        r"c_{\lambda\mu}^{\nu} = @N@",
        r"\dim \mathfrak{g} = @N@",
        r"d_{XSYM} = \sqrt{\dim \mathfrak{g}/\dim \mathfrak{h}}",
        r"\theta_{\lambda}\, M(\mu) = M(\lambda)",
        r"XSYM \in \mathcal{O}_{\lambda}",
        r"\operatorname{ch} L(\lambda) = \sum_{\mu} m_{\lambda\mu}\, e^{\mu}",
        r"H^{@I@}(\mathfrak{n}, XSYM) = @R@",
        r"\Gamma\bigl(G/B, \mathcal{L}_{\lambda}\bigr) \cong L(\lambda)^{*}",
        r"a(w) = @R@",
        r"\dim_q XSYM = [@N@]_q",
        r"\mathrm{soc}^{@I@} XSYM / \mathrm{soc}^{@R@} XSYM \cong L(\lambda)",
        r"\bar\pi \cong \pi^{(p)}",
        r"\operatorname{rk} K_0(\mathcal{O}_0) = |W|",
    ],
    display_eqns=[
        r"\operatorname{ch} L(\lambda) = "
        r"\frac{\sum_{w \in W} (-1)^{\ell(w)}\, e^{w(\lambda+\rho)}}"
        r"{\sum_{w \in W} (-1)^{\ell(w)}\, e^{w(\rho)}}",
        r"\dim L(\lambda) = \prod_{\alpha > 0} "
        r"\frac{\langle \lambda + \rho, \alpha^{\vee} \rangle}"
        r"{\langle \rho, \alpha^{\vee} \rangle}",
        r"[M(\lambda)] = \sum_{w \in W} (-1)^{\ell(w)}\, "
        r"P_{w_0 w, w_0}(1)\, [L(w \cdot \lambda)]",
        r"0 \to \bigoplus_{\ell(w)=k} M(w \cdot \lambda) \to \cdots "
        r"\to M(\lambda) \to L(\lambda) \to 0",
        r"XSYM \otimes ASYM \cong \bigoplus_{\nu} "
        r"c_{\lambda\mu}^{\nu}\, L(\nu)",
        r"\mathrm{Ind}_{P}^{G}\bigl(\sigma \otimes \tau\bigr) "
        r"= \mathrm{Ind}_{P}^{G} \sigma \,\boxtimes\, "
        r"\mathrm{Ind}_{P}^{G} \tau",
        r"R^{@I@}\Gamma\bigl(G/B, \mathcal{L}_{\lambda}\bigr) = "
        r"\begin{cases} L(\lambda)^{*} & i = 0,\ \lambda \text{ dominant} \\ "
        r"0 & i > 0 \end{cases}",
        r"H^{*}(\mathfrak{g}, XSYM) = \bigwedge\nolimits^{*} "
        r"\mathfrak{g}^{*} \otimes XSYM \big/ \operatorname{im} d",
        r"\sum_{\pi \in \widehat{G}} (\dim \pi)\, \chi_{\pi}(g) "
        r"= |G|\,\delta_{g, e}",
        r"L^2(G) \cong \widehat{\bigoplus_{\pi \in \widehat{G}}}\ "
        r"\pi \otimes \pi^{*}",
        r"D\text{-}\mathrm{mod}(G/B) \;\xrightarrow{\ \sim\ }\; "
        r"\mathcal{O}_{0}, \qquad \mathcal{M} \mapsto "
        r"\Gamma(G/B, \mathcal{M})",
        r"\mathcal{H}(G, K) \cong \mathbb{C}[X_{*}(T)]^{W} = "
        r"R(\widehat{G})",
        r"R^{G}_{T,\theta} = \frac{1}{|T^{F}|} \sum_{t \in T^{F}} "
        r"\theta(t)\, \operatorname{tr}\bigl(t \mid H^{*}_{c}(X)\bigr)",
        r"L(\mu) = \bigotimes_{i \ge 0} L(\mu_i)^{(p^{i})} "
        r"\qquad \text{(Steinberg tensor product)}",
        r"\sum_{\mu} \bigl(\dim M(\lambda)_{\mu} - \dim M(s_\alpha \cdot "
        r"\lambda)_{\mu}\bigr)\, e^{\mu} = \sum_{n \ge 1} "
        r"\operatorname{ch} M(\lambda - n\alpha)",
        r"P_{x,w}(q) = \sum_{i} \dim \mathcal{H}^{2i}_{x}\bigl("
        r"\mathrm{IC}_{w}\bigr)\, q^{i}",
        r"\langle \chi_{XSYM}, \chi_{ASYM} \rangle = "
        r"\frac{1}{|G|} \sum_{g \in G} \chi_{XSYM}(g)\, "
        r"\overline{\chi_{ASYM}(g)} = \delta_{XSYM, ASYM}",
        r"\Delta(R\text{-}\mathrm{matrix}) \colon XSYM \otimes ASYM "
        r"\xrightarrow{\ \sim\ } ASYM \otimes XSYM",
    ],
    msc=["20G05", "22E50", "17B10", "20C30", "22E46", "17B67", "20G42", "16G20"],
    adjacent=["math.NT", "math.AG", "math.QA"],
)
