"""math.SG - Symplectic Geometry.

Seeded from the geometry/topology research dossier and expanded into a broad
working vocabulary covering symplectic and contact geometry, Floer theory,
and the surrounding moduli problems.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

SG = SubfieldLexicon(
    code="math.SG",
    name="Symplectic Geometry",
    weight=5.0,
    banks={
        "objects": [
            "symplectic manifold",
            "symplectic form",
            "Lagrangian submanifold",
            "Lagrangian torus",
            "Legendrian submanifold",
            "Legendrian knot",
            "contact manifold",
            "contact structure",
            "Reeb vector field",
            "Reeb orbit",
            "Reeb chord",
            "Hamiltonian vector field",
            "Hamiltonian diffeomorphism",
            "symplectomorphism",
            "symplectic fibration",
            "Lefschetz fibration",
            "almost complex structure",
            "pseudoholomorphic curve",
            "pseudoholomorphic disc",
            "holomorphic strip",
            "Fukaya category",
            "Floer complex",
            "Floer homology",
            "Heegaard Floer homology",
            "embedded contact homology",
            "symplectic cohomology",
            "relative symplectic cohomology",
            "Floer persistence barcode",
            "moment map",
            "Liouville domain",
            "Weinstein domain",
            "Stein domain",
            "open book decomposition",
            "Lagrangian skeleton",
            "spectral invariant",
            "generating function",
            "capacity",
            "symplectic capacity",
            "Hamiltonian $S^1$-action",
            "toric variety",
            "polytope",
            "Calabi-Yau manifold",
            "displaceable subset",
        ],
        "props": [
            "symplectic",
            "Lagrangian",
            "Legendrian",
            "contact",
            "Hamiltonian",
            "exact",
            "monotone",
            "weakly monotone",
            "displaceable",
            "non-displaceable",
            "tight",
            "overtwisted",
            "fillable",
            "Weinstein",
            "Liouville",
            "Stein",
            "convex",
            "concave",
            "tamed",
            "compatible",
            "integrable",
            "completely integrable",
            "toric",
            "monotone Lagrangian",
            "embedded",
            "immersed",
            "displaceable by a Hamiltonian isotopy",
            "non-squeezable",
            "uniruled",
            "spherically monotone",
            "graded",
            "$\\mathbb{Z}$-graded",
            "unobstructed",
            "weakly unobstructed",
            "balanced",
            "rational",
            "subcritical",
            "flexible",
            "rigid",
        ],
        "spaces": [
            "symplectic manifold",
            "contact manifold",
            "Liouville domain",
            "Weinstein domain",
            "loop space",
            "free loop space",
            "moduli space of holomorphic discs",
            "moduli space of $J$-holomorphic curves",
            "the group of Hamiltonian diffeomorphisms",
            "the group of symplectomorphisms",
            "the Fukaya category",
            "the wrapped Fukaya category",
            "symplectic cohomology",
            "the symplectic mapping class group",
            "the Lagrangian Grassmannian",
            "the universal cover of $\\mathrm{Symp}$",
            "the space of compatible almost complex structures",
            "the Hofer metric space",
            "quantum cohomology",
        ],
        "maps": [
            "the moment map",
            "the Liouville flow",
            "the Reeb flow",
            "a Hamiltonian isotopy",
            "the Hamiltonian flow",
            "the symplectic reduction map",
            "the closed-open map",
            "the open-closed map",
            "the PSS isomorphism",
            "the continuation map",
            "the spectral invariant",
            "the Donaldson-Fukaya functor",
            "the Viterbo restriction map",
            "the Seidel representation",
            "the displacement energy",
        ],
        "invariants": [
            "Floer homology",
            "the symplectic cohomology",
            "the Gromov width",
            "the Hofer-Zehnder capacity",
            "the Ekeland-Hofer capacity",
            "the spectral invariant",
            "the Hofer norm",
            "the displacement energy",
            "the Maslov index",
            "the Conley-Zehnder index",
            "the Robbin-Salamon index",
            "the first Chern class",
            "the minimal Chern number",
            "the Gromov-Witten invariant",
            "the Seidel element",
            "the boundary depth",
            "the symplectic volume",
            "the action spectrum",
            "the mean Euler characteristic",
            "the ECH capacity",
            "the contact homology",
            "the self-linking number",
            "the Thurston-Bennequin invariant",
            "the rotation number",
            "the Lefschetz number",
        ],
        "namedResults": [
            "Gromov's non-squeezing theorem",
            "the Arnold conjecture",
            "the Arnol'd chord conjecture",
            "the Weinstein conjecture",
            "Gromov compactness",
            "the nearby Lagrangian conjecture",
            "Eliashberg's theorem",
            "the Conley-Zehnder theorem",
            "the Eliashberg--Gromov rigidity theorem",
            "Floer's theorem",
            "the homological mirror symmetry conjecture",
            "Donaldson's theorem",
            "the Hofer--Zehnder capacity bound",
            "the Gromov--Lees h-principle",
            "the Audin conjecture",
            "the Viterbo conjecture",
            "Kontsevich's formality theorem",
            "the Fukaya--Oh--Ohta--Ono machinery",
            "the symplectic camel theorem",
            "the Calabi--Yau equivalence",
            "the Lagrangian--Floer correspondence",
            "Polterovich's theorem",
            "Seidel's exact sequence",
            "the Biran--Cornea theorem",
            "the McDuff--Salamon classification",
        ],
        "methods": [
            "Floer-theoretic techniques",
            "the theory of pseudoholomorphic curves",
            "Gromov-Witten theory",
            "the h-principle",
            "symplectic reduction",
            "the method of generating functions",
            "Morse-Bott analysis",
            "neck stretching",
            "Lagrangian surgery",
            "the SFT compactness theorem",
            "a Hamiltonian perturbation argument",
            "spectral invariant estimates",
            "the bounding cochain formalism",
            "the closed-open map",
            "an energy quantization argument",
            "the analysis of moduli of discs",
            "a gluing construction",
            "persistence module techniques",
            "the theory of holomorphic curves",
            "a non-squeezing argument",
            "the polytope correspondence",
            "the Donaldson divisor technique",
            "the Biran decomposition",
            "an action-window filtration",
        ],
        "objectGloss": [
            "encodes the rigidity of Hamiltonian dynamics",
            "obstructs symplectic embeddings",
            "lies at the heart of mirror symmetry",
            "controls the Floer theory of the ambient manifold",
            "detects symplectic versus volume-preserving phenomena",
            "governs the count of pseudoholomorphic curves",
            "reflects the contact topology of the boundary",
            "is central to modern symplectic topology",
        ],
    },
    # Object-naming letters and forms only. No "J" (running almost complex
    # structure), no "H" (Hamiltonian function in equations), no "t" (flow time).
    symbols=[
        "M",
        "L",
        "\\omega",
        "\\Lambda",
        "X",
        "Y",
        "\\Sigma",
        "W",
        "V",
        "\\alpha",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"d\omega = 0",
        r"\omega^{n} \neq 0",
        r"\dim XSYM = 2n",
        r"\omega|_{ASYM} = 0",
        r"\iota_{X_H}\omega = dH",
        r"c_1(XSYM) = @N@\,[\omega]",
        r"\{F,G\} = \omega(X_F, X_G)",
        r"\mu(ASYM) = @N@",
        r"\mathrm{CZ}(\gamma) = @N@",
        r"c_{\mathrm{Gr}}(XSYM) = \pi r^{2}",
        r"e(ASYM) \le \|H\|_{1,\infty}",
        r"\dim HF^{@I@}(XSYM) = @N@",
        r"d_{\mathrm{Hofer}}(\phi,\mathrm{id}) > 0",
        r"\langle \mathrm{Floer} \rangle \cong H_{*}(ASYM)",
        r"\lambda \wedge (d\lambda)^{n} \neq 0",
        r"\xi = \ker\alpha",
        r"N_{XSYM} = \min\{c_1(A) > 0\}",
        r"\partial^{2} = 0",
        r"[\omega] \in H^{2}(XSYM;\mathbb{R})",
        r"\mathrm{tb}(ASYM) = -@N@",
        r"\int_{ASYM} \omega = @N@",
        r"\rho(\phi) \le \rho(\psi) + \rho(\phi\psi^{-1})",
        r"QH^{*}(XSYM) \cong H^{*}(XSYM) \otimes \Lambda",
        r"\dim H^{@I@}(XSYM) = b_{@I@}",
        r"\omega = d\lambda",
        r"\phi_{H}^{1}(ASYM) \cap ASYM = \varnothing",
        r"\#\,\mathrm{Fix}(\phi) \ge \dim H_{*}(XSYM)",
        r"\mathrm{vol}(XSYM,\omega) = \frac{1}{n!}\int_{XSYM}\omega^{n}",
        r"c_k(XSYM) \le c_{k+1}(XSYM)",
        r"\beta = e^{2\pi i \theta}",
        r"\mu_{\mathrm{Maslov}}(\partial u) = @N@",
        r"\langle \mathrm{ECH} \rangle_k = c_k",
        r"L(\phi) = \sum_i (-1)^{i}\,\mathrm{tr}\,\phi_{*}",
        r"r(\gamma) \in \mathbb{Q}/\mathbb{Z}",
        r"\omega_{\mathrm{std}} = \sum_{i} dx_i \wedge dy_i",
        r"a^{+}(H) - a^{-}(H) \ge 0",
    ],
    display_eqns=[
        r"B^{2n}(r) \hookrightarrow Z^{2n}(R) \ \Longrightarrow\ r \le R, "
        r"\qquad Z^{2n}(R) = B^{2}(R) \times \mathbb{R}^{2n-2}",
        r"HF_{*}(XSYM, \phi_{H}) \cong H_{*+n}(XSYM;\mathbb{Z})",
        r"\partial \langle x \rangle = \sum_{y}\ \#\,\mathcal{M}(x,y)\,\langle y \rangle, "
        r"\qquad \partial^{2} = 0",
        r"\#\,\mathrm{Fix}(\phi_{H}) \ \ge\ \sum_{i} \dim H_{i}(XSYM;\mathbb{Z}_2)",
        r"E(u) = \int_{\mathbb{R}\times S^{1}} \left|\partial_s u\right|^{2}\, ds\, dt "
        r"= \mathcal{A}_{H}(x^{-}) - \mathcal{A}_{H}(x^{+})",
        r"\mathcal{A}_{H}(x) = -\int_{D^{2}} \bar{x}^{*}\omega "
        r"+ \int_{0}^{1} H_{t}(x(t))\, dt",
        r"\mathrm{vol}(XSYM, \omega) = \frac{1}{n!}\int_{XSYM} \omega^{n}, "
        r"\qquad \dim XSYM = 2n",
        r"\bar\partial_{J} u = \tfrac{1}{2}\bigl(du + J \circ du \circ j\bigr) = 0",
        r"c_{\mathrm{HZ}}(XSYM) = \inf_{H}\bigl\{\, \max H - \min H \,\bigr\} "
        r"\quad\text{over admissible } H",
        r"0 \to QH^{*}(XSYM) \to SH^{*}(W) \to SH^{*}_{+}(W) \to 0",
        r"d_{\mathrm{Hofer}}(\phi, \psi) = \inf_{H}\int_{0}^{1} "
        r"\bigl(\max_{XSYM} H_t - \min_{XSYM} H_t\bigr)\, dt",
        r"QH^{*}(XSYM) \otimes \Lambda \cong "
        r"\bigoplus_{A \in H_2} H^{*}(XSYM)\, q^{A}",
        r"\dim \mathcal{M}(x,y) = \mu(x) - \mu(y) - 1",
        r"\mathrm{HF}^{*}(L_0, L_1) \cong \mathrm{Hom}_{\mathcal{F}(XSYM)}(L_0, L_1)",
        r"\sum_{\gamma} \frac{(-1)^{\mathrm{CZ}(\gamma)}}{\kappa(\gamma)}\, "
        r"t^{\mathcal{A}(\gamma)} = \chi_{\mathrm{mean}}(XSYM)",
        r"c_1(TXSYM) = @N@\,[\omega], \qquad N_{XSYM} = \frac{@N@}{\gcd(\dots)}",
        r"\int_{XSYM} e^{\omega}\, \mathrm{Td}(XSYM) "
        r"= \sum_{k\ge 0} \frac{1}{k!}\int_{XSYM}\omega^{k}\,\mathrm{Td}_{n-k}",
        r"\mathcal{A}_{H}\bigl(\phi_{H}^{1}(L)\bigr) - \mathcal{A}_{H}(L) "
        r"\le \int_{0}^{1}\!\!\max_{XSYM}\bigl(-\partial_t H_t\bigr)\, dt",
    ],
    msc=["53D05", "53D35", "53D40", "53D12", "53D42", "57R17", "37J05", "53D45"],
    adjacent=["math.GT", "math.DG"],
)
