"""math.SP - Spectral Theory.

Seed from the build spec, expanded with the arXiv analysis dossier (SP/MP/AP
cluster) into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

SP = SubfieldLexicon(
    code="math.SP",
    name="Spectral Theory",
    weight=4.0,
    banks={
        "objects": [
            "Schrödinger operator",
            "Laplacian",
            "Robin Laplacian",
            "Dirichlet Laplacian",
            "Neumann Laplacian",
            "magnetic Schrödinger operator",
            "Dirac operator",
            "Dirac system",
            "Sturm--Liouville operator",
            "Jacobi matrix",
            "CMV matrix",
            "almost Mathieu operator",
            "discrete Schrödinger operator",
            "random Schrödinger operator",
            "Anderson model",
            "quantum graph",
            "metric graph",
            "Steklov problem",
            "eigenvalue",
            "eigenfunction",
            "resolvent",
            "spectral measure",
            "spectral projection",
            "scattering matrix",
            "transfer operator",
            "Weyl function",
            "Titchmarsh--Weyl $m$-function",
            "Friedrichs extension",
            "self-adjoint extension",
            "spectral gap",
            "essential spectrum",
            "discrete spectrum",
            "absolutely continuous spectrum",
            "singular continuous spectrum",
            "point spectrum",
            "Weyl sequence",
            "heat kernel",
            "Green function",
            "boundary triple",
            "Krein--von Neumann extension",
            "Schatten-class perturbation",
            "Birman--Schwinger operator",
        ],
        "props": [
            "self-adjoint",
            "essentially self-adjoint",
            "lower semibounded",
            "non-self-adjoint",
            "positive",
            "non-negative",
            "elliptic",
            "hypoelliptic",
            "semiclassical",
            "magnetic",
            "periodic",
            "quasi-periodic",
            "almost periodic",
            "ergodic",
            "random",
            "discrete",
            "continuous",
            "absolutely continuous",
            "singular continuous",
            "purely point",
            "trace-class",
            "Schatten-class",
            "relatively compact",
            "relatively bounded",
            "gapped",
            "simple",
            "degenerate",
            "subcritical",
            "supercritical",
            "critical",
            "compactly supported",
            "rotationally symmetric",
            "uniformly elliptic",
            "weakly coupled",
            "long-range",
            "short-range",
            "anisotropic",
            "localized",
            "delocalized",
        ],
        "spaces": [
            "Hilbert space",
            "$L^2(\\Omega)$",
            "$L^2(\\mathbb{R}^d)$",
            "Sobolev space",
            "form domain",
            "operator domain",
            "the spectrum",
            "the essential spectrum",
            "the resolvent set",
            "the deficiency space",
            "the spectral subspace",
            "the kernel",
            "the range",
            "the numerical range",
            "the deficiency index",
            "the spectral manifold",
            "the trace ideal",
            "the Krein space",
            "the de Branges space",
            "the boundary space",
        ],
        "maps": [
            "the resolvent",
            "the spectral projection",
            "the heat semigroup",
            "the scattering operator",
            "the Birman--Schwinger operator",
            "the transfer matrix",
            "the Weyl $m$-function",
            "the Dirichlet-to-Neumann map",
            "the wave operator",
            "the Cayley transform",
            "the spectral shift function",
            "the trace map",
            "the unitary propagator",
            "the boundary map",
            "the spectral flow",
        ],
        "invariants": [
            "eigenvalue",
            "ground-state energy",
            "spectral gap",
            "spectral radius",
            "essential spectrum",
            "spectral multiplicity",
            "deficiency index",
            "Morse index",
            "eigenvalue counting function",
            "spectral shift function",
            "Lyapunov exponent",
            "integrated density of states",
            "Weyl asymptotics",
            "Cwikel--Lieb--Rozenblum bound",
            "Lieb--Thirring constant",
            "trace of the resolvent",
            "heat trace",
            "spectral determinant",
            "scattering phase",
            "spectral measure",
            "transmission coefficient",
            "fundamental gap",
            "nodal count",
            "Robin parameter",
            "coupling constant",
        ],
        "namedResults": [
            "the spectral theorem",
            "the Weyl law",
            "Weyl's asymptotic formula",
            "the min--max principle",
            "the Courant nodal domain theorem",
            "the Cwikel--Lieb--Rozenblum bound",
            "the Lieb--Thirring inequality",
            "the Faber--Krahn inequality",
            "the Ambarzumian theorem",
            "the Borg--Marchenko theorem",
            "Krein's trace formula",
            "Krein's resolvent formula",
            "the Birman--Schwinger principle",
            "the Kato--Rellich theorem",
            "the RAGE theorem",
            "the Aizenman--Molchanov method",
            "Anderson localization",
            "the Thouless formula",
            "the Ishii--Pastur theorem",
            "the Hardy inequality",
            "the Berezin--Li--Yau inequality",
            "the Payne--Pólya--Weinberger inequality",
            "the fundamental gap theorem",
            "the Mourre estimate",
            "the limiting absorption principle",
        ],
        "methods": [
            "the min--max principle",
            "variational methods",
            "the Birman--Schwinger principle",
            "trace formulas",
            "semiclassical analysis",
            "microlocal analysis",
            "the limiting absorption principle",
            "Mourre theory",
            "commutator methods",
            "perturbation theory",
            "the method of boundary triples",
            "the transfer matrix method",
            "subordinacy theory",
            "the multiscale analysis",
            "the fractional moment method",
            "resolvent estimates",
            "the heat kernel expansion",
            "inverse spectral methods",
            "Weyl asymptotics",
            "spectral shift analysis",
            "an analysis of the associated quadratic form",
            "scattering theory",
            "a Mourre estimate",
            "the Aizenman--Molchanov method",
        ],
        "objectGloss": [
            "encodes the quantum dynamics of the system",
            "governs the spectrum of the underlying operator",
            "arises naturally in semiclassical analysis",
            "controls the long-time behavior of the propagator",
            "is central to the inverse spectral problem",
            "reflects the geometry of the underlying domain",
            "determines the asymptotic distribution of eigenvalues",
            "lies at the heart of scattering theory",
        ],
    },
    # Object-naming letters only. No "n", "k", "j" (running indices in
    # \lambda_k, \sum_n) and no "t" (the time variable in e^{itH}).
    symbols=[
        "H",
        "L",
        "A",
        "T",
        "D",
        "P",
        "R",
        "G",
        "M",
        "\\Delta",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"XSYM \psi = \lambda \psi",
        r"\sigma(XSYM) = [0,\infty)",
        r"\sigma_{\mathrm{ess}}(XSYM) = [0,\infty)",
        r"\lambda_1 < \lambda_2 \le \lambda_3 \le \cdots",
        r"N(\lambda) \sim C_d \,\lambda^{d/2}",
        r"\lVert (XSYM - z)^{-1} \rVert = \mathrm{dist}(z,\sigma(XSYM))^{-1}",
        r"\langle XSYM \psi, \psi \rangle \ge 0",
        r"XSYM = XSYM^{*}",
        r"\operatorname{tr}\, e^{-t XSYM} < \infty",
        r"\dim \ker(XSYM - \lambda) = @N@",
        r"\lambda_{@K@}(XSYM) \le \lambda_{@K@}(ASYM)",
        r"\mathrm{ind}_{\pm}(XSYM) = @R@",
        r"\sigma_{\mathrm{ac}}(XSYM) = \varnothing",
        r"\gamma(E) = \lim_{n\to\infty}\tfrac{1}{n}\log\lVert T_n\rVert",
        r"\inf \sigma(XSYM) = -\Lambda",
        r"\#\{\lambda_j < 0\} \le C \int V_-^{d/2}\,dx",
        r"XSYM \ge -ASYM - C",
        r"\lambda_2 - \lambda_1 \ge \frac{3\pi^2}{d^2}",
        r"\zeta_{XSYM}(s) = \sum_j \lambda_j^{-s}",
        r"m(z) = \frac{\psi'(0,z)}{\psi(0,z)}",
        r"e^{-itXSYM}\psi_0 \rightharpoonup 0",
        r"\mathbb{E}\,N(\lambda) = \int k(\lambda)\,dx",
        r"\det{}_2(I + XSYM) \neq 0",
        r"S(\lambda) = I - 2\pi i\, T(\lambda)",
        r"\lambda_1(\Omega) \ge \lambda_1(\Omega^{*})",
        r"\sigma(XSYM) \subset [m, M]",
        r"\lVert XSYM \psi \rVert^2 = \int \lambda^2 \, d\mu_\psi(\lambda)",
        r"n_+(XSYM) = n_-(XSYM)",
        r"\operatorname{tr}(XSYM - ASYM) = \int \xi(\lambda)\,d\lambda",
        r"\mu_{\mathrm{ess}}(XSYM) = @N@",
        r"R(z) = (XSYM - z)^{-1}",
        r"\lambda_j \asymp j^{2/d}",
        r"V(x) \to 0 \ \text{as}\ |x|\to\infty",
    ],
    display_eqns=[
        r"N(\lambda) = \#\{\, j : \lambda_j \le \lambda \,\} "
        r"= \frac{\omega_d}{(2\pi)^d}\,|\Omega|\,\lambda^{d/2} + o\!\left(\lambda^{d/2}\right)",
        r"XSYM = \int_{\sigma(XSYM)} \lambda \, dE(\lambda), \qquad XSYM = XSYM^{*}",
        r"\lambda_k(XSYM) = \min_{\dim V = k}\ \max_{0 \neq \psi \in V} "
        r"\frac{\langle XSYM \psi, \psi\rangle}{\langle \psi, \psi\rangle}",
        r"\sum_{\lambda_j < 0} |\lambda_j|^{\gamma} \le L_{\gamma,d} "
        r"\int_{\mathbb{R}^d} V_-(x)^{\gamma + d/2}\,dx",
        r"\#\{\,\lambda_j(XSYM) < 0\,\} \le C_d \int_{\mathbb{R}^d} V_-(x)^{d/2}\,dx",
        r"(XSYM - z)^{-1} = (ASYM - z)^{-1} - (ASYM - z)^{-1} W (XSYM - z)^{-1}",
        r"\operatorname{tr}\bigl(f(XSYM) - f(ASYM)\bigr) "
        r"= \int_{\mathbb{R}} f'(\lambda)\,\xi(\lambda)\,d\lambda",
        r"\operatorname{tr}\, e^{-t XSYM} = (4\pi t)^{-d/2}\!\left(|\Omega| "
        r"- \tfrac{\sqrt{\pi t}}{2}\,|\partial\Omega| + O(t)\right)",
        r"\frac{1}{k}\sum_{j=1}^{k} \lambda_j \ge \frac{d}{d+2}\,"
        r"\frac{4\pi^2}{(\omega_d |\Omega|)^{2/d}}\, k^{2/d}",
        r"-\psi'' + V(x)\,\psi = \lambda\,\psi, \qquad x \in \mathbb{R}",
        r"\gamma(E) = \lim_{n\to\infty} \frac{1}{n}\,\log \left\lVert "
        r"\prod_{j=1}^{n} \begin{pmatrix} E - V_j & -1 \\ 1 & 0 \end{pmatrix}\right\rVert",
        r"\gamma(E) = \int_{\mathbb{R}} \log|E - \lambda|\, dk(\lambda) - \log b",
        r"\lambda_1(\Omega) \ge \lambda_1(\Omega^{*}), \qquad "
        r"|\Omega| = |\Omega^{*}|,\ \Omega^{*}\ \text{a ball}",
        r"H = -\Delta + V, \qquad \mathcal{D}(H) = H^2(\mathbb{R}^d) \cap \mathcal{D}(V)",
        r"\lim_{\varepsilon \downarrow 0} \langle (XSYM - \lambda - i\varepsilon)^{-1} f, g\rangle "
        r"\ \text{exists for}\ \lambda \in I",
        r"i\,\frac{d}{dt}\,\psi(t) = XSYM\,\psi(t), \qquad \psi(t) = e^{-it XSYM}\psi_0",
        r"E[\varphi] = i\langle XSYM \varphi, \varphi\rangle "
        r"\ge \theta\,\langle \varphi,\varphi\rangle - K\,\lVert C\varphi\rVert^2",
        r"S(\lambda) = I - 2\pi i\, \delta(XSYM - \lambda)\, V "
        r"\,\bigl(I + (ASYM - \lambda - i0)^{-1} V\bigr)^{-1}",
    ],
    msc=["35P15", "35P20", "47A10", "47B36", "81Q10", "34L40", "34L20", "58J50"],
    adjacent=["math-ph", "math.AP"],
)
