"""math.ST - Statistics Theory.

Seed from the build spec, expanded with the discrete/probability/applied
research dossier into a broad working vocabulary.
"""

from __future__ import annotations

from ..schema import SubfieldLexicon

ST = SubfieldLexicon(
    code="math.ST",
    name="Statistics Theory",
    weight=4.0,
    banks={
        "objects": [
            "estimator",
            "history estimator",
            "score-function estimator",
            "maximum likelihood estimator",
            "$M$-estimator",
            "minimax estimator",
            "Bayes estimator",
            "shrinkage estimator",
            "posterior distribution",
            "shrinkage prior",
            "Dirichlet process",
            "stick-breaking prior",
            "credible set",
            "confidence set",
            "confidence band",
            "confidence sequence",
            "e-process",
            "test statistic",
            "likelihood ratio",
            "empirical process",
            "empirical measure",
            "reproducing kernel Hilbert space",
            "Gaussian sequence model",
            "regression function",
            "density",
            "high-dimensional model",
            "sparse vector",
            "covariance matrix",
            "precision matrix",
            "graphical model",
            "loss function",
            "risk function",
            "sufficient statistic",
            "kernel estimator",
            "U-statistic",
            "histogram estimator",
            "wavelet estimator",
            "spectral estimator",
            "plug-in estimator",
            "Hawkes intensity",
        ],
        "props": [
            "minimax",
            "adaptive",
            "high-dimensional",
            "low-dimensional",
            "sparse",
            "Gaussian",
            "sub-Gaussian",
            "nonparametric",
            "semiparametric",
            "parametric",
            "Bayesian",
            "consistent",
            "asymptotically normal",
            "asymptotically efficient",
            "unbiased",
            "admissible",
            "inadmissible",
            "identifiable",
            "regular",
            "anytime-valid",
            "distributionally robust",
            "differentially private",
            "conformal",
            "well-specified",
            "misspecified",
            "rate-optimal",
            "honest",
            "uniformly valid",
            "asymptotically optimal",
            "locally asymptotically normal",
            "uniformly consistent",
            "exchangeable",
            "heteroscedastic",
            "smooth",
            "low-rank",
            "calibrated",
            "Fisher-consistent",
            "data-adaptive",
            "oracle-efficient",
        ],
        "spaces": [
            "parameter space",
            "sample space",
            "model class",
            "Sobolev ball",
            "Holder ball",
            "Besov space",
            "reproducing kernel Hilbert space",
            "space of densities",
            "nonparametric class",
            "Wasserstein space",
            "space of distributions",
            "tangent space",
            "sieve space",
            "function class of bounded variation",
            "hypothesis class",
            "covering net",
            "local neighborhood",
            "Gaussian sequence space",
            "space of priors",
            "support of the prior",
        ],
        "maps": [
            "the empirical risk functional",
            "the score function",
            "the influence function",
            "the likelihood map",
            "the posterior map",
            "the soft-thresholding operator",
            "the projection estimator",
            "the kernel smoother",
            "the link function",
            "the loss functional",
            "the estimating equation",
            "the conditional density operator",
            "the prior-to-posterior update",
            "the empirical measure map",
            "the plug-in functional",
        ],
        "invariants": [
            "minimax risk",
            "minimax rate",
            "convergence rate",
            "estimation error",
            "Fisher information",
            "bias",
            "variance",
            "mean squared error",
            "excess risk",
            "regret",
            "effective dimension",
            "metric entropy",
            "covering number",
            "critical radius",
            "separation rate",
            "posterior contraction rate",
            "coverage probability",
            "type I error",
            "type II error",
            "asymptotic variance",
            "efficiency bound",
            "sparsity level",
            "signal strength",
            "Le Cam distance",
            "Hellinger distance",
        ],
        "namedResults": [
            "the Cramer--Rao bound",
            "the Le Cam equivalence",
            "the Hajek--Le Cam theorem",
            "the Bernstein--von Mises theorem",
            "the Fano inequality",
            "the Assouad lemma",
            "the Stein paradox",
            "the James--Stein theorem",
            "the Behrens--Fisher problem",
            "the Donoho--Johnstone theorem",
            "the Tsybakov margin condition",
            "the Birge--Massart bound",
            "the Glivenko--Cantelli theorem",
            "the Dvoretzky--Kiefer--Wolfowitz inequality",
            "the Neyman--Pearson lemma",
            "the Wilks theorem",
            "the Chernoff theorem",
            "the de Finetti reduction",
            "the Ghosal--van der Vaart theorem",
            "the Pinsker theorem",
            "the Le Cam two-point method",
            "the Rao--Blackwell theorem",
            "the Lehmann--Scheffe theorem",
            "the Hodges--Le Cam bound",
            "the van Trees inequality",
        ],
        "methods": [
            "the minimax framework",
            "Le Cam's two-point method",
            "the Assouad cube argument",
            "Fano's method",
            "empirical process theory",
            "the chaining method",
            "the peeling argument",
            "concentration of measure",
            "the sieve method",
            "penalized estimation",
            "the bootstrap",
            "cross-validation",
            "the EM algorithm",
            "the plug-in principle",
            "posterior contraction analysis",
            "the local asymptotic normality framework",
            "the influence function expansion",
            "Stein's unbiased risk estimate",
            "model selection by penalization",
            "the oracle inequality method",
            "the testing-to-estimation reduction",
            "a moment matching argument",
            "the spectral method",
            "an information-theoretic lower bound",
        ],
        "objectGloss": [
            "attains the optimal minimax rate of convergence",
            "characterizes the fundamental limits of estimation",
            "encodes the information geometry of the model",
            "controls the bias-variance trade-off",
            "lies at the heart of nonparametric inference",
            "reflects the effective dimension of the problem",
            "governs the contraction of the posterior",
            "links estimation accuracy to sample complexity",
        ],
    },
    # Object-naming letters only. Hats name estimators, "T" tests; avoid "n"
    # (sample size), "p" (dimension/p-value), "i" (running index).
    symbols=[
        "\\hat\\theta",
        "T",
        "\\hat f",
        "\\hat\\mu",
        "\\Sigma",
        "\\Pi",
        "Q",
        "R",
        "\\hat F",
        "\\Psi",
    ],
    # Tokens @K@ @I@ @N@ @P@ @R@ @C@ are randomized per draw, so the same
    # template reads differently from paper to paper.
    inline_eqns=[
        r"R(XSYM, \theta) = \mathbb{E}_\theta\,\|XSYM - \theta\|^{2}",
        r"\inf_{XSYM} \sup_{\theta} R(XSYM, \theta) \asymp n^{-2\beta/(2\beta+1)}",
        r"\operatorname{Var}_\theta(XSYM) \ge \frac{1}{n\, I(\theta)}",
        r"\sqrt{n}\,(XSYM - \theta_0) \xrightarrow{d} N\!\left(0,\, I^{-1}\right)",
        r"\mathbb{P}_\theta\bigl(\theta \in C_n\bigr) \ge 1 - \alpha",
        r"\|XSYM - \theta_0\| = O_P\!\left(\sqrt{\tfrac{@K@ \log d}{n}}\right)",
        r"\Pi\bigl(\|\theta - \theta_0\| > M \varepsilon_n \mid Y\bigr) \to 0",
        r"\mathbb{E}\,\|XSYM - f\|_2^{2} \lesssim n^{-2\beta/(2\beta+1)}",
        r"\log N(\varepsilon, \mathcal{F}) \asymp \varepsilon^{-1/\beta}",
        r"\mathbb{P}\bigl(\text{reject } H_0 \mid H_0\bigr) \le \alpha",
        r"\mathrm{MSE}(XSYM) = \mathrm{Bias}^{2} + \operatorname{Var}",
        r"\widehat{\mathrm{Regret}}_T = O\!\left(\sqrt{T}\right)",
        r"\|\hat\Sigma - \Sigma\|_{\mathrm{op}} \lesssim \sqrt{\tfrac{@K@}{n}}",
        r"d_H^{2}(\theta, \theta') \ge c\, \|\theta - \theta'\|^{2}",
        r"\sup_x \bigl| XSYM(x) - F(x) \bigr| = O_P\!\left(n^{-1/2}\right)",
        r"\varepsilon_n \asymp \sqrt{\tfrac{\log n}{n}}",
        r"r_n^{\star} \asymp \left(\tfrac{\log d}{n}\right)^{1/2}",
        r"\mathbb{E}_\theta\,[XSYM] = \theta + b_n(\theta)",
        r"\lambda \asymp \sqrt{\tfrac{2 \log d}{n}}",
        r"s_n^{2} = \tfrac{1}{n}\sum_i (Y_i - \bar Y)^{2}",
        r"\mathbb{P}\bigl(|XSYM - \theta| > t\bigr) \le 2 e^{-n t^{2}/2}",
        r"\inf_{XSYM} \sup_{\theta} \mathbb{P}_\theta\bigl(XSYM \neq \theta\bigr) "
        r"\ge \tfrac{1}{2}",
        r"\mathrm{Cov}\bigl(\sqrt{n}\,XSYM\bigr) \to I(\theta_0)^{-1}",
        r"\widehat{\mathrm{SURE}}(XSYM) = \|Y - XSYM\|^{2} - n + 2\,\mathrm{df}",
        r"\Pi(B \mid Y) \propto \int_B e^{\ell_n(\theta)}\, d\Pi(\theta)",
        r"\mathrm{KL}(P_\theta \,\|\, P_{\theta'}) \le @C@\, \|\theta - \theta'\|^{2}",
        r"\sqrt{n}\,(T_n - \mu) \xrightarrow{d} N(0,\, \sigma^{2})",
        r"\mathrm{rate} = n^{-1/3} \quad (\text{isotonic})",
        r"\hat s = \|\theta_0\|_0 \le @K@",
        r"\mathbb{E}\,[\ell(XSYM)] - \ell^{\star} \lesssim \tfrac{@K@}{n}",
    ],
    display_eqns=[
        r"\inf_{XSYM} \sup_{\theta \in \Theta} "
        r"\mathbb{E}_\theta\, \|XSYM - \theta\|^{2} "
        r"\asymp n^{-\frac{2\beta}{2\beta + 1}}",
        r"\operatorname{Var}_\theta(XSYM) "
        r"\ge \frac{\bigl(\psi'(\theta)\bigr)^{2}}{n\, I(\theta)}, "
        r"\qquad I(\theta) = \mathbb{E}_\theta\!\left[\bigl(\partial_\theta "
        r"\log p_\theta\bigr)^{2}\right]",
        r"\sqrt{n}\,\bigl(XSYM_n - \theta_0\bigr) "
        r"\xrightarrow{d} N\!\left(0,\, I(\theta_0)^{-1}\right)",
        r"\Pi\!\left(\theta : d(\theta, \theta_0) > M \varepsilon_n "
        r"\,\middle|\, Y_{1:n}\right) \xrightarrow{P_{\theta_0}} 0, "
        r"\qquad n \varepsilon_n^{2} \to \infty",
        r"\inf_{XSYM} \sup_{\theta} \mathbb{P}_\theta\bigl(XSYM \neq \theta\bigr) "
        r"\ge 1 - \frac{I(\theta_1; \theta_2) + \log 2}{\log M}",
        r"\sup_{P \in \mathcal{P}} \Bigl| \mathbb{E}_P\, XSYM "
        r"- \mathbb{E}_P\, f \Bigr| \le \frac{C}{\sqrt{n}}",
        r"R(XSYM_{JS}, \theta) = d - \mathbb{E}_\theta\!\left[\frac{(d-2)^{2}}"
        r"{\|Y\|^{2}}\right] < d = R(Y, \theta)",
        r"\mathbb{E}\,\|XSYM - f_0\|_2^{2} "
        r"\le C \inf_{f} \left\{ \|f - f_0\|_2^{2} "
        r"+ \frac{\dim(f)\,\sigma^{2}}{n} \right\}",
        r"\mathbb{P}_{\theta_0}\!\left(\sup_{\theta} "
        r"2\bigl(\ell_n(\theta) - \ell_n(\theta_0)\bigr) > t\right) "
        r"\to \mathbb{P}\bigl(\chi^{2}_{d} > t\bigr)",
        r"\bigl\| \Pi(\cdot \mid Y) - N\!\left(\hat\theta, "
        r"(n I(\theta_0))^{-1}\right) \bigr\|_{TV} \xrightarrow{P} 0",
        r"\hat\theta_\lambda = \arg\min_\theta \left\{ \frac{1}{2n} "
        r"\|Y - X\theta\|_2^{2} + \lambda \|\theta\|_1 \right\}",
        r"\|\hat\theta_\lambda - \theta_0\|_2 "
        r"\lesssim \frac{\sigma}{\kappa}\sqrt{\frac{s \log d}{n}} "
        r"\quad \text{w.h.p.}",
        r"R^{\star}(\Theta) \ge \frac{1}{2}\max_{\theta, \theta'} "
        r"d(\theta, \theta')\,\bigl(1 - \mathrm{TV}(P_\theta, P_{\theta'})\bigr)",
        r"\log N\bigl(\varepsilon, \mathcal{F}, \|\cdot\|\bigr) "
        r"\le C\, \varepsilon^{-1/\beta}, "
        r"\qquad \varepsilon_n \asymp n^{-\frac{\beta}{2\beta+1}}",
        r"\mathbb{E}\!\left[\sup_{f \in \mathcal{F}} "
        r"\bigl(P_n - P\bigr) f\right] "
        r"\le \frac{C}{\sqrt{n}} \int_0^{D} "
        r"\sqrt{\log N(\varepsilon, \mathcal{F})}\, d\varepsilon",
        r"\mathrm{MSE}(XSYM) = \underbrace{\bigl(\mathbb{E}\,XSYM "
        r"- \theta\bigr)^{2}}_{\text{bias}^{2}} "
        r"+ \underbrace{\operatorname{Var}(XSYM)}_{\text{variance}}",
        r"\Pi_n(A) = \frac{\int_A \prod_{i=1}^{n} p_\theta(Y_i)\, d\Pi(\theta)}"
        r"{\int_\Theta \prod_{i=1}^{n} p_\theta(Y_i)\, d\Pi(\theta)}",
        r"\sup_{x}\, \bigl| XSYM(x) - F(x) \bigr| "
        r"\xrightarrow{d} \sup_{t \in [0,1]} |\mathbb{B}(t)|, "
        r"\qquad \mathbb{B} \text{ a Brownian bridge}",
    ],
    msc=["62G05", "62G20", "62C20", "62F12", "62G08", "62H12", "62F15", "62G10"],
    adjacent=["math.PR", "stat.ML"],
)
