"""Cross-field banks: names, journals, funding, institutions, and prose glue.

These read naturally in any subfield and supply author lists, eponyms, cited
results, bibliographies, and the connective tissue of proofs.
"""

from __future__ import annotations

# Surnames, historical and modern; adjacent ones pair into compound eponyms.
SURNAMES: tuple[str, ...] = (
    "Euler",
    "Gauss",
    "Riemann",
    "Hilbert",
    "Noether",
    "Galois",
    "Abel",
    "Jacobi",
    "Poincaré",
    "Cartan",
    "Weyl",
    "Hodge",
    "Serre",
    "Grothendieck",
    "Deligne",
    "Mumford",
    "Atiyah",
    "Singer",
    "Milnor",
    "Thurston",
    "Gromov",
    "Donaldson",
    "Hamilton",
    "Perelman",
    "Tao",
    "Bourgain",
    "Furstenberg",
    "Erdős",
    "Szemerédi",
    "Bombieri",
    "Selberg",
    "Iwasawa",
    "Tate",
    "Langlands",
    "Shimura",
    "Wiles",
    "Mazur",
    "Faltings",
    "Bridgeland",
    "Kontsevich",
    "Manin",
    "Beilinson",
    "Drinfeld",
    "Lurie",
    "Voevodsky",
    "Scholze",
    "Bhargava",
    "Venkatesh",
    "Maynard",
    "Zhang",
    "Calabi",
    "Yau",
    "Kähler",
    "Ricci",
    "Chern",
    "Weil",
    "Dirichlet",
    "Dedekind",
    "Kummer",
    "Hecke",
    "Maass",
    "Ramanujan",
    "Hardy",
    "Littlewood",
    "Vinogradov",
    "Sarnak",
    "Katz",
    "Rudnick",
    "Montgomery",
    "Dyson",
    "Wigner",
    "Kolmogorov",
    "Doob",
    "Itô",
    "Lévy",
    "Feller",
    "Harris",
    "Stanley",
    "Macdonald",
    "Schur",
    "Bruhat",
    "Tits",
    "Coxeter",
    "Lusztig",
    "Kazhdan",
    "Springer",
    "Borel",
    "Harish-Chandra",
    "Vogan",
    "Arthur",
    "Bernstein",
    "Gelfand",
    "Kirillov",
    "Bump",
    "Banach",
    "Hahn",
    "Sobolev",
    "Calderón",
    "Zygmund",
    "Stein",
    "Fefferman",
    "Nirenberg",
    "Caffarelli",
    "Moser",
    "Nash",
    "Bogomolov",
    "Mori",
    "Kollár",
    "Kawamata",
    "Fano",
    "Castelnuovo",
    "Enriques",
    "Zariski",
    "Krull",
    "Cohen",
    "Macaulay",
    "Auslander",
    "Eisenbud",
    "Bass",
    "Tschinkel",
    "Sturmfels",
    # A broad international pool. Eponyms and authors need variety, and most
    # named results in real papers carry ordinary, non-celebrity surnames.
    "Anderson",
    "Bennett",
    "Brooks",
    "Carter",
    "Coleman",
    "Dawson",
    "Edwards",
    "Fletcher",
    "Foster",
    "Gardner",
    "Hayes",
    "Holland",
    "Jennings",
    "Lambert",
    "Mercer",
    "Newton",
    "Osborne",
    "Parker",
    "Quinn",
    "Reeves",
    "Sanders",
    "Sutton",
    "Vaughan",
    "Whitaker",
    "Abramov",
    "Belov",
    "Egorov",
    "Frolov",
    "Karpov",
    "Lebedev",
    "Morozov",
    "Orlov",
    "Sokolov",
    "Voronin",
    "Andersson",
    "Bergström",
    "Lindqvist",
    "Nyström",
    "Sundberg",
    "Halvorsen",
    "Bakker",
    "Visser",
    "Janssen",
    "Müller",
    "Bauer",
    "Hofmann",
    "Vogel",
    "Werner",
    "Brandt",
    "Lefèvre",
    "Moreau",
    "Girard",
    "Faure",
    "Bianchi",
    "Greco",
    "Marino",
    "Costa",
    "Ferrari",
    "Romano",
    "Esposito",
    "Nowak",
    "Wójcik",
    "Kaminski",
    "Zielinski",
    "Novák",
    "Horák",
    "Varga",
    "Tóth",
    "Nagy",
    "García",
    "Fernández",
    "Rodríguez",
    "Navarro",
    "Vidal",
    "Castro",
    "Mendes",
    "Pereira",
    "Cardoso",
    "Demir",
    "Yilmaz",
    "Aydin",
    "Kaya",
    "Haddad",
    "Nasser",
    "Rahimi",
    "Karimi",
    "Farouk",
    "Sharma",
    "Iyer",
    "Nair",
    "Reddy",
    "Banerjee",
    "Chatterjee",
    "Ghosh",
    "Rao",
    "Khan",
    "Patel",
    "Mehta",
    "Tanaka",
    "Nakamura",
    "Watanabe",
    "Kobayashi",
    "Fujimoto",
    "Okamoto",
    "Chen",
    "Huang",
    "Zhao",
    "Sun",
    "Xu",
    "Lin",
    "Park",
    "Choi",
    "Jeong",
    "Kang",
    "Yoon",
    "Okafor",
    "Mensah",
    "Diallo",
    "Traoré",
    "Mwangi",
    "Abebe",
    "Botha",
    "Okeke",
    "Santos",
    "Silva",
    "Vega",
    "Marsh",
    "Whitlock",
    "Pearson",
    "Schmidt",
    "Keller",
    "Lang",
    # Further international surnames for authors and eponyms.
    "Adams",
    "Armstrong",
    "Baker",
    "Barnes",
    "Bishop",
    "Bradley",
    "Burton",
    "Chapman",
    "Clarke",
    "Cole",
    "Cross",
    "Day",
    "Dixon",
    "Ellis",
    "Ford",
    "Graham",
    "Gray",
    "Harvey",
    "Hill",
    "Hunt",
    "Jordan",
    "Knight",
    "Lowe",
    "Marshall",
    "Mason",
    "Nash",
    "Owen",
    "Page",
    "Payne",
    "Pope",
    "Reid",
    "Rhodes",
    "Rose",
    "Shaw",
    "Stone",
    "Wade",
    "Ward",
    "Webb",
    "Wells",
    "West",
    "Wood",
    "Young",
    "Bergmann",
    "Fischer",
    "Klein",
    "Krause",
    "Lehmann",
    "Neumann",
    "Richter",
    "Schäfer",
    "Schulz",
    "Wagner",
    "Weber",
    "Zimmermann",
    "Albrecht",
    "Dubois",
    "Fontaine",
    "Garnier",
    "Henry",
    "Leroy",
    "Marchand",
    "Renard",
    "Roche",
    "Roux",
    "Conti",
    "Fabbri",
    "Galli",
    "Gentile",
    "Longo",
    "Rizzo",
    "Serra",
    "Villa",
    "Blanco",
    "Cabrera",
    "Delgado",
    "Iglesias",
    "Molina",
    "Ortega",
    "Reyes",
    "Suárez",
    "Vargas",
    "Almeida",
    "Barbosa",
    "Carvalho",
    "Lima",
    "Macedo",
    "Pinto",
    "Ribeiro",
    "Teixeira",
    "Dvořák",
    "Kovač",
    "Marković",
    "Petrov",
    "Popescu",
    "Ionescu",
    "Kowalczyk",
    "Lewandowski",
    "Mazur",
    "Szabó",
    "Kiss",
    "Virtanen",
    "Korhonen",
    "Lindgren",
    "Johansson",
    "Larsen",
    "Dahl",
    "Eriksen",
    "Aalto",
    "Okonkwo",
    "Adeyemi",
    "Nkemelu",
    "Dube",
    "Mokoena",
    "Sithole",
    "Achterberg",
    "DeVries",
    "Vermeulen",
    "Tanaka",
    "Saitō",
    "Yoshida",
    "Matsumoto",
    "Inoue",
    "Hashimoto",
    "Ishikawa",
    "Wang",
    "Liu",
    "Yang",
    "Wu",
    "Zhou",
    "Tang",
    "Feng",
    "Cao",
    "Deng",
    "Kim",
    "Lee",
    "Jang",
    "Han",
    "Seo",
    "Bhattacharya",
    "Krishnan",
    "Subramanian",
    "Venkataraman",
    "Mukherjee",
    "Das",
    "Pillai",
    "Mansour",
    "Saleh",
    "Habib",
    "Naef",
    "Brunner",
    "Frei",
    "Steiner",
    "Widmer",
    "Aaronson",
    "Lovász",
)

FIRST_NAMES: tuple[str, ...] = (
    "Alexander",
    "Maria",
    "Liang",
    "Sofia",
    "Hiroshi",
    "Aisha",
    "David",
    "Elena",
    "Rahul",
    "Yuki",
    "Omar",
    "Katarzyna",
    "Diego",
    "Mei",
    "Tomasz",
    "Priya",
    "Lucas",
    "Nadia",
    "Sven",
    "Anaïs",
    "Viktor",
    "Ingrid",
    "Hassan",
    "Chiara",
    "Wei",
    "Jing",
    "Xin",
    "Hao",
    "Lei",
    "Yan",
    "Fang",
    "Ling",
    "Akira",
    "Kenji",
    "Yuki",
    "Haruka",
    "Sakura",
    "Ren",
    "Minjun",
    "Seoyeon",
    "Jiwoo",
    "Aarav",
    "Ananya",
    "Vikram",
    "Lakshmi",
    "Sanjay",
    "Devi",
    "Fatima",
    "Yusuf",
    "Layla",
    "Karim",
    "Zahra",
    "Mohammed",
    "Amina",
    "Ali",
    "Noor",
    "Ibrahim",
    "Sara",
    "Mateo",
    "Valentina",
    "Santiago",
    "Camila",
    "Joaquín",
    "Lucía",
    "Thiago",
    "Isabela",
    "Émile",
    "Margot",
    "Hugo",
    "Juliette",
    "Antoine",
    "Camille",
    "Lars",
    "Astrid",
    "Henrik",
    "Freya",
    "Magnus",
    "Sigrid",
    "Eero",
    "Aino",
    "Piotr",
    "Zofia",
    "Jakub",
    "Hanna",
    "Miloš",
    "Petra",
    "Ivan",
    "Olga",
    "Dmitri",
    "Natalia",
    "Sergei",
    "Vera",
    "Andrei",
    "Irina",
    "Kwame",
    "Ama",
    "Chidi",
    "Ngozi",
    "Thabo",
    "Naledi",
    "Kofi",
    "Adaeze",
    "Tariro",
    "Sefu",
    "Eleni",
    "Nikos",
    "Dilara",
    "Emre",
    "Selin",
    "Mehmet",
    "Hana",
    "Tomáš",
    "Beatriz",
    "Gonçalo",
    "Rui",
    "Inês",
    "Daniela",
    "Stefano",
    "Giulia",
    "Marco",
    "Elif",
    "Arjun",
    "Meera",
    "Rohan",
    "Sofía",
    "Noa",
    "Eitan",
    "Tal",
    "Yael",
    "Oliver",
    "Amelia",
    "Noah",
    "Grace",
    "Ethan",
    "Hannah",
    "Leo",
    "Clara",
    "Sebastian",
    "Nora",
    "Felix",
    "Iris",
    "Theodore",
    "Beatrice",
)

INITIALS: tuple[str, ...] = (
    "A.",
    "B.",
    "C.",
    "D.",
    "E.",
    "F.",
    "G.",
    "H.",
    "J.",
    "K.",
    "L.",
    "M.",
    "N.",
    "P.",
    "R.",
    "S.",
    "T.",
    "V.",
    "Y.",
    "S. A.",
    "M. L.",
)

INSTITUTIONS: tuple[str, ...] = (
    "Institut des Hautes Études Scientifiques",
    "Princeton University",
    "Institute for Advanced Study",
    "University of Cambridge",
    "University of Oxford",
    "ETH Zürich",
    "École Polytechnique Fédérale de Lausanne",
    "Kyoto University",
    "University of Tokyo",
    "Max Planck Institute for Mathematics",
    "Université Paris-Saclay",
    "Sorbonne Université",
    "Collège de France",
    "Stanford University",
    "Massachusetts Institute of Technology",
    "Harvard University",
    "University of California, Berkeley",
    "University of California, Los Angeles",
    "University of Chicago",
    "Columbia University",
    "New York University",
    "Courant Institute of Mathematical Sciences",
    "California Institute of Technology",
    "University of Michigan",
    "University of Wisconsin–Madison",
    "University of Texas at Austin",
    "University of Toronto",
    "McGill University",
    "University of British Columbia",
    "University of Bonn",
    "University of Münster",
    "Humboldt University of Berlin",
    "Technical University of Munich",
    "Heidelberg University",
    "Leibniz University Hannover",
    "Sapienza University of Rome",
    "Scuola Normale Superiore di Pisa",
    "University of Geneva",
    "Universidad Autónoma de Madrid",
    "Universidade de São Paulo",
    "Instituto Nacional de Matemática Pura e Aplicada",
    "Tata Institute of Fundamental Research",
    "Indian Institute of Science",
    "Tsinghua University",
    "Peking University",
    "Fudan University",
    "Seoul National University",
    "Korea Institute for Advanced Study",
    "Australian National University",
    "University of Sydney",
    "University of New South Wales",
    "University of Melbourne",
    "University of Edinburgh",
    "Imperial College London",
    "University College London",
    "University of Warwick",
    "Steklov Mathematical Institute",
    "Lomonosov Moscow State University",
    "Hebrew University of Jerusalem",
    "Tel Aviv University",
    "Weizmann Institute of Science",
    "KTH Royal Institute of Technology",
    "University of Copenhagen",
    "Aarhus University",
    "University of Amsterdam",
    "Radboud University",
    "KU Leuven",
    "Charles University",
    "Jagiellonian University",
    "Eötvös Loránd University",
    "National Taiwan University",
    "Kyushu University",
    "Osaka University",
    "Mathematical Sciences Research Institute",
    "Isaac Newton Institute",
    "Fields Institute",
    "Clay Mathematics Institute",
)

JOURNALS: tuple[str, ...] = (
    "Ann. of Math.",
    "Invent. Math.",
    "J. Amer. Math. Soc.",
    "Duke Math. J.",
    "Adv. Math.",
    "Compos. Math.",
    "Trans. Amer. Math. Soc.",
    "Proc. Amer. Math. Soc.",
    "J. Reine Angew. Math.",
    "Math. Ann.",
    "Comm. Math. Phys.",
    "Geom. Topol.",
    "Algebra Number Theory",
    "Int. Math. Res. Not. IMRN",
    "J. Algebra",
    "J. Funct. Anal.",
    "Probab. Theory Related Fields",
    "Ann. Probab.",
)

PUBLISHERS: tuple[str, ...] = (
    "Springer",
    "Cambridge Univ. Press",
    "Amer. Math. Soc.",
    "Oxford Univ. Press",
)

AGENCIES: tuple[str, ...] = ("NSF", "ERC", "EPSRC", "DFG", "JSPS", "NSERC", "Simons Foundation")

GRANT_CODES: tuple[str, ...] = ("DMS-2112747", "PID2022-137283", "URF R1 201129", "EP/X001234/1")

# Connective phrases sprinkled through proofs.
PROOF_CONNECTIVES: tuple[str, ...] = (
    "Indeed,",
    "It follows that",
    "Conversely,",
    "More precisely,",
    "Note that",
    "By a standard argument,",
    "A direct computation shows that",
    "Combining the above,",
    "In particular,",
    "Consequently,",
    "On the other hand,",
    "Moreover,",
    "Hence,",
    "It remains to show that",
    "We claim that",
    "After unwinding the definitions,",
    "Arguing as before,",
    "In view of the above,",
    "Therefore,",
    "A routine verification shows that",
)

# Proof openers, varied so a single paper does not repeat the same one. Kept
# neutral: none promises a structure (cases, two inclusions, a contradiction)
# that the body does not deliver.
PROOF_OPENERS: tuple[str, ...] = (
    "We argue by induction on the relevant invariant.",
    "The proof relies on the construction introduced above.",
    "We may assume without loss of generality that the normalization holds.",
    "Fix the data as above.",
    "We proceed in several steps.",
    "After reducing to the local case, the argument is standard.",
    "The key point is a dimension count.",
    "We adapt the strategy of the previous section.",
    "The proof is a routine diagram chase.",
    "We exhibit the required object explicitly.",
    "By duality, it suffices to treat the generic case.",
    "We combine the preceding lemmas.",
    "We record the relevant estimates.",
    "We follow the standard strategy.",
)

# Proof closers (deduplicated within a paper so consecutive proofs differ).
PROOF_CLOSERS: tuple[str, ...] = (
    "This completes the proof.",
    "The conclusion follows as desired.",
    "This is what we wanted.",
    "The result now follows.",
    "This proves the claim.",
    "The remaining case is entirely analogous.",
    "This completes the argument.",
    "This is exactly as required.",
    "This establishes the assertion.",
    "This finishes the proof.",
    "The proof is complete.",
    "The statement follows.",
    "This proves the proposition.",
    "This is precisely the claim.",
    "This is what we set out to show.",
    "The general case is similar.",
    "This concludes the argument.",
)

HEDGES: tuple[str, ...] = (
    "explicitly",
    "uniformly",
    "generically",
    "asymptotically",
    "canonically",
    "naturally",
    "up to isomorphism",
    "in general",
    "essentially",
)

# Predicates that apply to an invariant (a number or structure), as opposed to
# the object-level adjectives in each field's `props` bank. Used wherever an
# invariant is the subject of "is", so we never produce "the mu-invariant is CM".
INVARIANT_PREDICATES: tuple[str, ...] = (
    "finite",
    "nonzero",
    "trivial",
    "bounded",
    "well-defined",
    "explicitly computable",
    "stable under deformation",
    "independent of the choices involved",
    "invariant under base change",
    "preserved under specialization",
    "uniformly bounded",
    "additive",
    "computed in closed form",
    "compatible with the natural filtration",
)
